-- 1. Nạp danh sách 73 Cuốn Sách Kinh Thánh Công Giáo với ID mới (cn, mt, ga, st...)
INSERT INTO books (id, name, short_name, testament, total_chapters, book_order)
VALUES
  ('st', 'Sáng Thế', 'St', 'old', 50, 1),
  ('xh', 'Xuất Hành', 'Xh', 'old', 40, 2),
  ('lv', 'Lê-vi', 'Lv', 'old', 27, 3),
  ('ds', 'Dân Số', 'Ds', 'old', 36, 4),
  ('dnl', 'Đệ Nhị Luật', 'Đnl', 'old', 34, 5),
  ('gs', 'Giô-suê', 'Gs', 'old', 24, 6),
  ('tl', 'Thủ Lãnh', 'Tl', 'old', 21, 7),
  ('r', 'Rút', 'R', 'old', 4, 8),
  ('1sm', '1 Sa-mu-en', '1 Sm', 'old', 31, 9),
  ('2sm', '2 Sa-mu-en', '2 Sm', 'old', 24, 10),
  ('1v', '1 Các Vua', '1 V', 'old', 22, 11),
  ('2v', '2 Các Vua', '2 V', 'old', 25, 12),
  ('1sb', '1 Sử Biên Niên', '1 Sb', 'old', 29, 13),
  ('2sb', '2 Sử Biên Niên', '2 Sb', 'old', 36, 14),
  ('er', 'Ét-ra', 'Er', 'old', 10, 15),
  ('nhm', 'Nê-he-mi-a', 'Nhm', 'old', 13, 16),
  ('tb', 'Tô-bi-a', 'Tb', 'old', 14, 17),
  ('gdt', 'Giu-đi-tha', 'Gđt', 'old', 16, 18),
  ('et', 'Ê-sơ-te', 'Et', 'old', 10, 19),
  ('1mc', '1 Ma-ca-bê', '1 Mc', 'old', 16, 20),
  ('2mc', '2 Ma-ca-bê', '2 Mc', 'old', 15, 21),
  ('g', 'Gióp', 'G', 'old', 42, 22),
  ('tv', 'Thánh Vịnh', 'Tv', 'old', 150, 23),
  ('cn', 'Châm Ngôn', 'Cn', 'old', 31, 24),
  ('gv', 'Giảng Viên', 'Gv', 'old', 12, 25),
  ('dc', 'Diễm Ca', 'Dc', 'old', 8, 26),
  ('kn', 'Khôn Ngoan', 'Kn', 'old', 19, 27),
  ('hc', 'Huấn Ca', 'Hc', 'old', 51, 28),
  ('is', 'I-sai-a', 'Is', 'old', 66, 29),
  ('gr', 'Giê-rê-mi-a', 'Gr', 'old', 52, 30),
  ('ac', 'Ai Ca', 'Ac', 'old', 5, 31),
  ('br', 'Ba-rúc', 'Br', 'old', 6, 32),
  ('ed', 'Ê-dê-ki-en', 'Ed', 'old', 48, 33),
  ('dn', 'Đa-ni-en', 'Đn', 'old', 14, 34),
  ('hs', 'Hô-sê', 'Hs', 'old', 14, 35),
  ('ge', 'Giô-en', 'Ge', 'old', 4, 36),
  ('am', 'A-mốt', 'Am', 'old', 9, 37),
  ('ov', 'Ô-va-đi-a', 'Ôv', 'old', 1, 38),
  ('gn', 'Giô-na', 'Gn', 'old', 4, 39),
  ('mk', 'Mi-kha', 'Mk', 'old', 7, 40),
  ('nh', 'Na-hum', 'Nh', 'old', 3, 41),
  ('hb', 'Ha-ba-cúc', 'Hb', 'old', 3, 42),
  ('xp', 'Xô-phô-ni-a', 'Xp', 'old', 3, 43),
  ('kg', 'Khắc-gai', 'Kg', 'old', 2, 44),
  ('dcr', 'Da-ca-ri-a', 'Dcr', 'old', 14, 45),
  ('ml', 'Ma-la-khi', 'Ml', 'old', 3, 46),
  ('mt', 'Mát-thêu', 'Mt', 'new', 28, 47),
  ('mc', 'Mác-cô', 'Mc', 'new', 16, 48),
  ('lc', 'Lu-ca', 'Lc', 'new', 24, 49),
  ('ga', 'Gio-an', 'Ga', 'new', 21, 50),
  ('cv', 'Công Vụ Tông Đồ', 'Cv', 'new', 28, 51),
  ('rm', 'Rô-ma', 'Rm', 'new', 16, 52),
  ('1cr', '1 Cô-rin-tô', '1 Cr', 'new', 16, 53),
  ('2cr', '2 Cô-rin-tô', '2 Cr', 'new', 13, 54),
  ('gl', 'Ga-la-ti', 'Gl', 'new', 6, 55),
  ('ep', 'Ê-phê-xô', 'Ep', 'new', 6, 56),
  ('pl', 'Phi-líp-phê', 'Pl', 'new', 4, 57),
  ('cl', 'Cô-lô-xê', 'Cl', 'new', 4, 58),
  ('1tx', '1 Thê-xa-lô-ni-ca', '1 Tx', 'new', 5, 59),
  ('2tx', '2 Thê-xa-lô-ni-ca', '2 Tx', 'new', 3, 60),
  ('1tm', '1 Ti-mô-thê', '1 Tm', 'new', 6, 61),
  ('2tm', '2 Ti-mô-thê', '2 Tm', 'new', 4, 62),
  ('tt', 'Ti-tô', 'Tt', 'new', 3, 63),
  ('plm', 'Phi-lê-môn', 'Plm', 'new', 1, 64),
  ('dt', 'Do Thái', 'Dt', 'new', 13, 65),
  ('gc', 'Gia-cô-bê', 'Gc', 'new', 5, 66),
  ('1pr', '1 Phê-rô', '1 Pr', 'new', 5, 67),
  ('2pr', '2 Phê-rô', '2 Pr', 'new', 3, 68),
  ('1ga', '1 Gio-an', '1 Ga', 'new', 5, 69),
  ('2ga', '2 Gio-an', '2 Ga', 'new', 1, 70),
  ('3ga', '3 Gio-an', '3 Ga', 'new', 1, 71),
  ('gd', 'Giu-đa', 'Gđ', 'new', 1, 72),
  ('kh', 'Khải Huyền', 'Kh', 'new', 22, 73)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  short_name = EXCLUDED.short_name,
  testament = EXCLUDED.testament,
  total_chapters = EXCLUDED.total_chapters,
  book_order = EXCLUDED.book_order;