INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'et', 1, '[PART] PHẦN MỞ ĐẦU
[SECTION] Giấc chiêm bao của ông Moóc-đo-khai
(1a) Năm thứ hai triều đại A-suê-rô, ngày mồng một tháng Ni-xan, ông Moóc-đo-khai, con ông Gia-ia (ông Gia-ia là con ông Sim-y, ông Sim-y con ông Kít), thuộc chi tộc Ben-gia-min, đã có một giấc chiêm bao. (1b) Ông là một người Do-thái cư ngụ tại thành Su-san, một nhân vật có thế giá, giữ một chức vụ trong hoàng cung. (1c) Ông thuộc số những người đi đày, bị vua Ba-by-lon là Na-bu-cô-đô-nô-xo bắt rời khỏi Giê-ru-sa-lem và phát lưu cùng với vua Giu-đa là Giơ-khon-gia.
(1d) Đây là giấc chiêm bao: bỗng nhiên, nổi lên những tiếng la lối om sòm, sấm sét rền vang, đất rung chuyển, rối loạn xảy ra trên mặt đất! Và này hai con rồng lớn tiến ra, cả hai đều sẵn sàng giao chiến. Chúng hét lên một tiếng lớn. (1e) Khi tiếng chúng vang ra, mọi dân nước chuẩn bị chiến tranh chống lại dân công chính. (1g) Và này một ngày tối tăm u ám, trên mặt đất chỉ thấy toàn những gian truân, ngặt nghèo, sầu khổ và rối loạn lớn lao. (1h) Tất cả dân công chính đều bấn loạn vì kinh khiếp trước những tai họa sắp xảy đến cho họ. Thấy mình sắp bị tiêu diệt, họ kêu lên cùng Thiên Chúa. (1i) Từ tiếng kêu cứu đó, người ta thấy như từ dòng suối nhỏ phát ra một con sông lớn, nước đầy tràn. (1k) Mặt trời mọc lên, tỏa lan ánh sáng. Kẻ thấp hèn được cất nhắc lên và nuốt sống người cao sang quyền thế.
(1l) Sau khi chiêm bao thấy những gì Thiên Chúa có ý thực hiện, ông Moóc-đo-khai tỉnh dậy; ông giữ lại điều đó trong lòng và mãi đến tối, dùng đủ cách để tìm hiểu ý nghĩa.
[SECTION] Âm mưu chống lại vua
(1m) Rồi ông Moóc-đo-khai nghỉ ngơi tại hoàng cung với hai viên thái giám của vua là Bi-gơ-than và Te-rét, những người canh gác hoàng cung. (1n) Sau khi nghe biết âm mưu và tìm hiểu cặn kẽ mối bận tâm của họ, lại được tin họ đang chuẩn bị tra tay hại vua A-suê-rô, ông liền báo cho vua biết các sự việc đó. (1o) Vua cho người điều tra về hai viên thái giám. Họ đã thú tội và bị hành quyết. (1p) Vua cho ghi chép các sự việc đó vào sách Sử biên niên; ông Moóc-đo-khai cũng ghi chép các sự việc đó. (1q) Rồi vua truyền cho ông Moóc-đo-khai phải nhận một chức vụ trong hoàng cung và ban quà tặng thưởng cho ông, vì các sự việc đó. (1r) Nhưng Ha-man, con ông Hăm-mơ-đa-tha, người Bu-ghê, là nhân vật cao sang quyền thế trong triều đình; ông tìm cách hại ông Moóc-đo-khai và dân của ông, vì vụ hai viên thái giám của vua.
[PART] I. VUA A-SUÊ-RÔ VÀ HOÀNG HẬU VÁT-TI
[SECTION] Bữa tiệc của vua A-suê-rô
(1) Bấy giờ là thời vua A-suê-rô. Vua này cai trị một trăm hai mươi bảy miền từ Ấn-độ cho đến Ê-thi-óp. (2) Thời ấy, vua A-suê-rô đã ngồi vững trên ngai tại thành Su-san. (3) Năm thứ ba của triều đại, vua cho dọn tiệc thết đãi tất cả các khanh tướng và quần thần. Các tướng lãnh trong đạo binh Ba-tư và Mê-đi, các nhà quý tộc và các tổng đốc đều tề tựu lại trước mặt vua. (4) Vua muốn phơi bày cho họ thấy cảnh giàu sang tráng lệ của vương quốc cũng như uy thế rực rỡ huy hoàng của nhà vua trong vòng nhiều ngày, tức một trăm tám mươi ngày.
(5) Mãn thời gian ấy, vua lại cho dọn một bữa tiệc bảy ngày trong sân ngự uyển thuộc hoàng cung để thết đãi dân chúng từ lớn đến nhỏ đang ở trong thành Su-san. (6) Tại đây, có căng những bức màn bằng sợi gai trắng tinh và đỏ tía. Người ta dùng dải bằng sợi gai mịn và hồng điều móc những bức màn đó vào các vòng bạc và treo lên các cột trụ bằng đá bạch ngọc. Trong sân ngự uyển, có kê những ghế dài bằng vàng, bằng bạc trên nền lát đá vân ban, đá cẩm thạch, khảm xà cừ và đá ngọc đen. (7) Người ta dùng các bình vàng đủ kiểu mời thực khách uống. Nhà vua cho tiếp rượu dồi dào xứng với cung cách của bậc đế vương, (8) nhưng lại ra lệnh không được ép ai, vì vua truyền cho các quản gia hoàng cung phải làm theo sở thích của mỗi người.
[SECTION] Vụ hoàng hậu Vát-ti
(9) Hoàng hậu Vát-ti cũng cho dọn tiệc đãi các mệnh phụ trong hoàng cung của vua A-suê-rô. (10) Ngày thứ bảy, trong lúc rượu làm lòng vua vui sướng, vua truyền cho bảy viên thái giám phục vụ vua là các ông: Mơ-hu-man, Bít-dơ-tha, Khác-vô-na, Bi-gơ-tha, A-vác-tha, Dê-tha và Các-cát, (11) phải mời hoàng hậu Vát-ti đội triều thiên hoàng hậu vào chầu vua, để dân chúng và các khanh tướng chiêm ngưỡng sắc đẹp của bà, vì bà là người có nhan sắc. (12) Nhưng hoàng hậu Vát-ti từ chối không chịu đến theo lệnh vua chuyển đạt qua các viên thái giám. Vua rất tức giận; cơn thịnh nộ của vua bừng bừng bốc lên. (13) Bấy giờ, vua ngỏ lời với các nhà hiền triết am tường luật pháp. Quả thật, vua thường trình bày các sự việc liên quan đến mình cho những người am tường luật pháp và công lý. (14) Nhóm nhân vật thân cận nhà vua gồm các ông: Các-sơ-na, Sê-tha, Át-ma-tha, Tác-sít, Me-rét, Mác-xơ-na và Mơ-mu-khan là bảy quan chức cao cấp người Ba-tư và Mê-đi, những nhân vật thường được triều yết vua và chiếm địa vị cao nhất trong vương quốc. (15) Vua nói: “Theo luật, phải xử thế nào với hoàng hậu Vát-ti, vì bà đã không tuân hành lệnh vua chuyển đạt qua các viên thái giám?” (16) Ông Mơ-mu-khan nói trước mặt vua và các quan chức: “Hoàng hậu Vát-ti đã đắc tội không chỉ với đức vua, mà còn với tất cả các quan trong hàng quần thần và toàn thể dân chúng ở trong mọi miền thuộc quyền đức vua. (17) Quả thế, chuyện hoàng hậu sẽ lan ra đến toàn thể nữ giới, làm cho họ nhìn đức lang quân của họ với cặp mắt khinh bỉ; họ sẽ nói: vua A-suê-rô đã cho mời hoàng hậu Vát-ti vào trước long nhan, thế mà bà đã chẳng vào. (18) Ngay ngày hôm nay, khi nghe chuyện hoàng hậu, các mệnh phụ người Ba-tư và Mê-đi cũng sẽ ăn nói như thế với quần thần của đức vua. Bấy giờ sẽ sinh ra biết bao là khinh bỉ và tức giận! (19) Vậy nếu đẹp lòng đức vua, thì xin đức vua ban sắc chỉ, ghi vào số các luật lệ dân Ba-tư và Mê-đi; sắc chỉ này không thể hủy bỏ được và nội dung như sau: từ nay, bà Vát-ti không còn được vào chầu vua A-suê-rô nữa. Xin đức vua ban chức hoàng hậu của bà cho một người khác xứng đáng hơn. (20) Chỉ dụ của đức vua sẽ được công bố trong toàn vương quốc, dù rất bao la; khi đó, toàn thể nữ giới, từ sang đến hèn, đều tỏ lòng kính trọng đức lang quân của họ.”
(21) Lời đề nghị đó vừa ý vua và các quan chức. Vua làm theo lời đề nghị của ông Mơ-mu-khan. (22) Vua cho gửi thư đến mọi miền, miền nào theo chữ viết của miền ấy, dân nào theo tiếng nói của dân ấy, để mọi người đàn ông làm chủ nhà mình và nói tiếng dân mình.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'et', 2, '[PART] II. ÔNG MOÓC-ĐO-KHAI VÀ BÀ ÉT-TE
[SECTION] Bà Ét-te trở thành hoàng hậu
(1) Sau những biến cố đó, khi cơn giận đã dịu xuống, vua A-suê-rô lại nhớ đến bà Vát-ti, nhớ đến những gì bà đã làm và những quyết định của vua đối với bà. (2) Các quan hầu cận vua mới nói: “Phải kiếm cho đức vua những thiếu nữ còn trinh và có nhan sắc. (3) Xin đức vua bổ nhiệm các tổng đốc trong mọi miền thuộc vương quốc để tập hợp về thành Su-san tất cả các thiếu nữ còn trinh và có nhan sắc, rồi đem vào hậu cung, đặt dưới quyền viên thái giám của vua là Hê-ghe, người có nhiệm vụ trông nom phụ nữ. Phải cung cấp cho họ các mỹ phẩm. (4) Thiếu nữ nào được vua ưa thích, sẽ làm hoàng hậu thay thế bà Vát-ti.” Lời đề nghị đó vừa ý vua, và vua đã cho thi hành như vậy.
(5) Trong thành Su-san, có một người Do-thái tên là Moóc-đo-khai, con ông Gia-ia (ông Gia-ia là con ông Sim-y, ông Sim-y là con ông Kít), thuộc chi tộc Ben-gia-min. (6) Từ Giê-ru-sa-lem, ông đã bị đi đày trong số những người bị đi đày cùng với vua Giu-đa là Giơ-khon-gia, những người mà vua Ba-by-lon là Na-bu-cô-đô-nô-xo đã phát lưu. (7) Ông nuôi nấng dạy dỗ Ha-đát-xa, tức là Ét-te, con gái của người chú ông, vì cô ta mồ côi cả cha lẫn mẹ. Thiếu nữ dung mạo xinh đẹp và dễ coi. Sau khi cha mẹ cô qua đời. Ông Moóc-đo-khai đã nhận cô làm con.
(8) Khi lệnh vua và chỉ dụ được công bố, một số đông thiếu nữ được tập hợp về thành Su-san, đặt dưới quyền ông Hê-ghe. Cô Ét-te cũng được đưa về hoàng cung, ở dưới quyền ông Hê-ghe, người có nhiệm vụ trông nom phụ nữ. (9) Thiếu nữ được ông ưa thích và được lòng ông. Ông vội cung cấp các mỹ phẩm và phần lương thực cần thiết cho cô. Ông còn cho bảy cung nữ tuyển chọn trong hoàng cung để phục vụ cô, rồi chuyển cô và các cung nữ đó về phòng tốt nhất trong hậu cung. (10) Cô Ét-te không tiết lộ gì về dân tộc, nguồn gốc của mình, vì ông Moóc-đo-khai cấm cô không được tiết lộ. (11) Mỗi ngày, ông Moóc-đo-khai lui tới sân hậu cung để biết tin về sức khỏe của cô Ét-te và về những gì xảy ra cho cô.
(12) Một thiếu nữ được vào hầu vua A-suê-rô sau thời gian mười hai tháng thi hành đúng quy chế dành cho các phụ nữ. Thời gian trau dồi sắc đẹp diễn tiến như sau cho đến lúc hoàn thành: sáu tháng dùng dầu thơm mộc dược, sáu tháng thoa kem và dùng các mỹ phẩm khác của phụ nữ. (13) Thiếu nữ nào rời hậu cung để vào hoàng cung thì được lãnh tất cả những gì cô xin và được mang theo. (14) Thiếu nữ đó vào hoàng cung lúc ban chiều, và sáng hôm sau, trở về một hậu cung khác dưới quyền viên thái giám Sa-át-gát, người được vua trao nhiệm vụ trông nom các cung phi. Cô không còn được vào hầu vua nữa, trừ khi vua đem lòng sủng ái và gọi đích danh.
(15) Nay đến lượt Ét-te vào hầu vua. Cô là con gái ông A-vi-kha-gin, chú ông Moóc-đo-khai; ông này là người đã nhận cô làm con. Cô chẳng xin gì, ngoại trừ những món viên thái giám của vua đã dặn. Viên thái giám này tên là Hê-ghe, có nhiệm vụ trông nom phụ nữ. Ai nhìn thấy cô cũng đem lòng thương mến. (16) Cô được đem vào hoàng cung hầu vua A-suê-rô. Bấy giờ là tháng thứ mười, tức là tháng Tê-vết, năm thứ bảy triều đại vua. (17) Vua yêu quý cô hơn mọi phụ nữ khác. Cô được vua mến thương và ưu ái hơn mọi trinh nữ. Vì thế, vua đội triều thiên cho cô và tôn làm hoàng hậu thay thế bà Vát-ti.
(18) Vua mở tiệc linh đình đãi các khanh tướng quần thần, gọi là tiệc mừng hoàng hậu Ét-te. Vua cho tất cả các miền nghỉ lễ một ngày và rộng tay ban phát tặng vật xứng bậc đế vương.
[SECTION] Ông Moóc-đo-khai và quan Ha-man
(19) Khi các trinh nữ được tập hợp lần thứ hai, lúc ông Moóc-đo-khai ngồi ở cung môn, (20) hoàng hậu Ét-te vẫn không cho biết bà thuộc dòng giống nào, dân tộc nào, theo lời ông Moóc-đo-khai đã dặn. Bà vẫn thi hành chỉ thị của ông như hồi còn được ông nuôi nấng dạy dỗ. (21) Bấy giờ, ông Moóc-đo-khai ngồi ở cung môn. Có hai viên thái giám của vua là Bi-gơ-than và Te-rét đang giữ phận sự gác cửa hoàng cung, đã nổi giận vì bất mãn, nên tìm cách tra tay hại vua A-suê-rô. (22) Biết chuyện đó, ông Moóc-đo-khai liền báo cho hoàng hậu Ét-te; hoàng hậu tâu lại vua những điều ông Moóc-đo-khai đã tiết lộ. (23) Sự việc được điều tra và xác nhận, hai viên thái giám kia liền bị treo cổ. Vụ này được ghi chép vào sách Sử biên niên trước mặt vua.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'et', 3, '(1) Sau biến cố đó, vua A-suê-rô thăng chức cho ông Ha-man, con ông Hăm-mơ-đa-tha, người A-gác. Vua cất nhắc ông lên, đặt ông đứng đầu mọi khanh tướng hầu cận vua. (2) Quần thần nhất nhất đều cúi chào bái lạy ông Ha-man vì vua đã truyền như thế. Nhưng ông Moóc-đo-khai đã chẳng cúi chào, cũng không bái lạy. (3) Quần thần trong triều nói với ông Moóc-đo-khai: “Tại sao ông lại lỗi lệnh vua?” (4) Ngày nào họ cũng lặp đi lặp lại như thế, nhưng ông vẫn không chịu nghe; Ông cho họ thấy ông là người Do-thái. Họ mới trình sự việc cho ông Ha-man để xem ông Moóc-đo-khai còn giữ thái độ đó nữa không. (5) Khi thấy ông Moóc-đo-khai chẳng cúi chào, cũng không bái lạy mình, ông Ha-man hết sức phẫn nộ. (6) Nhưng đối với ông Ha-man, vì đã biết ông Moóc-đo-khai thuộc dân tộc nào, nên nếu chỉ giết một mình ông ta thôi thì tầm thường quá. Vì vậy, ông Ha-man tìm cách tiêu diệt cả dân tộc của ông Moóc-đo-khai. Đó là hết mọi người Do-thái đang sống trong toàn vương quốc của vua A-suê-rô.
[PART] III. NGƯỜI DO-THÁI BỊ ĐE DỌA
[SECTION] Sắc chỉ tru diệt người Do-thái
(7) Tháng thứ nhất, tức tháng Ni-xan, vào năm thứ mười hai triều đại vua A-suê-rô, người ta gieo “Pua” (nghĩa là bắt thăm) trước mặt ông Ha-man để biết ngày biết tháng. Thăm rơi trúng ngày mười bốn tháng thứ mười hai, tức là tháng A-đa. (8) Ông Ha-man thưa với vua A-suê-rô: “Trong khắp các miền thuộc vương quốc của đức vua, có một dân sống tản mác, rải rác đó đây giữa các dân. Luật lệ của chúng không giống như luật lệ của bất cứ dân nào khác. Luật lệ của đức vua, chúng chẳng tuân chẳng giữ. Quyền lợi của đức vua không cho phép để chúng yên như vậy. (9) Nếu đẹp lòng đức vua, thì xin đức vua cho viết sắc lệnh tru diệt chúng. Thần xin cân ba trăm ngàn ký bạc trao cho công chức đem vào kho bạc của đức vua.”
(10) Bấy giờ, vua tháo bửu ấn ở tay ra trao cho cừu địch của người Do-thái là ông Ha-man, con ông Hăm-mơ-đa-tha, người A-gác. (11) Rồi vua nói với ông Ha-man: “Ta tặng khanh số bạc đó, trao cho khanh cả dân tộc đó nữa. Khanh muốn làm gì chúng thì làm.”
(12) Ngày mười ba tháng thứ nhất, các ký lục của vua được triệu đến. Trên sắc lệnh có ghi tất cả những gì ông Ha-man đã chỉ thị để gửi đến các thủ hiến của nhà vua, các tổng đốc coi mỗi miền và các quan chức coi từng sắc dân, miền nào theo chữ viết của miền ấy, dân nào theo tiếng nói của dân ấy. Sắc lệnh được soạn thảo nhân danh vua A-suê-rô và niêm phong bằng bửu ấn nhà vua, (13) rồi được trao cho các phu trạm mang đến tất cả các miền dưới quyền vua. Mục đích là thủ tiêu, giết chết, tru diệt mọi người Do-thái từ trẻ đến già, cả thiếu nhi lẫn phụ nữ, nội trong một ngày, ngày mười ba tháng thứ mười hai, tức là tháng A-đa. Ngoài ra, sắc lệnh còn cho phép cướp của nữa.
(13a) Sau đây là bản sao sắc lệnh trên:
“Đại vương A-suê-rô viết như sau cho các tổng đốc của một trăm hai mươi bảy miền từ Ấn-độ đến Ê-thi-óp, và cho các quan chức dưới quyền:
(13b) Cai quản muôn dân nước, làm bá chủ toàn cõi địa cầu, ta không muốn say men quyền bính mà sinh thói kiêu căng, nhưng muốn luôn lãnh đạo sao cho khoan dung hiền hòa, không ngừng bảo đảm cho toàn dân một cuộc sống yên ổn, giúp cho vương quốc được thái bình thịnh vượng, ai nấy dễ dàng đi lại cho đến tận biên thùy, để phục hồi cảnh an hòa mọi người hằng mong ước. (13c) Để tìm cách thực hiện dự kiến trên, ta đã bàn hỏi các vị cố vấn. Trong số đó, quan Ha-man giữa chúng ta là một nhân vật khôn ngoan xuất chúng, đã tỏ ra luôn thành tâm thiện chí và hết dạ tín trung, nên trong vương quốc, đã lên tới địa vị thứ nhì. (13d) Ông đã cho ta thấy rằng có một dân đầy ác ý, sống trà trộn với trăm họ trên toàn cõi địa cầu, theo những luật lệ đối nghịch hẳn với các nước khác, chẳng hề đếm xỉa đến sắc dụ của các vua, khiến cho vương quốc không thể đạt tới sự thống nhất, vương quốc mà ta vẫn điều khiển một cách hoàn hảo, không ai chê trách được.
Vậy, ta khẳng định rằng đây là lũ dân lập dị, luôn chống đối mọi người, có nếp sống khác biệt vì tuân hành thứ luật pháp xa lạ, phạm những tội ác tày trời chống lại quyền lợi của ta, với ý đồ gây bất ổn cho vương quốc.
(13e) Do đó, ta truyền rằng: ngày mười bốn tháng thứ mười hai, tức là tháng A-đa năm nay, phải tận diệt tất cả những kẻ được đề cập trong văn thư của quan Ha-man, người đã được ta bổ nhiệm làm phụ chính lo việc triều đình cho ta. Phải lấy gươm của địch thù chúng mà tận diệt chúng cùng với vợ con, không nương tay, không thương xót. (13g) Như thế, nội trong một ngày, những kẻ xưa nay vốn đầy ác ý đều bị tống xuống âm phủ, để từ đây, việc triều chính được mãi mãi ổn định và êm xuôi.”
(14) Sắc chỉ này đã được công bố và có hiệu lực luật pháp cho mọi miền. Bản sao cũng đã được phổ biến, để vào ngày ấn định, mọi dân sẵn sàng tuân theo. (15) Theo lệnh vua, phu trạm tức tốc lên đường. Sắc chỉ được công bố tại thành Su-san.
Trong khi vua cùng quan Ha-man ngồi chè chén say sưa, thì cả thành Su-san đều xôn xao náo động.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'et', 4, '[SECTION] Ông Moóc-đo-khai và hoàng hậu Ét-te đẩy lui hiểm họa
(1) Khi biết tất cả những sự kiện trên, ông Moóc-đo-khai xé áo mình ra, mặc lấy bao bị và rắc tro lên người. Ông ra giữa thành, lớn tiếng thốt lên những lời đắng cay chua xót. (2) Ông đến tận trước cung môn là nơi không ai được phép vào mà lại mặc bao bị. (3) Trong mỗi miền, bất cứ nơi đâu mệnh lệnh và chỉ dụ của vua được chuyển tới, người ta cũng đều chứng kiến một cảnh thê lương buồn thảm: dân Do-thái ăn chay, khóc lóc, than van. Nhiều người nằm trên tro trên đất, mình mặc bao bị.
(4) Các cung nữ và thái giám báo tin cho hoàng hậu Ét-te. Bà hết sức bàng hoàng. Bà gửi áo ra cho ông Moóc-đo-khai mặc và xin ông cởi bỏ bao bị. Ông không chịu nghe. (5) Bà mới cho gọi ông Ha-thác là một trong những viên thái giám nhà vua đặt làm người phục vụ bà. Bà truyền cho ông đi gặp ông Moóc-đo-khai để biết sự việc đã xảy ra và lý do của sự việc đó.
(6) Ông Ha-thác ra gặp ông Moóc-đo-khai tại quảng trường đối diện với cung môn. (7) Ông Moóc-đo-khai cho ông biết tất cả những sự việc đã xảy ra và biết chuyện ông Ha-man đã hứa sẽ cân một số bạc bỏ vào kho của vua nhằm tru diệt người Do-thái. (8) Ông Moóc-đo-khai trao cho ông bản sao sắc chỉ đã công bố ở Su-san nhằm hủy diệt họ, mục đích là cho bà Ét-te xem bản sao đó và biết các sự việc. Ông Moóc-đo-khai cũng nhắn bà phải vào chầu vua để xin vua tỏ lòng nhân hậu và khẩn nài vua thương xót dân tộc bà. Ông nhắn rằng: (8a) “Con hãy nhớ lại thuở hàn vi của con, những ngày con đã được chính tay cha nuôi dưỡng. Người chiếm địa vị thứ nhì trong vương quốc là Ha-man đã đề nghị vua chống lại chúng ta, nhằm dẫn chúng ta đến chỗ chết. (8b) Con hãy cầu khẩn Chúa và xin vua thương tình tha chết cho chúng ta.”
(9) Ông Ha-thác trở vào, chuyển những lời này đến hoàng hậu Ét-te. (10) Bà ngỏ lời với ông Ha-thác, truyền cho ông ra gặp ông Moóc-đo-khai và nói: (11) “Bề tôi của vua và dân các miền thuộc quyền vua, ai cũng biết rõ: bất cứ người nào, nam cũng như nữ, không được triệu vời mà dám vào chầu vua ở phía trong sân rồng, thì đều chịu một luật duy nhất là phải chết, trừ phi vua giơ phủ việt vàng ra, người ấy mới được sống. Mà con đây đã ba mươi ngày rồi không được triệu vào chầu vua.”
(12) Người ta cho ông Moóc-đo-khai biết những điều bà Ét-te đã nói. (13) Ông nhờ người trả lời: “Đừng tưởng rằng trong cả dân Do-thái, chỉ có mình con ở tại hoàng cung là được thoát nạn. (14) Vì đến lúc này mà con vẫn cứ ngậm miệng làm thinh, thì người Do-thái sẽ nhận được sự trợ giúp và giải cứu từ một nơi khác; còn chính con và nhà cha con lại bị tru diệt. Biết đâu không phải vì thời buổi như thế này mà con đã lên tới địa vị hoàng hậu?”
(15) Bà Ét-te nhờ người trả lời ông Moóc-đo-khai: (16) “Xin cha cứ đi tập hợp tất cả những người Do-thái ở Su-san lại. Xin bà con ăn chay cầu nguyện cho con. Suốt ba ngày đêm, đừng ăn uống gì cả. Con và các cung nữ cũng sẽ làm như thế. Sau đó, dầu pháp luật không cho phép, con cũng vào chầu vua. Có chết con cũng đành.” (17) Ông Moóc-đo-khai rút lui và làm theo mọi điều hoàng hậu Ét-te dặn.
[SECTION] Lời cầu nguyện của ông Moóc-đo-khai
(17a) Ông nhắc lại mọi công việc Chúa đã làm mà cầu xin với Chúa:
(17b) “Lạy Chúa, Chúa là Vua toàn năng,
Chúa nắm quyền điều khiển vũ trụ.
Khi Chúa muốn cứu độ Ít-ra-en,
nào ai đương đầu nổi với Ngài!
(17c) Chính Ngài đã tạo dựng trời đất
và thực hiện mọi kỳ công dưới bầu trời.
Lạy Chúa, Ngài là Chúa vạn vật.
Ai chống lại được Ngài?
(17d) Lạy Chúa, Ngài biết mọi sự, Ngài biết rõ:
Không phải vì xấc xược, kiêu kỳ hoặc háo danh
mà con làm thế,
đã không bái lạy tên Ha-man ngạo mạn kiêu căng.
Quả thật, để cứu Ít-ra-en,
thì có phải hôn bàn chân hắn, con đây cũng sẵn sàng.
Nhưng con đã làm thế để khỏi đặt cái vinh của người phàm
trên vinh quang Thiên Chúa.
Con sẽ không bái lạy một ai, ngoại trừ Ngài, lạy Chúa,
và con sẽ không làm thế vì kiêu ngạo.
(17e) Giờ đây, lạy Chúa là Thiên Chúa.
Chúa là Vua, là Thiên Chúa tổ phụ Áp-ra-ham,
xin tha cho dân Ngài,
vì thù địch đang để tâm để ý chúng con
nhằm tìm cách hủy diệt.
Chúng những mong phá hủy
phần sản nghiệp ngàn xưa của Ngài.
(17g) Xin Ngài đừng chê bỏ dân riêng thuộc về Ngài,
dân Ngài đã chuộc lấy từ Ai-cập.
(17h) Xin nghe lời con nguyện
mà thương đến phần gia nghiệp của Ngài.
Lạy Chúa, cảnh tang tóc chúng con, xin biến thành hoan lạc
để chúng con được sống mà ca tụng danh Ngài.
Xin Ngài đừng hủy diệt
đoàn dân luôn mở miệng ngợi khen Ngài.”
(17i) Toàn thể Ít-ra-en hết lòng hết sức kêu van Chúa, vì cái chết ở trước mắt họ rồi.
[SECTION] Lời cầu nguyện của hoàng hậu Ét-te
(17k) Hoàng hậu Ét-te khắc khoải âu lo đến chết được, liền tìm đến nương ẩn bên Chúa. Tâm hồn sầu khổ, bà cởi bỏ y phục lộng lẫy, mặc áo tang vào. Thay cho dầu thơm quý giá, bà lấy bụi tro dơ bẩn rắc lên đầu; bà hãm mình phạt xác nhiệm nhặt; thay vì trang điểm trau chuốt, bà để cho tóc xõa rối bời. Bà cầu xin cùng Chúa, Thiên Chúa Ít-ra-en:
(17l) “Lạy Chúa của con, lạy Vua chúng con,
Ngài là Thiên Chúa duy nhất.
Này con đang liều mạng, xin đến cứu giúp con.
Con cô đơn, chẳng còn ai cứu giúp, ngoại trừ Ngài.
(17m) Lạy Chúa, trong chi tộc của cha ông,
từ khi lọt lòng mẹ, con từng được nghe biết
là chính Ngài đã chọn Ít-ra-en giữa muôn ngàn dân tộc,
đã tuyển chọn cha ông chúng con
giữa mọi bậc tiền bối của các ngài
để làm thành gia nghiệp mãi mãi thuộc về Ngài.
Ngài thực hiện cho cha ông chúng con
mọi điều Ngài đã hứa.
(17n) Nay chúng con đã phạm tội trước nhan Ngài,
và Ngài đã trao nộp chúng con vào tay kẻ thù địch
vì chúng con đã thờ các thần minh của chúng.
Lạy Chúa, Ngài công minh chính trực xiết bao!
(17o) Bây giờ, tuy chúng con phải nuốt cay ngậm đắng
làm nô lệ cho thù địch chúng con,
chúng vẫn chưa lấy làm thỏa mãn.
Chúng lại còn đặt tay lên tay các tượng thần của chúng,
liên kết cùng thần minh nhằm hủy bỏ
mệnh lệnh Ngài đã ban, nhằm phá tan gia nghiệp của Ngài,
làm những kẻ ca khen Ngài phải ngậm miệng,
dập tắt vinh quang không ngừng chiếu tỏa
trên thánh điện, trên bàn thờ của Ngài,
(17p) nhằm mở miệng chư dân
để họ hát mừng công đức các thần minh hư ảo
và mãi mãi sùng bái ông vua mang xác phàm.
(17q) Lạy Chúa, xin đừng trao phủ việt của Ngài
cho những gì hư ảo
cũng đừng để cho thù địch nhạo cười khi chúng con gục ngã.
Nhưng xin lấy mưu đồ của chúng mà quật lại chúng đi.
Và những kẻ manh tâm hại chúng con,
xin đưa ra làm gương cho thiên hạ.
(17r) Lạy Chúa, ngày chúng con gặp gian truân cùng khốn,
xin nhớ đến chúng con mà chứng tỏ quyền năng của Ngài.
Lạy Vua các thần minh,
Đấng thống trị mọi kẻ cầm quyền,
xin ban cho con lòng dũng cảm,
(17s) và dạy con biết nói lời êm tai
khi phải ra trước mặt loài sư tử.
Xin đổi lòng con sư tử ấy để nó căm thù kẻ chống lại chúng con,
khiến cho hắn và quân đồng lõa phải tiêu diệt hoàn toàn.
(17t) Thần dân Ngài, xin Ngài giải thoát.
Con cô đơn, xin đến cứu giúp con.
Lạy Chúa, ngoài Ngài ra, con đâu còn ai nữa!
(17u) Ngài thấu biết mọi sự trên đời,
Ngài biết rõ lòng con hằng căm ghét
cái vinh của những kẻ không Lề Luật,
và con cũng nhờm tởm gớm ghê
việc chăn gối với những kẻ không cắt bì
cũng như với những người dân ngoại.
(17v) Ngài biết rõ con đang cùng đường túng thế,
con ghê tởm cái huy hiệu kiêu hãnh mang trên đầu
trong những ngày xuất hiện trước công chúng;
con ghê tởm nó như ghê tởm cái khăn phải dùng khi khó ở.
Con chẳng mang nó vào những ngày bình an.
(17x) Nữ tỳ của Chúa đã không hề đồng bàn với Ha-man,
chẳng coi trọng tiệc tùng vua đãi,
chẳng thèm uống thứ rượu tế thần.
(17y) Từ ngày thay đổi địa vị cho đến nay,
nữ tỳ của Chúa chẳng hề được vui sướng
nếu không có những niềm vui bên Ngài,
lạy Chúa là Thiên Chúa tổ phụ Áp-ra-ham.
Lạy Thiên Chúa quyền uy dũng lực trên hết thảy mọi người,
xin nghe tiếng những kẻ sờn lòng nản chí.
Xin giải thoát chúng con khỏi tay những kẻ độc ác,
xin giải thoát con khỏi cơn sợ hãi này!”') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'et', 5, '[SECTION] Hoàng hậu Ét-te vào chầu vua
(1) Ngày thứ ba, cầu nguyện xong, hoàng hậu Ét-te bỏ áo cầu nguyện, mặc phẩm phục huy hoàng. (1a) Đẹp lộng lẫy, bà cầu khẩn Thiên Chúa là Đấng thấu suốt và cứu độ mọi người. Rồi bà đem theo hai cung nữ: bà tựa vào một cô, trông thật thướt tha duyên dáng; còn cô kia theo sau, nâng đuôi áo cho bà. (1b) Bà hết sức xinh đẹp, đôi má tươi hồng, vẻ mặt hớn hở, dễ thương, nhưng lòng đau như thắt vì khiếp sợ. (1c) Qua các cửa, bà đến trước mặt vua. Vua ngự trên ngai báu, mang trọn bộ long bào dùng trong những buổi triều yết, mình đầy vàng bạc châu báu, dáng vẻ rất đáng sợ. (1d) Vua ngẩng mặt lên nhìn, đôi mắt rực sáng, giận dữ đến cực độ. Hoàng hậu khuỵu xuống, tái mặt đi vì yếu sức; bà dựa đầu vào cô cung nữ đi trước. Thiên Chúa làm cho vua đổi lòng, khiến vua ra dịu hiền. Từ trên ngai vàng, vua lo âu lao mình xuống, đưa cánh tay đỡ lấy bà cho đến khi bà tỉnh lại. Rồi vua lấy lời trấn an khích lệ bà: (1e) “Sao thế, Ét-te? Ta là anh của em mà! Yên tâm đi! Em không phải chết đâu! Lệnh của ta chỉ áp dụng cho thường dân thôi. Lại đây em!” (2) Vua đưa phủ việt vàng lên đặt vào cổ bà, rồi ôm hôn bà và nói: “Hãy nói cho ta hay!” (2a) Bà nói với vua: “Tâu chúa thượng, thiếp nhìn thấy ngài giống như thiên sứ của Thiên Chúa. Tâm hồn thiếp bị rúng động vì khiếp sợ vẻ oai nghi của ngài. Quả thế, tâu chúa thượng, ngài thật kỳ diệu và long nhan ngài thật hấp dẫn!” (2b) Đang nói thế bà lại khuỵu xuống. Vua bị rúng động, còn các cận thần thì tìm cách làm cho bà tỉnh lại. (3) Vua nói với bà: “Hoàng hậu Ét-te, chuyện gì thế? Khanh muốn xin gì? Dù nửa nước ta cũng sẽ ban!” (4) Bà Ét-te đáp: “Nếu đẹp lòng đức vua, thì hôm nay, xin đức vua cùng quan Ha-man đến dự yến tiệc thiếp đã dọn hầu đức vua.” (5) Vua liền nói: “Hãy mau mau triệu Ha-man đến để làm như Ét-te vừa nói.” Vua đã cùng quan Ha-man đến dự yến tiệc bà Ét-te dọn. (6) Giữa tiệc rượu, vua lại nói với bà Ét-te: “Khanh thỉnh cầu gì, ta sẽ ban cho. Khanh muốn xin gì, dù nửa nước cũng sẽ được.” (7) Bà Ét-te đáp: “Điều thiếp thỉnh cầu, điều thiếp muốn xin... (8) Nếu thiếp được đức vua thương đến, nếu đức vua vui lòng ban điều thiếp muốn xin và thực hiện điều thiếp thỉnh cầu, thì ngày mai xin đức vua cùng quan Ha-man lại tới dự yến tiệc thiếp sẽ dọn hầu các ngài. Rồi thiếp sẽ tuân theo lời đức vua phán dạy.”
(9) Hôm ấy, Ha-man vui vẻ ra về, lòng phơi phới hân hoan. Nhưng khi thấy ông Moóc-đo-khai ở cung môn không buồn đứng dậy cũng chẳng thèm nhúc nhích, y hết sức căm giận ông. (10) Ha-man dằn lòng trở về nhà, sai người đi mời bạn hữu và vợ là De-rết đến. (11) Y kể cho họ nghe nào là y giàu có vinh hiển, nào là con cái đông đúc, nào là bao nhiêu việc vua đã làm để đề cao y và cất nhắc y lên trên hàng khanh tướng quần thần của nhà vua. (12) Y nói: “Hơn nữa, ngoài tôi ra, hoàng hậu Ét-te đã chẳng mời ai khác cùng đức vua đến dự yến tiệc của bà. Ngày mai, bà lại mời tôi với đức vua lần nữa. (13) Nhưng tất cả những điều đó chưa làm tôi thỏa mãn, bao lâu tôi còn thấy tên Do-thái Moóc-đo-khai ngồi tại cung môn.” (14) De-rết, vợ y, và tất cả các bạn hữu của y đều nói: “Ngài cứ cho dựng một cái giá cao hai mươi lăm thước, rồi sáng mai xin đức vua cho treo cổ tên Moóc-đo-khai lên. Sau đó, ngài sẽ vui vẻ theo đức vua vào dự tiệc.” Ha-man ưng thuận đề nghị đó và cho dựng giá treo cổ.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'et', 6, '[PART] IV. NGƯỜI DO-THÁI TRẢ THÙ
[SECTION] Ha-man thất bại nhục nhã
(1) Chính đêm ấy, vua mất ngủ. Vua mới truyền đem tập Kỷ Yếu, sách Sử biên niên của hoàng triều ra đọc trước mặt vua. (2) Trong sách có chép rằng: ông Moóc-đo-khai tố cáo hai viên thái giám gác cửa hoàng cung là Bi-gơ-than và Te-rét đã tìm cách tra tay hại vua A-suê-rô. (3) Bấy giờ vua nói: “Đã làm gì để tuyên dương và đề cao Moóc-đo-khai vì công trạng đó chưa?” Gia nhân tâu lại: “Thưa đức vua, chưa làm gì cho ông ấy cả.” (4) Vua nói: “Ai ở ngoài sân đó?” Lúc ấy, Ha-man vừa đến sân ngoài của hoàng cung để xin vua cho treo cổ ông Moóc-đo-khai lên giá đã dọn sẵn cho ông. (5) Gia nhân liền thưa: “Có quan Ha-man đang đứng ngoài sân.” Vua nói: “Cho phép quan ấy vào.” (6) Ha-man vào. Vua hỏi: “Nhà vua muốn tuyên dương một người thì nên làm gì cho người đó?” Ha-man tự nhủ: “Ngoài ta ra, nào đức vua còn muốn tuyên dương ai được nữa?” (7) Nên Ha-man mới tâu vua: “Đức vua muốn tuyên dương ai, (8) thì ngày lễ gia miện, đức vua đã mặc long bào nào, đã cỡi con ngựa nào, (9) nay xin đem trao cho một trong các vị cao cấp nhất của đức vua, để vị này mặc long bào ấy cho người đức vua muốn tuyên dương, rồi đặt người đó lên cỡi con ngựa ấy mà đem đi dạo trong quảng trường của thành phố. Vị này sẽ đi trước người đó và hô to: ‘Đây là cách đức vua đãi ngộ người đức vua muốn tuyên dương.’” (10) Vua liền nói: “Khanh mau lấy long bào và ngựa như vừa nói, và làm như vậy cho ông Moóc-đo-khai, người Do-thái. Tất cả các điều khanh vừa nói, đừng bỏ sót một chi tiết nào.”
(11) Ha-man lấy long bào mặc cho ông Moóc-đo-khai, đem ngựa ra cho ông cỡi, rồi vừa dẫn đi trong quảng trường của thành phố, vừa hô to trước mặt ông: “Đây là cách đức vua đãi ngộ người đức vua muốn tuyên dương.” (12) Ông Moóc-đo-khai trở về cung môn; còn Ha-man thì tức tốc chạy về nhà, lòng buồn bã, đầu trùm khăn. (13) Ha-man thuật lại cho vợ là De-rết và cho mọi bạn hữu nghe tất cả những gì đã xảy ra. Các bạn hữu khôn ngoan đó và De-rết vợ y mới nói: “Nếu Moóc-đo-khai thuộc dòng giống Do-thái thì trước mặt hắn, ngài chỉ mới bắt đầu tuột dốc đó thôi. Ngài sẽ không thắng được hắn đâu. Trước mặt hắn, ngài sẽ tuột dốc thê thảm.”
[SECTION] Ha-man dự yến tiệc cùng hoàng hậu Ét-te
(14) Câu chuyện còn dang dở thì các thái giám của vua đến. Họ vội vàng triệu Ha-man tới dự yến tiệc bà Ét-te đã dọn.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'et', 7, '(1) Vua và Ha-man đến dự yến tiệc với hoàng hậu Ét-te. (2) Ngày thứ hai này, giữa tiệc rượu, vua cũng lại nói với bà Ét-te: “Hoàng hậu Ét-te, khanh thỉnh cầu gì, ta sẽ ban. Khanh xin gì, dù nửa nước, ta cũng sẽ ban cho.” (3) Hoàng hậu Ét-te đáp: “Nếu thiếp được đức vua thương chiếu cố và nếu đẹp lòng đức vua, thì xin nhận lời thiếp khẩn cầu mà cho thiếp được sống, xin nghe lời thiếp nài van mà cho dân thiếp được sống, (4) vì thiếp và dân của thiếp đã bị bán đứng cho người ta triệt hạ, giết chết, tru diệt. Giả như bề tôi đây có bị bán làm tôi trai tớ gái người ta, thiếp sẽ chẳng nói gì; nhưng đối phương sau này không thể bù đắp được thiệt hại mà đức vua sẽ phải chịu.” (5) Vua A-suê-rô ngỏ lời với hoàng hậu Ét-te: “Tên đó là ai? Kẻ cả gan hành động như thế hiện đang ở đâu?” (6) Bà Ét-te thưa: “Đối phương ấy, địch thù ấy, chính là tên Ha-man khốn nạn này đây!” Trước mặt vua và hoàng hậu, Ha-man kinh hoàng sợ hãi. (7) Vua bừng bừng nổi giận, đứng lên, bỏ tiệc rượu, đi ra ngự uyển. Còn Ha-man thì ở lại nài xin hoàng hậu Ét-te cứu sống mình, vì y quá hiểu: thảm họa sẽ xảy đến cho y, vua đã quyết định rồi.
(8) Khi vua từ ngự uyển trở lại phòng tiệc rượu thì Ha-man đã nằm vật xuống giường, bên cạnh bà Ét-te. Vua nói: “Lại còn tính xâm phạm đến cả hoàng hậu tại hoàng cung, ngay khi ta có mặt hay sao?” Vua vừa nói xong, người ta liền lấy khăn che mặt Ha-man lại. (9) Một trong các thái giám là ông Khác-vô-na nói trước mặt vua: “Kìa, sẵn có cái giá Ha-man dựng lên để treo cổ ông Moóc-đo-khai. Chính nhờ lời báo cáo của ông này mà đức vua đã thoát nạn. Cái giá đó cao hai mươi lăm thước, dựng ngay tại nhà Ha-man.” Vua liền nói: “Treo cổ y lên đó!” (10) Ha-man bị treo cổ lên cái giá dành sẵn cho ông Moóc-đo-khai. Thế là nhà vua hả giận.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'et', 8, '[SECTION] Vua đổi lòng, mến chuộng dân Do-thái
(1) Ngày hôm ấy, vua A-suê-rô ban cho hoàng hậu Ét-te tài sản của Ha-man, cừu địch của người Do-thái. Ông Moóc-đo-khai vào chầu vua, vì bà Ét-te đã cho vua biết ông họ hàng làm sao với bà. (2) Chiếc bửu ấn đã lấy lại của Ha-man, vua rút ra trao cho ông Moóc-đo-khai. Còn bà Ét-te thì đặt ông coi sóc tài sản của Ha-man.
(3) Bà Ét-te lại vào thưa chuyện với vua. Bà sấp mình dưới chân vua mà khóc lóc, xin vua thương cất đi cái thảm họa Ha-man, người A-gác, đã tính gây ra và xin vua phá tan ý đồ của y toan hại người Do-thái. (4) Vua đưa phủ việt vàng lên trước mặt bà Ét-te. Bà trỗi dậy, đứng trước mặt vua (5) và thưa: “Nếu đẹp lòng đức vua, nếu thiếp được đức vua thương, nếu sự việc này đức vua xét là nên, và nếu thiếp làm vừa mắt đức vua, thì xin đức vua cho viết sắc chỉ thu hồi các văn thư mà Ha-man, con ông Hăm-mơ-đa-tha, người A-gác, đã viết. Ha-man đã nghĩ và viết các văn thư ấy nhằm tru diệt người Do-thái sống trong các miền thuộc quyền đức vua. (6) Làm sao thiếp lại có thể đành lòng chứng kiến tai họa giáng xuống dân của thiếp? Làm sao thiếp lại có thể đành lòng chứng kiến cảnh nòi giống của thiếp bị diệt vong?”
(7) Vua A-suê-rô nói với hoàng hậu Ét-te và ông Moóc-đo-khai người Do-thái: “Tài sản của Ha-man, ta đã tặng cho bà Ét-te rồi đó, còn Ha-man thì đã bị treo cổ vì muốn tra tay giết người Do-thái. (8) Vậy chư khanh cứ theo sự xét đoán của mình mà nhân danh vua viết về người Do-thái thế nào cho phải, rồi lấy bửu ấn của nhà vua mà niêm lại, vì công văn nào đã được soạn thảo nhân danh nhà vua và niêm bửu ấn thì không thể thu hồi.” (9) Các ký lục nhà vua được triệu đến. Lúc đó là tháng thứ ba, tức là tháng Xi-van, ngày hai mươi ba. Theo đúng lệnh của ông Moóc-đo-khai, họ soạn thảo công văn gửi cho người Do-thái, cho các thủ hiến, các tổng đốc và các quan chức các miền từ Ấn-độ cho đến Ê-thi-óp. Có một trăm hai mươi bảy miền, miền nào theo chữ viết của miền ấy, dân nào theo tiếng nói của dân ấy, người Do-thái theo chữ viết và tiếng nói của họ. (10) Các công văn được soạn thảo nhân danh vua A-suê-rô và niêm bửu ấn, rồi các phu trạm chuyển đi. Họ cỡi những con ngựa nhanh nhất nuôi trong chuồng nhà vua. (11) Vua cho người Do-thái ở trong bất cứ thành nào được quyền tụ họp để bảo vệ sinh mạng, để hủy diệt, giết chết và tru diệt tất cả những kẻ mang vũ khí đến tấn công họ, cho dù bọn người này thuộc sắc dân nào hay ở miền nào đi nữa, kể cả vợ con chúng; họ cũng được quyền cướp đoạt của cải của bọn chúng. (12) Lệnh này phải thi hành tại khắp các miền thuộc quyền vua A-suê-rô nội trong một ngày; đó là ngày mười ba tháng thứ mười hai, tức là tháng A-đa.
[SECTION] Sắc chỉ phục hồi quyền của người Do-thái
(12a) Đoạn văn sau đây là bản sao công văn:
(12b) “Đại vương A-suê-rô gửi các tổng đốc cai trị một trăm hai mươi bảy tỉnh từ Ấn-độ đến Ê-thi-óp, và gửi những trung thần quan tâm đến quốc sự. Chúc chư khanh vạn an.
(12c) Có lắm kẻ khi được các bậc ân nhân lấy lòng từ ái bao la mà đối xử thì sinh thói kiêu căng. Chẳng những chúng mưu hại thần dân ta, mà vì chưa thỏa mãn với danh vọng dư đầy, chúng còn nuôi ý đồ tra tay hại chính các ân nhân của mình. (12d) Chúng loại trừ tâm tình biết ơn ra khỏi lòng người. Không những thế, sau khi bị cuốn hút theo lời lẽ ba hoa của những kẻ không biết gì đến sự thiện, chúng còn cứ tưởng mình sẽ thoát được án công minh của Thiên Chúa là Đấng hằng nhìn thấy mọi sự và gớm ghét sự dữ. Nhiều kẻ cầm quyền đã trao việc triều chính cho bạn bè tín cẩn, và biết bao phen vì nghe theo họ mà trở thành đồng lõa trong việc đổ máu người vô tội để rồi bị lôi kéo vào những tai họa không sao thoát khỏi. (12e) Chẳng qua là vì những tên bịp bợm ấy đã dùng mưu mô thâm độc mà lừa dối các bậc cầm quyền vốn có lòng ưu ái chân thật. (12g) Không cần dùng những chuyện cổ xưa truyền lại, các khanh có thể nhìn vào những điều tai nghe mắt thấy ngày nay mà nhận ra rằng lũ ôn dịch nắm việc triều chính kia đã mưu toan phạm biết bao tội ác. (12h) Ta sẽ chú tâm đến tương lai, lo sao cho mọi người trong vương quốc được bình an thư thái. (12i) Ta sẽ thực hiện nhiều cải cách, luôn niềm nở tiếp nhận và xét xử những vụ sẽ đệ trình lên ta.
(12k) Riêng Ha-man, con của Hăm-mơ-đa-tha người Ma-kê-đô-ni-a, y thực là một người xa lạ đối với đồng bào Ba-tư, lại còn xa lạ hơn nữa đối với một người có lòng từ ái như ta, nhưng đã được ta đón tiếp như một khách quý. (12l) Y còn được hưởng lòng nhân nghĩa ta vốn dành cho mọi dân tộc đến mức được công khai gọi là quốc phụ và được mọi người bái lạy như nhân vật chiếm địa vị thứ hai sau ngai vàng. (12m) Nhưng vì không thắng nổi tính kiêu căng, y đã tìm cách làm cho ta mất cả quyền bính lẫn tính mạng. (12n) Y đã dùng những thủ đoạn tinh vi và những lập luận quanh co mà xin tiêu diệt vị cứu tinh và ân nhân của ta là Moóc-đo-khai; đồng thời, với chính những thủ đoạn và lập luận trên, y còn tiêu diệt con người đức hạnh đã cùng ta chia sẻ địa vị cao sang trong vương quốc là Ét-te, và xin tiêu diệt cả dân tộc của hai nhân vật đó. (12o) Hành động như thế, y tưởng có thể đưa ta vào thế cô lập và phải chuyển quyền cai trị của người Ba-tư sang tay người Ma-kê-đô-ni-a.
(12p) Nhưng ta nhận thấy rằng dân Do-thái mà tên cực kỳ gian ác đó muốn tận diệt không phải là những tội phạm, trái lại họ chính là những người có luật lệ rất công minh hướng dẫn. (12q) Họ là con cái Thiên Chúa Tối Cao, vĩ đại, hằng sống, Đấng vẫn giữ gìn cho vương quốc của ta và của tổ tiên ta được hưng thịnh. (12r) Vậy không thi hành những công văn mà Ha-man, con của Hăm-mơ-đa-tha đã gửi là chư khanh làm đúng, vì kẻ thảo ra các công văn đó đã bị treo cổ cùng với cả nhà y tại cửa thành Su-san. Thế là Thiên Chúa, chủ tể muôn loài, đã xét xử công minh mà không trì hoãn. (12s) Bản sao sắc chỉ này, chư khanh phải công khai niêm yết khắp nơi, đồng thời chư khanh phải để cho người Do-thái sống theo luật lệ riêng của họ; cũng phải tăng cường lực lượng giúp họ đẩy lui những kẻ sẽ đến tấn công họ trong ngày gian truân, ngày mười ba tháng thứ mười hai tức là tháng A-đa. (12t) Quả thật, Thiên Chúa, Đấng làm chủ vạn vật, đã biến ngày ấy thành ngày hoan lạc cho dân tộc được tuyển chọn thay thế ngày tận diệt dân tộc này. (12u) Còn các ngươi, hỡi người Do-thái, hãy tổ chức các cuộc liên hoan mà mừng ngày đặc biệt ấy như một trong những ngày lễ trọng của các ngươi. Như thế, trong hiện tại cũng như tương lai, đối với ta và những người Ba-tư thành tâm thiện chí, ngày ấy trở thành ngày kỷ niệm cuộc giải thoát; còn đối với những kẻ âm mưu chống lại ta, ngày ấy sẽ là ngày nhắc nhở cảnh diệt vong của chúng.
(12v) Thành nào và nói chung miền nào bất cứ không chịu thi hành chỉ thị này là chọc giận ta, ta sẽ dùng gươm, dùng lửa tiêu diệt hết. Nơi đó chẳng những sẽ không có bóng người qua lại, mà cả đến muông thú, chim trời cũng ghét bỏ và mãi mãi tránh xa.”
(13) Sắc chỉ này được công bố và có hiệu lực luật pháp trong mọi miền. Bản sao cũng được phổ biến cho mọi dân tộc, để vào ngày ấn định, người Do-thái sẵn sàng trả đũa địch thù. (14) Theo lệnh vua, phu trạm cỡi ngựa nhanh nhất nuôi trong chuồng nhà vua tức tốc lên đường. Sắc chỉ được công bố tại thành Su-san. (15) Ông Moóc-đo-khai rời hoàng cung, mặc triều phục bằng vải trắng điểm màu đỏ tía, đội triều thiên lớn bằng vàng, khoác cẩm bào bằng vải quý màu đỏ tươi. Dân chúng khắp thành Su-san đều reo vui mừng rỡ. (16) Đối với dân Do-thái, ngày ấy là một ngày tràn ngập ánh sáng, chan chứa vui mừng, hân hoan và vinh dự. (17) Trong mỗi miền và mỗi thành, bất cứ nơi đâu, mệnh lệnh và chỉ dụ của vua được chuyển tới, người ta đều chứng kiến cảnh tượng dân Do-thái vui sướng hân hoan mở tiệc ăn mừng. Giữa các dân trong xứ, nhiều người tự xưng là Do-thái vì quá sợ người Do-thái.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'et', 9, '[SECTION] Ngày Pu-rim
(1) Ngày mười ba tháng thứ mười hai, tức là tháng A-đa, mệnh lệnh và chỉ dụ của vua đến lúc phải thi hành. Trong ngày kẻ thù của người Do-thái mong thắng được họ, thì người Do-thái đã lật ngược thế cờ: chính họ đã thắng những kẻ thù ghét họ. (2) Người Do-thái tụ họp lại trong các thành của họ, trong mọi miền thuộc quyền vua A-suê-rô, để tra tay hại những kẻ mưu hại họ. Không ai dám đương đầu với họ, vì các dân đều khiếp sợ người Do-thái. (3) Mọi quan chức các miền, mọi tổng đốc và công chức nhà vua đều yểm trợ người Do-thái vì rất sợ ông Moóc-đo-khai. (4) Quả thế, ông Moóc-đo-khai là nhân vật có thế lực trong hoàng cung và danh tiếng của ông lan ra khắp mọi miền. Quả thế, uy tín của ông Moóc-đo-khai ngày càng lớn.
(5) Người Do-thái dùng gươm đâm chém hết mọi địch thù của họ. Đó là một cuộc tàn sát, một cuộc tận diệt. Họ đối xử tùy thích với những kẻ thù ghét họ. (6) Trong thành Su-san, có đến năm trăm người bị giết chết, bị tận diệt. (7) Ngoài ra họ còn giết Pác-san-đa-tha, Đa-lơ-phôn, Át-pa-tha, (8) Pô-ra-tha, A-đan-gia, A-ri-đa-tha, (9) Pác-mát-ta, A-ri-xai, A-ri-đai và Vai-da-tha, (10) tức là mười người con của Ha-man, cháu ông Hăm-mơ-đa-tha. Ha-man vốn là cừu địch của người Do-thái. Nhưng những người này không tra tay cướp của.
(11) Chính ngày ấy, con số những người bị giết trong thành Su-san được đệ trình lên vua. (12) Vua nói với hoàng hậu Ét-te: “Nội trong thành Su-san, người Do-thái đã giết chết, đã tận diệt năm trăm người cùng với mười người con của Ha-man; thế thì họ đã làm gì trong các miền khác thuộc quyền vua? Khanh thỉnh cầu gì, ta sẽ ban cho; khanh có muốn xin gì nữa thì cũng sẽ được.” (13) Bà Ét-te thưa: “Nếu đẹp lòng đức vua, xin ban phép cho người Do-thái ở Su-san ngày mai cũng được hành động như sắc chỉ đã cho phép hành động ngày hôm nay; còn mười đứa con của Ha-man thì xin treo cổ chúng lên giá.” (14) Vua truyền làm như thế. Một sắc chỉ được công bố ở Su-san, và mười người con của Ha-man bị treo cổ. (15) Người Do-thái ở Su-san tụ họp lại cả ngày mười bốn tháng A-đa nữa và ở đó đã giết thêm ba trăm người. Nhưng họ đã không tra tay cướp của.
(16) Những người Do-thái khác trong các miền thuộc quyền vua cũng tụ họp lại để tự bảo vệ tính mạng và sống yên ổn, không sợ địch thù nữa. Họ đã giết bảy mươi lăm ngàn kẻ thù ghét họ, nhưng không tra tay cướp của. (17) Đó là ngày mười ba tháng A-đa. Ngày mười bốn cùng tháng, họ nghỉ ngơi và biến ngày này thành một ngày tiệc tùng vui vẻ. (18) Còn những người Do-thái ở Su-san thì tụ họp lại ngày mười ba và ngày mười bốn tháng ấy; họ nghỉ ngơi ngày mười lăm và biến ngày này thành một ngày tiệc tùng vui vẻ. (19) Vì thế những người Do-thái ở thôn quê và các thị trấn không phòng thủ thì biến ngày mười bốn tháng A-đa thành một ngày vui vẻ tiệc tùng, một ngày hội hè lễ lạt; ngày đó họ gửi phần ăn cho nhau. (19a) Còn những người ở thành phố thì hân hoan mừng ngày mười lăm tháng A-đa như ngày lễ; ngày đó, họ cũng gửi phần ăn cho người thân cận.
[PART] V. NGÀY LỄ PU-RIM
[SECTION] Thiết lập ngày Pu-rim
(20) Ông Moóc-đo-khai ghi chép các sự việc đó và gửi thư cho mọi người Do-thái trong khắp các miền thuộc quyền vua A-suê-rô, kẻ ở gần cũng như người ở xa. (21) Ông truyền cho họ hằng năm phải biến ngày mười bốn và ngày mười lăm tháng A-đa (22) thành những ngày người Do-thái được sống yên ổn, không phải sợ hãi thù địch. Ông cũng truyền phải mừng tháng A-đa: tháng đó, phiền muộn biến thành hân hoan, ngày tang tóc trở nên ngày đại lễ. Họ phải biến những ngày ấy thành những ngày tiệc tùng vui vẻ, một cơ hội gửi phần ăn cho nhau và quà tặng cho người nghèo. (23) Những điều người Do-thái bắt đầu giữ và những gì ông Moóc-đo-khai đã viết cho họ, thì họ công nhận làm tập tục. (24) Quả thế, cừu địch của mọi người Do-thái là Ha-man, con ông Hăm-mơ-đa-tha người A-gác, đã âm mưu chống lại người Do-thái nhằm tận diệt họ; y đã gieo “Pua” (nghĩa là bắt thăm) để loại trừ và tận diệt họ. (25) Nhưng khi bà Ét-te đến trước mặt vua, thì vua ban sắc chỉ truyền rằng: âm mưu độc ác Ha-man đã nghĩ ra để chống người Do-thái phải quay lại giáng xuống đầu y; y cùng với các con phải bị treo cổ lên giá. (26) Vì vậy, người ta gọi những ngày này Pu-rim, do tiếng “Pua”. Cũng vì mọi lời viết trong lá thư trên, vì những gì liên quan đến sự việc họ đã chứng kiến, và vì những chuyện đã xảy đến cho họ, (27) nên người Do-thái đã quy định và công nhận việc sau đây làm tập tục không thể hủy bỏ được đối với họ cũng như dòng dõi họ và tất cả những ai liên kết với họ: hằng năm, họ phải mừng hai ngày đó theo như đã ghi chép và vào thời gian đã ấn định. (28) Đời đời, phải kỷ niệm và mừng những ngày đó trong mỗi gia đình, mỗi miền và mỗi thành. Người Do-thái không được bãi bỏ những ngày Pu-rim ấy, cũng không được để cho dòng dõi họ quên những ngày ấy.
(29) Hoàng hậu Ét-te, ái nữ của ông A-vi-kha-gin, cùng với ông Moóc-đo-khai người Do-thái, lấy tất cả uy tín của mình mà viết văn thư phê chuẩn văn thư thứ hai trên đây về lễ Pu-rim. (30) Ông Moóc-đo-khai đã gửi các văn thư ấy đến tất cả mọi người Do-thái ở một trăm hai mươi bảy tỉnh trong vương quốc của vua A-suê-rô kèm theo những lời lẽ chân thành cầu chúc bình an. (31) Mục đích của văn thư ấy là để thiết lập những ngày lễ Pu-rim vào đúng thời gian như ông Moóc-đo-khai người Do-thái và hoàng hậu Ét-te đã ấn định cho họ và theo đúng cách thức các vị ấy đã quy định cho họ và dòng dõi họ về việc ăn chay và kêu cầu. (32) Như thế, lệnh của bà Ét-te đã phê chuẩn các điều liên hệ đến lễ Pu-rim và đã được ghi vào sách.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'et', 10, '[SECTION] Ca ngợi ông Moóc-đo-khai
(1) Vua A-suê-rô bắt cư dân ở đất liền cũng như ở hải đảo phải nộp thuế. (2) Mọi sự việc diễn tả uy quyền của vua, mọi chiến công của vua, bài tường thuật về chức vị cao cả mà vua đã phong cho ông Moóc-đo-khai, tất cả đã chẳng được ghi chép trong sách Sử Biên Niên các vua Mê-đi và Ba-tư đó sao?
(3) Quả thật ông Moóc-đo-khai người Do-thái, quan đệ nhị của vua A-suê-rô, là nhân vật có uy thế lớn đối với người Do-thái, và được đông đảo đồng bào của ông quý mến. Ông không ngừng mưu cầu lợi ích cho dân ông và hằng chăm lo cho cả nòi giống được hưởng thái bình.
(3a) Ông Moóc-đo-khai nói: “Các điều xảy ra trên đây đều do bàn tay Thiên Chúa. (3b) Thật thế, khi tôi nhớ lại những gì đã thấy trong giấc chiêm bao về các sự việc này, thì quả không có gì đã bị bỏ sót: (3c) một con suối nhỏ đã thành sông; rồi có ánh sáng, có mặt trời, có nước dồi dào. Ét-te là con sông ấy; vua đã cưới nàng và phong làm hoàng hậu. (3d) Còn hai con rồng là tôi và Ha-man. Các dân tộc là những dân đã cấu kết với nhau nhằm hủy diệt tên của người Do-thái; (3e) còn dân của tôi là Ít-ra-en, những người đã kêu cầu Thiên Chúa và đã được cứu thoát. Đức Chúa đã cứu dân Người, Đức Chúa đã giải thoát chúng tôi khỏi tất cả những tai họa ấy. Thiên Chúa đã làm những điềm thiêng dấu lạ lớn lao chưa từng xảy ra nơi các dân tộc. (3g) Vì thế, Người đã làm ra hai số phận: một dành cho dân Thiên Chúa, và một dành cho mọi dân tộc. (3h) Hai số phận ấy đã được thể hiện cho mọi dân tộc vào đúng giờ, đúng buổi, đúng ngày Thiên Chúa đã ấn định. (3i) Và Thiên Chúa đã nhớ đến dân Người, đã trả lại quyền lợi chính đáng cho dân Người chọn làm cơ nghiệp. (3k) Đối với họ, qua mọi thế hệ và cho đến muôn đời, những ngày ấy trong tháng A-đa, tức là ngày mười bốn và ngày mười lăm, sẽ là những ngày hội đầy hân hoan vui sướng trước nhan Thiên Chúa, trong dân của Người là Ít-ra-en.
[SECTION] Lời ghi chú về bản dịch Hy-lạp
(3l) Năm thứ tư, triều đại vua Pơ-tô-lê-mai và bà Cơ-lê-ô-pát, ông Đô-xi-thê xưng mình là tư tế và thầy Lê-vi cùng với con ông là Pơ-tô-lê-mai, đã mang đến bức thư trên đây về lễ Pu-rim. Các ông ấy nói: đây chính là bức thư đó, và người phiên dịch là ông Ly-xi-ma-khô, con ông Pơ-tô-lê-mai, cư dân thành Giê-ru-sa-lem.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;