INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'er', 1, '[PART] I. HỒI HƯƠNG SAU THỜI LƯU ĐÀY. TÁI THIẾT ĐỀN THỜ.
[SECTION] Dân Xi-on trở về
(1) Năm thứ nhất thời vua Ky-rô trị vì nước Ba-tư, để lời ĐỨC CHÚA phán qua miệng ngôn sứ Giê-rê-mi-a được hoàn toàn ứng nghiệm, ĐỨC CHÚA tác động trên tâm trí Ky-rô, vua Ba-tư. Vua thông báo cho toàn vương quốc và ra sắc chỉ như sau: (2) “Ky-rô, vua Ba-tư, phán thế này: ĐỨC CHÚA, Thiên Chúa trên trời, đã ban cho ta mọi vương quốc dưới đất. Chính Người đã trao cho ta trách nhiệm tái thiết cho Người một ngôi Nhà ở Giê-ru-sa-lem tại Giu-đa. (3) Vậy ai trong các ngươi thuộc dân Người, thì xin Thiên Chúa của họ ở với họ, và họ hãy lên Giê-ru-sa-lem tại Giu-đa và xây Nhà ĐỨC CHÚA, Thiên Chúa của Ít-ra-en. Chính Người là Thiên Chúa ngự tại Giê-ru-sa-lem. (4) Và mọi người còn lại ở bất cứ nơi nào họ đang trú ngụ, phải được dân địa phương cấp cho bạc vàng, của cải và thú vật, cũng như lễ vật tự nguyện, để dâng cúng cho Nhà Thiên Chúa ở Giê-ru-sa-lem
(5) Những người đứng đầu các gia tộc của Giu-đa và Ben-gia-min, các tư tế và các thầy Lê-vi, tất cả những người được Thiên Chúa tác động trên tâm trí, trỗi dậy để đi lên xây Nhà ĐỨC CHÚA ở Giê-ru-sa-lem. (6) Mọi người hàng xóm láng giềng đều mạnh tay giúp họ: bạc, vàng, của cải, thú vật, những đồ vật có giá, không kể mọi lễ vật tự nguyện.
(7) Vua Ky-rô cho người đem ra ngoài những đồ vật thuộc Nhà ĐỨC CHÚA, mà vua Na-bu-cô-đô-nô-xo đã cho người đem ra khỏi Giê-ru-sa-lem và đặt trong thần miếu của nhà vua. (8) Ky-rô, vua Ba-tư, đã nhờ viên thủ quỹ Mít-rơ-đát đem những đồ vật ấy ra ngoài. Viên thủ quỹ kiểm kê và giao cho ông Sết-bát-xa là thủ lãnh xứ Giu-đa. (9) Đây là số các đồ vật: ba mươi chén vàng, một ngàn chén bạc, hai mươi chín con dao, (10) ba mươi tô vàng, bốn trăm mười tô bạc loại thường, một ngàn đồ vật khác. (11) Tổng số các đồ vật bằng vàng và bằng bạc là năm ngàn bốn trăm. Ông Sết-bát-xa mang theo tất cả các đồ vật đó, khi ông đưa những người lưu đày từ Ba-by-lon lên Giê-ru-sa-lem.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'er', 2, '[SECTION] Danh sách những người Xi-on hồi hương
(1) Đây là những người trong miền đã từ chốn lưu đày hồi hương. Họ là những người mà Na-bu-cô-đô-nô-xo, vua Ba-by-lon đã bắt đi đày sang Ba-by-lon. Họ trở về Giê-ru-sa-lem và Giu-đa, ai về thành nấy. (2) Họ về cùng với các ông Dơ-rúp-ba-ven, Giê-su-a, Nơ-khe-mi-a, Xơ-ra-gia, Rơ-ê-la-gia, Moóc-đo-khai, Bin-san, Mít-pa, Bích-vai, Rơ-khum, Ba-a-na.
Đây là số những người thuộc dân Ít-ra-en: (3) con cái ông Pác-ốt: hai ngàn một trăm bảy mươi hai; (4) con cái ông Sơ-phát-gia: ba trăm bảy mươi hai; (5) con cái ông A-rác: bảy trăm bảy mươi lăm; (6) con cái ông Pa-khát Mô-áp, tức là con cái ông Giê-su-a và ông Giô-áp: hai ngàn tám trăm mười hai; (7) con cái ông Ê-lam: một ngàn hai trăm năm mươi bốn; (8) con cái ông Dát-tu: chín trăm bốn mươi lăm; (9) con cái ông Dắc-cai: bảy trăm sáu mươi; (10) con cái ông Ba-ni: sáu trăm bốn mươi hai; (11) con cái ông Bê-vai: sáu trăm hai mươi ba; (12) con cái ông Át-gát: một ngàn hai trăm hai mươi hai; (13) con cái ông A-đô-ni-cam: sáu trăm sáu mươi sáu; (14) con cái ông Bích-vai: hai ngàn không trăm năm mươi sáu; (15) con cái ông A-đin: bốn trăm năm mươi bốn; (16) con cái ông A-te, tức là con cái ông Giơ-khít-ki-gia: chín mươi tám; (17) con cái ông Bê-xai: ba trăm hai mươi ba; (18) con cái ông Giô-ra: một trăm mười hai; (19) con cái ông Kha-sum: hai trăm hai mươi ba; (20) con cái ông Ghíp-ba: chín mươi lăm; (21) con cái ông Bê-lem: một trăm hai mươi ba; (22) người Nơ-tô-pha: năm mươi sáu; (23) người A-na-thốt: một trăm hai mươi tám; (24) con cái ông Át-ma-vét: bốn mươi hai; (25) con cái ông Kia-giát A-rim: ông Cơ-phi-ra và ông Bơ-ê-rốt: bảy trăm bốn mươi ba; (26) con cái ông Ra-ma và ông Ghe-va: sáu trăm hai mươi mốt; (27) người Mích-mát: một trăm hai mươi hai; (28) người Bết Ên và người Ai: hai trăm hai mươi ba; (29) con cái ông Nơ-vô: năm mươi hai; (30) con cái ông Mác-bít: một trăm năm mươi sáu; (31) con cái ông Ê-lam khác: một ngàn hai trăm năm mươi bốn; (32) con cái ông Kha-rim: ba trăm hai mươi; (33) con cái các ông Lốt, Kha-đích và Ô-nô: bảy trăm hai mươi lăm; (34) con cái ông Giê-ri-khô: ba trăm bốn mươi lăm; (35) con cái ông Xơ-na-a: ba ngàn sáu trăm ba mươi.
(36) Các tư tế: con cái ông Giơ-đa-gia thuộc nhà ông Giê-su-a: chín trăm bảy mươi ba; (37) con cái ông Im-me: một ngàn không trăm năm mươi hai; (38) con cái ông Pát-khua: một ngàn hai trăm bốn mươi bảy; (39) con cái ông Kha-rim: một ngàn không trăm mười bảy.
(40) Các thầy Lê-vi: con cái các ông Giê-su-a và Cát-mi-ên, tức là con cái ông Hô-đáp-gia: bảy mươi bốn.
(41) Các ca viên: con cái ông A-xáp: một trăm hai mươi tám.
(42) Con cái những người giữ cửa: con cái ông Sa-lum, con cái ông A-te, con cái ông Tan-môn, con cái ông Ắc-cúp, con cái ông Kha-ti-ta, con cái ông Sô-vai: tất cả là một trăm ba mươi chín.
(43) Những người phục vụ Đền Thờ: con cái Xi-kha, con cái Kha-xu-pha, con cái Táp-ba-ốt, (44) con cái Kê-rốt, con cái Xi-a, con cái Pa-đôn, (45) con cái Lơ-va-na, con cái Kha-ga-va, con cái Ắc-cúp, (46) con cái Kha-gáp, con cái San-mai, con cái Kha-nan, (47) con cái Ghít-đên, con cái Ga-kha, con cái Rơ-a-gia, (48) con cái Rơ-xin, con cái Nơ-cô-đa, con cái Gát-dam, (49) con cái Út-da, con cái Pa-xê-ác, con cái Bê-xai, (50) con cái Át-na, con cái người Mơ-u-nim, con cái người Nơ-phu-xim, (51) con cái Bác-búc, con cái Kha-cúp-pha, con cái Khác-khua, (52) con cái Bát-lút, con cái Mơ-khi-đa, con cái Khác-sa, (53) con cái Bác-cốt, con cái Xít-ra, con cái Te-mác, (54) con cái Nơ-xi-ác, con cái Kha-ti-pha.
(55) Con cái những người nô lệ của vua Sa-lô-môn: con cái Xô-tai, con cái Ha Xô-phe-rét, con cái Pơ-ru-đa, (56) con cái Gia-la, con cái Đác-côn, con cái Ghít-đên, (57) con cái Sơ-phát-gia, con cái Khát-tin, con cái Pô-khe-rét Ha Xơ-va-gim, con cái A-mi. (58) Tổng số những người phục vụ Đền Thờ và con cái những người nô lệ của vua Sa-lô-môn là ba trăm chín mươi hai.
(59) Con cái những người trở về từ Ten Me-lác, Ten Khác-sa, Cơ-rúp, Át-đan, Im-me. Họ không thể dựa vào gia tộc và dòng giống của họ để cho biết có thuộc về Ít-ra-en hay không: (60) con cái Đơ-la-gia, con cái Tô-vi-gia, con cái Nơ-cô-đa: sáu trăm năm mươi hai. (61) Trong số con cái các tư tế, có: con cái ông Khô-va-gia, con cái ông Hắc-cốt, con cái ông Bác-di-lai là người đã lấy một trong các con gái ông Bác-di-lai, người Ga-la-át, nên đã mang tên ông ấy. (62) Những người này đã tìm kiếm tên của họ trong cuốn gia phả, nhưng không thấy, nên đã bị loại ra khỏi hàng tư tế, vì bị coi là ô uế. (63) Quan tổng đốc cấm họ không được ăn của thánh, cho đến khi có một tư tế đứng lên xem thẻ xăm U-rim và Tum-mim.
(64) Toàn thể cộng đồng là bốn mươi hai ngàn ba trăm sáu mươi người, (65) không kể tôi trai tớ gái của họ lên tới bảy ngàn ba trăm ba mươi bảy người. Họ cũng có hai trăm nam nữ ca viên. (66) Họ có bảy trăm ba mươi sáu con ngựa, hai trăm mười lăm con la, (67) bốn trăm ba mươi lăm con lạc đà và sáu ngàn bảy trăm hai mươi con lừa.
(68) Khi về đến Nhà ĐỨC CHÚA ở Giê-ru-sa-lem, một số người đứng đầu các gia tộc dâng cúng những lễ vật tự nguyện cho Nhà Thiên Chúa, để tái thiết Nhà đó ở chỗ cũ. (69) Theo khả năng, họ đã dâng vào quỹ dùng cho công trình đó sáu mươi mốt ngàn quan tiền, hai ngàn năm trăm ký bạc và một trăm bộ phẩm phục tư tế.
(70) Các tư tế, các thầy Lê-vi và một phần dân chúng ở tại Giê-ru-sa-lem; còn các ca viên, những người giữ cửa, những người phục vụ Đền Thờ thì ở trong các thành của họ; mọi người Ít-ra-en khác cũng ở trong các thành của họ.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'er', 3, '[SECTION] Tái lập việc phụng tự
(1) Đến tháng thứ bảy, lúc con cái Ít-ra-en đang ở trong thành của họ, thì dân họp nhau tại Giê-ru-sa-lem, muôn người như một. (2) Ông Giê-su-a con ông Giô-xa-đắc, cùng với các tư tế, anh em của ông, và ông Dơ-rúp-ba-ven, con ông San-ti-ên, cùng với anh em của ông đứng ra xây bàn thờ Thiên Chúa Ít-ra-en, để dâng trên đó các lễ toàn thiêu, như đã chép trong Luật của ông Mô-sê, người của Thiên Chúa. (3) Họ dựng lại bàn thờ vào đúng vị trí, vì họ sợ các dân trong xứ. Trên đó, họ dâng lên ĐỨC CHÚA lễ toàn thiêu ban sáng và ban chiều. (4) Như lời đã chép, họ cử hành lễ Lều, dâng lễ toàn thiêu ngày này qua ngày khác theo số đã quy định cho mỗi ngày. (5) Sau đó, họ dâng lễ toàn thiêu thường tiến, lễ toàn thiêu vào các ngày sóc và mọi đại lễ kính ĐỨC CHÚA, và lễ toàn thiêu của tất cả những người dâng cúng ĐỨC CHÚA lễ vật tự nguyện. (6) Từ mồng một tháng bảy, họ bắt đầu dâng lễ toàn thiêu kính ĐỨC CHÚA, mặc dầu chưa đặt nền móng cho Đền Thờ của ĐỨC CHÚA.
(7) Họ cấp bạc cho thợ đá, thợ mộc, cấp thức ăn thức uống và dầu cho người Xi-đôn và Tia, để họ chở gỗ bá hương từ Li-băng, qua đường biển, về Gia-phô, theo phép Ky-rô, vua Ba-tư, đã ban. (8) Vào năm thứ hai, sau khi họ về đến Nhà Thiên Chúa ở Giê-ru-sa-lem, trong tháng thứ hai, ông Dơ-rúp-ba-ven, con ông San-ti-ên, và ông Giê-su-a, con ông Giô-xa-đắc, cùng với các anh em còn lại, các tư tế, các thầy Lê-vi và tất cả những người lưu đày trở về Giê-ru-sa-lem, khởi công và giao phó cho các thầy Lê-vi từ hai mươi tuổi trở lên điều khiển công việc xây Nhà ĐỨC CHÚA. (9) Ông Giê-su-a với con cái và anh em ông, ông Cát-mi-ên và con cái, con cái ông Hô-đáp-gia, con cái ông Khê-na-đát, con cái và anh em của họ, các thầy Lê-vi, cùng nhau điều khiển thợ làm việc tại Nhà Thiên Chúa. (10) Khi thợ xây nhà đặt nền móng Đền Thờ của ĐỨC CHÚA, thì các tư tế, y phục chỉnh tề, tay cầm kèn, và các thầy Lê-vi, con cái ông A-xáp, tay cầm chũm chọe, đứng ở đó mà ca tụng ĐỨC CHÚA, theo như vua Đa-vít, vua Ít-ra-en, đã quy định. (11) Họ luân phiên xướng đáp mà ca tụng và cảm tạ ĐỨC CHÚA: “Vì Chúa nhân từ, muôn ngàn đời Chúa vẫn trọn tình thương đối với Ít-ra-en!” Toàn dân lớn tiếng reo hò ca tụng ĐỨC CHÚA, vì bấy giờ Nhà ĐỨC CHÚA đã có nền móng. (12) Nhiều tư tế và thầy Lê-vi, nhiều người đứng đầu gia tộc nay lớn tuổi, là những người đã thấy Nhà Thiên Chúa trước kia, khóc to tiếng khi thấy người ta đặt nền móng Nhà mới này trước mắt họ; nhưng cũng có nhiều người khác cất tiếng reo hò vui sướng. (13) Không ai có thể phân biệt được tiếng reo hò vui sướng với tiếng khóc của dân, vì dân lớn tiếng reo hò và tiếng họ vọng đi xa.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'er', 4, '[SECTION] Dưới thời vua Ky-rô, người Sa-ma-ri cản trở việc tái thiết.
(1) Khi nghe tin là các người lưu đày trở về đang xây một Đền Thờ kính ĐỨC CHÚA, Thiên Chúa của Ít-ra-en, (2) thì những kẻ thù của Giu-đa và Ben-gia-min đến gặp ông Dơ-rúp-ba-ven, và những người đứng đầu các gia tộc, mà nói: “Chúng tôi muốn được cùng xây với các ông, bởi cũng như các ông, chúng tôi tìm kiếm Thiên Chúa của các ông, và dâng lễ tế kính Người, từ ngày Ê-xa-khát-đôn, vua Át-sua, đem chúng tôi lên đây.” (3) Ông Dơ-rúp-ba-ven, ông Giê-su-a và những người khác, là những người đứng đầu các gia tộc Ít-ra-en, bảo họ: “Việc xây Nhà cho Thiên Chúa chúng tôi không phải là việc chung của các ông và chúng tôi, vì chỉ có chúng tôi sẽ xây cho ĐỨC CHÚA, Thiên Chúa của Ít-ra-en, theo lệnh vua Ky-rô, vua Ba-tư, đã ban cho chúng tôi.” (4) Khi đó, dân trong xứ bắt đầu làm cho dân Giu-đa bủn rủn tay chân và sợ hãi, để họ không xây cất nữa. (5) Chúng mua chuộc các cố vấn, để làm hỏng ý định của dân Giu-đa trong suốt thời vua Ky-rô, vua Ba-tư, mãi cho đến triều vua Đa-ri-ô, vua Ba-tư.
[SECTION] Dưới thời vua Xéc-xét và vua Ác-tắc-sát-ta, người Sa-ma-ri cản trở việc tái thiết
(6) Dưới triều vua Xéc-xét, vào thời đầu triều đó, chúng viết một bản cáo tội dân cư Giu-đa và Giê-ru-sa-lem.
(7) Vào thời vua Ác-tắc-sát-ta, Bít-lam, Mít-rơ-đát, Táp-ên, và các bạn đồng liêu khác đã viết cho vua Ác-tắc-sát-ta, vua Ba-tư. Bản văn ấy được viết bằng tiếng A-ram và được phiên dịch. Nguyên văn tiếng A-ram: (8) Rơ-khum, thủ hiến, và Sim-sai, thư ký, gửi lên vua Ác-tắc-sát-ta một bức thư tố cáo Giê-ru-sa-lem, với những lời lẽ như sau: (9) “Rơ-khum, thủ hiến, Sim-sai, thư ký, và các bạn đồng liêu khác, các thẩm phán và khâm sai, những người Tác-pơ-lai, E-réc, Ba-by-lon và Su-san, nghĩa là những người Ê-lam, (10) và các dân tộc khác mà vua Át-náp-pa vĩ đại và lừng danh đã bắt đi đày và cho định cư tại các thành của Sa-ma-ri và các miền khác thuộc Vùng bên kia sông Êu-phơ-rát, đồng tấu:
(11) (Đây là bản sao bức thư họ gửi:)
‘Tâu vua Ác-tắc-sát-ta, bầy tôi của đức vua, những người ở Vùng bên kia sông Êu-phơ-rát xin thưa:
Và bây giờ, (12) xin trình để đức vua tường: từ nơi đức vua, người Do-thái đã lên chỗ chúng tôi tại Giê-ru-sa-lem, và đang tái thiết cái thành phản loạn và xấu xa ấy; chúng dựng lại tường thành và đặt lại nền móng. (13) Vậy xin trình để đức vua tường: nếu thành ấy được tái thiết, tường thành được dựng lại, thì chúng sẽ không nộp cống vật, thuế má, thuế thông quá; và như vậy, cuối cùng nhà vua sẽ phải thiệt thòi. (14) Vậy, vì được hưởng lộc của triều đình, chúng tôi thấy không được phép ngồi nhìn đức vua bị nhục mạ; cho nên chúng tôi đệ lên đức vua bản tường trình này, (15) để người ta tra cứu sách Sử Biên Niên của tổ tiên đức vua. Trong sách Sử Biên Niên đó, đức vua sẽ tìm ra và nhận thấy rằng thành ấy là một thành phản loạn, làm thiệt hại cho nhà vua và các tỉnh; ở đó, từ thời xa xưa chúng đã làm loạn. Vì thế thành ấy đã bị tàn phá. (16) Chúng tôi xin trình để đức vua tường: nếu thành ấy được tái thiết, và tường thành được dựng lại, thì điều đó sẽ làm cho đức vua chẳng còn phần đất nào nữa trong Vùng bên kia sông Êu-phơ-rát.’”
(17) Vua gửi thư trả lời:
“Gửi lời vấn an quan thủ hiến Rơ-khum, thư ký Sim-sai và các đồng liêu cư ngụ ở Sa-ma-ri và ở các nơi khác trong Vùng bên kia sông Êu-phơ-rát!
Vậy bây giờ, (18) bức thư mà các ngươi đệ lên ta, đã được dịch và đọc trước mặt ta. (19) Theo lệnh ta, người ta đã tra cứu và tìm ra rằng từ thời xa xưa, thành ấy đã từng nổi dậy chống các vua, và những cuộc phản loạn, những cuộc nổi dậy đã từng diễn ra ở đó. (20) Ở Giê-ru-sa-lem đã có những vua hùng mạnh làm bá chủ khắp Vùng bên kia sông Êu-phơ-rát. Người ta đã nộp cho họ cống vật, thuế má, thuế thông quá. (21) Vì thế, các ngươi hãy ra lệnh cấm chúng không được tái thiết thành ấy, cho đến khi có lệnh ta ban. (22) Các ngươi hãy coi chừng chớ trễ nải công việc này, kẻo gây nhiều thiệt hại cho nhà vua.”
(23) Như thế, sau khi bản sao sắc chỉ của vua Ác-tắc-sát-ta được đọc trước mặt quan thủ hiến Rơ-khum, viên thư ký Sim-sai và các đồng liêu, thì những người này vội vàng đi Giê-ru-sa-lem gặp người Do-thái, và dùng vũ lực mà ngăn cản họ.
[SECTION] Xây Đền Thờ (520-515)
(24) Khi đó, công việc xây Nhà Thiên Chúa ở Giê-ru-sa-lem phải ngưng lại và ngưng lại mãi cho đến năm thứ hai triều vua Đa-ri-ô, vua Ba-tư.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'er', 5, '(1) Ngôn sứ Khác-gai và ngôn sứ Da-ca-ri-a, con ông Ít-đô, phát ngôn về người Do-thái ở Giu-đa và ở Giê-ru-sa-lem, nhân danh Thiên Chúa của Ít-ra-en, là Đấng ngự trên họ. (2) Bấy giờ, ông Dơ-rúp-ba-ven, con ông San-ti-ên, và ông Giê-su-a, con ông Giô-xa-đắc, đứng ra khởi sự xây Nhà Thiên Chúa ở Giê-ru-sa-lem, và có các ngôn sứ của Thiên Chúa trợ giúp các ông. (3) Vào chính thời ấy, ông Tát-nai, trưởng Vùng bên kia sông Êu-phơ-rát, ông Sơ-tha Bốt-nai và các đồng liêu đến gặp họ và nói với họ như sau: “Ai cho phép các ông tái thiết Nhà này, tu bổ ngôi nhà gỗ này?” (4) Bấy giờ những người ấy còn hỏi họ: “Tên của những người xây ngôi nhà này là gì?” (5) Nhưng Thiên Chúa của người Do-thái để mắt nhìn đến các kỳ mục của họ, nên người ta đã không đình chỉ công việc của họ, cho đến khi một bản báo cáo được đệ lên vua Đa-ri-ô, và sau đó có sắc chỉ phúc đáp về vụ này.
(6) Đây là bản sao bức thư của ông Tát-nai, trưởng Vùng bên kia sông Êu-phơ-rát, ông Sơ-tha Bốt-nai và các bạn đồng liêu, các khâm sai Vùng bên kia sông Êu-phơ-rát, đã đệ lên vua Đa-ri-ô. (7) Họ đã đệ lên vua một bản tường trình viết như sau:
“Tâu vua Đa-ri-ô, kính chúc đức vua vạn an! (8) Xin trình để đức vua tường: chúng tôi đã đi tới tỉnh Giu-đa, tới Nhà của Thiên Chúa cao cả. Nhà đó được xây bằng đá đẽo, có xà gỗ gác vào tường. Công trình ấy được thực hiện cách chu đáo và tiến triển tốt đẹp nhờ tay họ. (9) Bấy giờ chúng tôi đã hỏi các kỳ mục đó, chúng tôi đã nói với họ thế này: ‘Ai cho phép các ông tái thiết Nhà này, tu bổ nhà gỗ này?’ (10) Chúng tôi cũng hỏi tên của họ để đức vua tường, và đã ghi tên những người làm đầu họ.
(11) Đây là câu họ trả lời chúng tôi: ‘Chúng tôi là những tôi trung của Thiên Chúa, Chúa trời đất. Chúng tôi tái thiết ngôi Nhà đã được xây dựng xưa kia, cách đây lâu lắm rồi, một đại vương của Ít-ra-en đã xây lên và đã hoàn thành. (12) Nhưng vì cha ông chúng tôi làm cho Thiên Chúa, Chúa các tầng trời, phải nổi cơn thịnh nộ, nên Người đã trao họ vào tay vua Na-bu-cô-đô-nô-xo, người Can-đê, vua Ba-by-lon. Vua đã phá hủy Nhà này và đày dân sang Ba-by-lon. (13) Tuy thế, năm thứ nhất đời vua Ky-rô, vua Ba-by-lon, vua Ky-rô ra lệnh tái thiết Nhà này của Thiên Chúa. (14) Và hơn nữa, vua Ky-rô lấy ra khỏi đền thờ Ba-by-lon những đồ vàng đồ bạc thuộc Nhà Thiên Chúa, mà vua Na-bu-cô-đô-nô-xo đã lấy ra khỏi đền thờ Giê-ru-sa-lem và đưa về đền thờ Ba-by-lon. Rồi vua Ky-rô trao những đồ vật ấy cho một người tên là Sết-bát-xa mà vua đã đặt làm tổng trấn.’ (15) Vua nói với ông: ‘Ông hãy lấy những đồ vật ấy, mang đi và đặt lại ở đền thờ Giê-ru-sa-lem. Nhà Thiên Chúa phải được tái thiết ở chỗ cũ.’ (16) Bấy giờ, ông Sết-bát-xa đến đặt nền Nhà Thiên Chúa ở Giê-ru-sa-lem. Từ đó đến nay, Nhà ấy vẫn được tái thiết, nhưng chưa hoàn thành.
(17) Vậy bây giờ, nếu đức vua đồng ý, xin đức vua cho người tìm kiếm trong kho tàng của đức vua, ở bên đó, tại Ba-by-lon, để xem vua Ky-rô có thật sự ban lệnh tái thiết Nhà Thiên Chúa ở Giê-ru-sa-lem hay không? Xin đức vua gửi cho chúng tôi quyết định của ngài về vấn đề này.”') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'er', 6, '(1) Bấy giờ, vua Đa-ri-ô ra lệnh cho tìm kiếm trong kho tàng, nơi trữ các văn thư ở Ba-by-lon. (2) Người ta đã tìm thấy ở Ác-mơ-tha, thành trì nằm trong tỉnh Mê-đi, một cuộn da trên đó có viết:
“Bản ghi nhớ.
(3) Năm thứ nhất đời vua Ky-rô, vua Ky-rô ra lệnh:
Về vấn đề Nhà Thiên Chúa ở Giê-ru-sa-lem.
Nhà sẽ được tái thiết làm nơi dâng các hy lễ, và nền móng cũ sẽ được duy trì. Chiều cao của Nhà sẽ là ba mươi thước, chiều rộng ba mươi thước. (4) Sẽ có ba lớp đá đẽo và một lớp gỗ. Nhà vua sẽ lấy quỹ của triều đình đài thọ các chi phí. (5) Hơn nữa, những đồ vàng đồ bạc thuộc Nhà Thiên Chúa, mà vua Na-bu-cô-đô-nô-xo đã lấy ra khỏi đền thờ Giê-ru-sa-lem và đưa về Ba-by-lon, sẽ được trả lại, để các đồ vật ấy trở về chỗ cũ trong đền thờ Giê-ru-sa-lem và được đặt trong Nhà Thiên Chúa.”
(6) “Vậy bây giờ, Tát-nai, trưởng Vùng bên kia sông Êu-phơ-rát, Sơ-tha Bốt-nai và các đồng liêu, các khâm sai Vùng bên kia sông Êu-phơ-rát, các ngươi hãy rời xa nơi đó. (7) Hãy để cho tổng trấn của người Do-thái và các kỳ mục Do-thái lo việc xây cất Nhà Thiên Chúa, họ phải tái thiết Nhà Thiên Chúa ở chỗ cũ. (8) Đây là lệnh ta ban cho các ngươi về cách đối xử với hàng kỳ mục Do-thái trong việc tái thiết Nhà Thiên Chúa: phải lấy tiền bạc của nhà vua trích từ thuế thu được ở Vùng bên kia sông Êu-phơ-rát, mà cung cấp đầy đủ các chi phí cho những người đó, không được gián đoạn. (9) Theo lời chỉ dẫn của các tư tế Giê-ru-sa-lem, những gì cần cho lễ toàn thiêu kính Thiên Chúa, Chúa các tầng trời: bò tơ, chiên cừu, lúa miến, muối, rượu và dầu, ngày ngày sẽ được cung cấp cho họ, không được chểnh mảng, (10) để họ dâng lên Thiên Chúa, Chúa các tầng trời, các hy lễ làm đẹp lòng Người, và cầu cho nhà vua và các hoàng tử được trường thọ. (11) Ta còn ra lệnh: Bất kỳ ai vi phạm sắc chỉ này, thì phải dỡ xà gỗ nhà nó, làm cột đóng xuyên qua người nó mà dựng lên; và vì lý do ấy, hãy biến nhà nó thành đống phân dơ. (12) Chớ gì Thiên Chúa, Đấng đã đặt Danh Người ngự tại đó, lật đổ bất cứ vua hay dân nào dám vi phạm sắc chỉ này mà tra tay phá hủy Nhà Thiên Chúa ở Giê-ru-sa-lem. Chính ta, Đa-ri-ô, đã ban lệnh này. Sắc chỉ phải được thi hành chu đáo!”
(13) Bấy giờ, ông Tát-nai, trưởng Vùng bên kia sông Êu-phơ-rát, ông Sơ-tha Bốt-nai và các đồng liêu thi hành chu đáo các chỉ thị vua Đa-ri-ô gửi đến. (14) Hàng kỳ mục Do-thái tiếp tục xây cất và thành công trong việc đó, theo lời sấm của ngôn sứ Khác-gai và của ông Da-ca-ri-a con ông Ít-đô. Họ hoàn thành công việc xây cất đúng theo lệnh của Thiên Chúa Ít-ra-en và lệnh của vua Ky-rô, vua Đa-ri-ô, và vua Ác-tắc-sát-ta vua Ba-tư. (15) Nhà đó được xây xong ngày mồng ba tháng A-đa, năm thứ sáu triều vua Đa-ri-ô. (16) Con cái Ít-ra-en, các tư tế, các thầy Lê-vi và những người lưu đày trở về, hân hoan cử hành lễ khánh thành Nhà Thiên Chúa. (17) Để khánh thành Nhà Thiên Chúa, họ đã dâng một trăm con bò, hai trăm con cừu đực, bốn trăm con chiên, và bắt mười hai con dê đực, theo số các chi tộc Ít-ra-en, làm lễ tạ tội cho toàn thể Ít-ra-en. (18) Họ thiết lập hàng tư tế theo các phẩm trật của họ, và các thầy Lê-vi theo các cấp bậc của họ, để phục vụ Thiên Chúa tại Giê-ru-sa-lem, như đã chép trong sách Mô-sê.
[SECTION] Lễ Vượt Qua năm 515
(19) Những người đi đày trở về cử hành lễ Vượt Qua ngày mười bốn tháng thứ nhất. (20) Các thầy Lê-vi, trăm người như một, đã thanh tẩy mình: tất cả đều thanh sạch, nên họ đã sát tế chiên Vượt Qua cho những người đi đày trở về, cho anh em của họ là các tư tế, và cho chính họ. (21) Con cái Ít-ra-en đi đày trở về đã ăn mừng lễ Vượt Qua, cùng với những người đã dứt bỏ những điều ô uế của các dân trong xứ, để hợp với họ tìm kiếm ĐỨC CHÚA, Thiên Chúa của Ít-ra-en. (22) Họ hân hoan cử hành lễ Bánh Không Men trong bảy ngày, vì ĐỨC CHÚA làm cho họ được hân hoan khi làm cho lòng vua Át-sua nghiêng về phía họ, để họ vững tay xây Nhà Thiên Chúa, Thiên Chúa của Ít-ra-en.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'er', 7, '[PART] II. CÁC ÔNG ÉT-RA VÀ NƠ-KHE-MI-A TỔ CHỨC CỘNG ĐOÀN
[SECTION] Thân thế và sứ mạng ông Ét-ra
(1) Sau những biến cố đó, dưới triều Ác-tắc-sát-ta, vua Ba-tư, có ông Ét-ra, con cháu của Xơ-ra-gia, con của A-dác-gia, con của Khin-ki-gia, (2) con của Sa-lum, con của Xa-đốc, con của A-khi-túp, (3) con của A-mác-gia, con của A-dác-gia, con của Mơ-ra-giốt, (4) con của Dơ-rác-gia, con của Út-di, con của Búc-ki, (5) con của A-vi-su-a, con của Pin-khát, con của E-la-da, con của thượng tế A-ha-ron; (6) chính ông Ét-ra này đã từ Ba-by-lon lên. Ông là một kinh sư thông Luật Mô-sê, mà ĐỨC CHÚA, Thiên Chúa của Ít-ra-en đã ban. Vì bàn tay ĐỨC CHÚA, Thiên Chúa của ông, che chở ông, nên tất cả những gì ông xin vua đều ban cho. (7) Con cái Ít-ra-en, các tư tế, các thầy Lê-vi, các ca viên, những người giữ cửa, những người phục vụ Đền Thờ, lên Giê-ru-sa-lem vào năm thứ bảy đời vua Ác-tắc-sát-ta. (8) Ông tới Giê-ru-sa-lem vào tháng thứ năm, năm thứ bảy của triều vua. (9) Quả thế, ông đã ấn định ngày rời Ba-by-lon để đi lên đó vào mồng một tháng thứ nhất, và tới Giê-ru-sa-lem vào ngày mồng một tháng thứ năm: có bàn tay nhân lành Thiên Chúa của ông che chở ông. (10) Quả thật, ông Ét-ra đã chú tâm tìm hiểu kỹ càng Lề Luật của ĐỨC CHÚA, thực hành Luật đó và dạy cho dân Ít-ra-en biết những thánh chỉ và quyết định.
[SECTION] Sắc chỉ của vua Ác-tắc-sát-ta
(11) Đây là bản sao sắc chỉ của vua Ác-tắc-sát-ta đã trao cho ông Ét-ra, tư tế kinh sư, kinh sư chuyên về các lời diễn tả mệnh lệnh và các thánh chỉ của ĐỨC CHÚA liên quan đến Ít-ra-en.
(12) “Ác-tắc-sát-ta, vua các vua, gửi cho tư tế Ét-ra, kinh sư chuyên về Lề Luật của Thiên Chúa, Chúa các tầng trời. Chúc ông vạn an!
Vậy giờ đây, (13) ta ra lệnh cho bất cứ ai thuộc dân Ít-ra-en, cho các tư tế và các thầy Lê-vi sống trong vương quốc của ta muốn tình nguyện đi Giê-ru-sa-lem, thì đều được phép đi cùng với ông, (14) bởi vì ông được vua và bảy vị cố vấn của vua cử đi để thị sát Giu-đa và Giê-ru-sa-lem, chiếu theo Lề Luật của Thiên Chúa của ông, Lề Luật mà ông có trong tay; (15) ông cũng được cử đi để mang vàng bạc, mà vua và các vị cố vấn của vua đã tự nguyện dâng cúng Thiên Chúa của Ít-ra-en ngự tại cung điện Người ở Giê-ru-sa-lem, (16) cũng như mang tất cả vàng bạc ông sẽ tìm ra trong khắp tỉnh Ba-by-lon, cùng với những lễ vật mà dân và các tư tế sẽ tự nguyện dâng cúng cho Nhà Thiên Chúa của họ tại Giê-ru-sa-lem. (17) Vì thế, ông hãy cẩn thận dùng tiền bạc đó mà mua bò, chiên, cừu, cũng như các lễ phẩm và rượu tế; ông sẽ tiến dâng các lễ vật đó trên bàn thờ của Nhà Thiên Chúa của các ông ở Giê-ru-sa-lem. (18) Với số vàng bạc còn dư, các ông sẽ làm những gì ông và anh em ông cho là tốt, và làm theo ý muốn của Thiên Chúa các ông thờ. (19) Còn những đồ vật đã được trao cho ông để dùng vào việc thờ phượng trong Nhà Thiên Chúa của ông, thì ông hãy đặt trước nhan Thiên Chúa ngự tại Giê-ru-sa-lem. (20) Còn những đồ vật cần thiết khác cho Nhà Thiên Chúa của ông, đồ vật ông có nhiệm vụ phải cung cấp, thì ông sẽ lĩnh ở kho tàng của vua mà cung cấp. (21) Chính ta, vua Ác-tắc-sát-ta, ra lệnh cho mọi thủ quỹ Vùng bên kia sông Êu-phơ-rát: tất cả những gì tư tế Ét-ra, kinh sư chuyên về Lề Luật của Thiên Chúa, Chúa các tầng trời, sẽ xin các ngươi, thì các ngươi phải thực hiện cho chu đáo. (22) Các ngươi có thể cấp cho tới ba ngàn ký bạc, một ngàn giạ lúa miến, hai trăm thùng rượu, hai trăm thùng dầu, còn muối thì không có hạn. (23) Tất cả những gì là lệnh của Thiên Chúa, Chúa các tầng trời, phải được nghiêm chỉnh thi hành cho Nhà Thiên Chúa, Chúa các tầng trời, để cơn thịnh nộ của Người khỏi giáng xuống vương quốc của vua và của các hoàng tử. (24) Ta cũng còn cho các ngươi biết là không được phép thu cống vật, thuế má, thuế thông quá của bất cứ tư tế hay thầy Lê-vi, ca viên hay người giữ cửa và những người phục vụ Đền Thờ, nói tóm lại, của bất cứ người nào phục vụ Nhà Thiên Chúa.
(25) “Phần ông, ông Ét-ra, với sự khôn ngoan của Thiên Chúa của ông, sự khôn ngoan mà ông nắm trong tay, ông hãy đặt các thẩm phán, các quan tòa để xử kiện cho toàn dân Vùng bên kia sông Êu-phơ-rát, cho tất cả những người biết Lề Luật của Thiên Chúa của ông. Còn kẻ không biết Lề Luật đó, các ông sẽ giúp cho họ biết. (26) Ai không giữ Lề Luật của Thiên Chúa của ông và luật của vua, thì phải trừng trị thích đáng: như xử tử, hoặc trục xuất, hoặc phạt tiền, hay bỏ tù.”
[SECTION] Cuộc hành trình của ông Ét-ra từ Ba-by-lon đến Pa-lét-tin
(27) Chúc tụng ĐỨC CHÚA, Thiên Chúa của tổ tiên chúng ta, Đấng đã ban cho đức vua lòng ước muốn tôn trọng Nhà của ĐỨC CHÚA ở Giê-ru-sa-lem, (28) và đã làm cho đức vua, các cố vấn và mọi quan chức quyền thế nhất của đức vua tỏ lòng thương yêu tôi. Còn tôi thì lên tinh thần, vì bàn tay ĐỨC CHÚA, Thiên Chúa của tôi, che chở tôi. Tôi tập họp một số thủ lãnh Ít-ra-en lại, để họ cùng đi lên với tôi.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'er', 8, '(1) Đây là những người làm đầu các gia tộc với gia phả của họ, những người đã rời Ba-by-lon mà đi lên với tôi, dưới triều vua Ác-tắc-sát-ta:
(2) Dòng dõi Pin-khát: có Ghéc-sôm; dòng dõi I-tha-ma: có Đa-ni-en; dòng dõi ông Đa-vít: có Khát-tút, (3) con của Sơ-khan-gia; dòng dõi Pác-ốt: có Dơ-khác-gia, và cùng với ông có một trăm năm mươi đàn ông con trai được ghi vào sổ gia phả; (4) dòng dõi Pa-khát Mô-áp: có En-giơ-hô-ê-nai, con của Dơ-rác-gia, và cùng với ông có hai trăm đàn ông con trai; (5) dòng dõi Dát-tu: có Sơ-khan-gia, con của Gia-kha-di-ên, và cùng với ông có ba trăm đàn ông con trai; (6) dòng dõi A-đin: có E-vét, con của Giô-na-than, và cùng với ông có năm mươi đàn ông con trai; (7) dòng dõi Ê-lam: có Giơ-sa-gia, con của A-than-gia, và cùng với ông có bảy mươi đàn ông con trai; (8) dòng dõi Sơ-phát-gia: có Dơ-vát-gia, con của Mi-kha-ên, và cùng với ông có tám mươi đàn ông con trai; (9) dòng dõi Giô-áp: có Ô-vát-gia, con của Giơ-khi-ên, và cùng với ông có hai trăm mười tám đàn ông con trai; (10) dòng dõi Ba-ni: có Sơ-lô-mít, con của Giô-xíp-gia, và cùng với ông có một trăm sáu mươi đàn ông con trai; (11) dòng dõi Bê-vai: có Dơ-khác-gia, con của Bê-vai, và cùng với ông có hai mươi tám đàn ông con trai; (12) dòng dõi Át-gát: có Giô-kha-nan, con của Ha-ca-tan, và cùng với ông có một trăm mười đàn ông con trai; (13) dòng dõi A-đô-ni-cam: những người cuối cùng; đây là tên của họ: Ê-li-phe-lét, Giơ-y-ên và Sơ-ma-gia, và cùng với họ có sáu mươi đàn ông con trai; (14) dòng dõi Bích-vai: có U-thai và Dáp-bút, và cùng với họ có bảy mươi đàn ông con trai.
(15) Tôi đã tập họp họ lại bên sông chảy về A-ha-va, và chúng tôi đóng trại ở đó ba ngày. Tôi để ý thì thấy có dân và các tư tế, nhưng ở đó tôi không tìm được một thầy Lê-vi nào. (16) Bấy giờ tôi phái những người này đi: các ông: Ê-li-e-de, A-ri-ên, Sơ-ma-gia, En-na-than, Gia-ríp, En-na-than, Na-than, Dơ-khác-gia, và Mơ-su-lam, là những người thủ lãnh, cùng với các ông Giô-gia-ríp và En-na-than, là những người giải thích Lề Luật. (17) Tôi đã cho họ những chỉ thị liên quan đến ông Ít-đô là người làm đầu ở Kha-xíp-gia, và nhờ họ chuyển đến ông Ít-đô và các anh em ông, những người phục vụ Đền Thờ tại Kha-xíp-gia, những lời miệng tôi muốn nói với các ông ấy, để xin đem đến cho chúng tôi những người giúp việc Nhà Thiên Chúa. (18) Vì có bàn tay nhân lành của Thiên Chúa che chở chúng tôi, họ đem đến cho chúng tôi một người khôn ngoan, thuộc dòng dõi ông Mác-li, con ông Lê-vi, con ông Ít-ra-en, đó là ông Sê-rếp-gia, cùng với các con và anh em của ông, tất cả mười tám người, (19) thêm vào đó còn có ông Kha-sáp-gia với em ông là ông Giơ-sa-gia, thuộc dòng dõi ông Mơ-ra-ri, cũng như các con của họ, tất cả hai mươi người. (20) Ngoài ra, trong số những người phục vụ Đền Thờ mà vua Đa-vít và các thủ lãnh đã cho để phục vụ các thầy Lê-vi, có hai trăm hai mươi người phục vụ Đền Thờ: tất cả những người này được chỉ định đích danh.
(21) Ở đó, gần bờ sông A-ha-va, tôi công bố lệnh ăn chay để hạ mình trước nhan Thiên Chúa chúng tôi, hầu nài xin Người cho chúng tôi đi đường bằng an cùng với con cái chúng tôi và mọi tài sản của chúng tôi. (22) Vì tôi sẽ hổ thẹn, nếu phải xin vua cấp cho một đội quân và những người kỵ mã, để bảo vệ chúng tôi khỏi tay kẻ thù trong lúc đi đường; quả vậy, chúng tôi có thưa với đức vua: “Bàn tay của Thiên Chúa chúng tôi che chở tất cả những ai tìm kiếm Người và giáng phúc cho họ, nhưng sức mạnh và cơn thịnh nộ của Người đè nặng trên mọi kẻ lìa bỏ Người.” (23) Để được như vậy, chúng tôi đã giữ chay, đã nài xin Thiên Chúa chúng tôi, và Người đã nhậm lời chúng tôi.
(24) Tôi chọn hai người làm đầu các tư tế, cũng như ông Sê-rếp-gia, ông Kha-sáp-gia và mười người anh em của họ. (25) Và tôi cân cho họ bạc vàng và những đồ vật dâng cúng vào Nhà của Thiên Chúa chúng tôi; đó là những gì đức vua, các vị cố vấn, các thủ lãnh và mọi người Ít-ra-en có mặt ở đó đã dâng cúng. (26) Tôi cân, rồi trao vào tay họ mười chín ngàn năm trăm ký bạc, những đồ bằng bạc trị giá ba ngàn ký, ba ngàn ký vàng, (27) hai mươi tô bằng vàng trị giá một ngàn đồng Đa-ri-ô, và hai bình bằng đồng đẹp, bóng loáng, cũng quý như vàng. (28) Tôi nói với họ: “Các ông được thánh hiến cho ĐỨC CHÚA; các đồ vật này là của thánh; bạc này, vàng này là lễ vật tự nguyện dâng ĐỨC CHÚA, Thiên Chúa của tổ tiên các ông. (29) Các ông hãy gìn giữ cẩn thận những thứ này, cho đến khi cân trước mặt những người làm đầu các tư tế và các thầy Lê-vi, trước mặt những người làm đầu các gia tộc Ít-ra-en ở Giê-ru-sa-lem, trong các phòng của Nhà ĐỨC CHÚA.” (30) Các tư tế và các thầy Lê-vi lãnh nhận bạc vàng và các đồ vật đã cân, để mang đi Giê-ru-sa-lem, đưa vào Nhà của Thiên Chúa chúng ta.
(31) Chúng tôi đã khởi hành từ sông A-ha-va ngày mười hai tháng thứ nhất, để đi Giê-ru-sa-lem. Bàn tay của Thiên Chúa chúng ta đã che chở chúng tôi, và cho chúng tôi thoát khỏi tay kẻ thù và những cạm bẫy trên đường đi. (32) Chúng tôi đến Giê-ru-sa-lem và nghỉ tại đó ba ngày. (33) Ngày thứ tư, bạc, vàng và các đồ vật được cân trong Nhà của Thiên Chúa chúng ta, và trao vào tay tư tế Mơ-rê-mốt, con ông U-ri-gia, cùng với ông còn có ông E-la-da, con ông Pin-khát; ngoài các nhân vật ấy, cũng có các thầy Lê-vi: Giô-da-vát, con ông Giê-su-a, và Nô-át-gia, con ông Bin-nui. (34) Số và lượng đều đúng cả. Tổng cộng số lượng được ghi vào sổ.
Thời ấy, (35) những người từ chốn lưu đày trở về, những người đã bị lưu đày, dâng những lễ toàn thiêu lên Thiên Chúa của Ít-ra-en: mười hai con bò cho toàn thể Ít-ra-en, chín mươi sáu con cừu, bảy mươi hai con chiên, mười hai con dê làm lễ vật tạ tội: tất cả trở thành lễ vật toàn thiêu dâng ĐỨC CHÚA.
(36) Rồi họ trao các sắc chỉ nhà vua cho các thủ hiến của vua và cho các trưởng Vùng bên kia sông Êu-phơ-rát. Các vị này đã giúp đỡ dân và giúp vào việc xây Nhà ĐỨC CHÚA.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'er', 9, '[SECTION] Hủy bỏ hôn nhân với người ngoại
(1) Giải quyết những việc ấy xong, các người lãnh đạo đến với tôi và nói: “Dân Ít-ra-en, các tư tế và các thầy Lê-vi không dứt mọi liên hệ với những thói tục ghê tởm của các dân trong xứ, của người Ca-na-an, Khết, Pơ-rít-di, Giơ-vút, Am-mon, Mô-áp, Ai-cập và E-mô-ri. (2) Họ và con cái họ đã lấy con gái của chúng; nòi giống thánh đã trà trộn với các dân trong những xứ ấy. Các người lãnh đạo, các quan chức là những người mau tay làm chuyện phản bội đó nhất!” (3) Nghe tin ấy, tôi xé áo dài trong và áo choàng ngoài, tôi bứt tóc bứt râu, rồi ngồi xuống sững sờ kinh ngạc. (4) Tất cả những ai run sợ khi nghe lời của Thiên Chúa Ít-ra-en thì quy tụ chung quanh tôi, trước sự phản bội của những người lưu đày trở về. Còn tôi thì cứ ngồi đó, sững sờ kinh ngạc, cho đến giờ dâng lễ phẩm ban chiều. (5) Vào giờ đó, tôi mới ra khỏi cơn sầu khổ, trỗi dậy; áo dài trong, áo choàng ngoài xé rách, tôi quỳ gối, giơ tay lên ĐỨC CHÚA, Thiên Chúa của tôi (6) và thưa:
“Lạy Thiên Chúa của con, con thật xấu hổ thẹn thùng khi ngẩng mặt lên Ngài, lạy Thiên Chúa của con, vì tội chúng con quá nhiều, đến nỗi ngập đầu ngập cổ, lỗi chúng con cứ chồng chất lên mãi tới trời. (7) Từ thời tổ tiên chúng con cho đến ngày nay, vì chúng con đã mắc lỗi nặng và phạm tội, nên các vua và các tư tế của chúng con đã bị nộp vào tay vua chúa các nước ngoại bang; chúng con đã bị nộp cho gươm giáo, phải đi đày, bị cướp bóc và bẽ mặt hổ ngươi như ngày hôm nay. (8) Và bây giờ, chỉ mới đây, ĐỨC CHÚA, Thiên Chúa chúng con, ban cho chúng con ân huệ này là để lại cho chúng con một số người sống sót, và cho chúng con được một chỗ ở vững chắc trong nơi thánh của Ngài; như thế, Thiên Chúa chúng con đã tỏa ánh sáng làm cho đôi mắt chúng con được rạng ngời, và làm cho chúng con được hồi sinh đôi chút trong cảnh nô lệ. (9) Tuy chúng con là những kẻ nô lệ, Thiên Chúa chúng con đã không bỏ rơi chúng con trong cảnh nô lệ đó. Ngài đã làm cho các vua Ba-tư tỏ lòng thương yêu chúng con, khiến chúng con được hồi sinh mà dựng lại Nhà Thiên Chúa chúng con, tái thiết ngôi Nhà đã hoang tàn, và xây lại tường thành tại Giê-ru-sa-lem ở Giu-đa. (10) Và giờ đây, lạy Thiên Chúa chúng con, chúng con biết nói gì sau cớ sự này? Vì chúng con đã không tuân giữ các mệnh lệnh của Ngài. (11) Ngài đã dùng các tôi trung của Ngài là các ngôn sứ mà truyền dạy rằng: ‘Đất mà các ngươi sắp vào chiếm hữu, là đất đã ra nhơ nhớp, vì những sự nhơ nhớp của các dân trong những xứ ấy, vì những thói tục ghê tởm họ đã làm cho tràn lan khắp nơi khắp chốn bằng sự ô uế của họ. (12) Và giờ đây, các ngươi đừng gả con gái các ngươi cho con trai chúng, và đừng cưới con gái chúng cho con trai các ngươi. Các ngươi đừng bao giờ mưu cầu bình an và hạnh phúc cho chúng. Như thế, các ngươi sẽ được mạnh sức, được hưởng dùng của cải trong xứ và trối lại cho con cái các ngươi làm gia tài mãi mãi.’
(13) Sau khi mọi điều ấy xảy ra cho chúng con vì các việc xấu và lỗi nặng của chúng con, mặc dầu Ngài, lạy Thiên Chúa chúng con, Ngài đã giảm nhẹ tội ác của chúng con, và đã để lại cho chúng con số người sống sót này, (14) lẽ nào chúng con lại còn vi phạm mệnh lệnh của Ngài, và kết nghĩa thông gia với các dân làm những điều ghê tởm như thế? Chẳng lẽ Ngài lại không nổi cơn thịnh nộ với chúng con và hủy diệt chúng con, không để một người sống sót hay thoát nạn sao? (15) Lạy ĐỨC CHÚA, Thiên Chúa Ít-ra-en, Ngài là Đấng công chính, nên chúng con mới được thoát nạn và sống sót, như ngày hôm nay. Này chúng con đang ở trước nhan Ngài, mang trong mình lỗi lầm của chúng con, mặc dầu trong tình trạng đó, không ai có thể đứng vững trước nhan Ngài!”') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'er', 10, '(1) Trong khi ông Ét-ra khóc lóc và phủ phục trước Nhà Thiên Chúa, mà cầu nguyện và thú nhận tội lỗi, thì một cộng đoàn đông đảo người Ít-ra-en, đàn ông, đàn bà và trẻ con, tụ họp lại chung quanh ông. Dân chúng khóc lóc thảm thiết. (2) Ông Sơ-khan-gia, con ông Giơ-khi-ên, thuộc dòng dõi Ê-lam, nói với ông Ét-ra: “Chúng tôi đã phản bội Thiên Chúa chúng tôi, khi cưới vợ người ngoại thuộc các dân trong xứ. Nhưng giờ đây, mặc dầu thế, vẫn còn hy vọng cho Ít-ra-en. (3) Vậy giờ đây, chúng ta hãy cam kết với Thiên Chúa chúng ta là sẽ đuổi tất cả những người vợ ấy với con cái họ, theo lời khuyên của ngài và của những ai có lòng kính sợ mệnh lệnh của Thiên Chúa chúng ta. Cứ theo Lề Luật mà làm! (4) Xin ông trỗi dậy, vì đây là việc của ông, nhưng chúng tôi sẽ ở bên ông. Ông cứ can đảm và hành động đi!” (5) Bấy giờ, ông Ét-ra trỗi dậy và bắt các thủ lãnh của hàng tư tế và của các thầy Lê-vi, cũng như toàn thể Ít-ra-en phải thề là sẽ làm như đã nói. Và họ đã thề. (6) Ông Ét-ra trỗi dậy, rồi từ phía trước Nhà Thiên Chúa đi tới phòng ông Giơ-hô-kha-nan, con ông En-gia-síp. Ông Ét-ra đi tới đó, không ăn bánh, cũng chẳng uống nước, vì ông quá buồn phiền về tội phản bội của những người lưu đày trở về.
(7) Người ta ra thông cáo này tại Giê-ru-sa-lem ở Giu-đa: mọi người lưu đày trở về phải tập họp ở Giê-ru-sa-lem. (8) Nội trong ba ngày, ai không đến, thì chiếu theo quyết định của các thủ lãnh và kỳ mục, tất cả tài sản sẽ bị biệt hiến và bản thân sẽ bị trục xuất khỏi cộng đồng những người lưu đày trở về. (9) Mọi người Giu-đa và Ben-gia-min đều tập họp ở Giê-ru-sa-lem vào ngày thứ ba, đó là ngày hai mươi tháng chín. Toàn dân ngồi ở quảng trường Nhà Thiên Chúa, run sợ vì sự việc đã xảy ra và vì trời mưa tầm tã. (10) Bấy giờ tư tế Ét-ra đứng dậy và nói với họ: “Anh em đã phản bội khi cưới vợ người ngoại, và như thế làm tăng thêm tội lỗi của Ít-ra-en. (11) Nhưng bây giờ anh em hãy suy tôn ĐỨC CHÚA, Thiên Chúa của cha ông anh em, và hãy thi hành ý muốn của Người: hãy dứt mọi liên hệ với dân trong xứ và các người vợ ngoại.” (12) Toàn thể đại hội lớn tiếng đáp: “Vâng! Chúng tôi phải làm như ông đã nói. (13) Nhưng dân thì đông, lại đang mùa mưa, nên không thể đứng ngoài trời. Và việc này không phải là chuyện ngày một ngày hai, vì trong vụ này rất đông người chúng tôi đã phạm tội. (14) Vậy xin hàng thủ lãnh chúng tôi ở lại thay cho đại hội; trong các thành của chúng tôi, tất cả những ai đã cưới vợ người ngoại thì sẽ đến vào thời đã quy định, cùng với các kỳ mục và thẩm phán của mỗi thành, cho đến khi Thiên Chúa rút lại cơn thịnh nộ Người giáng xuống chúng tôi vì vụ này.”
(15) Chỉ có ông Giô-na-than, con ông A-xa-hên, và ông Giác-dơ-gia, con ông Tích-va, chống lại giải pháp đó, và được ông Mơ-su-lam cùng thầy Lê-vi Sáp-thai ủng hộ. (16) Nhưng các người lưu đày trở về cứ làm như đã đề nghị. Tư tế Ét-ra chọn những người làm đầu các gia tộc, tùy theo số các gia tộc, tất cả đều được chỉ định đích danh. Ngày mồng một tháng mười họ ngồi lại để cứu xét vấn đề. (17) Tới ngày mồng một tháng thứ nhất, họ mới giải quyết xong vấn đề của tất cả những người đã lấy vợ người ngoại.
[SECTION] Danh sách những người phạm lỗi
(18) Người ta tìm thấy trong hàng tư tế những người sau đây đã lấy vợ người ngoại: trong số con cái ông Giê-su-a, con của Giô-xa-đắc, và trong số anh em của ông, có Ma-a-xê-gia, Ê-li-e-de, Gia-ríp và Gơ-đan-gia. (19) Họ cam đoan sẽ rẫy vợ và dâng một con cừu đực để làm lễ đền tội;
(20) trong số con cái ông Im-me, có Kha-na-ni và Dơ-vát-gia;
(21) trong số con cái ông Kha-rim, có Ma-a-xê-gia, Ê-li-gia, Sơ-ma-gia, Giơ-khi-ên và Út-di-gia;
(22) trong số con cái ông Pát-khua, có En-giô-ê-nai, Ma-a-xê-gia, Gít-ma-ên, Nơ-than-ên, Giô-da-vát và En-a-xa.
(23) Trong số các thầy Lê-vi, có Giô-da-vát, Sim-y, Kê-la-gia tức là Cơ-li-ta, Pơ-thác-gia, Giơ-hu-đa và Ê-li-e-de.
(24) Trong số các ca viên, có En-gia-síp.
Trong số những người giữ cửa, có Sa-lum, Te-lem và U-ri.
(25) Giữa những người Ít-ra-en:
trong số con cái ông Pác-ốt, có Ram-gia, Gít-di-gia, Man-ki-gia, Mi-gia-min, E-la-da, Man-ki-gia và Bơ-na-gia;
(26) trong số con cái ông Ê-lam, có Mát-tan-gia, Dơ-khác-gia, Giơ-khi-ên, Áp-đi, Giơ-rê-mốt và Ê-li-gia;
(27) trong số con cái ông Dát-tu, có En-giô-ê-nai, En-gia-síp, Mát-tan-gia, Giơ-rê-mốt, Da-vát và A-di-da;
(28) trong số con cái ông Bê-vai, có Giơ-hô-kha-nan, Kha-nan-gia, Dáp-bai và Át-lai;
(29) trong số con cái ông Ba-ni, có Mơ-su-lam, Ma-lúc, A-đa-gia, Gia-súp, Sơ-an và Giơ-ra-mốt;
(30) trong số con cái ông Pa-khát Mô-áp, có Át-na, Cơ-lan, Bơ-na-gia, Ma-a-xê-gia, Mát-tan-gia, Bơ-xan-ên, Bin-nui và Mơ-na-se;
(31) trong số con cái ông Kha-rim, có Ê-li-e-de, Gít-si-gia, Man-ki-gia, Sơ-ma-gia, Si-mê-ôn, (32) Ben-gia-min, Ma-lúc, Sơ-mác-gia;
(33) trong số con cái ông Kha-sum, có Mát-tơ-nai, Mát-tát-ta, Da-vát, Ê-li-phe-lét, Giơ-rê-mai, Mơ-na-se, Sim-y;
(34) trong số con cái ông Ba-ni, có Ma-a-đai, Am-ram, U-ên, (35) Bơ-na-gia, Bết-gia, Cơ-lu-hi, (36) Van-gia, Mơ-rê-mốt, En-gia-síp, (37) Mát-tan-gia, Mát-tơ-nai, Gia-a-xai;
(38) trong số con cái ông Bin-nui, có Sim-y, (39) Se-lem-gia, Na-than, A-đa-gia;
(40) trong số con cái ông Dắc-cai, có Sa-sai, Sa-rai, (41) A-dác-ên, Se-lem-gia-hu, Sơ-mác-gia, (42) Sa-lum, A-mác-gia, Giô-xếp;
(43) trong số con cái ông Nơ-vô, có Giơ-y-ên, Mát-tít-gia, Da-vát, Dơ-vi-na, Giát-đai, Giô-en và Bơ-na-gia.
(44) Tất cả những người này đã lấy vợ người ngoại; họ đã rẫy vợ và từ con.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;