INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'gl', 1, '[PART] Chương 1
[SECTION] Lời mở đầu
(1) Tôi là Phao-lô, Tông Đồ không phải do loài người, cũng không phải nhờ một người nào, nhưng bởi Đức Giê-su Ki-tô và Thiên Chúa là Cha, Đấng đã cho Người từ cõi chết trỗi dậy, (2) tôi và mọi anh em đang ở với tôi, kính gửi các Hội Thánh miền Ga-lát. (3) Xin Thiên Chúa là Cha chúng ta, và xin Chúa Giê-su Ki-tô ban cho anh em ân sủng và bình an. (4) Để cứu chúng ta thoát khỏi cõi đời xấu xa hiện tại, Đức Giê-su Ki-tô đã tự hiến vì tội lỗi chúng ta, theo ý muốn của Thiên Chúa là Cha chúng ta. (5) Xin tôn vinh Thiên Chúa đến muôn thuở muôn đời. A-men.
[SECTION] Lời cảnh cáo
(6) Tôi lấy làm ngạc nhiên, khi thấy anh em trở mặt mau lẹ như thế với Đấng đã kêu gọi anh em nhờ ân sủng của Đức Ki-tô, để theo một Tin Mừng khác. (7) Không có Tin Mừng nào khác đâu, mà chỉ có một vài kẻ phá rối anh em, và muốn làm xáo trộn Tin Mừng của Đức Ki-tô đó thôi. (8) Nhưng nếu có ai, kể cả chúng tôi, hoặc một thiên thần nào từ trời xuống, loan báo cho anh em Tin Mừng khác với Tin Mừng chúng tôi đã loan báo cho anh em, thì xin Thiên Chúa loại trừ kẻ ấy đi! (9) Như tôi đã nói, và nay tôi xin nói lại: nếu có ai loan báo cho anh em một Tin Mừng khác với Tin Mừng anh em đã lãnh nhận, thì xin Thiên Chúa loại trừ kẻ ấy đi! (10) Vậy, giờ đây tôi tìm cách lấy lòng người đời, hay lấy lòng Thiên Chúa? Phải chăng tôi tìm cách làm đẹp lòng người đời? Nếu tôi còn muốn làm đẹp lòng người đời, thì tôi không phải là tôi tớ của Đức Ki-tô.
[PART] I. LỜI THANH MINH
[SECTION] Ơn gọi của thánh Phao-lô
(11) Thật vậy, thưa anh em, tôi xin nói cho anh em biết: Tin Mừng tôi loan báo không phải là do loài người. (12) Vì không có ai trong loài người đã truyền lại hay dạy cho tôi Tin Mừng ấy, nhưng là chính Đức Giê-su Ki-tô đã mặc khải. (13) Anh em hẳn đã nghe nói tôi đã ăn ở thế nào trước kia trong đạo Do-thái: tôi đã quá hăng say bắt bớ, và những muốn tiêu diệt Hội Thánh của Thiên Chúa. (14) Trong việc giữ đạo Do-thái, tôi đã vượt xa nhiều đồng bào cùng lứa tuổi với tôi: hơn ai hết, tôi đã tỏ ra nhiệt thành với các truyền thống của cha ông.
(15) Nhưng Thiên Chúa đã dành riêng tôi ngay từ khi tôi còn trong lòng mẹ, và đã gọi tôi nhờ ân sủng của Người. (16) Người đã đoái thương mặc khải Con của Người cho tôi, để tôi loan báo Tin Mừng về Con của Người cho các dân ngoại. Tôi đã chẳng thuận theo các lý do tự nhiên, (17) cũng chẳng lên Giê-ru-sa-lem để gặp các vị đã là Tông Đồ trước tôi, nhưng tức khắc tôi đã sang xứ Ả-rập, rồi lại trở về Đa-mát. (18) Ba năm sau tôi mới lên Giê-ru-sa-lem diện kiến ông Kê-pha, và ở lại với ông mười lăm ngày. (19) Tôi đã không gặp một vị Tông Đồ nào khác ngoài ông Gia-cô-bê, người anh em của Chúa. (20) Viết cho anh em những điều này, tôi cam đoan trước mặt Thiên Chúa là tôi không nói dối. (21) Sau đó tôi đến miền Xy-ri và miền Ki-li-ki-a. (22) Nhưng lúc ấy các Hội Thánh Đức Ki-tô tại miền Giu-đê không biết mặt tôi. (23) Họ chỉ nghe nói rằng: “Người trước đây bắt bớ chúng ta, bây giờ lại loan báo đức tin mà xưa kia ông những muốn tiêu diệt”, (24) và vì tôi, họ tôn vinh Thiên Chúa.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'gl', 2, '[SECTION] Đại hội ở Giê-ru-sa-lem
(1) Rồi sau mười bốn năm, tôi lại lên Giê-ru-sa-lem một lần nữa cùng với ông Ba-na-ba; tôi cũng đem theo anh Ti-tô đi với tôi. (2) Tôi lên đó vì được Thiên Chúa mặc khải, và đã trình bày cho người ta Tin Mừng tôi rao giảng cho dân ngoại, –cách riêng cho các vị có thế giá–, vì sợ rằng tôi ngược xuôi, và đã ngược xuôi vô ích. (3) Thế mà ngay cả anh Ti-tô, người cùng đi với tôi và là người Hy-lạp, cũng không bị ép phải chịu cắt bì. (4) Sở dĩ thế là vì có những tên xâm nhập, những kẻ giả danh giả nghĩa anh em, đã len lỏi vào dò xét sự tự do của chúng ta, sự tự do chúng ta có được trong Đức Ki-tô Giê-su; họ làm như vậy là để bắt chúng ta trở thành nô lệ. (5) Nhưng với những người ấy, chúng tôi đã không chịu nhượng bộ, dù chỉ trong giây lát, để duy trì cho anh em chân lý của Tin Mừng. (6) Còn về các vị có thế giá –lúc bấy giờ các vị ấy có là gì đi nữa, điều đó không quan hệ đối với tôi: Thiên Chúa không thiên vị ai–, các vị có thế giá ấy đã không đưa ra thêm điều gì cho tôi. (7) Trái lại, các ngài thấy rằng tôi đã được ủy thác nhiệm vụ loan báo Tin Mừng cho những người không được cắt bì, cũng như ông Phê-rô được ủy thác nhiệm vụ loan báo Tin Mừng cho những người được cắt bì. (8) Thật vậy, Đấng đã hoạt động nơi ông Phê-rô, biến ông thành Tông Đồ của những người được cắt bì, cũng đã hoạt động biến tôi thành Tông Đồ các dân ngoại. (9) Vậy khi nhận ra ân huệ Thiên Chúa đã ban cho tôi, các ông Gia-cô-bê, Kê-pha và Gio-an, những người được coi là cột trụ, đã bắt tay tôi và ông Ba-na-ba để tỏ dấu hiệp thông: chúng tôi thì lo cho các dân ngoại, còn các vị ấy thì lo cho những người được cắt bì. (10) Chỉ có điều này là chúng tôi phải nhớ đến những người túng thiếu, điều mà tôi vẫn gắng làm.
[SECTION] Thánh Phê-rô và thánh Phao-lô tại An-ti-ô-khi-a
(11) Nhưng khi ông Kê-pha đến An-ti-ô-khi-a, tôi đã cự lại ông ngay trước mặt, vì ông đã làm điều đáng trách. (12) Thật vậy, ông thường dùng bữa với những người gốc dân ngoại trước khi có những người của ông Gia-cô-bê đến; nhưng khi những người này đến, ông lại tránh né và tự tách ra, vì sợ những người được cắt bì. (13) Những người Do-thái khác cũng theo ông mà giả hình giả bộ, khiến cả ông Ba-na-ba cũng bị lôi cuốn mà giả hình như họ.
(14) Nhưng khi tôi thấy các ông ấy không đi đúng theo chân lý của Tin Mừng, thì tôi đã nói với ông Kê-pha trước mặt mọi người: “Nếu ông là người Do-thái mà còn sống như người dân ngoại, chứ không như người Do-thái, thì làm sao ông lại ép người dân ngoại phải xử sự như người Do-thái?”
[SECTION] Tin Mừng của thánh Phao-lô
(15) Chúng ta bẩm sinh là người Do-thái chứ không phải hạng người tội lỗi xuất thân từ dân ngoại. (16) Tuy nhiên, vì biết rằng con người được nên công chính không phải nhờ làm những gì Luật dạy, nhưng nhờ tin vào Đức Giê-su Ki-tô, nên chúng ta cũng tin vào Đức Ki-tô Giê-su, để được nên công chính, nhờ tin vào Đức Ki-tô, chứ không phải nhờ làm những gì Luật dạy. Quả thế, không phàm nhân nào sẽ được nên công chính vì làm những gì Luật dạy. (17) Nhưng nếu khi tìm cách nên công chính trong Đức Ki-tô mà chúng ta vẫn bị liệt vào hàng tội lỗi, thì chẳng hóa ra Đức Ki-tô là người phục vụ tội lỗi sao? Không phải thế! (18) Thật vậy, nếu tôi xây lại những gì tôi đã phá, thì tôi tỏ ra mình là kẻ phạm pháp. (19) Quả thế, tại vì Lề Luật mà tôi đã chết đối với Lề Luật, để sống cho Thiên Chúa. Tôi cùng chịu đóng đinh với Đức Ki-tô vào thập giá. (20) Tôi sống, nhưng không còn phải là tôi, mà là Đức Ki-tô sống trong tôi. Hiện nay tôi sống kiếp phàm nhân trong niềm tin vào Con Thiên Chúa, Đấng đã yêu mến tôi và hiến mạng vì tôi. (21) Tôi không làm cho ân huệ của Thiên Chúa ra vô hiệu, vì nếu người ta được nên công chính do Lề Luật, thì hóa ra Đức Ki-tô đã chết vô ích.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'gl', 3, '[PART] II. PHẦN GIÁO THUYẾT
[SECTION] Kinh nghiệm của người tín hữu
(1) Hỡi những người Ga-lát ngu xuẩn, ai đã mê hoặc anh em là những người đã được thấy hình ảnh Đức Giê-su Ki-tô chịu đóng đinh vào thập giá phơi bày ra trước mắt? (2) Tôi muốn anh em cho tôi biết điều này thôi: anh em đã nhận được Thần Khí vì đã làm những gì Luật dạy, hay vì đã tin nhờ được nghe? (3) Anh em ngu xuẩn như thế sao? Anh em đã khởi sự nhờ Thần Khí, nay lại kết thúc nhờ xác thịt sao? (4) Bấy nhiêu kinh nghiệm anh em đã trải qua, lại uổng công sao? Mà quả thật là uổng công! (5) Vậy Đấng đã rộng ban Thần Khí cho anh em và thực hiện những phép lạ giữa anh em, có phải vì anh em làm những gì Luật dạy, hay vì anh em đã tin nhờ được nghe?
[SECTION] Kinh Thánh làm chứng: đức tin và Lề Luật
(6) Cũng như ông Áp-ra-ham đã tin Thiên Chúa, và vì thế Thiên Chúa kể ông là người công chính. (7) Vậy anh em nên biết rằng: những ai dựa vào đức tin, những người ấy là con cái ông Áp-ra-ham. (8) Đàng khác, Kinh Thánh thấy trước rằng Thiên Chúa sẽ làm cho dân ngoại nên công chính nhờ đức tin, nên đã tiên báo cho ông Áp-ra-ham tin mừng này: Nhờ ngươi, muôn dân sẽ được chúc phúc. (9) Như vậy, những kẻ dựa vào đức tin thì được chúc phúc làm một với ông Áp-ra-ham, người có đức tin.
(10) Thật thế, những ai dựa vào những việc Luật dạy phải làm thì đều chuốc lấy lời nguyền rủa, vì Kinh Thánh viết: Đáng nguyền rủa thay mọi kẻ không bền chí thi hành tất cả những gì chép trong sách Luật! (11) Vả lại, không ai được nên công chính trước mặt Thiên Chúa nhờ Lề Luật, đó là điều hiển nhiên, vì người công chính nhờ đức tin sẽ được sống. (12) Thế mà Lề Luật không lệ thuộc đức tin, nhưng ai thực hành những điều Lề Luật dạy, thì nhờ đó sẽ được sống. (13) Đức Ki-tô đã chuộc chúng ta cho khỏi bị nguyền rủa vì Lề Luật, khi vì chúng ta chính Người trở nên đồ bị nguyền rủa, vì có lời chép: Đáng nguyền rủa thay mọi kẻ bị treo trên cây gỗ! (14) Như thế là để nhờ Đức Giê-su Ki-tô, các dân ngoại cũng được hưởng phúc lành dành cho ông Áp-ra-ham, và để nhờ đức tin, chúng ta nhận được ơn Thiên Chúa đã hứa tức là Thần Khí.
[SECTION] Lề Luật không hủy bỏ lời hứa
(15) Thưa anh em, tôi nói theo kiểu người đời: một chúc thư đúng thể thức, dù chỉ là do một người phàm, thì cũng không ai được hủy bỏ hay thêm thắt điều gì. (16) Thế mà những lời hứa đã được ban cho ông Áp-ra-ham và dòng dõi ông, Kinh Thánh không nói: và cho những dòng dõi, như thể nói về nhiều, mà chỉ nói về một: và cho dòng dõi người là Đức Ki-tô. (17) Tôi muốn nói là: một chúc thư xưa kia đã được Thiên Chúa lập đúng thể thức, thì Lề Luật, mãi bốn trăm ba mươi năm sau mới có, không phế bỏ chúc thư đó được, và như vậy làm cho lời hứa ra vô hiệu. (18) Thật thế, nếu nhờ Lề Luật mà người ta được hưởng gia tài, thì không còn phải là nhờ lời hứa nữa. Thế nhưng Thiên Chúa đã dùng một lời hứa mà ban ân huệ cho ông Áp-ra-ham.
[SECTION] Vai trò của Lề Luật
(19) Vậy Lề Luật để làm gì? Chính là để gây ra các vi phạm mà Lề Luật đã được đặt thêm, cho tới khi Đấng là dòng dõi Áp-ra-ham đến, Đấng được hưởng lời hứa. Lề Luật đã được ban bố nhờ các thiên thần, qua tay một trung gian. (20) Nhưng không thể có trung gian khi chỉ có một bên, mà Thiên Chúa thì chỉ có một. (21) Vậy thì Lề Luật đi ngược lại với những lời hứa của Thiên Chúa sao? Không phải thế. Thật vậy, giả như có một luật nào đã được ban cho con người mà lại có khả năng làm cho sống, thì quả là người ta được nên công chính nhờ Lề Luật. (22) Nhưng Kinh Thánh đã giam hãm mọi sự trong vòng tội lỗi, để nhờ lòng tin vào Đức Giê-su Ki-tô, điều Thiên Chúa đã hứa được ban cho các kẻ tin.
[SECTION] Thời của đức tin đã đến
(23) Trước khi đức tin đến, chúng ta bị Lề Luật giam giữ, cho tới khi đức tin được mặc khải. (24) Như thế, Lề Luật đã thành người quản giáo dẫn chúng ta tới Đức Ki-tô, để chúng ta được nên công chính nhờ đức tin. (25) Nhưng khi đức tin đến, thì chúng ta không còn ở dưới quyền giám hộ nữa. (26) Thật vậy, nhờ đức tin, tất cả anh em đều là con cái Thiên Chúa trong Đức Giê-su Ki-tô. (27) Quả thế, bất cứ ai trong anh em được thanh tẩy để thuộc về Đức Ki-tô, đều mặc lấy Đức Ki-tô. (28) Không còn chuyện phân biệt Do-thái hay Hy-lạp, nô lệ hay tự do, đàn ông hay đàn bà; nhưng tất cả anh em chỉ là một trong Đức Ki-tô. (29) Mà nếu anh em thuộc về Đức Ki-tô, thì anh em là dòng dõi ông Áp-ra-ham, những người thừa kế theo lời hứa.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'gl', 4, '[SECTION] Chúng ta được làm con cái Thiên Chúa
(1) Tôi thiết nghĩ: bao lâu người thừa kế còn là thiếu niên thì không khác gì một nô lệ, mặc dù là chủ mọi tài sản. (2) Nó phải ở dưới quyền những người giám hộ và quản lý, cho đến khi mãn hạn người cha đã định. (3) Chúng ta cũng vậy, khi còn là thiếu niên, chúng ta phải làm nô lệ những yếu tố của vũ trụ. (4) Nhưng khi thời gian tới hồi viên mãn, Thiên Chúa đã sai Con mình tới, sinh làm con một người phụ nữ, và sống dưới Lề Luật, (5) để chuộc những ai sống dưới Lề Luật, hầu chúng ta nhận được ơn làm nghĩa tử. (6) Để chứng thực anh em là con cái, Thiên Chúa đã sai Thần Khí của Con mình đến ngự trong lòng anh em mà kêu lên: “Áp-ba, Cha ơi!” (7) Vậy anh em không còn phải là nô lệ nữa, nhưng là con, mà đã là con thì cũng là người thừa kế, nhờ Thiên Chúa.
(8) Trước kia, khi chưa biết Thiên Chúa, anh em làm nô lệ những vật tự bản chất không phải là thần. (9) Nhưng nay anh em đã biết Thiên Chúa, hay đúng hơn được Thiên Chúa biết đến, làm sao anh em còn trở lại với những yếu tố bất lực và nghèo nàn ấy, còn muốn làm nô lệ chúng một lần nữa? (10) Anh em cẩn thận giữ ngày, giữ tháng, giữ mùa, giữ năm! (11) Anh em làm tôi sợ rằng tôi đã vất vả uổng công vì anh em!
[SECTION] Nhắc lại quá khứ
(12) Thưa anh em, tôi van anh em, anh em hãy nên giống như tôi, vì tôi cũng đã nên giống như anh em. Anh em đã không làm tổn thương gì cho tôi cả. (13) Anh em biết: nhân khi thân xác bị đau ốm, tôi đã loan báo Tin Mừng cho anh em lần đầu tiên. (14) Mặc dù thân xác tôi là một dịp thử thách cho anh em, anh em đã không khinh, không tởm; trái lại anh em đã tiếp đón tôi như một sứ giả của Thiên Chúa, như Đức Ki-tô Giê-su. (15) Vậy hạnh phúc của anh em lúc đó, bây giờ đâu rồi? Thật thế, tôi xin làm chứng cho anh em rằng: nếu có thể, hẳn anh em đã móc mắt hiến cho tôi. (16) Thành thử tôi đã trở nên kẻ thù của anh em vì nói sự thật cho anh em sao? (17) Họ nhiệt thành với anh em không phải vì mục đích tốt, mà chỉ vì muốn ly gián anh em với tôi, để anh em nhiệt thành với họ. (18) Được người ta tỏ lòng nhiệt thành là điều tốt, miễn là vì mục đích tốt và trong mọi trường hợp, chứ không phải chỉ khi nào tôi có mặt giữa anh em. (19) Hỡi anh em, những người con bé nhỏ của tôi, mà tôi phải quặn đau sinh ra một lần nữa cho đến khi Đức Ki-tô được thành hình nơi anh em, (20) tôi ước ao được có mặt giữa anh em lúc này, để lựa lời nói sao cho thích hợp, vì tôi thấy khó xử với anh em quá!
[SECTION] Hai giao ước: Ha-ga và Xa-ra
(21) Hãy nói cho tôi hay: anh em là những người muốn sống dưới Lề Luật, anh em không nghe Lề Luật nói gì sao? (22) Thật vậy, có lời chép rằng: ông Áp-ra-ham có hai người con, mẹ của một người là nô lệ, mẹ của người kia là tự do. (23) Nhưng con của người mẹ nô lệ thì sinh ra theo lẽ tự nhiên; còn con của người mẹ tự do thì sinh ra nhờ lời hứa. (24) Chuyện đó ngụ ý thế này: hai người đàn bà là hai giao ước. Giao ước thứ nhất tại núi Xi-nai, thì sinh ra nô lệ: đó là Ha-ga. (25) Ha-ga chỉ núi Xi-nai trong miền Ả-rập, và tương đương với Giê-ru-sa-lem ngày nay, vì thành này cùng với các con đều là nô lệ. (26) Còn Giê-ru-sa-lem thượng giới thì tự do: đó là mẹ chúng ta. (27) Thật vậy, có lời chép:
[SECTION] Reo mừng lên,
[SECTION] hỡi người phụ nữ son sẻ,
[SECTION] không sinh con;
[SECTION] hãy bật tiếng reo hò mừng vui,
[SECTION] hỡi ai chưa một lần chuyển dạ,
[SECTION] vì con của phụ nữ bị bỏ rơi
[SECTION] thì đông hơn con của phụ nữ có chồng!
(28) Thưa anh em, như I-xa-ác, anh em là những người con sinh ra do lời Thiên Chúa hứa. (29) Nhưng cũng như thuở ấy đứa con sinh ra theo lẽ tự nhiên đã ngược đãi đứa con sinh ra theo thần khí, thì bây giờ cũng vậy. (30) Thế nhưng Kinh Thánh nói gì? Kinh Thánh nói: Tống cổ người nô lệ và con của nó đi, vì con của nô lệ không đời nào được thừa kế gia tài cùng với con của người tự do. (31) Ấy vậy, thưa anh em, chúng ta không phải là con của một người nô lệ, nhưng là con của người tự do.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'gl', 5, '[PART] III. PHẦN KHUYÊN NHỦ
[SECTION] Tự do của người tín hữu
(1) Chính để chúng ta được tự do mà Đức Ki-tô đã giải thoát chúng ta. Vậy, anh em hãy đứng vững, đừng mang lấy ách nô lệ một lần nữa. (2) Phải, tôi đây, Phao-lô, tôi nói cho anh em biết: anh em mà chịu phép cắt bì thì Đức Ki-tô sẽ không có ích gì cho anh em. (3) Một lần nữa, tôi xin khẳng định với bất cứ ai chịu phép cắt bì là: người ấy buộc phải giữ trọn vẹn Lề Luật. (4) Anh em mà tìm sự công chính trong Lề Luật, là anh em đoạn tuyệt với Đức Ki-tô và mất hết ân sủng. (5) Còn chúng tôi thì nhờ Thần Khí và dựa vào đức tin mà vững lòng chờ đợi được nên công chính như chúng tôi hy vọng. (6) Quả thật, trong Đức Ki-tô Giê-su, cắt bì hay không cắt bì đều không có giá trị, chỉ có đức tin hành động nhờ đức ái. (7) Anh em đang chạy ngon trớn như thế mà ai đã ngăn cản anh em vâng phục chân lý? (8) Lời dụ dỗ ấy không phát xuất từ Đấng kêu gọi anh em. (9) Một chút men làm cả khối bột dậy men. (10) Đối với anh em, trong Chúa, tôi tin tưởng rằng anh em sẽ không nghĩ khác. Còn kẻ phá rối anh em thì phải chuốc lấy án phạt, bất kể người ấy là ai. (11) Về phần tôi, thưa anh em, giả như tôi còn rao giảng phép cắt bì, thì tại sao tôi lại vẫn bị ngược đãi? Như thế, thập giá đâu còn là chướng ngại nữa! (12) Những kẻ làm cho anh em bị rối loạn, phải chi họ tự thiến cho xong!
[SECTION] Tự do và bác ái
(13) Quả thế, thưa anh em, anh em đã được gọi để hưởng tự do. Có điều là đừng lợi dụng tự do để sống theo tính xác thịt, nhưng hãy lấy đức mến mà phục vụ lẫn nhau. (14) Vì tất cả Lề Luật được nên trọn trong điều răn duy nhất này là: Ngươi phải yêu người thân cận như chính mình. (15) Nhưng nếu anh em cắn xé nhau, anh em hãy coi chừng, anh em tiêu diệt lẫn nhau đấy!
(16) Tôi xin nói với anh em là hãy sống theo Thần Khí, và như vậy, anh em sẽ không còn thỏa mãn đam mê của tính xác thịt nữa. (17) Vì tính xác thịt thì ước muốn những điều trái ngược với Thần Khí, còn Thần Khí lại ước muốn những điều trái ngược với tính xác thịt, đôi bên kình địch nhau, khiến anh em không làm được điều anh em muốn. (18) Nếu anh em để cho Thần Khí hướng dẫn, thì anh em không còn lệ thuộc Lề Luật nữa. (19) Những việc do tính xác thịt gây ra thì ai cũng rõ, đó là: dâm bôn, ô uế, phóng đãng, (20) thờ quấy, phù phép, hận thù, bất hòa, ghen tuông, nóng giận, tranh chấp, chia rẽ, bè phái, (21) ganh tị, say sưa, chè chén, và những điều khác giống như vậy. Tôi bảo trước cho mà biết, như tôi đã từng bảo: những kẻ làm các điều đó sẽ không được thừa hưởng Nước Thiên Chúa. (22) Còn hoa quả của Thần Khí là: bác ái, hoan lạc, bình an, nhẫn nhục, nhân hậu, từ tâm, trung tín, (23) hiền hòa, tiết độ. Không có luật nào chống lại những điều như thế. (24) Những ai thuộc về Đức Ki-tô Giê-su thì đã đóng đinh tính xác thịt vào thập giá cùng với các dục vọng và đam mê.
(25) Nếu chúng ta sống nhờ Thần Khí, thì cũng hãy nhờ Thần Khí mà tiến bước. (26) Chúng ta đừng có tìm hư danh, đừng khiêu khích nhau, đừng ganh tị nhau.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'gl', 6, '[SECTION] Đôi lời khuyên nhủ sống bác ái và nhiệt thành
(1) Thưa anh em, nếu có ai vướng mắc tội nào, thì anh em, những người được Thần Khí thúc đẩy, hãy lấy tinh thần hiền hòa mà sửa dạy người ấy; phải tự đề phòng kẻo chính mình cũng bị cám dỗ. (2) Anh em hãy mang gánh nặng cho nhau, như vậy là anh em chu toàn luật Đức Ki-tô. (3) Thật vậy, ai tưởng mình là gì mà kỳ thực không là gì hết, thì là lừa gạt chính mình. (4) Mỗi người hãy xem xét việc làm của chính mình, và bấy giờ sẽ có lý do để hãnh diện vì chính mình, chứ không phải vì so sánh với người khác. (5) Quả thế, mỗi người phải mang gánh nặng của riêng mình.
(6) Người được học Lời Chúa, hãy chia sẻ mọi của cải với người dạy dỗ mình.
(7) Anh em đừng có lầm tưởng: Thiên Chúa không để cho người ta nhạo báng đâu! Thật vậy, ai gieo giống nào thì sẽ gặt giống ấy. (8) Ai theo tính xác thịt mà gieo điều xấu, thì sẽ gặt được hậu quả của tính xác thịt là sự hư nát. Còn ai theo Thần Khí mà gieo điều tốt, thì sẽ gặt được kết quả của Thần Khí là sự sống đời đời. (9) Khi làm điều thiện, chúng ta đừng nản chí, vì đến mùa chúng ta sẽ được gặt, nếu không sờn lòng. (10) Vậy bao lâu còn thời giờ, chúng ta hãy làm điều thiện cho mọi người, nhất là cho những anh em trong cùng đại gia đình đức tin.
[SECTION] Lời cuối thư
(11) Anh em thấy những chữ to này: chính tay tôi viết cho anh em đó! (12) Những ai muốn nở mày nở mặt vì những lý do thuần túy con người, thì ép anh em phải chịu cắt bì, chỉ là để khỏi bị ngược đãi vì thập giá Đức Ki-tô. (13) Thật vậy, chính những kẻ được cắt bì cũng không giữ Lề Luật, nhưng họ muốn anh em phải cắt bì để tìm được nơi thân xác anh em, một lý do hãnh diện. (14) Ước chi tôi chẳng hãnh diện về điều gì, ngoài thập giá Đức Giê-su Ki-tô, Chúa chúng ta! Nhờ thập giá Người, thế gian đã bị đóng đinh vào thập giá đối với tôi, và tôi đối với thế gian. (15) Quả thật, cắt bì hay không cắt bì chẳng là gì cả, điều quan trọng là trở nên một thụ tạo mới. (16) Chúc tất cả những ai sống theo quy tắc ấy, và chúc Ít-ra-en của Thiên Chúa được hưởng bình an và lòng thương xót của Người.
(17) Từ nay, xin đừng có ai gây phiền toái cho tôi nữa, vì tôi mang trên mình tôi những dấu tích của Đức Giê-su. (18) Thưa anh em, nguyện xin Đức Giê-su Ki-tô, Chúa chúng ta, ban cho thần trí anh em được đầy tràn ân sủng. A-men.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;