INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'dt', 1, '[PART] Chương 1
[PART] LỜI TỰA
[SECTION] Địa vị cao trọng của Con Thiên Chúa làm người
(1) Thuở xưa, nhiều lần nhiều cách, Thiên Chúa đã phán dạy cha ông chúng ta qua các ngôn sứ; (2) nhưng vào thời sau hết này, Thiên Chúa đã phán dạy chúng ta qua Thánh Tử. Thiên Chúa đã nhờ Người mà dựng nên vũ trụ, đã đặt Người làm Đấng thừa hưởng muôn vật muôn loài. (3) Người là phản ánh vẻ huy hoàng, là hình ảnh trung thực của bản thể Thiên Chúa. Người là Đấng dùng lời quyền năng của mình mà duy trì vạn vật. Sau khi đã tẩy trừ tội lỗi, Người lên ngự bên hữu Đấng Cao Cả trên trời. (4) Danh hiệu Người được thừa hưởng, cao cả hơn danh hiệu các thiên thần bao nhiêu, thì Người lại trổi hơn họ bấy nhiêu.
[PART] I. CON THIÊN CHÚA CAO TRỌNG HƠN CÁC THIÊN THẦN
[SECTION] Bằng chứng Kinh Thánh
(5) Thật vậy, có bao giờ Thiên Chúa đã phán cùng vị thiên thần nào: Con là Con của Cha, ngày hôm nay Cha đã sinh ra Con hoặc là: Ta sẽ là Cha Người, và chính Người sẽ là Con Ta. (6) Còn khi đưa Trưởng Tử vào thế giới loài người, Thiên Chúa lại nói: Mọi thiên thần của Thiên Chúa, phải thờ lạy Người. (7) Về các thiên thần, thì có lời chép: Người làm cho thiên thần của Người nên những luồng gió, và thuộc hạ của Người thành những ngọn lửa. (8) Nhưng về Người Con, thì Kinh Thánh lại nói: Lạy Thiên Chúa, ngôi báu Ngài sẽ trường tồn vạn kỷ! Vương trượng Ngài, vương trượng công minh. (9) Ngài ưa điều chính trực, ghét điều gian ác. Chính vì vậy, Thiên Chúa là Thiên Chúa của Ngài đã tôn phong Ngài vượt trổi các đồng liêu, mà xức cho dầu thơm hoan lạc. (10) Và có lời khác: Lạy Chúa, lúc khởi đầu, Chúa đã đặt nền trái đất, chính tay Ngài tạo tác vòm trời. (11) Chúng tiêu tan, Chúa vẫn còn hoài; chúng đều sẽ cũ đi như chiếc áo. (12) Chúa sẽ cuốn chúng lại như cuốn áo choàng, chúng sẽ bị thay như người ta thay áo. Nhưng chính Chúa vẫn tiền hậu y nguyên, và năm tháng của Ngài sẽ không chấm dứt. (13) Và có bao giờ Thiên Chúa đã phán với một thiên thần nào rằng: Bên hữu Cha đây, Con lên ngự trị, để rồi bao địch thù, Cha sẽ đặt làm bệ dưới chân Con? (14) Nào tất cả các vị đó không phải là những bậc thiêng liêng chuyên lo phụng thờ Chúa, được sai đi phục vụ để mưu ích cho những kẻ sẽ được thừa hưởng ơn cứu độ sao?') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'dt', 2, '[SECTION] Lời khuyên nhủ
(1) Vì thế, chúng ta càng phải chú tâm hơn nữa vào những lời đã nghe, kẻo bị cuốn trôi đi mất. (2) Quả vậy, nếu lời được các thiên thần loan báo đã có hiệu lực, và nếu mọi vi phạm cũng như bất tuân đều bị phạt đích đáng, (3) thì làm sao chúng ta thoát khỏi, nếu chúng ta thờ ơ với ơn cứu độ cao quý như thế? Ơn cứu độ đó, đầu tiên đã được Chúa rao giảng, rồi được những kẻ nghe cho chúng ta thấy là có hiệu lực, (4) đồng thời được Thiên Chúa chứng thực bằng những dấu lạ điềm thiêng, bằng nhiều quyền năng khác nhau và bằng các ân huệ của Thánh Thần mà Người phân phát tùy ý muốn của Người.
[SECTION] Đức Ki-tô thực hiện công trình cứu chuộc, chứ không phải các thiên thần
(5) Thật vậy, Thiên Chúa đã không trao cho các thiên thần quyền làm chủ thế giới tương lai, thế giới mà chúng ta đang nói đến. (6) Nhưng trong một đoạn Kinh Thánh kia, có người đã làm chứng rằng: Phàm nhân là chi mà Chúa cần nhớ đến? Con người là gì mà Chúa phải thăm nom? (7) Chúa đã làm cho con người thua kém các thiên thần trong một thời gian ngắn, ban vinh quang, danh dự làm mũ triều thiên, (8) đặt muôn loài, muôn sự dưới chân con người, bắt chúng phải phục quyền con người. Khi bắt muôn loài muôn sự phải phục quyền con người, Thiên Chúa không để cho một sự gì không phục quyền con người. Thật ra, hiện nay chúng ta chưa thấy muôn loài muôn sự phục quyền con người. (9) Nhưng con người đã bị thua kém các thiên thần trong một thời gian ngắn, thì chúng ta lại thấy được Thiên Chúa ban vinh quang danh dự làm mũ triều thiên, bởi vì đã cam chịu tử hình. Con người đó, chính là Đức Giê-su. Thật vậy, Đức Giê-su đã phải nếm sự chết, là để cho mọi người được cứu độ, nhờ ơn Thiên Chúa.
(10) Quả thế, Thiên Chúa là nguồn gốc và cùng đích mọi loài, chính vì muốn đưa muôn vàn con cái đến vinh quang, nên Người đã làm một việc thích đáng, là cho Đức Giê-su trải qua gian khổ mà trở thành vị lãnh đạo thập toàn, dẫn đưa họ tới nguồn ơn cứu độ. (11) Thật vậy, Đấng thánh hóa là Đức Giê-su, và những ai được thánh hóa đều do một nguồn gốc. Vì thế, Người đã không hổ thẹn gọi họ là anh em, (12) khi nói: Con nguyện sẽ loan truyền danh Chúa cho anh em tất cả được hay, và trong đại hội Dân Ngài, con xin dâng tiến một bài tán dương.
(13) Người lại nói: Phần tôi, tôi sẽ tin cậy Thiên Chúa. Người còn nói: Này tôi đây, cùng với những con cái mà Thiên Chúa đã ban cho tôi.
(14) Như thế, vì con cái thì đều chung một huyết nhục, nên Đức Giê-su đã cùng mang lấy huyết nhục đó. Như vậy, nhờ cái chết của Người, Người đã tiêu diệt tên lãnh chúa gây ra sự chết, tức là ma quỷ, (15) và đã giải thoát những ai vì sợ chết mà suốt đời sống trong tình trạng nô lệ. (16) Vì những kẻ được Người giúp đỡ không phải là các thiên thần, mà là con cháu Áp-ra-ham. (17) Bởi thế, Người đã phải nên giống anh em mình về mọi phương diện, để trở thành một vị Thượng Tế nhân từ và trung tín trong việc thờ phượng Thiên Chúa, hầu đền tội cho dân. (18) Vì bản thân Người đã trải qua thử thách và đau khổ, nên Người có thể cứu giúp những ai bị thử thách.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'dt', 3, '[PART] II. ĐỨC GIÊ-SU, VỊ THƯỢNG TẾ TRUNG THÀNH VÀ BIẾT CẢM THƯƠNG
[SECTION] Đức Ki-tô cao trọng hơn ông Mô-sê
(1) Do đó, thưa anh em là những người trong dân thánh, những người được hưởng chung ơn gọi bởi trời, anh em hãy ngắm nhìn Đức Giê-su là Sứ Giả, là Thượng Tế, là Trung Gian cho chúng ta tuyên xưng đức tin. (2) Người trung thành với Đấng đã đặt Người lên chức vụ đó, cũng như ông Mô-sê đã trung thành khi thi hành chức vụ đối với toàn thể nhà Thiên Chúa. (3) Như người làm nhà đáng tôn vinh hơn chính ngôi nhà, thì Đức Giê-su cũng được coi là đáng tôn vinh hơn ông Mô-sê. (4) Quả thật, nhà nào cũng phải có người làm ra, và Đấng làm ra mọi sự là Thiên Chúa. (5) Ông Mô-sê đã trung thành khi thi hành chức vụ đối với toàn thể nhà Thiên Chúa, với tư cách là tôi tớ để làm chứng về các điều Thiên Chúa sẽ phán truyền. (6) Còn Đức Ki-tô thì trung thành với tư cách là người Con đứng đầu nhà Thiên Chúa. Mà nhà Thiên Chúa là chính chúng ta, miễn là chúng ta giữ vững đến cùng lòng tin tưởng và thái độ hiên ngang về niềm hy vọng của chúng ta.
[SECTION] Đức tin dẫn vào chốn yên nghỉ của Thiên Chúa
(7) Vì thế, như lời Thánh Thần phán: Ngày hôm nay, nếu các ngươi nghe tiếng Chúa, (8) thì chớ cứng lòng như hồi chúng nổi loạn, như ngày chúng thử thách Ta trong sa mạc, (9) nơi cha ông các ngươi đã từng dò xét mà thử thách Ta và đã thấy các việc Ta làm (10) suốt bốn mươi năm. Vì thế, Ta đã nổi giận với dòng giống này, Ta đã nói: Tâm hồn chúng cứ lầm lạc mãi, chúng nào biết đến đường lối của Ta. (11) Nên Ta mới thịnh nộ thề rằng: chúng sẽ không được vào chốn yên nghỉ của Ta! (12) Thưa anh em, hãy đề phòng, đừng để người nào trong anh em có lòng dạ xấu xa chối bỏ đức tin mà lìa xa Thiên Chúa hằng sống. (13) Trái lại, ngày ngày anh em hãy khuyên bảo nhau bao lâu còn được gọi là ngày hôm nay, kẻo có ai trong anh em ra cứng lòng vì bị tội lỗi lừa gạt. (14) Quả thế, chúng ta đã được thông phần Đức Ki-tô, miễn là chúng ta cứ giữ vững cho đến cùng căn bản của lòng tin đã có từ ban đầu. (15) Trong câu: Ngày hôm nay, nếu các ngươi nghe tiếng Chúa, thì chớ cứng lòng như hồi chúng nổi loạn, (16) ai là những kẻ đã nghe tiếng Chúa, rồi nổi loạn? Chẳng phải là những người đã được ông Mô-sê đưa ra khỏi Ai-cập sao? (17) Thiên Chúa đã nổi giận với ai suốt bốn mươi năm? Chẳng phải là với những người đã phạm tội và đã ngã gục, bỏ xác trong sa mạc sao? (18) Nhưng Người thề với ai: Sẽ không được vào chốn yên nghỉ của Người, nếu không phải là với những kẻ bất tuân? (19) Và chúng ta thấy rằng họ đã không thể vào được đó, bởi vì họ chối bỏ đức tin.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'dt', 4, '(1) Vậy chúng ta phải sợ rằng trong khi lời hứa được vào chốn yên nghỉ của Người vẫn còn đó, mà có ai trong anh em bị coi đã mất cơ hội. (2) Quả thế, chúng ta đã được nghe loan báo Tin Mừng như những người kia. Nhưng lời họ đã nghe không sinh ích gì cho họ, bởi vì những kẻ đã nghe không lấy đức tin đáp lại lời giảng. (3) Còn chúng ta là những người tin, chúng ta đang vào chốn yên nghỉ đó, như lời Thiên Chúa đã phán: Nên Ta mới thịnh nộ thề rằng: chúng sẽ không được vào chốn yên nghỉ của Ta. Công việc của Thiên Chúa đã hoàn thành từ tạo thiên lập địa, (4) như có chỗ Thiên Chúa phán về ngày thứ bảy rằng: Khi đã làm xong mọi công việc, thì ngày thứ bảy Thiên Chúa nghỉ. (5) Trong đoạn thánh vịnh nói trên, lại cũng có lời chép rằng: Chúng sẽ không được vào chốn yên nghỉ của Ta. (6) Vậy vì phải có một số người được vào chốn yên nghỉ, và vì những người đầu tiên được nghe loan báo Tin Mừng đã không được vào bởi họ bất tuân, (7) nên Thiên Chúa lại ấn định một ngày khác, tức là ngày hôm nay, khi Người dùng vua Đa-vít mà phán, sau một thời gian rất lâu dài, như đã nói ở trên: Ngày hôm nay, nếu các ngươi nghe tiếng Chúa, thì chớ cứng lòng. (8) Thật vậy, nếu ông Giô-suê đã cho họ được yên nghỉ, thì sau đó, Thiên Chúa đã chẳng nói đến một ngày khác nữa. (9) Như thế, Dân Thiên Chúa còn có thể được nghỉ như Thiên Chúa nghỉ ngày thứ bảy, (10) vì ai đã vào chốn yên nghỉ của Thiên Chúa, thì cũng đã nghỉ sau khi làm xong công việc của mình, như Thiên Chúa đã nghỉ sau khi làm xong công việc của Người. (11) Vậy, chúng ta hãy cố gắng vào chốn yên nghỉ này, kẻo có ai cũng theo gương bất tuân đó mà sa ngã. (12) Lời Thiên Chúa là lời sống động, hữu hiệu và sắc bén hơn cả gươm hai lưỡi: xuyên thấu chỗ phân cách tâm với linh, cốt với tủy; lời đó phê phán tâm tình cũng như tư tưởng của lòng người. (13) Vì không có loài thụ tạo nào mà không hiện rõ trước Lời Chúa, nhưng tất cả đều trần trụi và phơi bày trước mặt Đấng có quyền đòi chúng ta trả lẽ.
[SECTION] Đức Giê-su, vị Thượng Tế biết cảm thương
(14) Chúng ta có một vị Thượng Tế siêu phàm đã băng qua các tầng trời, là Đức Giê-su, Con Thiên Chúa. Vậy chúng ta hãy giữ vững lời tuyên xưng đức tin. (15) Vị Thượng Tế của chúng ta không phải là Đấng không biết cảm thương những nỗi yếu hèn của ta, vì Người đã chịu thử thách về mọi phương diện cũng như ta, nhưng không phạm tội. (16) Bởi thế, ta hãy mạnh dạn tiến lại gần ngai Thiên Chúa là nguồn ân sủng, để được xót thương và lãnh ơn trợ giúp mỗi khi cần.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'dt', 5, '(1) Quả vậy, thượng tế nào cũng là người được chọn trong số người phàm, và được đặt lên làm đại diện cho loài người, trong các mối tương quan với Thiên Chúa, để dâng lễ phẩm cũng như tế vật đền tội. (2) Vị ấy có khả năng cảm thông với những kẻ ngu muội và những kẻ lầm lạc, bởi vì chính người cũng đầy yếu đuối; (3) mà vì yếu đuối, nên người phải dâng lễ đền tội cho dân thế nào, thì cũng phải dâng lễ đền tội cho chính mình như vậy. (4) Không ai tự gán cho mình vinh dự ấy, nhưng phải được Thiên Chúa gọi, như ông A-ha-ron đã được gọi. (5) Cũng vậy, không phải Đức Ki-tô đã tự tôn mình làm Thượng Tế, nhưng là Đấng đã nói với Người: Con là Con của Cha, ngày hôm nay Cha đã sinh ra Con, (6) như lời Đấng ấy đã nói ở một chỗ khác: Muôn thuở, Con là Thượng Tế theo phẩm trật Men-ki-xê-đê. (7) Khi còn sống kiếp phàm nhân, Đức Giê-su đã lớn tiếng kêu van khóc lóc mà dâng lời khẩn nguyện nài xin lên Đấng có quyền năng cứu Người khỏi chết. Người đã được nhậm lời, vì có lòng tôn kính. (8) Dầu là Con Thiên Chúa, Người đã phải trải qua nhiều đau khổ mới học được thế nào là vâng phục; (9) và khi chính bản thân đã tới mức thập toàn, Người trở nên nguồn ơn cứu độ vĩnh cửu cho tất cả những ai tùng phục Người, (10) vì Người đã được Thiên Chúa tôn xưng là Thượng Tế theo phẩm trật Men-ki-xê-đê.
[PART] III. ĐỨC GIÊ-SU KI-TÔ, VỊ THƯỢNG TẾ ĐÍCH THỰC
[SECTION] Đời sống Ki-tô hữu và vấn đề đạo lý
(11) Về vấn đề này, chúng tôi còn có nhiều điều phải nói, nhưng khó mà cắt nghĩa, vì anh em đã trở nên uể oải không muốn nghe. (12) Quả thật, với thời gian, đáng lẽ anh em đã phải là những bậc thầy, thế mà anh em lại cần phải để cho người ta dạy anh em những điều sơ đẳng về các sấm ngôn của Thiên Chúa: thay vì thức ăn đặc, anh em lại phải cần dùng sữa. (13) Thật vậy, phàm ai còn phải dùng đến sữa, thì không hiểu gì về đạo lý liên quan đến sự công chính, vì người ấy vẫn là trẻ con. (14) Thức ăn đặc thì dành cho những người đã trưởng thành, những người nhờ thực hành mà rèn luyện được khả năng phân biệt điều lành điều dữ.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'dt', 6, '[SECTION] Ý định của tác giả
(1) Vì thế, gác một bên giáo huấn sơ đẳng về Đức Ki-tô, chúng ta hãy vươn tới trình độ giáo huấn trưởng thành mà không trở lại những điều căn bản, là lòng sám hối ăn năn vì những việc đưa tới sự chết, là niềm tin vào Thiên Chúa, (2) là giáo lý về mấy loại phép rửa; là nghi thức đặt tay, là vấn đề kẻ chết sống lại và cuộc phán xét cuối cùng. (3) Đó là điều chúng ta sắp làm, nếu Thiên Chúa cho phép.
(4) Quả thật, những kẻ đã một lần được chiếu sáng, đã được nếm thử ân huệ bởi trời, đã được thông chia Thánh Thần, (5) đã được thưởng thức Lời tốt đẹp của Thiên Chúa và được cảm nghiệm những sức mạnh của thế giới tương lai, (6) những kẻ ấy mà sa ngã, thì không thể được đổi mới một lần nữa để sám hối ăn năn, vì họ đã tự tay đóng đinh Con Thiên Chúa vào thập giá một lần nữa và đã công khai sỉ nhục Người. (7) Khi mảnh đất nào được thấm mưa thường xuyên đổ xuống và sinh ra những loại cây có ích cho người canh tác, thì mảnh đất ấy nhận được phúc lành của Thiên Chúa. (8) Nhưng nếu chỉ sinh ra những gai cùng góc, thì đó là mảnh đất bỏ đi, bị nguyền rủa đến nơi rồi, và rốt cuộc sẽ bị đốt cháy.
[SECTION] Lời mang lại hy vọng và khích lệ
(9) Anh em thân mến, mặc dầu nói như thế, chúng tôi tin chắc rằng anh em ở trong một tình trạng tốt đẹp hơn và thuận lợi để được ơn cứu độ. (10) Quả thế, Thiên Chúa không bất công đến nỗi quên việc anh em đã làm và lòng yêu mến anh em đã tỏ ra đối với danh Người, khi trước đấy anh em phục vụ các người trong dân thánh, và hiện nay vẫn còn đang phục vụ. (11) Nhưng chúng tôi ao ước cho mỗi người trong anh em cũng tỏ ra nhiệt thành như thế, để niềm hy vọng của anh em được thực hiện đầy đủ cho đến cùng. (12) Anh em đừng trở nên uể oải, nhưng hãy bắt chước những người nhờ có đức tin và lòng kiên nhẫn mà được thừa hưởng các lời hứa.
(13) Quả thế, khi Thiên Chúa hứa với ông Áp-ra-ham, Người đã không thể lấy danh ai cao trọng hơn mình mà thề, nên đã lấy chính danh mình mà thề (14) rằng: Ta sẽ ban phúc dư dật cho ngươi và sẽ làm cho dòng dõi ngươi nên đông vô số. (15) Như thế, vì nhẫn nại đợi chờ, ông Áp-ra-ham đã nhận được lời hứa. (16) Người ta thường lấy danh một người cao trọng hơn mình mà thề, và lời thề là một bảo đảm chấm dứt mọi tranh chấp giữa người ta với nhau. (17) Do đó, vì Thiên Chúa muốn chứng minh rõ hơn cho những người thừa hưởng lời hứa được biết về ý định bất di bất dịch của Người, nên Người đã dùng lời thề mà bảo đảm điều Người đã hứa. (18) Như vậy, cả lời hứa lẫn lời thề đều bất di bất dịch, và khi thề hứa, Thiên Chúa không thể nói dối được. Do đó, chúng ta là những kẻ ẩn náu bên Thiên Chúa, chúng ta được mạnh mẽ khuyến khích nắm giữ niềm hy vọng dành cho chúng ta. (19) Chúng ta có niềm hy vọng đó cũng tựa như cái neo chắc chắn và bền vững của tâm hồn, chìm sâu vào bên trong bức màn cung thánh. (20) Đó là nơi Đức Giê-su đã vào như người tiền phong mở đường cho chúng ta, sau khi trở thành vị Thượng Tế đời đời theo phẩm trật Men-ki-xê-đê.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'dt', 7, '[PART] 1. ĐỨC KI-TÔ CAO TRỌNG HƠN CÁC TƯ TẾ LÊ-VI
[SECTION] Ông Men-ki-xê-đê
(1) Quả vậy, ông Men-ki-xê-đê là vua Sa-lem, là tư tế của Thiên Chúa Tối Cao, đã đón gặp và chúc lành cho ông Áp-ra-ham, lúc ông này đang trên đường về sau khi đánh bại các vua. (2) Ông Áp-ra-ham đã chia cho ông Men-ki-xê-đê một phần mười chiến lợi phẩm. Trước hết, ông tên là Men-ki-xê-đê, nghĩa là “vua công chính”; rồi ông lại là vua Sa-lem, nghĩa là “vua bình an”. (3) Ông không có cha, không có mẹ, không có gia phả, cuộc đời không có khởi đầu, cũng không có kết thúc. Như thế là ông giống Con Thiên Chúa: mãi mãi ông vẫn là tư tế.
[SECTION] Ông Men-ki-xê-đê nhận một phần mười chiến lợi phẩm của ông Áp-ra-ham
(4) Anh em hãy coi xem: ông Men-ki-xê-đê cao trọng biết bao! Ông Áp-ra-ham là tổ phụ, mà cũng đã dâng cho ông một phần mười chiến lợi phẩm tốt nhất. (5) Trong hàng con cháu ông Lê-vi, những ai lãnh chức tư tế, thì theo Lề Luật, được lệnh thu một phần mười hoa lợi của dân, tức là của anh em mình, mặc dù những người này cũng từ lòng ông Áp-ra-ham mà sinh ra. (6) Còn ông Men-ki-xê-đê, tuy không thuộc dòng tộc Lê-vi, lại thu một phần mười chiến lợi phẩm của ông Áp-ra-ham và chúc lành cho ông là người đã nhận được lời hứa. (7) Điều không ai chối cãi được là chỉ người dưới mới nhận lời chúc lành của người trên. (8) Hơn nữa, một đàng các tư tế Lê-vi thu một phần mười hoa lợi là những người phàm phải chết; một đàng ông Men-ki-xê-đê, người thu một phần mười chiến lợi phẩm, lại là nhân vật đang sống, như lời Kinh Thánh chứng nhận. (9) Có thể nói rằng: chính ông Lê-vi, người thu một phần mười hoa lợi, cũng đã nộp một phần mười chiến lợi phẩm qua ông Áp-ra-ham, (10) vì ông còn ở trong lòng ông tổ Áp-ra-ham, khi ông Men-ki-xê-đê ra đón gặp ông này.
[SECTION] Từ chức tư tế Lê-vi đến chức tư tế theo phẩm trật Men-ki-xê-đê
(11) Chức vụ tư tế Lê-vi là nền tảng của Lề Luật Thiên Chúa đã ban cho Dân. Vậy giả như người ta đạt được sự hoàn thiện nhờ chức vụ tư tế đó rồi, thì còn cần chi phải đặt lên một tư tế khác theo phẩm trật Men-ki-xê-đê, thay vì theo phẩm trật A-ha-ron? (12) Quả thế, một khi chức tư tế thay đổi, thì nhất thiết phải thay đổi Lề Luật. (13) Thật ra những điều nói trên nhắm đến một người thuộc một chi tộc khác, chi tộc này chưa hề có ai đã phục vụ bàn thờ. (14) Hiển nhiên là Chúa chúng ta đã xuất thân từ chi tộc Giu-đa, một chi tộc không được ông Mô-sê nói gì đến, khi bàn về các tư tế.
[SECTION] Bãi bỏ Lề Luật cũ
(15) Điều ấy lại còn hiển nhiên hơn nữa, khi một vị tư tế khác tương tự như ông Men-ki-xê-đê xuất hiện; (16) vị này đã trở nên tư tế không phải do Lề Luật quy định việc cha truyền con nối, nhưng do sức mạnh của một đời sống bất diệt. (17) Quả thật, có lời chứng nhận rằng: Muôn thuở, Con là Thượng Tế theo phẩm trật Men-ki-xê-đê. (18) Như vậy, một đàng, quy luật cũ đã bị bãi bỏ, vì có nhược điểm và vô ích, (19) –thật thế, Lề Luật đã chẳng làm cho cái gì nên hoàn hảo–; đàng khác, một niềm hy vọng tốt đẹp hơn đã được đưa vào thay thế, nhờ đó chúng ta đến gần Thiên Chúa.
[SECTION] Đức Ki-tô là Thượng Tế đời đời
(20) Hơn nữa, điều ấy đã xảy ra không phải là không có lời thề. Một đàng, các tư tế Lê-vi đã trở nên tư tế mà không có lời thề; (21) còn Đức Giê-su khi trở nên tư tế, thì lại có lời thề của Đấng nói với Người: Đức Chúa đã thề ước, Người sẽ chẳng rút lời, rằng: Muôn thuở, Con là Thượng Tế. (22) Do đó, Đức Giê-su đã trở nên Đấng bảo đảm cho một giao ước tốt đẹp hơn. (23) Lại nữa, trong dòng tộc Lê-vi, có nhiều người kế tiếp nhau làm tư tế, bởi vì họ phải chết, không thể giữ mãi chức vụ đó. (24) Còn Đức Giê-su, chính vì Người hằng sống muôn đời, nên phẩm vị tư tế của Người tồn tại mãi mãi. (25) Do đó, Người có thể đem ơn cứu độ vĩnh viễn cho những ai nhờ Người mà tiến lại gần Thiên Chúa. Thật vậy, Người hằng sống để chuyển cầu cho họ.
[SECTION] Vị Thượng Tế thập toàn
(26) Phải, đó chính là vị Thượng Tế mà chúng ta cần đến: một vị Thượng Tế thánh thiện, vẹn toàn, vô tội, tách biệt khỏi đám tội nhân và được nâng cao vượt các tầng trời. (27) Đức Giê-su không như các vị thượng tế khác: mỗi ngày họ phải dâng lễ tế hy sinh, trước là để đền tội của mình, sau là để đền thay cho dân; phần Người, Người đã dâng chính mình và chỉ dâng một lần là đủ. (28) Vì Luật Mô-sê thì đặt làm thượng tế những con người vốn mỏng giòn yếu đuối, còn lời thề có sau Lề Luật, lại đặt Người Con đã nên thập toàn cho đến muôn đời.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'dt', 8, '[PART] 2. PHỤNG TỰ, THÁNH ĐIỆN VÀ ĐỊA VỊ TRUNG GIAN CỦA ĐỨC KI-TÔ CAO TRỌNG HƠN
[SECTION] Chức tư tế mới và thánh điện mới
(1) Điểm chủ yếu trong những điều đang nói ở đây là điểm này: chúng ta có một vị Thượng Tế cao cả như thế ngự bên hữu ngai Đấng uy linh ở trên trời. (2) Vị đó lo việc tế tự trong cung thánh, trong lều trại thật, do Thiên Chúa chứ không phải do người phàm dựng lên. (3) Quả vậy, bất cứ ai được phong làm thượng tế cũng là để dâng lễ vật và tế phẩm; vì thế, vị này cũng cần phải có cái gì để dâng. (4) Vậy, giả như Đức Giê-su ở dưới thế, thì Người chẳng phải là tư tế, bởi vì đã có những người dâng lễ vật như Luật truyền. (5) Những người này lo việc phụng tự trong một thánh điện, mà thánh điện này chỉ là hình ảnh lu mờ mô phỏng thánh điện trên trời. Quả vậy, khi ông Mô-sê sắp dựng lều trại, thì ông được Thiên Chúa phán dạy rằng: Hãy nhìn xem và làm tất cả theo mẫu đã chỉ cho ngươi trên núi.
[SECTION] Đức Ki-tô, trung gian của một giao ước tốt đẹp hơn
(6) Nhưng hiện nay, Đức Giê-su được một tác vụ cao trọng hơn, bởi vì Người là trung gian của một giao ước tốt đẹp hơn; giao ước này căn cứ vào những lời hứa tốt đẹp hơn. (7) Thật vậy, giả như giao ước thứ nhất đã hoàn hảo rồi, thì chẳng cần phải tìm giao ước thứ hai để thay thế. (8) Quả thật, Thiên Chúa khiển trách Dân rằng: Đức Chúa phán: Này sắp đến những ngày Ta hoàn thành một Giao Ước Mới với nhà Ít-ra-en và nhà Giu-đa. (9) Giao ước đó sẽ không như giao ước Ta đã thiết lập với cha ông của chúng, trong ngày Ta cầm tay dẫn chúng ra khỏi Ai-cập. Bởi vì chúng đã không trung thành với giao ước của Ta, nên Ta cũng đã bỏ mặc chúng, Đức Chúa phán: (10) Đây là giao ước Ta sẽ lập với nhà Ít-ra-en sau những ngày đó, Đức Chúa phán: Ta sẽ ghi vào lòng trí chúng, sẽ khắc vào tâm khảm chúng lề luật của Ta; Ta sẽ là Thiên Chúa của chúng, còn chúng sẽ là Dân của Ta. (11) Không ai còn phải dạy đồng bào mình, không ai còn phải dạy anh em mình rằng: “Hãy học cho biết Đức Chúa”, vì hết thảy chúng, từ người nhỏ đến người lớn, sẽ biết Ta. (12) Ta sẽ dung thứ những điều gian ác chúng làm, sẽ không còn nhớ đến lỗi lầm của chúng nữa.
(13) Khi Thiên Chúa nói đến Giao Ước Mới, Người làm cho giao ước thứ nhất hóa ra giao ước cũ; và cái gì cũ kỹ, lỗi thời, thì sắp tan biến đi.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'dt', 9, '[SECTION] Đức Ki-tô tiến vào thánh điện trên trời
(1) Vậy, giao ước thứ nhất đã có những quy luật phụng tự và có thánh điện dưới đất. (2) Quả thật, một cái lều, cái lều thứ nhất, đã được dựng lên; lều này được gọi là Nơi Thánh, có cây đèn bảy ngọn, có bàn và bánh dâng tiến. (3) Đằng sau bức màn thứ hai, có một cái lều gọi là Nơi Cực Thánh. (4) Trong đó, có hương án bằng vàng và Hòm Bia Giao Ước hoàn toàn bọc vàng; Hòm Bia này chứa bình vàng đựng man-na, cây gậy trổ hoa của ông A-ha-ron và các tấm bia Giao Ước. (5) Trên Hòm Bia, có hai tượng Kê-ru-bim rạng ngời vinh quang Thiên Chúa, dang cánh che phủ nắp xá tội. Bây giờ không phải là lúc nói tỉ mỉ về các điều đó.
(6) Mọi sự xếp đặt như thế rồi, các tư tế thường xuyên vào lều thứ nhất để cử hành việc phụng tự. (7) Còn lều thứ hai, thì chỉ một mình vị thượng tế mới được vào mỗi năm một lần, đem theo máu để dâng làm của lễ đền tội cho chính mình và cho dân. (8) Như thế, Thánh Thần tỏ cho biết là lối vào Nơi Cực Thánh chưa được mở, bao lâu lều thứ nhất vẫn còn đó. (9) Điều ấy là hình ảnh ám chỉ thời hiện tại, cho thấy những lễ vật và hy lễ dâng tiến Thiên Chúa không thể làm cho lương tâm người cử hành việc phụng tự trở nên hoàn thiện. (10) Những cái đó chỉ liên quan đến của ăn thức uống cùng các loại nghi thức tẩy rửa, và là những quy luật chỉ có hiệu lực bên ngoài, buộc phải giữ cho đến thời Thiên Chúa chấn chỉnh mọi sự.
(11) Nhưng Đức Ki-tô đã đến làm Thượng Tế đem phúc lộc của thế giới tương lai. Để vào cung thánh, Người đã đi qua một cái lều lớn hơn và hoàn hảo hơn, không do bàn tay con người làm nên, nghĩa là không thuộc về thế giới thụ tạo này. (12) Người đã vào cung thánh không phải với máu các con dê, con bò, nhưng với chính máu của mình, Người vào chỉ một lần thôi, và đã lãnh được ơn cứu chuộc vĩnh viễn cho chúng ta. (13) Vậy nếu máu các con dê, con bò, nếu nước tro của xác bò cái, đem rảy lên mình những kẻ nhiễm uế còn thánh hóa được họ, nghĩa là cho thân xác họ trở nên trong sạch, (14) thì máu của Đức Ki-tô càng hiệu lực hơn biết mấy. Nhờ Thánh Thần hằng hữu thúc đẩy, Đức Ki-tô đã tự hiến tế như lễ vật vẹn toàn dâng lên Thiên Chúa. Máu của Người thanh tẩy lương tâm chúng ta khỏi những việc đưa tới sự chết, để chúng ta xứng đáng phụng thờ Thiên Chúa hằng sống.
[SECTION] Đức Ki-tô lấy máu mình lập Giao Ước Mới
(15) Bởi vậy, Người là trung gian của một Giao Ước Mới, lấy cái chết của mình mà chuộc tội lỗi người ta đã phạm trong thời giao ước cũ, và đem lại cho những ai được Thiên Chúa kêu gọi quyền lãnh nhận gia nghiệp vĩnh cửu Thiên Chúa đã hứa. (16) Ở đâu có chúc thư, thì cần phải chứng minh rằng người làm chúc thư đã chết. (17) Thật vậy, chúc thư chỉ có giá trị khi người làm chúc thư đã chết, bởi vì chúc thư không bao giờ có hiệu lực bao lâu người làm chúc thư còn sống. (18) Do đó, nếu không có máu, thì đã không khai mạc giao ước thứ nhất. (19) Quả thế, sau khi ông Mô-sê công bố cho toàn dân mọi điều răn như đã ghi chép trong Sách Luật, thì ông lấy máu các con bê, con dê hòa lẫn với nước, rồi dùng len đỏ thắm và cành hương thảo mà rảy trên chính cuốn Sách Luật cũng như trên toàn dân và (20) nói: Đây là máu giao ước, Thiên Chúa đã truyền cho anh em tuân giữ. (21) Rồi, cũng theo cách thức đó, ông rảy máu vào lều thánh và mọi đồ phụng tự. (22) Chiếu theo Lề Luật, hầu hết mọi sự đều được thanh tẩy bằng máu. Không có máu đổ ra, thì không có ơn tha thứ. (23) Vậy, nếu các hình ảnh mô phỏng những thực tại trên trời còn cần phải được thanh tẩy như thế, thì chính những thực tại trên trời đó lại càng phải được thanh tẩy bằng những hy lễ cao trọng hơn biết mấy. (24) Quả thế, Đức Ki-tô đã chẳng vào một cung thánh do tay người phàm làm ra, vì cung thánh ấy chỉ là hình bóng của cung thánh thật. Nhưng Người đã vào chính cõi trời, để giờ đây ra đứng trước mặt Thiên Chúa chuyển cầu cho chúng ta. (25) Người vào đó, không phải để dâng chính mình làm của lễ nhiều lần, như vị thượng tế mỗi năm phải đem theo máu của loài khác mà vào cung thánh. (26) Chẳng vậy, Người đã phải chịu khổ hình nhiều lần, từ khi thế giới được tạo thành. Nhưng nay, vào kỳ kết thúc thời gian, Người đã xuất hiện chỉ một lần, để tiêu diệt tội lỗi bằng việc hiến tế chính mình. (27) Phận con người là phải chết một lần, rồi sau đó chịu phán xét. (28) Cũng vậy, Đức Ki-tô đã tự hiến tế chỉ một lần, để xóa bỏ tội lỗi muôn người. Người sẽ xuất hiện lần thứ hai, nhưng lần này không phải để xóa bỏ tội lỗi, mà để cứu độ những ai trông đợi Người.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'dt', 10, '[PART] TÓM LƯỢC: HY LỄ CỦA ĐỨC KI-TÔ CAO TRỌNG HƠN HY LỄ THEO LUẬT MÔ-SÊ
[SECTION] Hy lễ theo luật cũ thì vô hiệu
(1) Lề Luật chỉ phác họa lờ mờ những phúc lộc của thế giới tương lai, chứ không phản ánh chính xác những thực tại đó. Cho nên, Lề Luật không bao giờ có thể làm cho những người tiến lại gần Thiên Chúa được nên hoàn thiện, nhờ những ngần ấy thứ hy lễ người ta cứ dâng mãi năm này qua năm khác. (2) Chẳng vậy, người ta đã thôi không còn dâng hy lễ, vì giả như những kẻ làm việc thờ phượng đã được thanh tẩy dứt khoát rồi, thì họ đâu còn ý thức mình có tội nữa? (3) Trái lại, năm này qua năm khác, chính những hy lễ đó nhắc cho người ta nhớ mình có tội. (4) Thật thế, máu các con bò, con dê không thể nào xóa được tội lỗi. (5) Vì vậy, khi vào trần gian, Đức Ki-tô nói: Chúa đã không ưa hy lễ và hiến tế, nhưng đã tạo cho con một thân thể. (6) Chúa cũng chẳng thích lễ toàn thiêu và lễ xá tội. (7) Bấy giờ con mới thưa: Lạy Thiên Chúa, này con đây, con đến để thực thi ý Ngài, như Sách Thánh đã chép về con.
(8) Trước hết, Đức Ki-tô nói: Hy lễ và hiến tế, lễ toàn thiêu và lễ xá tội, Chúa đã chẳng ưa, chẳng thích, mà đó chính là những thứ của lễ được dâng tiến theo Lề Luật truyền. (9) Rồi Người nói: Này con đây, con đến để thực thi ý Ngài. Thế là Người bãi bỏ các lễ tế cũ mà thiết lập lễ tế mới. (10) Theo ý đó, chúng ta được thánh hóa nhờ Đức Giê-su Ki-tô đã hiến dâng thân mình làm lễ tế, chỉ một lần là đủ.
[SECTION] Hy lễ của Đức Ki-tô thì hữu hiệu
(11) Vị tư tế nào cũng phải đứng trong Đền Thờ lo việc phụng tự mỗi ngày và dâng đi dâng lại cũng ngần ấy thứ lễ tế; mà những lễ tế đó chẳng bao giờ xóa bỏ được tội lỗi. (12) Còn Đức Ki-tô, sau khi dâng lễ tế duy nhất để đền tội cho nhân loại, Người đã lên ngự bên hữu Thiên Chúa đến muôn đời. (13) Và từ khi đó, Người chờ đợi ngày các kẻ thù bị đặt làm bệ dưới chân. (14) Quả thật, Người chỉ dâng hiến lễ một lần, mà vĩnh viễn làm cho những kẻ Người đã thánh hóa được nên hoàn hảo. (15) Điều đó cả Thánh Thần cũng làm chứng cho chúng ta thấy. Quả thật, sau khi phán: (16) Đây là giao ước Ta sẽ lập với chúng sau những ngày đó, thì Đức Chúa phán: Ta sẽ ghi vào tâm khảm chúng, sẽ khắc vào lòng trí chúng lề luật của Ta. (17) Ta sẽ không còn nhớ đến lỗi lầm và việc gian ác của chúng nữa. (18) Mà nơi nào đã có ơn tha tội, thì đâu cần lễ đền tội nữa.
[PART] IV. ĐỨC TIN KIÊN TRÌ
[SECTION] Chuyển tiếp
(19) Vậy, thưa anh em, nhờ máu Đức Giê-su đã đổ ra, chúng ta được mạnh dạn bước vào cung thánh. (20) Người đã mở cho chúng ta một con đường mới và sống động qua bức màn, tức là chính thân xác của Người. (21) Chúng ta lại có một vị tư tế cao trọng đứng đầu nhà Thiên Chúa. (22) Vì thế, chúng ta hãy tiến lại gần Thiên Chúa với một lòng chân thành và một đức tin trọn vẹn, vì trong lòng thì đã được tẩy sạch mọi vết nhơ của lương tâm, còn ngoài xác thì đã được tắm rửa bằng nước tinh tuyền. (23) Chúng ta hãy tiếp tục tuyên xưng niềm hy vọng của chúng ta cách vững vàng, vì Đấng đã hứa là Đấng trung tín. (24) Chúng ta hãy để ý đến nhau, làm sao cho người này thúc đẩy người kia sống yêu thương và làm những việc tốt. (25) Chúng ta đừng bỏ các buổi hội họp, như vài người quen làm; trái lại, phải khuyến khích nhau, nhất là khi anh em thấy Ngày Chúa đến đã gần.
[SECTION] Nguy cơ chối đạo
(26) Thật vậy, nếu chúng ta cố tình phạm tội sau khi đã học biết sự thật, thì không còn hy lễ nào đền tội được nữa, (27) mà chỉ còn phải sợ hãi đợi chờ cuộc phán xét và ngọn lửa nóng bừng thiêu hủy các đối tượng của Thiên Chúa. (28) Ai khinh thường luật Mô-sê, theo lời chứng của hai hay ba người, thì sẽ bị xử tử thẳng tay. (29) Phương chi kẻ đã chà đạp Con Thiên Chúa, đã xúc phạm đến Máu Giao Ước đã thánh hiến mình và nhục mạ Thần Khí ban ân sủng, thì anh em thử nghĩ xem, kẻ ấy đáng chịu hình phạt ghê gớm hơn biết mấy! (30) Vì chúng ta biết Đấng đã nói: Chính Ta sẽ báo oán, chính Ta sẽ đáp trả. Lại có lời rằng: Chúa sẽ xét xử Dân Người. (31) Thật là khủng khiếp, khi phải rơi vào tay Thiên Chúa hằng sống!
[SECTION] Lý do để kiên trì
(32) Xin anh em nhớ lại những ngày đầu: lúc vừa được ơn chiếu sáng, anh em đã phải đối phó với bao nỗi đau khổ dồn dập. (33) Khi thì anh em bị sỉ nhục và hành hạ trước mặt mọi người, khi thì phải liên đới với những người cùng cảnh ngộ. (34) Quả thật, anh em đã thông phần đau khổ với những người bị tù tội, và đã vui mừng để cho người ta tước đoạt của cải, bởi biết rằng mình có những của vừa quý giá hơn lại vừa bền vững. (35) Vậy, anh em đừng đánh mất lòng tin tưởng mạnh dạn của anh em; lòng tin tưởng đó sẽ mang lại một phần thưởng lớn lao. (36) Anh em cần phải kiên nhẫn, để sau khi thi hành ý Thiên Chúa, anh em được hưởng điều Người đã hứa. (37) Vì chỉ còn ít lâu nữa, một ít thôi, Đấng phải đến sẽ đến, Người sẽ không trì hoãn. (38) Người công chính của Ta nhờ lòng tin sẽ được sống; nhưng nếu người ấy bỏ cuộc, thì Ta không hài lòng về người ấy.
(39) Phần chúng ta, chúng ta không phải là những người bỏ cuộc để phải hư vong, nhưng là những người có lòng tin để bảo toàn sự sống.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'dt', 11, '[SECTION] Đức tin gương mẫu của các tổ phụ
(1) Đức tin là bảo đảm cho những điều ta hy vọng, là bằng chứng cho những điều ta không thấy. (2) Nhờ đức tin ấy, các tiền nhân đã được Thiên Chúa chứng giám.
(3) Nhờ đức tin, chúng ta hiểu rằng vũ trụ đã được hình thành bởi lời của Thiên Chúa; vì thế, những cái hữu hình là do những cái vô hình mà có. (4) Nhờ đức tin, ông A-ben đã dâng lên Thiên Chúa một hy lễ cao quý hơn hy lễ của ông Ca-in: nhờ tin như vậy, ông A-ben đã được chứng nhận là người công chính, bởi vì Thiên Chúa đã chấp nhận những lễ phẩm ông dâng. Và cũng nhờ tin như thế, mà tuy đã chết rồi, ông vẫn còn lên tiếng.
(5) Nhờ đức tin, ông Kha-nốc được đem đi nơi khác để khỏi chết, và người ta không tìm thấy ông nữa, bởi vì Thiên Chúa đã đem ông đi. Quả thật, Kinh Thánh chứng nhận rằng: trước khi được đem đi, ông đã làm đẹp lòng Thiên Chúa. (6) Mà không có đức tin, thì không thể làm đẹp lòng Thiên Chúa, vì ai đến gần Thiên Chúa, thì phải tin là có Thiên Chúa và tin Người là Đấng ban phần thưởng cho những ai tìm kiếm Người.
(7) Nhờ đức tin, ông Nô-ê được Thiên Chúa báo cho biết những gì người ta chưa thấy; vì có lòng kính sợ Thiên Chúa, ông đã đóng một chiếc tàu để cứu gia đình ông. Tin như thế là ông đã lên án thế gian, và được phần gia nghiệp là sự công chính nhờ đức tin.
(8) Nhờ đức tin, ông Áp-ra-ham đã vâng nghe tiếng Chúa gọi mà ra đi đến một nơi ông sẽ được lãnh nhận làm gia nghiệp, và ông đã ra đi mà không biết mình đi đâu. (9) Nhờ đức tin, ông đã tới cư ngụ tại Đất Hứa như tại một nơi đất khách, ông sống trong lều cũng như ông I-xa-ác và ông Gia-cóp là những người đồng thừa kế cùng một lời hứa, (10) vì ông trông đợi một thành có nền móng do chính Thiên Chúa vẽ mẫu và xây dựng. (11) Nhờ đức tin, cả bà Xa-ra vốn hiếm muộn, cũng đã có thể thụ thai và sinh con nối dòng vào lúc tuổi đã cao, vì bà tin rằng Đấng đã hứa là Đấng trung tín. (12) Vì thế, do một người duy nhất, một người kể như chết rồi mà đã sinh ra một dòng dõi nhiều như sao trời cát biển, không tài nào đếm được. (13) Tất cả các ngài đã chết, lúc vẫn còn tin như vậy, mặc dù chưa được hưởng các điều Thiên Chúa hứa; nhưng từ xa các ngài đã thấy và đón chào các điều ấy, cùng xưng mình là ngoại kiều, là lữ khách trên mặt đất. (14) Những người nói như vậy cho thấy là họ đang đi tìm một quê hương. (15) Và nếu quả thật họ còn nhớ tới quê hương mình đã bỏ ra đi, thì họ vẫn có cơ hội trở về. (16) Nhưng thật ra các ngài mong ước một quê hương tốt đẹp hơn, đó là quê hương trên trời. Bởi vậy, Thiên Chúa đã không hổ thẹn để cho các ngài gọi mình là Thiên Chúa của các ngài, vì Người đã chuẩn bị một thành cho các ngài.
(17) Nhờ đức tin, khi bị thử thách, ông Áp-ra-ham đã hiến tế I-xa-ác; dù đã nhận được lời hứa, ông vẫn hiến tế người con một. (18) Về người con này, Thiên Chúa đã phán bảo: Chính do I-xa-ác mà sẽ có một dòng dõi mang tên ngươi. (19) Quả thật, ông Áp-ra-ham nghĩ rằng Thiên Chúa có quyền năng cho người chết trỗi dậy. Rốt cuộc, ông đã nhận lại người con ấy như là một biểu tượng.
(20) Nhờ đức tin, khi nhìn về tương lai, ông I-xa-ác đã chúc phúc cho Gia-cóp và Ê-xau. (21) Nhờ đức tin, ông Gia-cóp, khi sắp chết, đã chúc phúc cho mỗi người con ông Giu-se; ông dựa vào đầu gậy, cúi mình xuống sụp lạy. (22) Nhờ đức tin, ông Giu-se, khi sắp lìa đời, đã nhắc lại cuộc xuất hành của con cái Ít-ra-en và ra chỉ thị liên quan đến hài cốt của ông.
(23) Nhờ đức tin, lúc chào đời, ông Mô-sê đã được cha mẹ giấu đi ba tháng, bởi vì ông bà thấy đứa trẻ khôi ngô, và không sợ sắc chỉ nhà vua. (24) Nhờ đức tin, ông Mô-sê, khi lớn lên đã từ chối không chịu cho người ta gọi là con của công chúa Pha-ra-ô; (25) ông thà cùng chịu ngược đãi với Dân Thiên Chúa còn hơn là được hưởng cái sung sướng chóng qua do tội lỗi mang lại; (26) ông coi sự ô nhục của người được xức dầu là của cải quý báu hơn các kho tàng của người Ai-cập, vì mắt ông vẫn đăm đăm nhìn phần thưởng mai sau. (27) Nhờ đức tin, ông bỏ Ai-cập mà không sợ cơn thịnh nộ của nhà vua; ông vững vàng không nao núng, như thể xem thấy Đấng vô hình. (28) Nhờ đức tin, ông đã cử hành lễ Vượt Qua và rảy máu để Thần tiêu diệt khỏi đụng đến các con đầu lòng. (29) Nhờ đức tin, người Do-thái đã băng qua Biển Đỏ như đi trên đất khô, còn người Ai-cập lại bị chết chìm trong khi tìm cách rượt theo.
(30) Nhờ đức tin, tường thành Giê-ri-khô đã sụp đổ, sau khi dân Ít-ra-en đi vòng quanh trong bảy ngày. (31) Nhờ đức tin, cô kỹ nữ Ra-kháp đã không phải chết cùng với quân phản nghịch, vì cô đã hòa nhã tiếp đón những người do thám.
(32) Tôi còn phải nói gì nữa đây? Tôi sợ không có đủ thời giờ để kể truyện các ông Ghít-ôn, Ba-rắc, Sam-sôn, Gíp-tác, Đa-vít, Sa-mu-en và các ngôn sứ. (33) Nhờ đức tin, các vị này đã chinh phục các nước, thực hành công lý, đạt được những gì Thiên Chúa đã hứa; các ngài đã khóa miệng sư tử, (34) dập tắt lửa hồng mãnh liệt, thoát khỏi lưỡi gươm. Các ngài đã lướt thắng bệnh tật mà trở nên mạnh mẽ, đã tỏ ra dũng cảm tại chiến trường, và đẩy lui được quân ngoại xâm. (35) Có những phụ nữ đã thấy thân nhân mình chết nay sống lại. Có những người bị tra tấn mà không muốn được giải thoát, để được hưởng một sự sống lại tốt đẹp hơn. (36) Có những người phải chịu nhạo cười và roi vọt, hơn nữa còn bị xiềng xích và bỏ tù; (37) họ bị ném đá, bị cưa đôi, bị chết vì gươm; họ phải lưu lạc, mặc áo da cừu da dê, chịu thiếu thốn, bị áp bức và hành hạ. (38) Thế gian chẳng xứng với họ! Họ đi lang thang trong hoang địa, trên núi đồi, trong hang hốc và hầm hố. (39) Nhờ đức tin, tất cả các nhân vật đó đã được chứng giám, thế mà họ không đạt được những điều Thiên Chúa đã hứa. (40) Quả thật, Thiên Chúa đã trù liệu cho chúng ta một phần phúc tốt hơn, nên không muốn cho họ đạt tới hạnh phúc trọn vẹn mà không có chúng ta.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'dt', 12, '[SECTION] Gương sáng của Đức Ki-tô
(1) Như thế, phần chúng ta, được ngần ấy nhân chứng đức tin như đám mây bao quanh, chúng ta hãy cởi bỏ mọi gánh nặng và tội lỗi đang trói buộc mình, và hãy kiên trì chạy trong cuộc đua dành cho ta, (2) mắt hướng về Đức Giê-su là Đấng khai mở và kiện toàn lòng tin. Chính Người đã khước từ niềm vui dành cho mình, mà cam chịu khổ hình thập giá, chẳng nề chi ô nhục, và nay đang ngự bên hữu ngai Thiên Chúa. (3) Anh em hãy tưởng nhớ Đấng đã cam chịu để cho những người tội lỗi chống đối mình như thế, để anh em khỏi sờn lòng nản chí. (4) Quả thật, trong cuộc chiến đấu với tội lỗi, anh em chưa chống trả đến mức đổ máu đâu.
[SECTION] Thiên Chúa lấy tình cha mà giáo dục
(5) Anh em đã quên lời khuyên nhủ được nói với anh em như với những người con: Con ơi, đừng coi nhẹ lời Chúa sửa dạy, chớ nản lòng khi Người khiển trách. (6) Vì Chúa thương ai thì mới sửa dạy kẻ ấy, và có nhận ai làm con thì Người mới cho roi cho vọt. (7) Anh em hãy kiên trì để cho Thiên Chúa sửa dạy. Người đối xử với anh em như với những người con. Thật vậy, có đứa con nào mà người cha không sửa dạy? (8) Nếu anh em không được sửa dạy như tất cả mọi người, thì khi đó anh em là con ngoại hôn, chứ không phải là con chính thức. (9) Vả lại, chúng ta có cha trần thế sửa dạy mà chúng ta vẫn tôn kính, thì chúng ta lại càng phải tùng phục Cha trên trời để được sống. (10) Cha trần thế sửa dạy chúng ta trong một thời gian ngắn, và theo sở thích của mình; còn Thiên Chúa sửa dạy là vì lợi ích của chúng ta, để chúng ta được thông phần vào sự thánh thiện của Người. (11) Ngay lúc bị sửa dạy, thì chẳng ai lấy làm vui thú mà chỉ thấy buồn phiền. Nhưng sau đó, những người chịu rèn luyện như thế sẽ gặt được hoa trái là bình an và công chính. (12) Bởi vậy, hãy làm cho những bàn tay bủn rủn, những đầu gối rã rời, nên mạnh mẽ. (13) Hãy sửa đường cho thẳng mà đi, để người què khỏi trật bước và hơn nữa, còn được chữa lành.
[SECTION] Trừng phạt tội bất trung
(14) Anh em phải cố ăn ở hòa thuận với mọi người, phải gắng trở nên thánh thiện; vì không có sự thánh thiện, thì không ai sẽ được thấy Chúa. (15) Anh em phải coi chừng, kẻo có ai lừng khừng mà mất ân sủng của Thiên Chúa, kẻo có ai trở nên rễ đắng nảy mầm, gây xáo trộn và do đó làm hư hỏng nhiều người. (16) Đừng có ai gian dâm hoặc phàm tục như Ê-xau, kẻ đã vì một món ăn mà bán quyền trưởng nam. (17) Anh em quá biết: sau này, cho dù muốn được thừa hưởng lời chúc phúc, anh ta cũng không thể làm thay đổi tình thế, mặc dù đã khóc lóc van xin.
[SECTION] Hai giao ước
(18) Anh em đã chẳng tới một quả núi sờ thấy được, có lửa đang cháy, mây mù, bóng tối và dông tố, (19) có tiếng kèn vang dậy, và tiếng nói thét gầm, khiến những kẻ nghe phải van xin đừng để lời ấy thốt ra với họ nữa, (20) vì họ không chịu nổi mệnh lệnh sau đây: Ngay cả thú vật đụng đến núi, cũng phải bị ném đá. (21) Cảnh tượng hãi hùng đến mức ông Mô-sê phải nói: Tôi kinh hoàng và run rẩy! (22) Nhưng anh em đã tới núi Xi-on, tới thành đô Thiên Chúa hằng sống, là Giê-ru-sa-lem trên trời, với con số muôn vàn thiên sứ. Anh em đã tới dự hội vui, (23) dự đại hội giữa các con đầu lòng của Thiên Chúa, là những kẻ đã được ghi tên trên trời. Anh em đã tới cùng Thiên Chúa, Đấng xét xử mọi người, đến với linh hồn những người công chính đã được nên hoàn thiện. (24) Anh em đã tới cùng vị Trung Gian giao ước mới là Đức Giê-su và được máu của Người rảy xuống, máu đó kêu thấu trời còn mạnh thế hơn cả máu A-ben. (25) Anh em phải coi chừng, chớ từ chối không nghe Đấng phán dạy. Quả thật, những ai từ chối không nghe Đấng tuyên sấm ở dưới đất đã không thoát khỏi hình phạt; huống hồ là chúng ta, làm sao chúng ta thoát được, nếu chúng ta quay lưng lại không chịu nghe Đấng tuyên sấm từ trời! (26) Xưa tiếng Người phán đã làm cho đất rung chuyển, thì nay Người lại đưa ra lời hứa sau đây: Một lần nữa, Ta sẽ lay chuyển không những trái đất, mà cả các tầng trời! (27) Những tiếng một lần nữa cho thấy rằng những sự vật bị rung chuyển sẽ phải thay đổi, bởi vì đã được làm ra, để những gì không bị rung chuyển được tồn tại. (28) Cho nên, bởi vì chúng ta được lãnh nhận một vương quốc vững bền không lay chuyển, chúng ta phải biết ơn Thiên Chúa. Với lòng biết ơn đó, chúng ta hãy kính sợ mà phụng thờ Thiên Chúa cho đẹp lòng Người. (29) Quả thật, Thiên Chúa chúng ta là một ngọn lửa thiêu.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'dt', 13, '[PART] DẶN BẢO THÊM
[SECTION] Lời nhắn nhủ cuối cùng
(1) Anh em hãy giữ mãi tình huynh đệ. (2) Anh em đừng quên tỏ lòng hiếu khách, vì nhờ vậy, có những người đã được tiếp đón các thiên thần mà không biết. (3) Anh em hãy nhớ đến các người bị xiềng xích, chẳng khác gì anh em cũng bị xiềng xích với họ; anh em hãy nhớ đến những người bị hành hạ, chẳng khác gì mình với họ chỉ là một thân thể. (4) Ai nấy phải tôn trọng hôn nhân, chớ làm cho loan phòng ra ô uế, vì Thiên Chúa sẽ xét xử các kẻ gian dâm và ngoại tình. (5) Trong cách ăn nết ở, anh em đừng có ham tiền, hãy coi những gì mình đang có là đủ, vì Thiên Chúa đã phán: Ta sẽ không bỏ rơi ngươi, Ta sẽ không ruồng bỏ ngươi!, (6) đến nỗi chúng ta có thể tin tưởng mà nói: Có Chúa ở cùng tôi mà bênh đỡ, tôi chẳng sợ gì. Hỏi người đời làm chi tôi được?
[SECTION] Về lòng trung thành
(7) Anh em hãy nhớ đến những người lãnh đạo đã giảng lời Chúa cho anh em. Hãy nhìn xem cuộc đời họ kết thúc thế nào mà noi theo lòng tin của họ. (8) Đức Giê-su Ki-tô vẫn là một, hôm qua cũng như hôm nay, và như vậy mãi đến muôn đời. (9) Đừng để cho đủ thứ học thuyết xa lạ mê hoặc anh em. Điều tốt là củng cố tâm hồn bằng ân sủng, chứ không phải bằng đồ ăn thức uống, là những thứ chẳng sinh ích gì cho những người giữ luật Mô-sê về chuyện ăn uống. (10) Chúng ta có một bàn thờ; những gì dâng trên đó, các người lo việc phụng tự trong Lều không có quyền ăn. (11) Vị thượng tế mang máu thú vật vào cung thánh để dâng làm của lễ đền tội; nhưng thây các thú vật đó đều bị thiêu ở ngoài trại. (12) Vì thế, Đức Giê-su đã chịu khổ hình ngoài cửa thành, lấy máu mình mà thánh hóa toàn dân. (13) Vậy ta hãy ra khỏi trại mà đến với Người, cam lòng gánh vác nỗi khổ nhục Người đã chịu. (14) Vì trên đời này, chúng ta không có thành trì bền vững, nhưng đang tìm kiếm thành trì tương lai. (15) Vậy nhờ Người, chúng ta hãy luôn luôn dùng lời ngợi khen làm lễ tế dâng lên Thiên Chúa, tức là dùng miệng lưỡi mà ca tụng Danh Thánh. (16) Anh em chớ quên làm việc từ thiện, giúp đỡ lẫn nhau, vì Thiên Chúa ưa thích những hy lễ như thế.
[SECTION] Vâng phục các vị lãnh đạo tinh thần
(17) Anh em hãy vâng lời những người lãnh đạo anh em và hãy phục tùng họ, vì họ chăm sóc linh hồn anh em như những người sẽ phải trả lẽ với Thiên Chúa. Như thế, họ sẽ vui vẻ thi hành phận sự của mình mà không than thở, bởi vì điều đó chẳng ích gì cho anh em. (18) Xin anh em cầu nguyện cho chúng tôi. Chúng tôi tin rằng chúng tôi có lương tâm ngay lành, muốn ăn ở tốt trong mọi hoàn cảnh. (19) Tôi tha thiết khuyên anh em làm như thế, để tôi được sớm trở về với anh em.
[SECTION] Tin tức. Lời chào cuối thư.
(20) Thiên Chúa là nguồn mạch bình an đã đưa Đức Giê-su, Chúa chúng ta ra khỏi cái chết. Đức Giê-su là vị Mục Tử cao cả của đoàn chiên, là Đấng đã đổ máu mình ra để thiết lập giao ước vĩnh cửu. (21) Xin Thiên Chúa ban cho anh em mọi ơn lành để có sức thi hành thánh ý Người. Xin Người thực hiện nơi anh em điều đẹp lòng Người, nhờ Đức Giê-su Ki-tô. Kính dâng Đức Ki-tô vinh quang đến muôn thuở muôn đời. A-men.
(22) Thưa anh em, tôi xin anh em chịu khó nghe lời khuyên này. Vả lại, tôi chỉ viết cho anh em vắn tắt thôi. (23) Xin báo cho anh em biết: Ti-mô-thê, người anh em của chúng ta, đã được thả rồi. Nếu anh ấy đến đây sớm, thì tôi sẽ cùng với anh đến gặp anh em. (24) Xin gửi lời chào các vị lãnh đạo anh em và mọi người trong dân thánh. Những người từ I-ta-li-a gửi lời chào anh em. (25) Chúc tất cả anh em được đầy tràn ân sủng của Thiên Chúa!') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;