INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'gc', 1, '[SECTION] Lời chào thăm
(1) Tôi là Gia-cô-bê, tôi tớ của Thiên Chúa và của Chúa Giê-su Ki-tô, kính gửi mười hai chi tộc đang sống tản mác khắp nơi. Chúc anh em được an vui mạnh khỏe!
[SECTION] Ích lợi của thử thách
(2) Thưa anh em, anh em hãy tự cho mình là được chan chứa niềm vui khi gặp thử thách trăm chiều. (3) Vì như anh em biết: đức tin có vượt qua thử thách mới sinh ra lòng kiên nhẫn. (4) Chớ gì anh em chứng tỏ lòng kiên nhẫn đó ra bằng những việc hoàn hảo, để anh em nên hoàn hảo, không có chi đáng trách, không thiếu sót điều gì.
[SECTION] Cầu xin với lòng tin
(5) Nếu ai trong anh em thiếu đức khôn ngoan, thì hãy cầu xin Thiên Chúa, Người sẽ ban cho. Vì Thiên Chúa ban cho mọi người cách rộng rãi, không quở trách. (6) Nhưng người ấy phải cầu xin với lòng tin không chút do dự, vì kẻ do dự thì giống như sóng biển bị gió đẩy lên vật xuống. (7) Người ấy đừng tưởng mình sẽ nhận được cái gì của Chúa: (8) họ là kẻ hai lòng, hay thay đổi trong mọi việc họ làm.
[SECTION] Số phận người giàu
(9) Người anh em phận hèn hãy tự hào khi được Chúa nâng lên; (10) còn người giàu có hãy tự hào khi bị Chúa hạ xuống, vì họ sẽ qua đi như hoa cỏ. (11) Quả thế, mặt trời mọc lên tỏa ra sức nóng làm cho cỏ khô, khiến hoa rụng xuống, vẻ đẹp tiêu tan. Người giàu có cũng sẽ héo tàn như vậy trong các việc họ làm.
[SECTION] Thử thách
(12) Phúc thay người biết kiên trì chịu đựng cơn thử thách, vì một khi đã được tôi luyện, họ sẽ lãnh phần thưởng là sự sống Chúa đã hứa ban cho những ai yêu mến Người.
(13) Khi bị cám dỗ, đừng ai nói: “Tôi bị Thiên Chúa cám dỗ”, vì Thiên Chúa không thể bị cám dỗ làm điều xấu, và chính Người cũng không cám dỗ ai. (14) Nhưng mỗi người có bị cám dỗ, là do dục vọng của mình lôi cuốn và dùng mồi mà bắt. (15) Rồi một khi dục vọng đã cưu mang thì đẻ ra tội; còn tội khi đã phạm rồi, thì sinh ra cái chết.
[SECTION] Lãnh nhận và thực hành Lời Chúa
(16) Anh em thân mến của tôi, anh em đừng có lầm lẫn. (17) Mọi ơn lành và mọi phúc lộc hoàn hảo đều do từ trên, đều tuôn xuống từ Cha là Đấng dựng nên muôn tinh tú; nơi Người không hề có sự thay đổi, cũng không hề có sự chuyển vần khi tối khi sáng. (18) Người đã tự ý dùng Lời chân lý mà sinh ra chúng ta, để chúng ta nên như của đầu mùa trong các thụ tạo của Người.
(19) Anh em thân mến của tôi, anh em nên biết rằng: mỗi người phải mau nghe, đừng vội nói, và khoan giận, (20) vì khi nóng giận, con người không thực thi đường lối công chính của Thiên Chúa. (21) Vì vậy, anh em hãy giũ sạch mọi điều ô uế và mọi thứ độc ác còn lan tràn; hãy khiêm tốn đón nhận lời đã được gieo vào lòng anh em; lời ấy có sức cứu độ linh hồn anh em.
(22) Anh em hãy đem Lời ấy ra thực hành, chứ đừng nghe suông mà lừa dối chính mình. (23) Thật vậy, ai lắng nghe Lời Chúa mà không thực hành, thì giống như người soi gương thấy khuôn mặt tự nhiên của mình. (24) Người ấy soi gương rồi đi, và quên ngay không nhớ mặt mình thế nào. (25) Ai thiết tha và trung thành tuân giữ luật trọn hảo –luật mang lại tự do–, ai thi hành luật Chúa, chứ không nghe qua rồi bỏ, thì sẽ tìm được hạnh phúc trong mọi việc mình làm.
(26) Ai cho mình đạo đức mà không kiềm chế miệng lưỡi, là tự dối lòng mình, vì đó chỉ là thứ đạo đức hão. (27) Có lòng đạo đức tinh tuyền và không tỳ ố trước mặt Thiên Chúa Cha, là thăm viếng cô nhi quả phụ lâm cảnh gian truân, và giữ mình cho khỏi mọi vết nhơ của thế gian.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'gc', 2, '[SECTION] Phải kính trọng người nghèo
(1) Thưa anh em, anh em đã tin vào Đức Giê-su Ki-tô, Chúa chúng ta, là Chúa vinh quang, thì đừng đối xử thiên tư. (2) Quả vậy, giả như có một người bước vào nơi anh em hội họp, tay đeo nhẫn vàng, áo quần lộng lẫy, đồng thời có một người nghèo khó, ăn mặc tồi tàn, cũng bước vào, (3) và giả như mà anh em kính cẩn nhìn người ăn mặc lộng lẫy và nói: “Xin mời ông ngồi vào chỗ danh dự này”, còn với người nghèo, anh em lại nói: “Đứng đó!” hoặc: “Ngồi dưới bệ chân tôi đây!”, (4) thì bấy giờ, anh em đã chẳng tỏ ra kỳ thị và trở thành những thẩm phán đầy tà tâm đó sao?
(5) Anh em thân mến của tôi, anh em hãy nghe đây: nào Thiên Chúa đã chẳng chọn những kẻ nghèo khó trước mặt người đời, để họ trở nên người giàu đức tin và thừa hưởng vương quốc Người đã hứa cho những ai yêu mến Người hay sao? (6) Thế mà anh em, anh em lại khinh dể người nghèo! Chẳng phải những người giàu áp bức anh em đó sao? Chẳng phải họ lôi anh em ra tòa đó sao? (7) Chẳng phải họ nói xúc phạm đến Danh Thánh cao đẹp mà anh em được mang đó sao? (8) Đã hẳn, anh em làm điều tốt, nếu anh em chu toàn luật Kinh Thánh đưa lên hàng đầu: Ngươi phải yêu người thân cận như chính mình. (9) Nhưng nếu anh em đối xử thiên tư, thì anh em phạm một tội và bị Lề Luật kết án là kẻ vi phạm.
(10) Quả thế, ai tuân giữ tất cả Lề Luật, mà chỉ sa ngã về một điểm thôi, thì cũng thành người có tội về hết mọi điểm. (11) Thật vậy, Đấng đã phán: Ngươi không được ngoại tình, cũng đã phán: Ngươi không được giết người. Vậy nếu bạn không ngoại tình, nhưng lại giết người, thì bạn cũng thành kẻ vi phạm Lề Luật. (12) Anh em hãy nói năng và hành động như những người sẽ bị xét xử theo luật tự do. (13) Vì Thiên Chúa không thương xót khi xét xử kẻ không biết thương xót. Còn ai thương xót, thì chẳng quan tâm đến việc xét xử.
[SECTION] Đức tin và hành động
(14) Thưa anh em, ai bảo rằng mình có đức tin mà không hành động theo đức tin, thì nào có ích lợi gì? Đức tin có thể cứu người ấy được chăng? (15) Giả như có người anh em hay chị em không có áo che thân và không đủ của ăn hằng ngày, (16) mà có ai trong anh em lại nói với họ: “Hãy đi bình an, mặc cho ấm và ăn cho no”, nhưng lại không cho họ những thứ thân xác họ đang cần, thì nào có ích lợi gì?
(17) Cũng vậy, đức tin không có hành động thì quả là đức tin chết. (18) Đàng khác, có người sẽ bảo: “Bạn, bạn có đức tin; còn tôi, tôi có hành động. Bạn thử cho tôi thấy thế nào là tin mà không hành động, còn tôi, tôi sẽ hành động để cho bạn thấy thế nào là tin. (19) Bạn tin rằng chỉ có một Thiên Chúa duy nhất. Bạn làm phải. Cả ma quỷ cũng tin như thế, và chúng run sợ.” (20) Hỡi người đầu óc rỗng tuếch, bạn có muốn biết rằng đức tin không có hành động là vô dụng không? (21) Ông Áp-ra-ham tổ phụ chúng ta, đã chẳng được nên công chính nhờ hành động, khi ông hiến dâng con mình là I-xa-ác trên bàn thờ đó sao? (22) Bạn thấy đó: đức tin hợp tác với hành động của ông, và nhờ hành động mà đức tin nên hoàn hảo. (23) Như thế ứng nghiệm lời Kinh Thánh đã chép: Ông Áp-ra-ham tin Thiên Chúa, và vì thế Thiên Chúa kể ông là người công chính và ông được gọi là bạn của Thiên Chúa.
(24) Anh em thấy đó, nhờ hành động mà con người được nên công chính, chứ không phải chỉ nhờ đức tin mà thôi. (25) Ra-kháp, cô gái điếm cũng vậy: há chẳng phải nhờ hành động mà đã được nên công chính, vì đã đón tiếp các sứ giả và đưa họ đi lối khác sao? (26) Thật thế, một thân xác không hơi thở là một xác chết, cũng vậy, đức tin không có hành động là đức tin chết.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'gc', 3, '[SECTION] Kiềm chế miệng lưỡi
(1) Thưa anh em, đừng có nhiều người trong anh em ham làm thầy thiên hạ, vì anh em biết rằng chúng ta sẽ bị xét xử nghiêm khắc hơn. (2) Thật vậy, tất cả chúng ta thường hay vấp ngã.
Ai không vấp ngã về lời nói, ấy là người hoàn hảo, có khả năng kiềm chế toàn thân. (3) Nếu ta tra hàm thiếc vào miệng ngựa để bắt chúng vâng lời, thì ta điều khiển được toàn thân chúng. (4) Anh em cũng hãy nhìn xem tàu bè: dù nó có to lớn, và có bị cuồng phong đẩy mạnh thế nào đi nữa, thì cũng chỉ cần một bánh lái rất nhỏ để điều khiển theo ý của người lái. (5) Cái lưỡi cũng vậy: nó là một bộ phận nhỏ bé của thân thể, mà lại huênh hoang làm được những chuyện to lớn. Cứ xem tia lửa nhỏ bé dường nào, mà làm bốc cháy đám rừng to lớn biết bao! (6) Cái lưỡi cũng là một ngọn lửa, là cả một thế giới của sự ác. Cái lưỡi có một vị trí giữa các bộ phận của thân thể chúng ta, nó làm cho toàn thân bị ô nhiễm, đốt cháy bánh xe cuộc đời, vì chính nó bị lửa hỏa ngục đốt cháy. (7) Thật thế, mọi loài thú vật và chim chóc, loài bò sát và cá biển, thì loài người đều có thể chế ngự và đã chế ngự được. (8) Nhưng cái lưỡi thì không ai chế ngự được: nó là một sự dữ không bao giờ ở yên, vì nó chứa đầy nọc độc giết người. (9) Ta dùng lưỡi mà chúc tụng Chúa là Cha chúng ta, ta cũng dùng lưỡi mà nguyền rủa những con người đã được làm ra theo hình ảnh Thiên Chúa. (10) Từ cùng một cái miệng, phát xuất lời chúc tụng và lời nguyền rủa. Thưa anh em, như vậy thì không được. (11) Chẳng lẽ một mạch nước lại có thể phun ra, từ một nguồn, cả nước ngọt lẫn nước chua sao? (12) Thưa anh em, làm sao cây vả lại có thể sinh ra trái ô-liu, hoặc cây nho sinh trái vả? Nước mặn cũng không thể sinh ra nước ngọt.
[SECTION] Khôn ngoan thật và khôn ngoan giả
(13) Trong anh em, ai là người khôn ngoan hiểu biết? Người ấy hãy dùng lối sống tốt đẹp mà chứng tỏ rằng: những hành động của họ phát xuất từ lòng hiền hậu và đức khôn ngoan. (14) Nhưng nếu trong lòng anh em có sự ghen tuông, chua chát và tranh chấp, thì anh em đừng có tự cao tự đại mà nói dối, trái với sự thật. (15) Sự khôn ngoan đó không phải từ trời cao ban xuống, nhưng là sự khôn ngoan của thế gian, của con người tự nhiên, của ma quỷ. (16) Thật vậy, ở đâu có ghen tuông và tranh chấp, ở đấy có xáo trộn và đủ mọi thứ việc xấu xa. (17) Đức khôn ngoan Chúa ban làm cho con người trở nên trước là thanh khiết, sau là hiếu hòa, khoan dung, mềm dẻo, đầy từ bi và sinh nhiều hoa thơm trái tốt, không thiên vị, cũng chẳng giả hình. (18) Người xây dựng hòa bình thu hoạch được hoa trái đã gieo trong hòa bình, là cuộc đời công chính.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'gc', 4, '[SECTION] Tránh những mối bất hòa
(1) Bởi đâu có chiến tranh, bởi đâu có xung đột giữa anh em? Chẳng phải là bởi chính những khoái lạc của anh em đang gây chiến trong con người anh em đó sao? (2) Thật vậy, anh em ham muốn mà không có, nên anh em chém giết; anh em ganh ghét cũng chẳng được gì, nên anh em xung đột với nhau, gây chiến với nhau. Anh em không có, là vì anh em không xin; (3) anh em xin mà không được, là vì anh em xin với tà ý, để lãng phí trong việc hưởng lạc.
(4) Hỡi những kẻ ngoại tình, các người không biết rằng: yêu thế gian là ghét Thiên Chúa sao? Vậy ai muốn là bạn của thế gian thì tự coi mình là thù địch của Thiên Chúa. (5) Hay các người nghĩ rằng lời Kinh Thánh sau đây là vô nghĩa: Thần Khí mà Thiên Chúa đã đặt trong chúng ta, ước muốn đến phát ghen lên? (6) Nhưng ân sủng Người ban còn mạnh hơn; vì thế, có lời Kinh Thánh nói: Thiên Chúa chống lại kẻ kiêu ngạo, nhưng ban ơn cho kẻ khiêm nhường. (7) Anh em hãy phục tùng Thiên Chúa. Hãy chống lại ma quỷ; chúng sẽ chạy xa anh em. (8) Hãy đến gần Thiên Chúa, Người sẽ đến gần anh em. Hỡi tội nhân, hãy rửa tay cho sạch; hỡi kẻ hai lòng, hãy tẩy luyện tâm can. (9) Hãy cảm cho thấu nỗi khốn cùng của anh em, hãy khóc lóc than van. Chớ gì tiếng cười của anh em biến thành tiếng khóc, niềm vui của anh em đổi ra nỗi buồn. (10) Anh em hãy hạ mình xuống trước mặt Chúa và Người sẽ cất nhắc anh em lên.
(11) Thưa anh em, anh em đừng nói xấu nhau. Ai nói xấu hoặc xét đoán anh em mình là nói xấu và xét đoán Lề Luật. Nếu anh xét đoán Lề Luật, thì anh không còn là kẻ vâng giữ, mà là kẻ xét đoán Lề Luật. (12) Chỉ có một Đấng ra Lề Luật và xét xử, đó là Đấng có quyền cứu thoát và tiêu diệt. Còn anh là ai mà dám xét đoán người thân cận?
[SECTION] Cảnh cáo người giàu
(13) Bây giờ, hãy nghe tôi, những kẻ nói: “Hôm nay hoặc ngày mai, chúng ta sẽ đi đến thành nọ thành kia, sẽ ở lại đó một năm và buôn bán kiếm lời”, (14) trong khi các người không biết cuộc đời mình ngày mai sẽ ra sao. Thật vậy, các người chỉ là hơi nước xuất hiện trong giây lát, rồi lại tan biến đi. (15) Thay vì nói: “Nếu Chúa muốn, chúng ta sẽ sống và làm điều nọ điều kia”, (16) thì các người lại tự phụ vì những chuyện khoác lác của mình. Mọi thứ tự phụ như thế đều xấu. (17) Vậy kẻ nào biết làm điều tốt mà không chịu làm thì mắc tội.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'gc', 5, '(1) Giờ đây, hỡi những kẻ giàu có, các người hãy than van rên rỉ về những tai họa sắp đổ xuống trên đầu các người. (2) Tài sản của các người đã hư nát, quần áo của các người đã bị mối ăn. (3) Vàng bạc của các người đã bị rỉ sét; và chính rỉ sét ấy là bằng chứng buộc tội các người; nó sẽ như lửa thiêu hủy xác thịt các người. Các người đã lo tích trữ trong những ngày sau hết này. (4) Các người đã gian lận mà giữ lại tiền lương của những thợ đi cắt lúa trong ruộng của các người. Kìa, tiền lương ấy đang kêu lên oán trách các người, và tiếng kêu của những thợ gặt ấy đã thấu đến tai Chúa các đạo binh. (5) Trên cõi đất này, các người đã sống xa hoa, đã buông theo khoái lạc, lòng các người đã được no đầy thỏa mãn trong ngày sát hại. (6) Các người đã kết án, đã giết hại người công chính, và họ đã chẳng cưỡng lại các người.
[SECTION] Ngày Chúa quang lâm
(7) Thưa anh em, xin anh em cứ kiên nhẫn cho tới ngày Chúa quang lâm. Kìa xem nhà nông, họ kiên nhẫn chờ đợi cho đất trổ sinh hoa màu quý giá: họ phải đợi cả mưa đầu mùa lẫn mưa cuối mùa. (8) Anh em cũng vậy, hãy kiên nhẫn và bền tâm vững chí, vì ngày Chúa quang lâm đã gần tới. (9) Thưa anh em, anh em đừng phàn nàn kêu trách lẫn nhau, để khỏi bị xét xử. Kìa vị Thẩm Phán đang đứng ngoài cửa. (10) Thưa anh em, về sức chịu đựng và lòng kiên nhẫn, anh em hãy noi gương các ngôn sứ là những vị đã nói nhân danh Chúa. (11) Kìa xem: chúng ta tuyên bố: phúc thay những kẻ đã có lòng kiên trì! Anh em đã nghe nói đến lòng kiên trì của ông Gióp và đã thấy mục đích Chúa nhắm, vì Chúa là Đấng từ bi nhân hậu.
[SECTION] Những lời khuyên cuối cùng
(12) Nhưng, thưa anh em, trước hết, đừng có thề, dù là lấy trời, lấy đất, hay lấy cái gì khác mà thề. Nhưng hễ “có” thì phải nói “có”, “không” thì phải nói “không”, như thế, anh em sẽ không bị xét xử.
(13) Ai trong anh em đau khổ ư? Người ấy hãy cầu nguyện. Ai vui vẻ chăng? Người ấy hãy hát thánh ca. (14) Ai trong anh em đau yếu ư? Người ấy hãy mời các kỳ mục của Hội Thánh đến; họ sẽ cầu nguyện cho người ấy, sau khi xức dầu nhân danh Chúa. (15) Lời cầu nguyện do lòng tin sẽ cứu người bệnh; người ấy được Chúa nâng dậy, và nếu người ấy đã phạm tội, thì sẽ được Chúa thứ tha. (16) Anh em hãy thú tội với nhau và cầu nguyện cho nhau để được cứu thoát. Vì lời cầu xin tha thiết của người công chính rất có hiệu lực. (17) Ông Ê-li-a xưa cũng là người cùng chung một thân phận như chúng ta; ông đã tha thiết cầu xin cho đừng có mưa, thì đã không có mưa xuống trên mặt đất suốt ba năm sáu tháng. (18) Rồi ông lại cầu xin, thì trời liền mưa xuống và đất đã trổ sinh hoa trái.
(19) Thưa anh em, nếu có người nào trong anh em lạc xa chân lý và có ai đưa người ấy trở về, (20) thì anh em hãy biết rằng: kẻ nào làm cho một tội nhân bỏ đường lầm lạc mà trở về, thì cứu được linh hồn ấy khỏi chết và che lấp được muôn vàn tội lỗi của mình.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;