INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, '3ga', 1, '[PART] Chương 1
[SECTION] Lời chào
(1) Tôi là kỳ mục, gửi anh Gai-ô thân mến, người mà tôi thật sự quý mến. (2) Anh thân mến, tôi cầu chúc anh được mọi bề thịnh đạt: thể xác mạnh khỏe và tinh thần phấn chấn.
[SECTION] Ca tụng ông Gai-ô
(3) Quả thật, tôi rất vui mừng bởi có những anh em đến đây và làm chứng là anh gắn bó với sự thật, như anh vẫn sống trong sự thật. (4) Không có gì làm tôi vui sướng bằng khi nghe biết con cái tôi sống sự thật.
(5) Anh thân mến, anh hành động theo đức tin trong mọi việc anh làm cho các người anh em, dù họ là những người xa lạ. (6) Họ đã làm chứng về đức bác ái của anh trước mặt Hội Thánh. Anh sẽ làm một việc nghĩa, nếu anh giúp đỡ cho chuyến đi của họ cách xứng đáng trước mặt Thiên Chúa. (7) Quả thật, chính vì danh Chúa, họ đã ra đi mà không nhận gì của người ngoại. (8) Vậy, chúng ta phải tiếp đón những con người như thế, để cộng tác vào việc truyền bá sự thật.
[SECTION] Hành vi của ông Đi-ốt-rê-phét
(9) Tôi viết đôi lời cho Hội Thánh, nhưng Đi-ốt-rê-phét, một con người thích ăn trên ngồi trước, không chịu nhận quyền của chúng tôi. (10) Vì thế, nếu tôi đến, tôi sẽ nhắc lại cho anh ta những việc anh ta đã làm: anh ta cứ rêu rao những lời độc địa chống chúng tôi. Chưa lấy thế làm đủ, anh ta còn không tiếp đón các người anh em, và ai muốn tiếp đón thì anh ta ngăn cản và trục xuất khỏi Hội Thánh. (11) Anh thân mến, anh đừng bắt chước làm điều dữ, nhưng hãy bắt chước làm điều lành. Ai làm điều lành thì thuộc về Thiên Chúa; kẻ làm điều dữ thì đã không thấy Thiên Chúa.
[SECTION] Làm chứng cho ông Đê-mết-ri-ô
(12) Mọi người đều làm chứng tốt cho anh Đê-mết-ri-ô, và chính sự thật cũng làm chứng như vậy. Cả chúng tôi nữa, chúng tôi cũng làm chứng cho anh ấy, và anh biết rằng lời chứng của chúng tôi là xác thực.
[SECTION] Lời kết thúc
(13) Tôi còn có nhiều điều đáng lẽ phải viết cho anh, nhưng tôi không muốn dùng bút mực mà viết cho anh. (14) Tôi hy vọng sắp được gặp anh, và chúng ta sẽ nói chuyện trực tiếp. (15) Chúc anh được bình an! Các bạn hữu gửi lời chào anh. Cho tôi gửi lời chào các bạn hữu, đích danh từng người một.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;