INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'gd', 1, '[SECTION] Lời mở đầu
(1) Tôi là Giu-đa, tôi tớ của Đức Giê-su Ki-tô, anh em với ông Gia-cô-bê, xin gửi lời thăm những người được kêu gọi, được Thiên Chúa là Cha yêu mến, và được dành riêng cho Đức Giê-su Ki-tô. (2) Chúc anh em được đầy tràn lòng thương xót, sự bình an và tình thương.
[SECTION] Lý do viết thư
(3) Anh em thân mến, tôi vẫn ước mong viết thư cho anh em về ơn cứu độ chung của chúng ta, thì nay lại bó buộc phải viết cho anh em, để khuyên nhủ anh em chiến đấu cho đức tin đã được truyền lại cho dân thánh chỉ một lần là đủ. (4) Thật vậy, có những người đã len lỏi vào, những người từ lâu đã bị ghi trước vào danh sách những kẻ bị lên án, những kẻ vô luân này đã biến ân sủng của Thiên Chúa chúng ta thành lý do biện minh cho lối sống dâm ô, họ chối bỏ Chúa chúng ta là Đức Giê-su Ki-tô, vị Chúa Tể duy nhất.
[SECTION] Các thầy dạy giả hiệu. Hình phạt dành cho họ.
(5) Cho dù anh em đã biết mọi sự chỉ một lần là đủ, tôi cũng muốn nhắc cho anh em nhớ lại rằng: Chúa đã cứu dân ra khỏi đất Ai-cập, sau đó lại tiêu diệt những kẻ không chịu tin. (6) Những thiên thần đã không giữ địa vị của mình, nhưng rời bỏ nơi mình ở, thì Người dùng xiềng xích mà giam giữ họ đời đời trong nơi tối tăm, để chờ phán xét trong Ngày lớn lao. (7) Còn Xơ-đôm, Gô-mô-ra và các thành lân cận làm chuyện gian dâm như họ và chạy theo những thú vui xác thịt trái tự nhiên, thì đã phải chịu lửa đời đời làm hình phạt để nêu gương.
[SECTION] Họ nói lộng ngôn
(8) Cả những người mê sảng kia cũng vậy, họ làm cho thân xác ra ô uế, khinh dể chủ quyền của Chúa, nói phạm đến các Bậc uy linh. (9) Khi bàn cãi và tranh luận với quỷ về thi hài ông Mô-sê, ngay cả tổng lãnh thiên thần Mi-ca-en cũng không dám đưa ra một phán quyết nào phạm đến nó, mà chỉ nói: Xin Chúa trừng phạt ngươi! (10) Nhưng họ, họ lại nói phạm đến những điều họ không biết; còn những điều họ biết được một cách tự nhiên như loài vật vô tri, thì chỉ làm cho họ phải tiêu diệt.
[SECTION] Họ là những kẻ gian tà
(11) Khốn cho họ, bởi họ đi vào con đường của Ca-in; vì chút tiền công, họ đã ngã theo sự lầm lạc của Bi-lơ-am, và bị diệt vong vì làm loạn như Cô-rắc. (12) Họ làm cho những bữa tiệc thân ái của anh em ra nhơ nhuốc; họ chè chén mà không biết xấu hổ, họ chỉ lo cho chính mình. Họ là mây không có nước, cuốn theo chiều gió. Họ là cây cuối mùa thu, không trái, chết hai lần, bị nhổ tận rễ. (13) Họ là sóng biển hung dữ, tung bọt là những hành vi bỉ ổi của họ. Họ là những vì sao lạc, u ám tối tăm là nơi dành cho họ đến muôn đời. (14) Ông Kha-nốc, tổ phụ thứ bảy sau ông A-đam đã tuyên sấm về họ rằng: Này Chúa đến giữa muôn vàn thần thánh của Người, (15) để xét xử mọi người, và kết án mọi kẻ vô luân về tất cả các việc vô luân của họ, về tất cả những lời hỗn xược quân tội lỗi vô luân đã nói phạm đến Người. (16) Họ là những người hay lẩm bẩm, phàn nàn, đi theo các dục vọng của mình, miệng nói lời huênh hoang, tâng bốc người ta để trục lợi.
[SECTION] Lời khuyên nhủ các tín hữu. Giáo huấn của các Tông Đồ.
(17) Anh em thân mến, phần anh em hãy nhớ lại những lời các Tông Đồ của Đức Giê-su Ki-tô, Chúa chúng ta, đã nói trước kia. (18) Các ngài đã nói với anh em: “Vào thời cuối cùng sẽ có những kẻ nhạo báng, sống theo những dục vọng vô luân của mình.” (19) Họ là những kẻ gây chia rẽ, sống theo tính tự nhiên, không có Thần Khí.
[SECTION] Nhiệm vụ của đức bác ái
(20) Nhưng anh em, hỡi anh em thân mến, hãy xây dựng đời mình trên nền tảng đức tin rất thánh của anh em, hãy cầu nguyện nhờ Thánh Thần, (21) hãy cố gắng sống mãi trong tình thương của Thiên Chúa, hãy chờ đợi lòng thương xót của Đức Giê-su Ki-tô, Chúa chúng ta, để được sống đời đời. (22) Những người do dự thì anh em phải thương xót; (23) hãy lo cứu họ, kéo họ ra khỏi lửa thiêu. Còn những người khác, thì anh em phải vừa thương xót, vừa sợ hãi, gớm ghét ngay cả chiếc áo đã bị thân xác họ làm cho ra ô uế.
[SECTION] Vinh tụng ca
(24) Xin kính dâng Đấng có quyền phép gìn giữ anh em khỏi sa ngã và cho anh em đứng vững, tinh tuyền, trước vinh quang của Người, trong niềm hoan lạc, (25) xin kính dâng Thiên Chúa duy nhất, Đấng cứu độ chúng ta, nhờ Đức Giê-su Ki-tô, Chúa chúng ta, kính dâng Người vinh quang, oai phong, sức mạnh và quyền năng, trước mọi thời, bây giờ và cho đến muôn đời! A-men.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;