INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'tl', 1, '[PART] LỜI DẪN THỨ NHẤT KỂ SƠ LƯỢC VỀ CUỘC ĐỊNH CƯ TẠI CA-NA-AN
[SECTION] Cuộc định cư của Giu-đa, Si-mê-ôn, Ca-lếp và Kê-ni
(1) Sau khi ông Giô-suê từ trần, con cái Ít-ra-en đã thỉnh ý ĐỨC CHÚA rằng: “Ai trong chúng con sẽ lên đương đầu với quân Ca-na-an trước tiên để giao tranh với chúng?” (2) ĐỨC CHÚA phán: “Giu-đa sẽ lên: Này Ta đã trao đất ấy vào tay nó.” (3) Giu-đa liền nói với Si-mê-ôn, anh mình, rằng: “Mời anh cùng tôi lên phần đất tôi đã trúng thăm; chúng ta cùng chiến đấu chống quân Ca-na-an; tới lượt tôi, tôi sẽ cùng anh đi đến phần đất anh đã trúng thăm.” Và Si-mê-ôn đã cùng đi với ông ta. (4) Vậy Giu-đa đi lên; ĐỨC CHÚA đã trao quân Ca-na-an và quân Pơ-rít-di vào tay họ; và tại Be-déc, họ đã đánh bại mười ngàn người của chúng. (5) Họ đã gặp A-đô-ni Be-déc tại Be-déc; họ liền tấn công y, đánh tan quân Ca-na-an và quân Pơ-rít-di. (6) A-đô-ni Be-déc tháo chạy, nhưng họ đã đuổi theo bắt được y, và chặt ngón tay cái và ngón chân cái của y. (7) A-đô-ni Be-déc nói: “Bảy mươi vua bị chặt ngón tay cái và ngón chân cái, đã ăn mót dưới gầm bàn của tôi. Tôi đã xử sự thế nào, thì Thiên Chúa cũng xử lại với tôi như vậy.” Họ đưa y vào Giê-ru-sa-lem và y đã chết tại đó. (8) Con cái Giu-đa đã tấn công Giê-ru-sa-lem, chiếm lấy thành, dùng gươm giết và nổi lửa đốt thành.
(9) Sau đó con cái Giu-đa đã xuống tấn công người Ca-na-an bấy giờ đang ở trên núi, ở vùng Ne-ghép và vùng Sơ-phê-la. (10) Giu-đa cũng tiến đánh quân Ca-na-an bấy giờ đang ở Khép-rôn, –tên của Khép-rôn trước kia là Kia-giát Ác-ba– và họ đã đánh bại Sê-sai, A-khi-man và Tan-mai. (11) Từ đấy họ tiến đánh dân cư thành Đơ-via – tên của Đơ-via trước kia là Kia-giát Xê-phe. (12) Ông Ca-lếp nói: “Ai đánh và chiếm được Kia-giát Xê-phe, tôi sẽ gả Ác-xa con gái tôi cho người ấy.” (13) Ót-ni-ên con ông Cơ-nát, em ông Ca-lếp, đã chiếm được thành; và ông Ca-lếp đã gả Ác-xa con gái mình cho Ót-ni-ên. (14) Khi cô ta đến, Ót-ni-ên liền xúi cô xin cha một thửa ruộng. Cô xuống lừa, và ông Ca-lếp hỏi cô: “Chuyện gì thế con?” (15) Cô thưa: “Xin cha cho con một món quà: vì cha đã cho con đất Ne-ghép, thì xin cũng cho con cả suối nước nữa.” Ông Ca-lếp đã cho cô suối trên suối dưới. (16) Con cái ông Kê-ni, nhạc phụ ông Mô-sê, đã từ Thành Chà Là cùng với con cái Giu-đa đi lên sa mạc Giu-đa, trong vùng Ne-ghép A-rát. Họ đã đi và đến ở với dân ấy. (17) Giu-đa đã đi với Si-mê-ôn anh mình. Họ tấn công quân Ca-na-an bấy giờ đang ở Xơ-phát và đã tru diệt chúng. Người ta đã gọi tên thành ấy là Khoóc-ma. (18) Rồi Giu-đa chiếm Ga-da và vùng lân cận, chiếm Át-cơ-lôn và vùng lân cận, chiếm Éc-rôn và vùng lân cận. (19) ĐỨC CHÚA phù trợ Giu-đa và ông đã chiếm giữ vùng núi; nhưng ông không trục xuất được dân cư vùng đồng bằng, vì chúng có xe sắt. (20) Các ông đã cứ lời ông Mô-sê mà giao Khép-rôn cho ông Ca-lếp, và ông này đã đuổi ba người con của A-nác ra khỏi đó. (21) Còn những người Giơ-vút cư ngụ tại Giê-ru-sa-lem, thì con cái Ben-gia-min đã không đánh đuổi họ; vì thế những người Giơ-vút vẫn ở với con cái Ben-gia-min tại Giê-ru-sa-lem cho tới ngày nay.
[SECTION] Chiếm Bết Ên
(22) Nhà Giu-se cũng tiến lên Bết Ên và ĐỨC CHÚA ở với họ. (23) Nhà Giu-se đã cho người do thám Bết Ên – tên thành này trước kia là Lút. (24) Các thám tử gặp một người đàn ông từ trong thành đi ra, liền nói với người ấy: “Chỉ cho chúng tôi lối vào thành; chúng tôi sẽ xử khoan hồng với anh!” (25) Người ấy chỉ cho họ lối vào thành, và họ đã dùng gươm tàn sát cả thành; còn người ấy cùng với cả thị tộc thì họ để cho đi. (26) Người ấy ra đi đến đất người Khết, xây một thành và đặt tên là Lút. Đó là tên của thành ấy cho tới ngày nay.
[SECTION] Các chi tộc phía bắc
(27) Mơ-na-se không đánh thắng được Bết San và các vùng phụ thuộc, cũng như Ta-nác và các vùng phụ thuộc, cũng chẳng đánh thắng được dân cư thành Đo và các vùng phụ thuộc, dân cư thành Gíp-lơ-am và các vùng phụ thuộc, dân cư thành Mơ-ghít-đô và các vùng phụ thuộc. Người Ca-na-an quyết ở lại trong đất đó. (28) Nhưng khi Ít-ra-en trở nên hùng cường, thì bắt người Ca-na-an làm nô dịch cho mình, chứ không trục xuất được chúng. (29) Ép-ra-im không trục xuất được người Ca-na-an cư ngụ ở Ghe-de, và người Ca-na-an vẫn sống giữa họ ở Ghe-de. (30) Dơ-vu-lun không trục xuất được dân cư thành Kít-rôn và dân cư thành Na-ha-lôn; người Ca-na-an vẫn sống giữa họ, nhưng phải làm nô dịch cho họ. (31) A-se không trục xuất được dân cư thành Ác-cô, dân cư thành Xi-đôn, Ác-láp, Ác-díp, Khen-ba, A-phích và Rơ-khốp. (32) Thế là người A-se cư ngụ giữa người Ca-na-an đang sống trên đất ấy, vì họ đã không trục xuất được chúng. (33) Náp-ta-li không trục xuất được dân cư thành Bết Se-mét và dân cư thành Bết A-nát, nên họ cư ngụ giữa người Ca-na-an đang sống trong đất ấy, nhưng dân cư thành Bết Se-mét và Bết A-nát đã phải làm nô dịch cho họ. (34) Người E-mô-ri đã dồn con cháu Đan lên vùng núi, không để cho họ xuống đồng bằng. (35) Người E-mô-ri quyết giữ vững Ha Khe-rét, Ai-gia-lôn và Sa-an-vim; nhưng khi bàn tay nhà Giu-se đè nặng trên chúng, thì chúng đã phải làm nô dịch cho họ. (36) Ranh giới của người E-mô-ri chạy dài từ dốc Ác-ráp-bim, từ Núi Đá trở lên.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'tl', 2, '[SECTION] Thần sứ của ĐỨC CHÚA cho Ít-ra-en biết trước những điều bất hạnh
(1) Thần sứ của ĐỨC CHÚA từ Ghin-gan lên Bô-khim và nói: “Ta đã đưa các ngươi lên từ Ai-cập và dẫn vào đất Ta đã thề ban cho tổ tiên các ngươi. Ta đã phán: Chẳng bao giờ Ta phá hủy giao ước của Ta với các ngươi. (2) Còn các ngươi thì không được kết ước với dân cư trong xứ này; phải triệt hạ các bàn thờ của chúng. Nhưng các ngươi đã không nghe lời Ta. Các ngươi đã làm gì thế? (3) Vậy Ta bảo: Ta sẽ không đuổi chúng cho khuất mắt các ngươi, và chúng sẽ sống kè kè bên các ngươi; các thần của chúng sẽ là cạm bẫy cho các ngươi.” (4) Khi thần sứ của ĐỨC CHÚA nói những lời ấy cho toàn thể con cái Ít-ra-en, thì dân òa lên khóc. (5) Thế là người ta đặt tên cho nơi ấy là Bô-khim và họ đã tế lễ kính ĐỨC CHÚA tại đó.
[PART] LỜI DẪN THỨ HAI NHẬN ĐỊNH TỔNG QUÁT VỀ THỜI CÁC THỦ LÃNH
[SECTION] Cuối đời ông Giô-suê
(6) Bấy giờ ông Giô-suê giải tán dân chúng, và con cái Ít-ra-en ai nấy về nơi mình đã trúng thăm làm gia nghiệp, để chiếm hữu đất đai. (7) Dân đã phục vụ ĐỨC CHÚA suốt thời ông Giô-suê và suốt thời các kỳ mục là những người sống lâu sau ông Giô-suê, và đã chứng kiến tất cả những công cuộc vĩ đại ĐỨC CHÚA đã thực hiện cho Ít-ra-en. (8) Ông Giô-suê, con ông Nun, tôi trung của ĐỨC CHÚA, từ trần, thọ một trăm mười tuổi. (9) Người ta chôn cất ông tại thửa đất ông đã nhận được làm gia nghiệp ở Tim-nát Khe-rét trong vùng núi Ép-ra-im, phía bắc núi Ga-át. (10) Khi đến lượt cả thế hệ ấy về sum họp với tổ tiên mình, thì xuất hiện một thế hệ kế tiếp không hề biết ĐỨC CHÚA và những công cuộc Người đã thực hiện cho Ít-ra-en.
[SECTION] Ý nghĩa tôn giáo thời các thủ lãnh
(11) Con cái Ít-ra-en đã làm điều dữ trái mắt ĐỨC CHÚA, và đã làm tôi các thần Ba-an. (12) Họ đã lìa bỏ ĐỨC CHÚA, Thiên Chúa của tổ tiên, Đấng đã đưa họ ra khỏi đất Ai-cập, và họ đã đi theo các thần ngoại lai trong số các thần của các dân chung quanh. Họ sụp lạy các thần ấy và chọc giận ĐỨC CHÚA. (13) Họ đã lìa bỏ ĐỨC CHÚA để làm tôi thần Ba-an và các nữ thần Át-tô-rét. (14) ĐỨC CHÚA nổi cơn thịnh nộ với Ít-ra-en và đã trao họ vào tay quân cướp cho chúng tha hồ bóc lột; Người đã trao họ vào tay kẻ thù chung quanh, nên họ không thể đương đầu nổi với kẻ thù. (15) Cứ mỗi lần họ xuất trận là tay ĐỨC CHÚA giáng họa trên họ, như ĐỨC CHÚA đã phán và thề với họ. Họ lâm cảnh khốn cùng.
(16) Bấy giờ ĐỨC CHÚA cho xuất hiện các thủ lãnh để giải thoát họ khỏi tay những kẻ cướp phá họ. (17) Nhưng rồi các thủ lãnh của họ, họ cũng chẳng nghe mà cứ đàng điếm với các thần ngoại lai và sụp lạy các thần đó. Họ vội từ bỏ con đường cha ông họ đã đi, là tuân giữ mệnh lệnh của ĐỨC CHÚA; họ đã không noi gương các ngài. (18) Khi ĐỨC CHÚA cho xuất hiện các thủ lãnh để giúp họ, thì ĐỨC CHÚA ở với vị thủ lãnh và Người cứu họ khỏi tay quân thù bao lâu vị thủ lãnh còn sống, vì ĐỨC CHÚA động lòng trắc ẩn trước những tiếng than khóc của họ, khi họ bị đàn áp và ức hiếp. (19) Nhưng sau khi vị thủ lãnh qua đời thì họ lại ra hư đốn hơn cả cha ông họ. Họ chạy theo các thần ngoại lai để làm tôi và sụp lạy chúng, chứ không từ bỏ những hành vi và đường lối ngoan cố của họ.
[SECTION] Lý do tồn tại của chư dân
(20) ĐỨC CHÚA nổi cơn thịnh nộ với Ít-ra-en; Người phán: “Vì lũ dân này đã vi phạm giao ước Ta đã truyền cho cha ông chúng phải giữ, và chúng đã không nghe tiếng Ta, (21) nên trong số các dân mà Giô-suê còn để lại khi từ trần, Ta cũng sẽ không đuổi một dân nào cho khuất mắt chúng. (22) Ta sẽ dùng các dân ấy để thử thách Ít-ra-en, xem chúng có tuân giữ đường lối ĐỨC CHÚA như cha ông chúng đã tuân giữ hay không. (23) Vậy ĐỨC CHÚA đã để cho các dân ấy tiếp tục tồn tại mà không vội trục xuất chúng, cũng chẳng trao chúng vào tay ông Giô-suê.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'tl', 3, '(1) Đây là các dân ĐỨC CHÚA cho tồn tại, để dùng chúng mà thử thách tất cả những người Ít-ra-en đã không biết các cuộc chiến tại Ca-na-an là gì, (2) chỉ cốt cho các thế hệ con cái Ít-ra-en biết học việc binh đao, ít là cho những kẻ trước đây chưa biết. (3) Năm vương hầu Phi-li-tinh và tất cả các người Ca-na-an, người Xi-đôn, người Khi-vi ở trên vùng núi Li-băng, từ núi Ba-an Khéc-môn đến Cửa Ải Kha-mát. (4) Chúng còn đó để thử thách Ít-ra-en, xem họ có tuân giữ mệnh lệnh ĐỨC CHÚA đã dùng ông Mô-sê mà truyền cho cha ông họ hay không. (5) Vậy con cái Ít-ra-en đã sống giữa người Ca-na-an, người Khết, người E-mô-ri, người Pơ-rít-di, người Khi-vi và người Giơ-vút. (6) Và họ đã cưới con gái của chúng, cũng như gả con gái mình cho chúng, và họ đã làm tôi các thần của chúng.
[PART] SỰ TÍCH CÁC THỦ LÃNH
[PART] 1. ÔNG ÓT-NI-ÊN
(7) Con cái Ít-ra-en đã làm điều dữ trái mắt ĐỨC CHÚA. Họ đã lìa bỏ ĐỨC CHÚA, Thiên Chúa của họ, và làm tôi các thần Ba-an và nữ thần A-sê-ra. (8) ĐỨC CHÚA nổi cơn thịnh nộ với Ít-ra-en và đã trao họ vào tay Cu-san Rít-a-tha-gim, vua A-ram Na-ha-ra-gim; con cái Ít-ra-en đã làm tôi Cu-san Rít-a-tha-gim tám năm.
(9) Con cái Ít-ra-en kêu lên ĐỨC CHÚA và ĐỨC CHÚA cho xuất hiện một vị cứu tinh là ông Ót-ni-ên, con ông Cơ-nát, em ông Ca-lếp, để cứu con cái Ít-ra-en; ông Ót-ni-ên đã giải thoát họ. (10) Thần khí của ĐỨC CHÚA ở trên ông, và ông đã lãnh đạo Ít-ra-en. Ông xuất trận và ĐỨC CHÚA đã trao Cu-san Rít-a-tha-gim, vua A-ram, vào tay ông, và tay ông đè nặng lên Cu-san Rít-a-tha-gim. (11) Bấy giờ lãnh thổ được bình an bốn mươi năm. Sau đó ông Ót-ni-ên, con ông Cơ-nát, từ trần.
[PART] 2. ÔNG Ê-HÚT
(12) Con cái Ít-ra-en lại làm điều dữ trái mắt ĐỨC CHÚA, và ĐỨC CHÚA đã tăng cường sức mạnh cho Éc-lon, vua Mô-áp, chống Ít-ra-en, vì họ đã làm điều dữ trái mắt ĐỨC CHÚA. (13) Ông đã phối hợp với con cái Am-mon và A-ma-lếch, rồi tiến quân, đánh bại Ít-ra-en và chiếm lấy Thành Chà Là của họ. (14) Con cái Ít-ra-en phải làm tôi Éc-lon, vua Mô-áp, mười tám năm.
(15) Bấy giờ con cái Ít-ra-en kêu lên ĐỨC CHÚA, ĐỨC CHÚA liền cho xuất hiện một vị cứu tinh là ông Ê-hút, con ông Ghê-ra, người Ben-gia-min, một người thuận tay trái. Vậy con cái Ít-ra-en nhờ ông mang cống lễ nộp cho Éc-lon, vua Mô-áp. (16) Ông Ê-hút làm cho mình một chiếc gươm hai lưỡi, dài một gô-mét, và cột dưới áo bên hông phải. (17) Ông mang cống lễ nộp cho Éc-lon, vua Mô-áp; Éc-lon là một người béo phì. (18) Sau khi đã trao cống lễ, ông cho đám người mang cống lễ đi ra. (19) Còn chính ông, người đã viếng các tượng đá ở Ghin-gan trở về, thì nói: “Thưa ngài, tôi có một điều bí mật muốn thưa với ngài.” Vua nói: “Im lặng!” Tất cả mọi người túc trực bên vua đều ra ngoài. (20) Bấy giờ ông Ê-hút tới gần vua, lúc ấy đang ngồi ở phòng mát phía trên dành riêng cho vua, và ông Ê-hút nói: “Tôi có một lời của Thiên Chúa phải nói cho ngài.” Vua liền bỏ ghế đứng lên. (21) Ông Ê-hút thò tay trái, rút chiếc gươm từ hông phải, thọc vào bụng vua (22) lút cán, mỡ bám chặt lưỡi gươm –vì ông Ê-hút không rút gươm khỏi bụng vua– và lưỡi gươm lòi ra đằng mông. (23) Ông Ê-hút qua hành lang mà đi ra, sau khi đã đóng các cửa phòng trên và khóa lại.
(24) Ông vừa đi ra thì các đầy tớ vua đi vào. Họ thấy các cửa phòng trên vẫn khóa thì nói: “Hẳn là vua đang mắc việc cần trong phòng sau.” (25) Họ đợi hoài mà không thấy mở cửa phòng trên; nên sau cùng họ lấy chìa khóa mở phòng ra, thì kìa tôn chủ của họ nằm chết sóng sượt dưới đất.
(26) Phần ông Ê-hút đã tẩu thoát, lúc họ còn đang chờ. Ông đi qua các tượng đá mà trốn chạy về hướng Ha Xơ-i-ra. (27) Vừa tới nơi, ông liền rúc tù và vang khắp núi Ép-ra-im. Con cái Ít-ra-en cùng với ông từ núi tràn xuống; chính ông đi tiên phong. (28) Ông bảo họ: “Hãy theo tôi, vì ĐỨC CHÚA đã trao vào tay anh em kẻ thù của anh em là người Mô-áp.” Họ đi theo ông, chiếm giữ các lối qua sông Gio-đan, không để lọt một người Mô-áp nào. (29) Thời kỳ ấy họ hạ được khoảng mười ngàn người Mô-áp, tất cả những kẻ cường tráng và dũng cảm, không sót một tên. (30) Ngày hôm ấy, Mô-áp đã bị bàn tay Ít-ra-en hạ nhục, và lãnh thổ được bình an tám mươi năm.
[PART] 3. ÔNG SAM-GA
(31) Sau ông là ông Sam-ga, con ông A-nát, ông đã dùng gậy thúc bò đánh giết sáu trăm người Phi-li-tinh. Ông cũng là một vị cứu tinh của Ít-ra-en.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'tl', 4, '[PART] 4. BÀ ĐƠ-VÔ-RA VÀ ÔNG BA-RẮC
(1) Con cái Ít-ra-en lại làm điều dữ trái mắt ĐỨC CHÚA sau khi ông Ê-hút từ trần, (2) nên ĐỨC CHÚA trao họ vào tay Gia-vin, vua Ca-na-an, trị vì tại Kha-xo. Tướng chỉ huy quân đội của ông là Xi-xơ-ra, cư ngụ ở Kha-rô-sét Ha Gô-gim.
(3) Con cái Ít-ra-en kêu lên ĐỨC CHÚA, vì ông Gia-vin có đến chín trăm xe sắt, và ông đã đàn áp con cái Ít-ra-en một cách tàn bạo suốt hai mươi năm trường.
[SECTION] Bà Đơ-vô-ra
(4) Bà Đơ-vô-ra, một nữ ngôn sứ, vợ ông Láp-pi-đốt, thời ấy làm thủ lãnh xét xử Ít-ra-en. (5) Bà ngồi xử dưới cây Chà Là Đơ-vô-ra, giữa Ra-ma và Bết Ên, trên núi Ép-ra-im, và con cái Ít-ra-en đến với bà để bà xét xử cho. (6) Bà sai người mời ông Ba-rắc, con ông A-vi-nô-am, từ Ke-đét thuộc Náp-ta-li tới, và nói với ông: “ĐỨC CHÚA, Thiên Chúa của Ít-ra-en, lại không nói với ông thế này sao? Hãy đi chiêu mộ trong vùng núi Ta-bo lấy mười ngàn người trong số con cái Náp-ta-li và trong số con cái Dơ-vu-lun để đi với ngươi. (7) Ta sẽ dụ tướng Xi-xơ-ra, chỉ huy quân đội vua Gia-vin tiến về phía ngươi, bên suối Ki-sôn, cùng với chiến xa và quân binh của nó, và Ta sẽ trao nó vào tay ngươi.” (8) Ông Ba-rắc nói với bà: “Nếu bà đi với tôi thì tôi đi, nếu bà không đi với tôi thì tôi không đi.” (9) Bà trả lời: “Chắc chắn tôi sẽ đi với ông. Có điều là trong chuyến đi này, vinh dự không thuộc về ông, vì ĐỨC CHÚA sẽ trao Xi-xơ-ra vào tay một người đàn bà.” Bà Đơ-vô-ra trỗi dậy đi với ông Ba-rắc đến Ke-đét. (10) Ông Ba-rắc triệu tập Dơ-vu-lun và Náp-ta-li tiến về Ke-đét. Mười ngàn người theo chân ông, cả bà Đơ-vô-ra cũng đi với ông.
[SECTION] Ông Khe-ve, người Kê-ni
(11) Ông Khe-ve, người Kê-ni, đã tách khỏi Ca-in, khỏi con cái ông Khô-váp, nhạc phụ ông Mô-sê, và đã dựng lều bên cây sồi tại Xa-an-na-gim, gần Ke-đét.
[SECTION] Xi-xơ-ra bị đánh bại
(12) Người ta báo tin cho Xi-xơ-ra rằng: “Ông Ba-rắc, con ông A-vi-nô-am, đã lên núi Ta-bo”. (13) Tướng Xi-xơ-ra liền tập trung tất cả các chiến xa, chín trăm xe sắt và toàn bộ lực lượng dưới quyền ông, đưa từ Kha-rô-sét Ha Gô-gim đến suối Ki-sôn. (14) Bấy giờ bà Đơ-vô-ra nói với ông Ba-rắc: “Đứng lên! Vì đây là ngày ĐỨC CHÚA trao Xi-xơ-ra vào tay ông. ĐỨC CHÚA lại không xuất trận trước mặt ông sao?” Ông Ba-rắc từ núi Ta-bo đi xuống với mười ngàn quân theo sau. (15) ĐỨC CHÚA dùng gươm của ông Ba-rắc đánh Xi-xơ-ra cùng với chiến xa và toàn thể doanh trại của ông này, khiến tất cả phải tán loạn trước mặt ông Ba-rắc. Xi-xơ-ra tụt khỏi xe và chạy bộ mà trốn. (16) Ông Ba-rắc truy kích đoàn xe và quân binh cho đến Kha-rô-sét Ha Gô-gim. Tất cả quân binh của Xi-xơ-ra đều ngã gục dưới lưỡi gươm của ông Ba-rắc, không sót một tên.
[SECTION] Xi-xơ-ra bị giết
(17) Xi-xơ-ra chạy bộ trốn về phía lều bà Gia-ên, vợ ông Khe-ve, người Kê-ni, vì lúc ấy đang có hòa bình giữa Gia-vin, vua Kha-xo, với nhà Khe-ve, người Kê-ni. (18) Bà Gia-ên ra đón Xi-xơ-ra, và nói với ông: “Thưa ngài, xin dừng lại, xin dừng lại nơi đây, đừng sợ!” Ông dừng lại, đi theo bà vào lều; bà lấy tấm thảm phủ lên ông. (19) Ông nói với bà: “Cho tôi xin chút nước uống, vì tôi khát quá.” Bà liền mở vò sữa, cho ông uống, rồi lại phủ kín ông. (20) Ông nói với bà: “Xin bà đứng ở cửa lều, hễ ai đến hỏi có người nào ở đây không, thì bà nói: ‘Không.’” (21) Nhưng bà Gia-ên, vợ ông Khe-ve, lấy cái cọc lều, tay cầm búa, lặng lẽ đến bên Xi-xơ-ra, đóng cọc vào màng tang ông, xuyên xuống đất, đang lúc ông ngủ say vì mệt. Thế là ông chết. (22) Đang lúc ấy, ông Ba-rắc truy nã Xi-xơ-ra vừa tới, thì bà Gia-ên ra đón ông và nói: “Lại đây, tôi cho ông xem người ông đang tìm.” Ông đi theo bà, thì này, Xi-xơ-ra nằm chết với cái cọc xuyên màng tang.
[SECTION] Ít-ra-en được giải thoát
(23) Hồi đó Thiên Chúa hạ nhục Gia-vin, vua Ca-na-an, trước mặt con cái Ít-ra-en. (24) Bàn tay con cái Ít-ra-en ngày càng đè nặng trên Gia-vin, vua Ca-na-an, cho đến khi họ tiễu trừ được Gia-vin, vua Ca-na-an.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'tl', 5, '[SECTION] Bài ca của bà Đơ-vô-ra và ông Ba-rắc
(1) Ngày hôm ấy bà Đơ-vô-ra và ông Ba-rắc, con ông A-vi-nô-am, hát rằng:
(2) “Trong Ít-ra-en thuở chiến binh xõa tóc xung phong,
thuở toàn dân tình nguyện lên đường,
các bạn ơi, nào chúc tụng ĐỨC CHÚA!
(3) Nghe đây, hỡi các vua! Hãy lắng tai, này các thủ lãnh!
Tôi sẽ hát lên mừng ĐỨC CHÚA,
sẽ đàn ca kính Người là Thiên Chúa của Ít-ra-en.
(4) Thân lạy ĐỨC CHÚA, khi Ngài ra khỏi Xê-ia,
khi Ngài từ ruộng đồng Ê-đôm xuất phát,
thì trái đất chuyển rung, các tầng trời tan chảy,
mây cũng tan chảy thành mưa.
(5) Núi đồi chấn động trước nhan ĐỨC CHÚA,
Xi-nai cũng chấn động trước nhan Người
là Thiên Chúa của Ít-ra-en.
(6) Thời Sam-ga, con ông A-nát,
thời Gia-ên, còn đâu những đoàn khách lữ hành!
Những kẻ xưa kia đi trên quan lộ
nay lần mò theo những lối quanh co.
(7) Trong Ít-ra-en không còn thủ lãnh,
không còn nữa cho tới khi bà đứng lên, hỡi bà Đơ-vô-ra
bà đứng lên, hỡi mẹ hiền trong Ít-ra-en!
(8) Khi người ta chọn những thần mới,
bấy giờ chiến tranh đến ngay trước cửa,
khiên mộc chẳng thấy, gươm giáo cũng không
trong tay bốn mươi ngàn quân Ít-ra-en.
(9) Lòng tôi ngưỡng mộ các nhà chỉ huy Ít-ra-en,
những kẻ trong dân tình nguyện lên đường.
Các bạn ơi, nào chúc tụng ĐỨC CHÚA!
(10) Hỡi những ai cỡi lừa trắng,
hỡi những kẻ ngồi thảm hoa,
hỡi khách bộ hành, hát lên đi!
(11) Những người chia nhau chiến lợi phẩm bên bồn nước,
hãy cất tiếng ca ngợi hồng ân của ĐỨC CHÚA,
những hồng ân Người ban cho thủ lãnh Ít-ra-en,
bấy giờ dân của ĐỨC CHÚA ùa xuống các cửa.
(12) Phấn khởi lên! Phấn khởi lên nào! Đơ-vô-ra hỡi!
Phấn khởi lên! Phấn khởi lên nào! Hát một bài ca!
Đứng lên! Hỡi Ba-rắc!
Bỏ tù kẻ bỏ tù ông! Hỡi con của A-vi-nô-am!
(13) Bấy giờ Ít-ra-en xuống cửa vì chính nghĩa của mình,
dân của ĐỨC CHÚA đã xuống như những vị anh hùng.
(14) Các lãnh tụ Ép-ra-im ở trong thung lũng,
trong hàng ngũ theo ông, có Ben-gia-min.
Các vị chỉ huy xuất thân từ Ma-khia,
từ Dơ-vu-lun, những người nắm côn trượng.
(15) Các lãnh tụ Ít-xa-kha theo bà Đơ-vô-ra.
Náp-ta-li trung thành với Ba-rắc,
chạy theo vết chân ông trong thung lũng.
Trong các thị tộc của Rưu-vên,
bàn bạc thì thật là sôi nổi!
(16) ‘Sao bạn cứ ở lì trong hốc đá,
mải nghe tiếng sáo bên đàn chiên?’
Trong các thị tộc của Rưu-vên,
bàn bạc thì thật là sôi nổi!
(17) Ga-la-át ở lại bên kia sông Gio-đan,
còn Đan, sao cứ sống trên tàu bè?
A-se thì định cư miền duyên hải,
trong các hải cảng, vẫn cứ nhởn nhơ!
(18) Dơ-vu-lun, dân coi nhẹ cái chết,
cùng với Náp-ta-li, trên điểm cao chiến trường.
(19) Các vua đã tới, đã giao tranh,
các vua Ca-na-an đã giao tranh
tại Ta-nác, bên dòng suối Mơ-ghít-đô.
Chúng đã không cướp được bạc làm chiến lợi phẩm.
(20) Từ trời cao, tinh tú đã giao tranh,
từ trên quỹ đạo, tinh tú chống lại Xi-xơ-ra.
(21) Dòng suối Ki-sôn đã cuốn trôi chúng,
dòng suối ngàn xưa, suối Ki-sôn.
Dũng cảm tiến lên, hồn ta hỡi!
(22) Bấy giờ vó ngựa vang rền trên mặt đất,
đoàn thiên lý mã phi nhanh, phi thật nhanh.
(23) Hãy nguyền rủa Mê-rốt –thần sứ ĐỨC CHÚA nói–,
nguyền rủa, nguyền rủa các dân cư của nó.
Vì chúng đã không đến yểm trợ ĐỨC CHÚA,
yểm trợ ĐỨC CHÚA với các bậc anh hùng.
(24) Phúc thay bà Gia-ên, phu nhân ông Khe-ve, người Kê-ni,
hơn các phụ nữ,
hơn các phụ nữ trong lều trại, bà thật là có phúc.
(25) Y xin nước, bà cho sữa.
Bà dâng sữa béo trong chén quý của hàng thượng lưu.
(26) Rồi tay trái cầm lấy chiếc cọc,
còn tay phải nắm búa công nhân,
đánh Xi-xơ-ra, đập cho bể đầu,
và đâm thủng màng tang.
(27) Dưới chân bà, y ngã quỵ, té nhào, nằm sóng sượt,
dưới chân bà, y ngã quỵ, té nhào;
ngã quỵ nơi nào, té nhào nơi ấy, nằm bất động.
(28) Qua cửa sổ, một bà khác nghiêng mình kêu la,
đó là mẹ của Xi-xơ-ra, nói qua song cửa:
‘Sao xe của con tôi mãi không về?
Sao đoàn xe trận của con tôi về chậm thế?’
(29) Công chúa khôn ngoan nhất của bà đã trả lời,
và bà cứ nhẩm đi nhắc lại:
(30) ‘Chắc họ đã gặp may, và đang chia nhau chiến lợi phẩm:
một hai nàng cho mỗi chiến binh,
và nhiễu điều làm chiến lợi phẩm cho Xi-xơ-ra.
Một hai tấm nhiễu điều thêu sặc sỡ,
choàng lên cổ của người toàn thắng.’
(31) Lạy ĐỨC CHÚA! Mọi kẻ thù của Ngài
đều tiêu vong như thế!
Còn những ai yêu mến Ngài,
xin cho họ rạng rỡ như mặt trời hừng đông.”
Và lãnh thổ bình an bốn mươi năm.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'tl', 6, '[PART] 5. ÔNG GHÍT-ÔN VÀ ÔNG A-VI-ME-LÉC
[PART] A. Thiên Chúa gọi ông Ghít-ôn
[SECTION] Người Ma-đi-an áp bức dân Ít-ra-en
(1) Con cái Ít-ra-en đã làm điều dữ trái mắt ĐỨC CHÚA, nên ĐỨC CHÚA đã trao họ vào tay người Ma-đi-an trong bảy năm. (2) Tay người Ma-đi-an đè nặng trên Ít-ra-en. Để tránh mặt người Ma-đi-an, con cái Ít-ra-en đã thiết lập những khu an toàn trong các vùng núi, những hang động hốc đá. (3) Hễ Ít-ra-en gieo giống thì người Ma-đi-an, người A-ma-lếch và người Phương Đông cũng lên; chúng lên chống lại Ít-ra-en. (4) Chúng đóng trại bên cạnh họ và tàn phá hoa màu, đất đai cho đến sát Ga-da, không để sót lại vật gì trong Ít-ra-en, dù là gia súc hay bò lừa cũng vậy. (5) Vì chúng lên cùng với đàn vật và lều trại của chúng, tiến vào nhiều vô kể như châu chấu; chúng và lạc đà của chúng đông không đếm nổi. Chúng tràn vào tàn phá xứ sở. (6) Như vậy người Ít-ra-en hoàn toàn kiệt quệ vì người Ma-đi-an. Và con cái Ít-ra-en đã kêu lên ĐỨC CHÚA.
[SECTION] Một ngôn sứ can thiệp
(7) Khi con cái Ít-ra-en kêu lên ĐỨC CHÚA về người Ma-đi-an, (8) thì ĐỨC CHÚA đã sai một vị ngôn sứ đến với con cái Ít-ra-en. Ông nói với họ: “ĐỨC CHÚA, Thiên Chúa của Ít-ra-en phán thế này: Chính Ta đã đưa các ngươi lên khỏi Ai-cập, đã kéo các ngươi ra khỏi nhà nô lệ, (9) đã giải thoát các ngươi khỏi tay Ai-cập, khỏi tay mọi kẻ áp bức các ngươi, và đã đuổi chúng cho khuất mắt các ngươi, đã ban cho các ngươi đất đai của chúng. (10) Và Ta đã phán với các ngươi: Ta là ĐỨC CHÚA, Thiên Chúa của các ngươi. Các ngươi không được kính sợ các thần của người E-mô-ri, khi các ngươi cư ngụ trên đất của chúng. Nhưng các ngươi đã không nghe tiếng Ta.”
[SECTION] Thần sứ của ĐỨC CHÚA hiện ra với ông Ghít-ôn
(11) Thần sứ của ĐỨC CHÚA đến và ngồi dưới cây tùng ở Óp-ra. Cây này là của ông Giô-át, thuộc gia đình A-vi-e-de. Con ông là Ghít-ôn bấy giờ đang đập lúa trong bồn đạp nho để tránh mặt người Ma-đi-an. (12) Thần sứ ĐỨC CHÚA hiện ra với ông và nói: “Chào chiến sĩ can trường! ĐỨC CHÚA ở với ông.” (13) Ông Ghít-ôn đáp: “Ôi, thưa Ngài, nếu ĐỨC CHÚA ở với chúng tôi, thì sao chúng tôi đến nông nỗi này? Đâu cả rồi những kỳ công mà cha ông đã kể lại cho chúng tôi nghe, rằng: chẳng phải ĐỨC CHÚA đã đưa chúng ta lên khỏi Ai-cập sao? Thế mà bây giờ ĐỨC CHÚA đã bỏ rơi chúng tôi, trao chúng tôi vào tay người Ma-đi-an.”
(14) Bấy giờ ĐỨC CHÚA quay lại nhìn ông và nói: “Hãy mạnh bạo lên đường cứu Ít-ra-en khỏi tay quân Ma-đi-an. Không phải chính Ta sai ngươi sao?” (15) Nhưng ông đáp: “Ôi, thưa Ngài, con lấy gì mà cứu Ít-ra-en? Này dòng họ con thấp kém nhất trong chi tộc Mơ-na-se, mà con lại nhỏ nhất trong nhà cha con.” (16) ĐỨC CHÚA phán với ông: “Ta sẽ ở với ngươi, và ngươi sẽ đánh quân Ma-đi-an như đánh có một người.” (17) Ông thưa: “Nếu Ngài thương con thì xin cho con một dấu chứng tỏ Ngài đang nói với con. (18) Xin Ngài đừng rời khỏi đây cho tới khi con trở lại, mang theo của lễ đặt trước nhan Ngài.” Người phán: “Ta sẽ ở lại cho tới khi ngươi trở về.”
(19) Ông Ghít-ôn đi bắt một con dê non làm thịt, và lấy hai thùng bột làm mấy chiếc bánh không men. Thịt thì ông để trong một cái rổ, còn nước cốt thì đựng trong một cái thố. Rồi ông mang đến cho Người ở dưới cây tùng. Khi ông đến gần, (20) thì Thần sứ Thiên Chúa nói với ông: “Hãy lấy thịt và bánh không men đặt trên tảng đá này và rưới nước cốt lên.” Ông đã làm như thế.
(21) Thần sứ của ĐỨC CHÚA giơ đầu gậy đang cầm trong tay đụng vào thịt và bánh không men, lửa liền từ tảng đá bốc lên, đốt cháy hết thịt cùng bánh không men. Thần sứ ĐỨC CHÚA biến khỏi mắt ông. (22) Ông Ghít-ôn thấy đó chính là Thần sứ ĐỨC CHÚA. Ông Ghít-ôn nói: “Chết tôi rồi, lạy ĐỨC CHÚA là Chúa Thượng của tôi, vì tôi đã thấy Thần sứ ĐỨC CHÚA nhãn tiền!” (23) Nhưng ĐỨC CHÚA phán với ông: “Bình an cho ngươi! Đừng sợ: ngươi không chết đâu.” (24) Tại đó ông Ghít-ôn xây một bàn thờ kính ĐỨC CHÚA, và ông gọi nơi ấy là ĐỨC CHÚA – Bình an. Cho đến ngày nay, bàn thờ ấy vẫn còn tại Óp-ra, đất của gia đình A-vi-e-de.
[SECTION] Ông Ghít-ôn triệt hạ Ba-an
(25) Một đêm kia ĐỨC CHÚA phán bảo ông: “Hãy lấy con bò mộng của cha ngươi, con bò bảy tuổi, rồi phá hủy bàn thờ Ba-an của cha ngươi và chặt đứt cây cột thần bên cạnh. (26) Ngươi sẽ xây bàn thờ kính ĐỨC CHÚA, Thiên Chúa ngươi, trên đỉnh của nơi kiên cố này, sắp xếp sao cho gọn ghẽ. Ngươi sẽ lấy con bò và dâng làm lễ toàn thiêu với gỗ cây cột thần ngươi đã chặt.” (27) Vậy ông Ghít-ôn mang theo mười người đầy tớ và làm như ĐỨC CHÚA đã nói với ông. Tuy nhiên, vì sợ người nhà của cha mình và những người trong thành, ông không dám làm ban ngày, nên đã làm ban đêm. (28) Sáng hôm sau, khi những người trong thành thức dậy, thì kìa bàn thờ Ba-an đã bị triệt hạ, cây cột thần cạnh đó đã bị chặt, và con bò mộng thứ hai đã được dâng làm lễ toàn thiêu trên bàn thờ mới xây. (29) Họ nói với nhau: “Ai đã làm chuyện này thế?” Rồi họ điều tra và tìm hiểu, thì ra là ông Ghít-ôn, con ông Giô-át, đã làm chuyện đó. (30) Dân thành liền nói với ông Giô-át: “Đưa con ông ra đây! Nó phải chết, vì nó đã triệt hạ bàn thờ Ba-an và đã chặt đứt cây cột thần bên cạnh.” (31) Ông Giô-át nói với tất cả mọi người đứng trước mặt ông: “Các anh bênh quyền lợi của Ba-an ư? Hay là các anh tính cứu thần đó? Kẻ nào bênh quyền lợi Ba-an sẽ phải chết trước khi trời rạng sáng. Nếu Ba-an là thần thì Ba-an cứ tự biện hộ. Ghít-ôn đã phá bàn thờ của Ba-an đó.” (32) Ngày hôm ấy, người ta gọi ông Ghít-ôn là Giơ-rúp-ba-an, mà rằng: “Xin Ba-an đối phó với hắn, vì hắn đã triệt hạ bàn thờ của người.”
[SECTION] Kêu gọi chiến đấu
(33) Tất cả các người Ma-đi-an, người A-ma-lếch và người Phương Đông đều nhất tề tập hợp; họ băng qua sông và đóng trại tại đồng bằng Gít-rơ-en. (34) Ông Ghít-ôn được đầy thần khí của ĐỨC CHÚA; ông rúc tù và, và người A-vi-e-de quy tụ lại sau lưng ông. (35) Ông sai sứ giả kêu gọi mọi người trong chi tộc Mơ-na-se, và họ quy tụ lại sau lưng ông; ông sai sứ giả kêu gọi mọi người trong chi tộc A-se, Dơ-vu-lun và Náp-ta-li, họ cũng đều tiến lên đón ông.
[SECTION] Lông cừu làm điềm báo
(36) Ông Ghít-ôn thưa với Thiên Chúa: “Nếu đúng là Ngài sẽ dùng tay con để cứu Ít-ra-en như Ngài đã phán, (37) thì này đây con đặt một mớ lông cừu trong sân lúa: nếu chỉ có sương trên lông cừu mà thôi, còn tất cả mặt đất đều khô, thì con biết Ngài sẽ dùng tay con để cứu Ít-ra-en như Ngài đã phán.” (38) Và đã xảy ra như vậy. Sáng hôm sau ông dậy sớm, bóp mớ lông cừu, vắt cho sương chảy ra đầy một chén nước. (39) Ông Ghít-ôn lại thưa với Thiên Chúa: “Xin Ngài đừng thịnh nộ với con, để con được nói một lần nữa. Xin cho con được trắc nghiệm bằng lông cừu một lần nữa thôi: chỉ có lông cừu là khô, còn tất cả mặt đất đều đẫm sương.” (40) Đêm ấy Thiên Chúa đã làm như vậy. Chỉ có lông cừu là khô, còn tất cả mặt đất đều đẫm sương.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'tl', 7, '[PART] B. Ông Ghít-ôn giao chiến bên tây ngạn sông Gio-đan
[SECTION] ĐỨC CHÚA rút bớt quân số của ông Ghít-ôn
(1) Ông Giơ-rúp-ba-an, tức Ghít-ôn, cũng như toàn dân đang ở với ông, thức dậy thật sớm, và ông đóng trại gần Ên Kha-rốt; còn trại quân Ma-đi-an thì nằm ở phía bắc trại ông, sát đồi Mô-re, trong đồng bằng. (2) ĐỨC CHÚA phán bảo ông: “Đám dân ở với ngươi quá đông; Ta không trao quân Ma-đi-an vào tay chúng được, kẻo Ít-ra-en lại tự phụ phạm đến Ta, khi cho rằng ‘Chính tay tôi đã cứu tôi.’ (3) Vậy ngươi hãy công bố cho dân nghe: ‘Ai sợ hãi và run khiếp thì hãy về đi!’” Và ông Ghít-ôn đã thử họ: hai mươi ngàn người trong dân rút lui, còn lại mười ngàn.
(4) ĐỨC CHÚA phán với ông Ghít-ôn: “Dân này vẫn còn đông. Hãy bảo chúng xuống gần nước, ở đó Ta sẽ thử chúng. Kẻ nào Ta nói với ngươi ‘người này sẽ đi với ngươi’ thì kẻ đó sẽ đi với ngươi. Còn tất cả những ai Ta nói với ngươi ‘người này không đi với ngươi’, kẻ đó sẽ không được đi.” (5) Vậy ông Ghít-ôn đem đám dân ấy đến gần nước, và ĐỨC CHÚA phán với ông Ghít-ôn: “Tất cả những ai thè lưỡi tớp nước như chó, ngươi hãy để riêng ra, tất cả những ai quỳ xuống mà uống cũng vậy.” (6) Số người dùng tay đưa nước lên miệng mà tớp là ba trăm. Tất cả số dân còn lại đều quỳ xuống mà uống nước. (7) Bấy giờ ĐỨC CHÚA phán với ông Ghít-ôn: “Với ba trăm người đã tớp nước, Ta sẽ cứu các ngươi, và sẽ trao quân Ma-đi-an vào tay ngươi. Còn tất cả những người khác thì hãy rút lui, ai về nhà nấy.” (8) Người ta giữ lại vò lương thực của đám dân, cùng với các tù và. Sau đó, ông Ghít-ôn cho tất cả con cái Ít-ra-en trở về, ai nấy về lều mình, chỉ giữ lại ba trăm người. Doanh trại của người Ma-đi-an nằm phía dưới trại của ông, trong đồng bằng.
[SECTION] Điềm báo thắng trận
(9) Đêm ấy ĐỨC CHÚA phán với ông: “Đứng lên! Đi xuống doanh trại, vì Ta sẽ trao nó vào tay ngươi. (10) Nhưng nếu ngươi sợ không dám xuống, thì hãy đi xuống trại với Pu-ra, đầy tớ ngươi. (11) Ngươi sẽ nghe ngóng xem chúng nói gì; sau đó tay ngươi sẽ ra cứng rắn, và ngươi sẽ xuống đánh trại.” Vậy chính ông đã cùng với Pu-ra, đầy tớ ông, xuống tới đầu tiền đồn của trại.
(12) Quân Ma-đi-an, A-ma-lếch và toàn quân Phương Đông nằm đầy đồng bằng, nhiều vô kể như châu chấu, và số lạc đà của chúng không đếm nổi, như cát trên bờ biển. (13) Ông Ghít-ôn tới nơi, thì này một tên đang kể cho đồng đội một giấc chiêm bao. Hắn nói: “Đây là giấc chiêm bao tôi đã nằm mơ: một tấm bánh lúa mạch lăn trong trại Ma-đi-an, tới một chiếc lều, đụng vào lều thì nó ngã xuống, cuốn chỏng gọng cái lều lên, thế là cái lều đổ.” (14) Người đồng đội họa theo và nói: “Đây chỉ có thể là chiếc gươm của Ghít-ôn, con Giô-át, người Ít-ra-en. Thiên Chúa đã trao người Ma-đi-an và cả doanh trại vào tay ông ta.” (15) Khi nghe kể giấc chiêm bao và lời giải thích, ông Ghít-ôn sấp mình xuống, đoạn trở về trại Ít-ra-en và nói: “Đứng lên! Vì ĐỨC CHÚA đã trao vào tay anh em doanh trại Ma-đi-an.”
[SECTION] Cuộc đột kích
(16) Bấy giờ ông chia ba trăm người thành ba cánh quân, trao vào tay mọi người tù và, vò rỗng có đuốc bên trong. (17) Ông bảo họ: “Hãy nhìn và làm theo tôi. Khi tới đầu trại, tôi làm gì thì các anh cứ làm theo! (18) Tôi sẽ rúc tù và cùng một lúc với tất cả những người đi với tôi; bấy giờ các anh cũng rúc tù và khắp quanh trại và cùng hô: Vì ĐỨC CHÚA! Vì Ghít-ôn!”
(19) Ông Ghít-ôn cùng với một trăm người theo ông đi tới đầu trại vào đầu canh hai, lúc vừa thay người canh; họ rúc tù và, đồng thời đập bể những chiếc vò đang cầm trong tay. (20) Bấy giờ cả ba cánh quân đều rúc tù và, đập bể vò; tay trái nắm chắc đuốc, tay phải cầm tù và rúc lên, rồi họ cùng hô: “Vì ĐỨC CHÚA, vì Ghít-ôn, vung kiếm lên!” (21) Chung quanh trại, ai nấy đứng yên tại chỗ. Cả trại tán loạn, la ó và chạy trốn. (22) Trong lúc ba trăm người rúc tù và thì ĐỨC CHÚA làm cho mỗi người trong khắp trại quay gươm giết bạn mình. Cả doanh trại đều trốn chạy về phía Xơ-rê-ra cho đến Bết Ha Sít-ta, bên bờ suối A-vên Mơ-khô-la, đối diện với Táp-bát.
[SECTION] Truy kích
(23) Bấy giờ từ Náp-ta-li, A-se và toàn thể Mơ-na-se, các người Ít-ra-en họp nhau lại và rượt đuổi quân Ma-đi-an. (24) Ông Ghít-ôn sai sứ giả đi kêu gọi khắp vùng núi Ép-ra-im: “Hãy xuống đón đầu quân Ma-đi-an, chiếm cứ các nguồn nước của chúng, cho đến Bết Ba-ra và sông Gio-đan.” Tất cả các người Ép-ra-im đều họp lại chiếm lấy các nguồn nước cho đến Bết Ba-ra và sông Gio-đan. (25) Họ bắt được hai tướng của Ma-đi-an là Ô-rếp và Dơ-ếp; họ giết Ô-rếp tại tảng đá Ô-rếp, còn Dơ-ếp thì giết tại bồn ép nho Dơ-ếp. Họ còn rượt theo quân Ma-đi-an và mang thủ cấp của Ô-rếp và Dơ-ếp từ bên kia sông Gio-đan về cho ông Ghít-ôn.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'tl', 8, '[SECTION] Ép-ra-im kêu trách
(1) Những người Ép-ra-im nói với ông: “Ông đối xử với chúng tôi như vậy nghĩa là thế nào? Ông đã không thèm gọi chúng tôi, khi ông lên đường đánh quân Ma-đi-an.” Họ đã công kích ông dữ dội. (2) Nhưng ông nói với họ: “Việc tôi đã làm sánh sao được với các anh? Thứ mà Ép-ra-im ăn mót, lại không tốt hơn cả mùa trái của A-vi-e-de sao? (3) Thiên Chúa đã trao vào tay các anh các thủ lãnh Ma-đi-an là Ô-rếp và Dơ-ếp, thì tôi có thể làm gì sánh được với các anh?” Nghe ông nói thế, họ mới nguôi giận.
[PART] C. Ông Ghít-ôn giao chiến bên kia sông Gio-đan. Ông từ trần.
[SECTION] Ông Ghít-ôn vượt sông Gio-đan truy lùng địch
(4) Tới sông Gio-đan, ông Ghít-ôn sang sông cùng với ba trăm người theo ông, rất mệt mỏi nhưng vẫn truy lùng quân địch. (5) Ông nói với các người Xúc-cốt: “Làm ơn cho đám người theo tôi mấy tấm bánh, vì họ đã mệt mỏi rồi, mà tôi thì còn phải truy lùng De-vác và Xan-mun-na, vua Ma-đi-an.” (6) Nhưng các thủ lãnh Xúc-cốt trả lời: “Số mạng của De-vác và Xan-mun-na nay đã nằm gọn trong tay ông rồi sao, mà chúng tôi phải cấp bánh cho quân đội của ông?” (7) Ông Ghít-ôn đáp: “Đã vậy thì một khi ĐỨC CHÚA trao De-vác và Xan-mun-na vào tay ta rồi, ta sẽ lấy gai rừng và cây ké mà xé xác các ngươi!” (8) Từ đấy, ông đi lên Pơ-nu-ên, và lại nói với người ta như vậy, nhưng những người Pơ-nu-ên trả lời y như những người Xúc-cốt. (9) Ông cũng nói với người Pơ-nu-ên rằng: “Khi ta trở về bình an vô sự, ta sẽ triệt hạ tháp này.”
[SECTION] De-vác và Xan-mun-na bại trận
(10) De-vác và Xan-mun-na lúc ấy đang ở Các-co cùng với đạo quân của họ, chừng mười lăm ngàn người, đó là số còn lại trong toàn bộ doanh trại con cái Phương Đông. Vì mười hai ngàn mạng biết tuốt gươm đã gục ngã. (11) Ông Ghít-ôn tiến lên theo con đường của dân du mục, ở phía đông Nô-vác và Gióc-bô-ha, và đã tấn công trại khi trại cứ tưởng là an toàn. (12) De-vác và Xan-mun-na chạy trốn, nhưng ông đã đuổi kịp và bắt được cả hai vua Ma-đi-an là De-vác và Xan-mun-na, gây khiếp đảm cho toàn bộ doanh trại.
[SECTION] Ông Ghít-ôn báo thù
(13) Sau trận chiến, ông Ghít-ôn, con ông Giô-át trở về qua ngả đường lên Khe-rét. (14) Ông bắt một thiếu niên thuộc dân Xúc-cốt và tra hỏi nó. Nó viết cho ông tên các thủ lãnh Xúc-cốt, và các kỳ mục trong dân là bảy mươi bảy người. (15) Vậy ông đến với người Xúc-cốt và nói: “Đây là De-vác và Xa-mun-na! Vì chúng, các ngươi đã đay nghiến ta mà rằng: ‘Số mạng của De-vác và Xan-mun-na nay đã nằm gọn trong tay ông rồi sao, mà chúng tôi phải cấp bánh cho những người mệt mỏi của ông?’” (16) Ông bắt các kỳ mục trong thành, lấy gai rừng và cây ké mà dạy cho những người Xúc-cốt một bài học. (17) Tháp Pơ-nu-ên, ông cũng triệt hạ, và tàn sát cả những người trong thành. (18) Ông nói với De-vác và Xan-mun-na: “Những kẻ các ngươi đã tàn sát ở Ta-bo là người thế nào?” Chúng thưa: “Ông thế nào, họ cũng vậy; người nào cũng có vẻ hoàng tử.” (19) Ông nói: “Họ là anh em cùng mẹ với ta đó. Thề có ĐỨC CHÚA hằng sống! Giả như các ngươi để họ sống, thì ta chẳng sát hại các ngươi đâu!” (20) Rồi ông bảo người con cả của ông Gie-the: “Đứng lên! Giết chúng đi!” Nhưng chàng thiếu niên sợ không dám tuốt gươm, vì cậu còn trẻ. (21) De-vác và Xan-mun-na liền nói: “Vậy thì chính nhà ngươi đứng lên giết chúng ta đi, vì anh hùng đâu có sợ chết!” Ông Ghít-ôn đứng lên hạ sát De-vác và Xan-mun-na, rồi tháo lấy những chiếc vòng đeo cổ các con lạc đà của chúng.
[SECTION] Cuối đời ông Ghít-ôn
(22) Người Ít-ra-en nói với ông Ghít-ôn: “Xin ông cai trị chúng tôi, cả ông cũng như con cháu ông, vì ông đã giải thoát chúng tôi khỏi tay quân Ma-đi-an.” (23) Ông Ghít-ôn trả lời: “Chính tôi sẽ không cai trị, mà con tôi cũng không cai trị anh em, nhưng ĐỨC CHÚA sẽ cai trị anh em.” (24) Ông Ghít-ôn nói với họ: “Tôi xin anh em một điều là mỗi người cho tôi một cái nhẫn trong số chiến lợi phẩm của mình.” Sở dĩ như vậy là vì những người bại trận là dân Ít-ma-ên, nên chúng mang nhẫn vàng. (25) Những người ấy đáp: “Hẳn là chúng tôi sẽ tặng ông rồi.” Họ trải chiếc áo choàng ra, và mỗi người bỏ vào đấy một chiếc nhẫn đã chiếm được. (26) Trọng lượng số nhẫn vàng ông đã xin được là mười bảy ký vàng, không kể các vòng khuyên, các hoa tai và những chiếc áo điều các vua Ma-đi-an vẫn mặc, và không kể các vòng đeo cổ các con lạc đà của chúng. (27) Ông Ghít-ôn lấy số vàng đó làm một tượng ê-phốt và đặt trong thành của ông tại Óp-ra; và toàn thể Ít-ra-en đã đàng điếm với nó, nên nó hóa cái bẫy cho ông Ghít-ôn và nhà ông.
(28) Ma-đi-an bị hạ nhục trước mặt con cái Ít-ra-en; chúng không còn ngẩng đầu lên được nữa. Dưới thời ông Ghít-ôn, lãnh thổ được bình an bốn mươi năm. (29) Ông Giơ-rúp-ba-an, con ông Giô-át, lui về sống cảnh điền viên. (30) Ông Ghít-ôn sinh được bảy mươi người con, vì ông có nhiều vợ. (31) Ông có người tỳ thiếp ở Si-khem, bà cũng sinh cho ông một con trai; và ông đặt tên cho nó là A-vi-me-léc. (32) Ông Ghít-ôn, con ông Giô-át, qua đời sau khi hưởng tuổi già hạnh phúc, và được chôn cất trong phần mộ của ông Giô-át, thân phụ ông, tại Óp-ra của dòng họ A-vi-e-de.
[SECTION] Ít-ra-en lại suy sụp
(33) Sau khi ông Ghít-ôn qua đời, con cái Ít-ra-en lại đàng điếm với các Ba-an, và tôn Ba-an Bơ-rít làm thiên chúa của mình. (34) Con cái Ít-ra-en không nhớ ĐỨC CHÚA là Thiên Chúa của mình, Đấng đã giải thoát họ khỏi tay mọi thù địch chung quanh. (35) Họ cũng chẳng đối xử nhân nghĩa với nhà ông Giơ-rúp-ba-an, tức Ghít-ôn, mà đền đáp tất cả những điều tốt lành ông đã làm cho Ít-ra-en.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'tl', 9, '[PART] D. Vương triều của A-vi-me-léc
(1) A-vi-me-léc, con ông Giơ-rúp-ba-an, đến Si-khem gặp bà con bên ngoại, và nói với họ, cùng cả gia tộc bên ngoại rằng: (2) “Xin bà con hỏi các thân hào Si-khem xem: điều nào tốt cho các vị? Để cho bảy mươi người, tức là tất cả các con ông Giơ-rúp-ba-an cai trị các vị, hay là để một người cai trị các vị mà thôi? Xin các vị nhớ cho rằng tôi là anh em ruột thịt của các vị.” (3) Bà con bên ngoại dùng chính những lời đó nói về A-vi-me-léc cho toàn thể thân hào Si-khem nghe, và lòng họ nghiêng về A-vi-me-léc, vì họ nói: “Ông ấy là bà con của chúng ta.” (4) Vậy họ trao cho ông bảy mươi se-ken bạc, lấy của đền Ba-an Bơ-rít, A-vi-me-léc dùng tiền ấy thuê những đứa vô lại cùng bọn du đãng, và chúng theo ông. (5) Thế là ông đến nhà cha mình tại Óp-ra, hạ sát các anh em, tức là bảy mươi người con của ông Giơ-rúp-ba-an, trên cùng một tảng đá; chỉ sót có Giô-tham, con út của ông Giơ-rúp-ba-an, vì anh ta lẩn trốn được. (6) Bấy giờ tất cả thân hào Si-khem cùng toàn dân Bết Mi-lô họp lại, kéo đến tôn A-vi-me-léc lên làm vua, bên cạnh cây sồi trước bia đá ở Si-khem.
[SECTION] Ngụ ngôn của ông Giô-tham
(7) Khi người ta báo tin ấy cho ông Giô-tham, ông liền lên đứng trên đỉnh núi Gơ-ri-dim, cất tiếng gọi và nói với những người kia rằng: “Hỡi các thân hào Si-khem! Hãy nghe tôi đây, thì Thiên Chúa cũng sẽ nghe các người.
(8) Cây cối đã lên đường đi xức dầu phong một vua cai trị chúng. Chúng nói với cây ô-liu: ‘Hãy làm vua cai trị chúng tôi!’
(9) Nhưng cây ô-liu nói với chúng: ‘Chẳng lẽ tôi lại từ bỏ dầu của tôi là thứ đã từng làm cho thần minh và người đời được tôn trọng, mà đi đu đưa trên cây cối hay sao?’
(10) Cây cối liền nói với cây vả: ‘Hãy đến làm vua cai trị chúng tôi!’
(11) Nhưng cây vả bảo chúng: ‘Chẳng lẽ tôi lại từ bỏ vị ngọt và trái ngon của tôi mà đi đu đưa trên cây cối hay sao?’
(12) Bấy giờ cây cối nói với cây nho: ‘Hãy đến làm vua cai trị chúng tôi!’
(13) Nhưng cây nho bảo chúng: ‘Chẳng lẽ tôi lại từ bỏ rượu của tôi là thứ đã từng làm cho thần minh và người đời phấn khởi, mà đi đu đưa trên cây cối hay sao?’
(14) Tất cả cây cối liền nói với bụi gai: ‘Hãy đến làm vua cai trị chúng tôi!’
(15) Bụi gai trả lời cây cối: ‘Nếu quả thật các ngươi xức dầu phong ta làm vua cai trị các ngươi, thì hãy tới nương náu dưới bóng ta; bằng không, lửa sẽ bốc ra từ bụi gai và sẽ thiêu rụi các cây bá hương Li-băng!’
(16) Các người có đối xử thành thật và trọn đạo khi tôn A-vi-me-léc lên làm vua không? Các người có đối xử tốt với ông Giơ-rúp-ba-an và nhà ông ấy không? Có đối xử với ông xứng với công lao của ông không? (17) Cha tôi đã chiến đấu vì các người, đã liều mạng để giải thoát các người khỏi tay quân Ma-đi-an. (18) Thế mà ngày nay các người lại phản bội nhà cha tôi, tàn sát con cái ông, tất cả bảy mươi người trên cùng một tảng đá, rồi đặt đứa con người tỳ thiếp của ông là A-vi-me-léc lên làm vua cai trị các thân hào Si-khem, vì y là bà con của các người. (19) Vậy, nếu ngày hôm nay các người đã đối xử thành thật và trọn đạo với ông Giơ-rúp-ba-an và nhà ông, thì cứ việc vui vì A-vi-me-léc, và mong sao y cũng được vui vì các người. (20) Bằng không, thì xin cho một ngọn lửa phát ra từ A-vi-me-léc để thiêu hủy các thân hào Si-khem cùng với dân Bết Mi-lô, và xin cho một ngọn lửa phát ra từ các thân hào Si-khem và dân Bết Mi-lô để thiêu hủy A-vi-me-léc nữa!” (21) Rồi ông Giô-tham chạy về phía Bơ-e và trú ngụ tại đây, vì sợ A-vi-me-léc, người anh em của ông.
[SECTION] Si-khem phản loạn chống A-vi-me-léc
(22) A-vi-me-léc cầm quyền cai trị Ít-ra-en ba năm. (23) Rồi Thiên Chúa gây một thần khí bất hòa giữa A-vi-me-léc và các thân hào Si-khem, khiến các thân hào Si-khem phản lại A-vi-me-léc. (24) Như vậy là để báo phục tội giết bảy mươi người con ông Giơ-rúp-ba-an, và để làm cho máu họ đổ xuống trên A-vi-me-léc, người anh em đã giết họ, và đổ xuống trên các thân hào Si-khem, những người đã tiếp tay với y, để y giết anh em mình. (25) Các thân hào Si-khem đã đặt những ổ mai phục trên các ngọn núi, để cướp bóc tất cả những người đi ngang qua đó. Người ta báo tin ấy cho A-vi-me-léc biết.
(26) Bấy giờ ông Ga-an, con ông E-vét, cùng đi với anh em ông, và họ qua Si-khem; các thân hào Si-khem tín nhiệm ông. (27) Họ ra vườn hái nho, rồi đạp ép và tổ chức vui chơi. Họ vào đền các thần minh của họ, ăn uống và nguyền rủa A-vi-me-léc. (28) Ông Ga-an, con ông E-vét nói: “A-vi-me-léc là ai, và Si-khem là ai mà chúng ta làm tôi nó? Nó chẳng phải là con Giơ-rúp-ba-an, và đại diện của nó chẳng phải là Dơ-vun sao? Các người hãy làm tôi con cái Kha-mo, cha của Si-khem; còn chúng tôi, việc gì chúng tôi phải làm tôi nó? (29) Ai sẽ trao dân này vào tay tôi, để tôi loại trừ A-vi-me-léc? Và tôi nói với nó: ‘Hãy tăng thêm quân của mi và ra đây!’”
(30) Ông Dơ-vun, tổng trấn thành, nghe những lời ông Ga-an, con ông E-vét nói, thì nổi giận. (31) Ông lập mưu sai sứ đến nói với A-vi-me-léc rằng: “Này, Ga-an, con của E-vét, và anh em y đã đến Si-khem và đang khích động thành này chống lại ông. (32) Vậy, đang đêm ông hãy trỗi dậy, và cùng với quân lính của ông mai phục ngoài đồng. (33) Rồi sáng sớm, lúc rạng đông, hãy mau lẹ tấn công thành. Khi y và đám người cùng đi với y ra đón ông, thì gặp chúng đâu ông hãy đánh đó.”
(34) Đang đêm, A-vi-me-léc cùng với quân lính của ông trỗi dậy, chia thành bốn nhóm mai phục gần Si-khem. (35) Ông Ga-an, con ông E-vét, đi ra và dừng lại ở lối vào cổng thành. A-vi-me-léc cùng với quân lính của ông từ chỗ mai phục trỗi dậy. (36) Ông Ga-an thấy đám dân thì nói với ông Dơ-vun: “Đây là đám dân từ các đỉnh núi xuống.” Nhưng ông Dơ-vun nói: “Đó là bóng núi mà ông lại trông ra như người ta.” (37) Ông Ga-an còn lên tiếng nói: “Đây là những người từ rốn đất mà xuống, còn nhóm kia thì từ con đường Cây Sồi Các Thầy Bói mà đến.” (38) Bấy giờ ông Dơ-vun nói với ông: “Đâu rồi cái miệng ngươi từng nói: A-vi-me-léc là ai mà chúng ta làm tôi nó? Đây chẳng phải là đám dân ngươi đã khinh dể sao? Bây giờ ngươi hãy đi ra mà giao chiến với nó.” (39) Ông Ga-an đi ra, dẫn đầu các thân hào Si-khem, giao chiến với A-vi-me-léc. (40) Nhưng A-vi-me-léc đuổi đánh ông, và ông Ga-an phải trốn chạy. Nhiều người gục chết trước khi tới được lối vào cổng. (41) Sau đó A-vi-me-léc cư ngụ ở A-ru-ma; còn ông Dơ-vun thì trục xuất ông Ga-an và anh em ông, không cho ở Si-khem nữa.
[SECTION] Triệt hạ thành và tháp Si-khem
(42) Hôm sau đám người kia đi ra cánh đồng, và người ta báo cho A-vi-me-léc biết. (43) Ông lấy dân của mình chia thành ba nhóm và sắp xếp một cuộc mai phục ngoài đồng. Ông nhìn, và này đám người kia đi ra khỏi thành; ông trỗi dậy tiến đánh chúng tơi bời. (44) A-vi-me-léc cùng với quân lính của ông ập tới chặn lối vào cổng thành, còn hai nhóm kia thì ập tới tất cả những kẻ ở ngoài đồng và đánh chúng tơi bời. (45) Suốt ngày hôm ấy A-vi-me-léc tấn công thành. Ông đã chiếm được thành và tàn sát tất cả dân cư, rồi triệt hạ và rắc muối lên thành. (46) Nghe tin đó, các thân hào Mích-đan Si-khem liền xuống hầm đền thờ En Bơ-rít. (47) Người ta báo tin cho A-vi-me-léc biết là tất cả thân hào Mích-đan Si-khem đã họp nhau lại. (48) Bấy giờ A-vi-me-léc lên núi Xan-môn cùng với tất cả quân lính của ông. Ông cầm rìu chặt một cành cây, giơ lên, rồi đặt xuống vai mình, và nói với quân lính của ông: “Các anh thấy tôi làm gì, thì cứ làm như tôi, mau lên!” (49) Mọi người đều chặt, mỗi người một cành cây. Họ đi theo A-vi-me-léc, đặt cành cây trên hầm, rồi nổi lửa đốt hầm, làm cho mọi người ở Mích-đan Si-khem chết hết, khoảng chừng một ngàn người, cả đàn ông lẫn đàn bà.
[SECTION] A-vi-me-léc tấn công Tê-vết và bị tử trận
(50) Sau đó A-vi-me-léc đi đến Tê-vết, đóng trại đối diện với Tê-vết và chiếm thành ấy. (51) Có một ngọn tháp kiên cố ở giữa thành và tất cả đàn ông, đàn bà cùng toàn thể các thân hào trong thành đều trốn vào tháp ấy; họ ẩn náu bên trong và leo lên lầu của ngọn tháp. (52) A-vi-me-léc đi tới và tấn công tháp; ông đến sát lối vào tháp để châm lửa đốt. (53) Bấy giờ một người đàn bà liệng một phiến đá cối xuống đầu A-vi-me-léc làm ông bể sọ. (54) Ông liền gọi chàng thanh niên cận vệ của mình và bảo: “Hãy tuốt gươm giết ta đi, kẻo người ta lại nói về ta rằng: Một người đàn bà đã giết hắn.” Người cận vệ đâm ông, và ông đã chết. (55) Người Ít-ra-en thấy A-vi-me-léc đã chết thì bỏ đi, ai nấy về nhà mình.
(56) Thế là Thiên Chúa đã báo oán A-vi-me-léc vì sự dữ ông đã gây cho thân phụ mình là giết bảy mươi người anh em. (57) Và Thiên Chúa đã báo oán những người Si-khem vì tất cả sự dữ họ đã gây ra. Như thế là đã ứng nghiệm nơi họ lời chúc dữ của Giô-tham, con ông Giơ-rúp-ba-an.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'tl', 10, '[PART] ÔNG GÍP-TÁC VÀ CÁC THỦ LÃNH NHỎ
[PART] 6. ÔNG TÔ-LA
(1) Sau A-vi-me-léc, có ông Tô-la con ông Pu-a, cháu ông Đô-đô, người Ít-xa-kha, đã xuất hiện để cứu Ít-ra-en. Ông cư ngụ tại Sa-mia, vùng núi Ép-ra-im. (2) Ông làm thủ lãnh Ít-ra-en được hai mươi ba năm, thì qua đời và được chôn cất tại Sa-mia.
[PART] 7. ÔNG GIA-IA
(3) Sau ông Tô-la, thì có ông Gia-ia, người Ga-la-át, xuất hiện, làm thủ lãnh Ít-ra-en hai mươi hai năm. (4) Ông có ba mươi người con, cỡi ba mươi con lừa và coi ba mươi thành, mà người ta đặt tên là Kha-vốt Gia-ia; những thành đó còn cho tới ngày nay trong đất Ga-la-át.
(5) Rồi ông Gia-ia qua đời và được chôn cất tại Ca-môn.
[PART] 8. ÔNG GÍP-TÁC
[SECTION] Ít-ra-en bị người Am-mon đàn áp
(6) Con cái Ít-ra-en lại làm điều dữ trái mắt ĐỨC CHÚA và làm tôi các thần Ba-an và Át-tô-rét, các thần của người A-ram, các thần của người Xi-đôn, các thần của người Mô-áp, các thần của con cái Am-mon và các thần của người Phi-li-tinh; họ đã lìa bỏ ĐỨC CHÚA và không làm tôi Người nữa. (7) ĐỨC CHÚA nổi cơn thịnh nộ với Ít-ra-en và đã trao họ vào tay người Phi-li-tinh và vào tay con cái Am-mon. (8) Trong thời ấy, suốt mười tám năm, chúng hành hạ và áp bức con cái Ít-ra-en, tức là toàn thể con cái Ít-ra-en ở bên kia sông Gio-đan, trong đất người E-mô-ri tại Ga-la-át. (9) Con cái Am-mon vượt sông Gio-đan để giao chiến với cả Giu-đa, Ben-gia-min và nhà Ép-ra-im nữa, khiến Ít-ra-en phải lâm cảnh khốn cùng. (10) Bấy giờ con cái Ít-ra-en mới kêu lên ĐỨC CHÚA rằng: “Chúng con đã xúc phạm đến Ngài, bởi vì chúng con đã lìa bỏ Thiên Chúa của chúng con mà làm tôi các Ba-an.” (11) ĐỨC CHÚA phán với con cái Ít-ra-en: “Khi người Ai-cập, người E-mô-ri, con cái Am-mon, người Phi-li-tinh, (12) người Xi-đôn, người A-ma-lếch và người Ma-đi-an áp bức các ngươi, và các ngươi kêu lên Ta, thì Ta đã chẳng cứu các ngươi khỏi tay chúng sao? (13) Nhưng các ngươi đã lìa bỏ Ta và làm tôi các thần khác; vì thế, Ta sẽ không cứu các ngươi nữa. (14) Đi mà kêu lên các thần các ngươi đã chọn; chúng sẽ cứu các ngươi lúc các ngươi bị cơ cực!” (15) Con cái Ít-ra-en mới thưa cùng ĐỨC CHÚA: “Chúng con đã phạm tội. Xin Ngài cứ xử với chúng con sao cho đẹp mắt Ngài; nhưng hôm nay xin cứu chúng con.” (16) Họ cất bỏ, không giữ lại những thần ngoại bang nữa, và họ làm tôi ĐỨC CHÚA, vì thế Người không dằn lòng được trước sự đau khổ của Ít-ra-en.
(17) Con cái Am-mon tập họp lại và đóng trại ở Ga-la-át. Con cái Ít-ra-en cũng hội lại và đóng trại ở Mít-pa. (18) Dân chúng và các thủ lãnh Ga-la-át nói với nhau: “Ai là người sẽ xung phong giao chiến với con cái Am-mon? Người ấy sẽ đứng đầu toàn thể dân cư Ga-la-át.”') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'tl', 11, '[SECTION] Ông Gíp-tác đặt điều kiện
(1) Ông Gíp-tác, người Ga-la-át, bấy giờ là một dũng sĩ. Ông là con của một gái điếm. Ông Ga-la-át sinh ra Gíp-tác. (2) Nhưng vợ ông Ga-la-át cũng sinh cho ông những người con khác nữa. Các người con của bà này khi lớn lên đã đuổi Gíp-tác đi, và nói với ông: “Mày không có phần gia nghiệp trong nhà của cha chúng tao, vì mày là con của một mụ khác.” (3) Ông Gíp-tác liền bỏ trốn, không ở với các anh nữa. Ông cư ngụ tại đất Tốp; những đứa vô lại kết đảng với ông Gíp-tác và cùng với ông tung hoành.
(4) Sau đó một thời gian, con cái Am-mon giao chiến với Ít-ra-en. (5) Và khi con cái Am-mon giao chiến với Ít-ra-en, thì các kỳ mục Ga-la-át đi tìm ông Gíp-tác ở đất Tốp. (6) Họ nói với ông Gíp-tác: “Xin ông đến chỉ huy chúng tôi giao chiến với con cái Am-mon.” (7) Ông Gíp-tác trả lời các kỳ mục Ga-la-át: “Nào chẳng phải chính các ông đã ghét tôi và đuổi tôi ra khỏi nhà cha tôi sao? Vì cớ gì bây giờ các ông lại đến với tôi, lúc các ông lâm cảnh khốn cùng?” (8) Các kỳ mục Ga-la-át nói với ông Gíp-tác: “Ấy vậy bây giờ chúng tôi mới phải quay về với ông; xin ông đến với chúng tôi, ông sẽ giao chiến với con cái Am-mon, sẽ thành người lãnh đạo chúng tôi, tức là toàn thể dân cư Ga-la-át.” (9) Ông Gíp-tác nói với các kỳ mục Ga-la-át: “Nếu các ông đưa tôi về để giao chiến với con cái Am-mon, và ĐỨC CHÚA trao chúng vào tay tôi, thì tôi sẽ là người lãnh đạo các ông.” (10) Các kỳ mục Ga-la-át nói với ông Gíp-tác: “Xin ĐỨC CHÚA chứng giám cho chúng ta, nếu chúng tôi không làm như lời ông nói.” (11) Rồi ông Gíp-tác cùng đi với các kỳ mục Ga-la-át, và dân đã đặt ông làm người lãnh đạo và chỉ huy họ; ông Gíp-tác lặp lại tất cả các lời ông đã nói, trước nhan ĐỨC CHÚA tại Mít-pa.
[SECTION] Ông Gíp-tác điều đình với con cái Am-mon
(12) Ông Gíp-tác sai sứ giả đến nói với vua dân Am-mon rằng: “Giữa tôi với ông có chuyện gì mà ông lại đến chống tôi, để giao chiến với xứ sở tôi?” (13) Vua dân Am-mon nói với các sứ giả của ông Gíp-tác: “Tại sao, khi lên khỏi Ai-cập, Ít-ra-en lại chiếm đất của ta, từ Ác-nôn cho tới Giáp-bốc và tới sông Gio-đan? Bây giờ muốn yên thì trả lại đi!” (14) Ông Gíp-tác lại sai sứ giả đến với vua dân Am-mon lần nữa (15) và thưa: “Ông Gíp-tác nói thế này: Ít-ra-en không chiếm đất của Mô-áp cũng như đất của con cái Am-mon, (16) vì khi đi lên khỏi Ai-cập, Ít-ra-en đã đi con đường sa mạc tới Biển Sậy và đã đến Ca-đê. (17) Bấy giờ Ít-ra-en sai sứ giả đến thưa với vua Ê-đôm rằng: Xin cho phép tôi đi qua đất của ngài. Nhưng vua Ê-đôm không nghe. Ít-ra-en cũng sai người đến với vua Mô-áp, nhưng ông này cũng chẳng nghe; Ít-ra-en đành lưu lại Ca-đê. (18) Sau đó, họ đã theo con đường sa mạc đi bọc xứ Ê-đôm và Mô-áp, tới phía đông đất Mô-áp, và đóng trại bên kia Ác-nôn, nhưng không vào biên giới Mô-áp vì Ác-nôn là biên giới Mô-áp. (19) Rồi Ít-ra-en sai sứ giả đến gặp ông Xi-khôn, vua dân E-mô-ri, trị vì tại Khét-bôn và thưa với ông: Xin cho phép tôi đi qua đất của ngài để tới nơi tôi phải đến. (20) Thế nhưng ông Xi-khôn đã không tin mà cho Ít-ra-en đi qua biên giới của ông; ông Xi-khôn lại còn triệu tập toàn dân, đóng trại tại Gia-hát và giao chiến với Ít-ra-en. (21) Và ĐỨC CHÚA, Thiên Chúa của Ít-ra-en, đã trao ông Xi-khôn và toàn dân của ông vào tay Ít-ra-en, và Ít-ra-en đã đánh chúng tơi bời. Rồi Ít-ra-en chiếm hết đất của dân E-mô-ri cư ngụ trên đất ấy. (22) Họ cũng chiếm tất cả các biên giới của người E-mô-ri từ Ác-nôn tới Giáp-bốc, và từ sa mạc tới sông Gio-đan. (23) Bây giờ ĐỨC CHÚA, Thiên Chúa của Ít-ra-en đã trục xuất người E-mô-ri khỏi Ít-ra-en dân của Người, thì liệu ông có trục xuất được nó không? (24) Cái mà thần Cơ-mốt của ông, ban cho ông làm sở hữu, ông lại không chiếm hữu sao? Cũng thế, tất cả những gì ĐỨC CHÚA, Thiên Chúa của chúng tôi đã truất hữu của những dân sở hữu, trước mặt chúng tôi, thì chúng tôi chiếm hữu. (25) Nay liệu ông có hơn gì ông Ba-lác, con ông Xíp-po, vua Mô-áp không? Ông ta có tranh chấp nổi với Ít-ra-en, hay là đánh bại được nó không? (26) Khi Ít-ra-en định cư tại Khét-bôn và các thị trấn phụ thuộc, tại A-rô-e và các thị trấn phụ thuộc, tại tất cả các thành nằm trên các nhánh của Ác-nôn đã ba trăm năm, thì tại sao lúc bấy giờ các người không chiếm lại? (27) Tôi đã không xúc phạm đến ông, còn ông đã xử tệ với tôi là giao chiến với tôi. Xin ĐỨC CHÚA, Đấng phán xét, hôm nay phân xử giữa con cái Ít-ra-en và con cái Am-mon.’” (28) Nhưng vua dân Am-mon không nghe những lời ông Gíp-tác sai người nói với vua.
[SECTION] Ông Gíp-tác khấn và thắng trận
(29) Thần khí của ĐỨC CHÚA ở trên ông Gíp-tác và ông đã sang Ga-la-át và Mơ-na-se, rồi qua Mít-pa Ga-la-át, và từ Mít-pa Ga-la-át ông qua đánh con cái Am-mon. (30) Ông Gíp-tác khấn hứa với ĐỨC CHÚA rằng: “Nếu Ngài trao con cái Am-mon vào tay con, (31) thì –khi con đã thắng con cái Am-mon mà trở về bình an– hễ người nào ra khỏi cửa nhà con để đón con, người đó sẽ thuộc về ĐỨC CHÚA, và con sẽ dâng nó làm lễ toàn thiêu.” (32) Ông Gíp-tác qua bên con cái Am-mon để giao chiến với chúng, và ĐỨC CHÚA đã trao chúng vào tay ông. (33) Ông đánh chúng tơi bời từ A-rô-e cho tới gần Min-nít, tất cả là hai mươi thành, và cho tới A-vên Cơ-ra-mim. Thật là một cuộc đại bại: con cái Am-mon bị hạ nhục trước mặt con cái Ít-ra-en.
(34) Khi ông Gíp-tác trở về Mít-pa, về nhà ông, thì này con gái ông ra đón ông, vừa đánh trống vừa nhảy múa. Cô là con gái độc nhất của ông: ngoài cô ra, ông không có con trai con gái nào khác. (35) Thoạt nhìn thấy cô, ông liền xé áo và nói: “Ôi, con gái của cha, thật con làm khổ cha rồi! Chính con lại ở trong số những kẻ gây bất hạnh cho cha! Cha đã trót mở miệng khấn hứa cùng ĐỨC CHÚA và không thể rút lại được.” (36) Cô thưa với ông: “Thưa cha, cha đã trót mở miệng khấn hứa cùng ĐỨC CHÚA, thì cha cứ thi hành cho con như lời cha đã khấn hứa, vì ĐỨC CHÚA đã cho cha trả thù được con cái Am-mon, kẻ thù của cha.” (37) Cô lại nói với cha: “Xin cha cho con điều này là hoãn cho con hai tháng để con đi lang thang trên các núi đồi, mà khóc cho đời con gái của con cùng với các bạn con.” (38) Ông nói: “Con cứ đi”, và ông để cho cô đi hai tháng. Cô ra đi cùng với các bạn, khóc cho đời con gái của cô trên các núi đồi. (39) Hết hai tháng, cô trở về với cha, và ông thi hành cho cô lời ông đã khấn hứa. Cô chưa biết đến việc vợ chồng. Và đã thành mọi tục lệ trong Ít-ra-en, là (40) hằng năm các cô gái Ít-ra-en đi khóc thương con gái ông Gíp-tác, người Ga-la-át, mỗi năm bốn ngày.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'tl', 12, '[SECTION] Chiến tranh giữa Ép-ra-im và Ga-la-át. Ông Gíp-tác qua đời.
(1) Người Ép-ra-im tập hợp lại, vượt sông tới Xa-phôn và nói với ông Gíp-tác: “Tại sao ông vượt sông đánh con cái Am-mon, mà lại không gọi chúng tôi cùng đi? Chúng tôi sẽ nổi lửa đốt nhà ông cho ông chết luôn!” (2) Ông Gíp-tác nói với họ: “Tôi và dân tôi phải tranh chấp ác liệt với con cái Am-mon. Tôi đã cầu cứu các người, mà các người đã chẳng cứu tôi khỏi tay chúng. (3) Tôi thấy không ai cứu, nên đã liều mạng vượt sông đánh con cái Am-mon, và ĐỨC CHÚA đã trao tay chúng vào tay tôi. Vậy tại sao hôm nay các người lại lên gây chiến với tôi?” (4) Ông Gíp-tác tập hợp tất cả các người Ga-la-át và giao chiến với Ép-ra-im. Người Ga-la-át đánh Ép-ra-im tơi bời, vì Ép-ra-im đã nói: “Này quân Ga-la-át! Tụi bay chỉ là người Ép-ra-im đào thoát, ăn bám cả Ép-ra-im lẫn Mơ-na-se.” (5) Ga-la-át chiếm giữ các khúc cạn trên sông Gio-đan, nơi Ép-ra-im có thể qua. Khi có người Ép-ra-im đào thoát nói: “Cho tôi qua”, thì những người Ga-la-át hỏi: “Anh có phải là người Ép-ra-im không?” Nếu hắn đáp: “Không”, (6) thì họ bảo: “Hãy nói: Síp-bô-lét.” Nếu hắn nói: “Xíp-bô-lét”, vì hắn không nói đúng được, thì bấy giờ họ bắt lấy hắn mà giết, gần khúc cạn trên sông Gio-đan. Thời gian đó, bốn mươi hai ngàn người Ép-ra-im đã ngã gục.
(7) Ông Gíp-tác làm thủ lãnh Ít-ra-en sáu năm, rồi ông Gíp-tác, người Ga-la-át, qua đời và được chôn cất trong thành của mình, ở Ga-la-át.
[PART] 9. ÔNG ÍP-XAN
(8) Sau ông Gíp-tác, thì có ông Íp-xan, người Bê-lem, làm thủ lãnh Ít-ra-en. (9) Ông có ba mươi người con trai và ba mươi người con gái. Ông gả các cô cho người ngoại bang, và hỏi ba mươi người vợ cho các con trai ông, cũng người ngoại bang. Ông làm thủ lãnh Ít-ra-en bảy năm. (10) Rồi ông Íp-xan qua đời và được chôn cất tại Bê-lem.
[PART] 10. ÔNG Ê-LÔN
(11) Sau ông Íp-xan, thì có ông Ê-lôn, người Dơ-vu-lun, làm thủ lãnh Ít-ra-en. Ông làm thủ lãnh mười năm. (12) Rồi ông Ê-lôn, người Dơ-vu-lun, qua đời và được chôn cất tại Ai-gia-lôn, trong đất Dơ-vu-lun.
[PART] 11. ÔNG ÁP-ĐÔN
(13) Sau ông Ê-lôn, thì có ông Áp-đôn, con ông Hi-lên, người Pia-a-thôn, làm thủ lãnh Ít-ra-en. (14) Ông có bốn mươi con trai và ba mươi cháu trai, cỡi bảy mươi con lừa. Ông làm thủ lãnh Ít-ra-en tám năm. (15) Rồi ông Áp-đôn, con ông Hi-lên, người Pia-a-thôn, qua đời và được chôn cất tại Pia-a-thôn, trong đất Ép-ra-im, trên núi của người A-ma-lếch.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'tl', 13, '[PART] 12. ÔNG SAM-SÔN
[SECTION] Truyền tin ông Sam-sôn ra đời
(1) Con cái Ít-ra-en lại làm sự dữ trái mắt ĐỨC CHÚA, và ĐỨC CHÚA đã trao họ vào tay người Phi-li-tinh bốn mươi năm.
(2) Có một người đàn ông ở Xo-rơ-a, thuộc chi tộc Đan, tên là Ma-nô-ác. Vợ ông son sẻ và không sinh con. (3) Sứ giả của ĐỨC CHÚA hiện ra với người vợ và nói với bà: “Này, bà là người son sẻ và không sinh con, nhưng bà sẽ có thai và sinh một con trai. (4) Vậy bây giờ phải kiêng cữ: đừng uống rượu và thức có men, cũng đừng ăn mọi thứ không thanh sạch. (5) Vì này bà sẽ có thai và sinh một con trai. Dao cạo sẽ không được lướt trên đầu nó, vì con trẻ sẽ là một na-dia của Thiên Chúa từ lòng mẹ. Chính nó sẽ bắt đầu cứu Ít-ra-en khỏi tay người Phi-li-tinh.” (6) Bà đi vào và nói với chồng rằng: “Một người của Thiên Chúa đã đến gặp tôi; hình dáng của người như hình dáng một sứ giả của Thiên Chúa, rất đáng sợ. Tôi đã không dám hỏi người từ đâu tới; và danh tánh người, người cũng không tiết lộ cho tôi. (7) Nhưng người nói với tôi: ‘Này bà sẽ có thai và sẽ sinh một con trai; bây giờ bà phải kiêng cữ: đừng uống rượu và thức có men, cũng đừng ăn mọi thứ không thanh sạch, vì con trẻ ấy sẽ là một na-dia của Thiên Chúa, từ lòng mẹ cho đến ngày nó chết.’”
[SECTION] Thiên sứ hiện ra lần thứ hai
(8) Ông Ma-nô-ác khẩn cầu ĐỨC CHÚA, ông nói: “Thưa Ngài, xin vui lòng cho người của Thiên Chúa mà Ngài đã sai, đến với chúng con một lần nữa, và dạy chúng con phải làm gì cho đứa trẻ sẽ sinh ra.” (9) Thiên Chúa nghe tiếng ông Ma-nô-ác, và sứ giả của ĐỨC CHÚA lại đến gặp vợ ông, lúc bà đang ở ngoài đồng, khi ông Ma-nô-ác, chồng bà, không có mặt ở đó. (10) Bà vội vã chạy đi báo cho chồng, và nói với ông: “Này người đã gặp tôi hôm trước, lại hiện ra với tôi nữa.” (11) Ông Ma-nô-ác đứng dậy đi theo vợ, đến gặp người kia và nói: “Ngài có phải là người đã nói với bà này không?” Người ấy đáp: “Chính tôi.” (12) Ông Ma-nô-ác nói: “Khi xảy ra như ngài nói, thì đứa bé phải giữ luật nào, và nó phải làm gì?” (13) Sứ giả của ĐỨC CHÚA nói với ông Ma-nô-ác: “Tất cả những điều tôi đã nói với bà ấy thì bà ấy phải giữ. (14) Tất cả những gì bởi cây nho mà ra, thì bà không được ăn, cũng không được uống rượu và thức có men; tất cả những gì không thanh sạch, thì bà không được ăn. Mọi điều tôi đã truyền, thì bà phải tuân giữ.” (15) Ông Ma-nô-ác thưa với sứ giả của ĐỨC CHÚA: “Xin cho phép chúng tôi giữ ngài lại và dọn hầu ngài một con dê tơ!” (16) Sứ giả của ĐỨC CHÚA nói với ông Ma-nô-ác: “Ông có giữ tôi lại, tôi cũng chẳng ăn bánh của ông; nhưng nếu ông dọn lễ toàn thiêu kính ĐỨC CHÚA, thì ông hãy dâng lên Người đi”, vì ông Ma-nô-ác không biết người ấy là sứ giả của ĐỨC CHÚA. (17) Bấy giờ ông Ma-nô-ác nói với sứ giả của ĐỨC CHÚA: “Xin ngài cho biết quý danh, để khi xảy ra như ngài nói, chúng tôi sẽ trọng đãi ngài!” (18) Sứ giả của ĐỨC CHÚA nói với ông: “Sao ông lại hỏi tên tôi? Đó là một điều bí nhiệm.” (19) Bấy giờ ông Ma-nô-ác bắt một con dê tơ và lấy tế phẩm, để dâng làm lễ toàn thiêu trên tảng đá kính ĐỨC CHÚA, Đấng đã thực hiện những kỳ công, rồi ông Ma-nô-ác và bà vợ đứng nhìn. (20) Khi ngọn lửa từ bàn thờ bốc lên trời, thì sứ giả của ĐỨC CHÚA cũng lên theo trong ngọn lửa của bàn thờ, trước sự chứng kiến của ông Ma-nô-ác và vợ ông; họ phục lạy sát đất. (21) Sứ giả của ĐỨC CHÚA không hiện ra với ông Ma-nô-ác và vợ ông nữa. Bấy giờ ông Ma-nô-ác mới biết vị đó chính là sứ giả của ĐỨC CHÚA. (22) Ông Ma-nô-ác liền nói với vợ: “Chúng ta chết mất thôi, vì đã thấy Thiên Chúa.” (23) Nhưng vợ ông nói với ông: “Nếu ĐỨC CHÚA có ý định giết chúng ta, thì Người đã chẳng nhận lễ toàn thiêu và tế phẩm từ tay chúng ta, đã chẳng cho chúng ta thấy tất cả những điều ấy, và mới đây đã chẳng cho chúng ta nghe một điều như thế.” (24) Bà sinh được một con trai và đặt tên là Sam-sôn. Đứa bé lớn lên, và ĐỨC CHÚA chúc lành cho nó. (25) Thần khí ĐỨC CHÚA bắt đầu tác động trên Sam-sôn tại Trại Đan giữa Xo-rơ-a và Ét-ta-ôn.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'tl', 14, '[SECTION] Ông Sam-sôn kết hôn
(1) Ông Sam-sôn xuống Tim-na và để ý đến một phụ nữ trong số các con gái của người Phi-li-tinh tại Tim-na. (2) Ông trở lên và báo cho cha mẹ rằng: “Con đã để ý đến một phụ nữ trong số con gái của người Phi-li-tinh tại Tim-na. Vậy xin cha mẹ cưới cô ấy cho con.” (3) Cha ông cũng như mẹ ông nói: “Trong số con gái của bà con mày và trong tất cả dân tao, không có phụ nữ hay sao mà mày lại đi lấy vợ trong đám người Phi-li-tinh không cắt bì ấy?” Nhưng ông Sam-sôn trả lời cha: “Xin cha cứ cưới cô ấy cho con, vì nàng vừa mắt con.” (4) Cha mẹ ông không biết rằng việc đó là do ĐỨC CHÚA xui khiến, bởi lẽ Người đang tìm cớ cho người Phi-li-tinh gây chuyện, vì thời ấy người Phi-li-tinh đang đô hộ Ít-ra-en.
(5) Ông Sam-sôn xuống Tim-na, và khi ông tới các vườn nho ở Tim-na, thì này một con sư tử con rống lên và chồm ra phía ông. (6) Bấy giờ thần khí của ĐỨC CHÚA ập xuống trên ông; ông dùng tay không xé nó ra như xé một con dê con; nhưng ông không cho cha mẹ hay việc ông đã làm. (7) Sau đó ông xuống chuyện trò với người phụ nữ và nàng vừa mắt Sam-sôn. (8) Ít lâu sau, ông trở lại cưới nàng. Ông rẽ qua để xem xác chết con sư tử, thì này có một đàn ong đậu trong bộ xương con sư tử và cả mật nữa. (9) Ông móc ra và cầm trong tay, vừa đi vừa ăn. Rồi khi về nhà, ông biếu cha mẹ và cha mẹ ông cũng ăn. Nhưng ông không cho cha mẹ biết là ông đã móc mật ong từ bộ xương con sư tử. (10) Sau đó cha ông đã xuống gặp người phụ nữ và tại đó ông Sam-sôn làm một bữa tiệc, vì các trai tráng vẫn làm như thế. (11) Khi thấy ông, người ta đã cử ba mươi người trong số bạn hữu để ở với ông.
[SECTION] Ông Sam-sôn ra câu đố
(12) Ông Sam-sôn nói với họ: “Tôi ra cho các anh một câu đố. Nếu trong bảy ngày tiệc, các anh giải được câu đố ấy và tìm ra câu đáp, thì tôi sẽ tặng các anh ba mươi chiếc áo lụa quý và ba mươi chiếc khác để thay. (13) Nếu các anh không giải được, thì các anh phải cho tôi ba mươi chiếc áo lụa quý và ba mươi chiếc khác để thay.” Họ nói với ông: “Anh ra câu đố đi; chúng tôi nghe đây!” (14) Ông liền nói với họ:
“Thức ăn xuất tự người dùng,
ngọt ngào xuất tự sức hùng, là chi?”
Nhưng sau ba ngày họ vẫn không giải được câu đố.
(15) Ngày thứ tư họ nói với vợ ông Sam-sôn: “Hãy dụ chồng chị để anh ấy giải nghĩa câu đố cho chúng tôi, nếu không, chúng tôi sẽ nổi lửa đốt cả chị lẫn nhà cha chị. Có phải để bóc lột chúng tôi mà các người đã mời chúng tôi tới đây hay không?” (16) Vợ ông Sam-sôn khóc tỉ tê bên ông. Nàng nói: “Anh chỉ có ghét em thôi, chẳng yêu em chút nào. Anh ra câu đố cho đồng bào em, mà lại không giải cho em.” Ông nói với nàng: “Này, cha mẹ anh, anh cũng còn không giải cho, huống chi là em!” (17) Nhưng nàng khóc tỉ tê bên ông suốt bảy ngày tiệc. Ngày thứ bảy ông đã giải nghĩa cho nàng, vì nàng quấy rầy ông; và nàng giải câu đố cho đồng bào mình.
(18) Ngày thứ bảy, trước khi mặt trời lặn, người trong thành nói với ông:
“Cái gì ngọt quá mật ong,
khỏe hơn sư tử thì ông chịu hàng!”
Ông bảo họ:
“Không cày với bò cái của ta,
tụi bay đã chẳng tìm ra câu này!”
(19) Bấy giờ thần khí của ĐỨC CHÚA ập xuống trên ông; ông liền xuống Át-cơ-lôn và giết ba mươi người trong bọn họ, lột áo của những người ấy, rồi trao những áo để thay cho những kẻ đã giải được câu đố. Ông bừng bừng nổi giận trở về nhà cha ông. (20) Còn vợ của ông Sam-sôn, thì được gán cho một người đã làm phù rể cho ông.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'tl', 15, '[SECTION] Ông Sam-sôn đốt mùa màng của người Phi-li-tinh
(1) Ít lâu sau, vào mùa gặt lúa miến, ông Sam-sôn mang một con dê tơ đến thăm vợ. Ông nói: “Tôi muốn vào phòng ngủ của vợ tôi”; nhưng bố vợ không cho ông vào. (2) Bố vợ nói: “Thật sự tôi tưởng là anh đã chán ghét nó, nên tôi đã trao nó cho người đã làm phù rể cho anh. Con em nó lại chẳng khá hơn nó sao? Vậy để con em thay cho chị nó đi!” (3) Ông Sam-sôn nói với họ: “Lần này thì tôi vô tội đối với người Phi-li-tinh, nếu tôi làm hại chúng.” (4) Ông Sam-sôn đi bắt ba trăm con chó sói; lấy đuốc, rồi cột ngược đuôi con này với đuôi con kia và buộc một chiếc đuốc giữa hai đuôi. (5) Ông châm lửa vào đuốc và lùa sói vào đồng lúa chín của người Phi-li-tinh, thiêu rụi từ gốc rạ cho đến bông lúa, thiêu cả nho và ô-liu nữa.
(6) Người Phi-li-tinh hỏi: “Ai đã làm chuyện này?” Và người ta đáp: “Đó là Sam-sôn, con rể của ông người Tim-na, vì ông ấy đã đem vợ hắn gán cho người phù rể của hắn.” Những người Phi-li-tinh đi lên, nổi lửa đốt cả nàng lẫn cha nàng. (7) Ông Sam-sôn nói với họ: “Vì chúng bay đã làm như thế, thì tao sẽ trả thù cho được mới thôi.” (8) Ông đánh cho chúng một trận tơi bời, khiến chúng bị thảm bại. Rồi ông xuống ở trong một hốc đá tại Ê-tham.
[SECTION] Hàm lừa
(9) Người Phi-li-tinh lên đóng trại ở Giu-đa và tràn ra tới Le-khi.
(10) Người Giu-đa nói với chúng: “Tại sao các anh lại lên chống chúng tôi?” Chúng đáp; “Để bắt trói Sam-sôn; chúng tôi lên để xử với hắn như hắn đã xử với chúng tôi.” (11) Ba ngàn người Giu-đa xuống hốc đá ở Ê-tham, nói với ông Sam-sôn: “Ông không biết là người Phi-li-tinh đang đô hộ chúng ta sao? Ông đã làm gì cho chúng tôi thế?” Ông trả lời họ: “Chúng xử với tôi làm sao, tôi cũng xử với chúng như vậy!” (12) Họ nói: “Chúng tôi xuống bắt trói và nộp ông cho người Phi-li-tinh!” Ông Sam-sôn nói với họ: “Các anh phải thề với tôi là chính các anh sẽ không đập chết tôi.” (13) Họ đáp: “Chúng tôi chỉ bắt trói và nộp ông cho chúng thôi; chứ giết ông thì chúng tôi không giết.” Rồi họ dùng hai chiếc dây thừng mới mà trói ông và xốc ông lên khỏi hốc đá.
(14) Ông vào đến Le-khi, thì người Phi-li-tinh reo hò ra đón ông. Bấy giờ khi thần khí của ĐỨC CHÚA ập xuống trên ông, thì những chiếc dây thừng trên cánh tay ông tựa như những sợi chỉ cháy xèo trong lửa và dây cột tay ông đều tuột xuống. (15) Vớ được một hàm lừa còn tươi, ông đưa tay lượm lấy và dùng nó đánh chết một ngàn người. (16) Ông Sam-sôn nói:
“Với một hàm lừa ta đã giết chúng từng đống,
với một hàm lừa ta đánh chết cả ngàn tên.”
(17) Nói xong ông liệng chiếc hàm khỏi tay, và gọi nơi ấy là Ra-mát Le-khi. (18) Ông khát quá, nên kêu cầu ĐỨC CHÚA rằng: “Ngài là Đấng đã dùng tay tôi tớ Ngài thực hiện cuộc chiến thắng vĩ đại này, mà chẳng lẽ giờ đây con lại phải chết khát và rơi vào tay những kẻ không cắt bì?” (19) Bấy giờ Thiên Chúa xẻ khe đá ở Le-khi, nước liền vọt ra; ông uống, thấy hồi sức và tỉnh táo lại. Bởi thế người ta gọi nơi ấy là Ên Ha Cô-rê; suối ấy vẫn còn ở Le-khi cho tới ngày nay. (20) Ông Sam-sôn làm thủ lãnh Ít-ra-en hai mươi năm trong thời người Phi-li-tinh cai trị.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'tl', 16, '[SECTION] Chuyện xảy ra ở cổng thành Ga-da
(1) Ông Sam-sôn đến Ga-da. Tại đây ông gặp một cô điếm và đi với cô. (2) Người ta báo cho những người Ga-da rằng: “Sam-sôn đã tới đây.” Họ liền bao vây và rình ông suốt đêm ấy ở cổng thành. Họ ở yên suốt đêm mà rằng: “Đợi đến tảng sáng, ta sẽ giết hắn.” (3) Nhưng ông Sam-sôn nằm ngủ tới nửa đêm, và giữa đêm ông trỗi dậy, nắm lấy cánh cổng thành cùng với hai cây cột, nhổ luôn cả then ngang, rồi vác lên vai, đi trên đỉnh núi đối diện với Khép-rôn.
[SECTION] Ông Sam-sôn bị Đa-li-la phản trắc
(4) Sau đó ông phải lòng một phụ nữ tên là Đa-li-la, ở thung lũng Xô-rếch. (5) Các vương hầu Phi-li-tinh lên gặp cô ta. Họ nói với nàng: “Cô hãy dụ hắn xem bởi đâu hắn có sức mạnh như thế, và chúng tôi phải dùng cách nào mới trị được hắn, trói làm sao mới khống chế được hắn, rồi mỗi người chúng tôi sẽ cho cô một ngàn mốt bạc.”
(6) Đa-li-la nói với ông Sam-sôn: “Nào cho em biết, em xin anh: bởi đâu anh có sức mạnh như thế? Trói làm sao mới khống chế anh được?” (7) Ông Sam-sôn đáp: “Nếu trói anh bằng bảy dây cung mới, chưa phơi khô, thì anh sẽ mất sức và trở nên như bất cứ một người nào khác.” (8) Các vương hầu Phi-li-tinh đem đến cho nàng bảy dây cung mới chưa phơi khô; nàng dùng các dây ấy trói ông lại, (9) đang khi cho người rình sẵn trong phòng. Nàng nói với ông: “Này anh Sam-sôn! Quân Phi-li-tinh đấy!” Ông liền giật đứt các dây cung như sợi đay đứt khi đụng vào lửa. Thế là sức mạnh của ông không bị tiết lộ.
(10) Bấy giờ Đa-li-la nói với ông Sam-sôn: “Anh chỉ xí gạt em thôi, toàn nói xạo không à! Bây giờ hãy cho em biết, em xin anh: phải dùng cái gì mới trói được anh?” (11) Ông nói với nàng: “Nếu trói chặt anh bằng những dây thừng mới, chưa dùng vào việc gì, thì anh sẽ mất sức và trở nên như bất cứ một người nào khác.” (12) Đa-li-la liền lấy những dây thừng mới, trói ông lại, rồi nói: “Này anh Sam-sôn, quân Phi-li-tinh đấy!” Đang khi cho người rình sẵn trong phòng. Nhưng ông đã giựt bung các dây thừng đó khỏi cánh tay như giựt một sợi chỉ.
(13) Đa-li-la lại nói với ông Sam-sôn: “Đến bây giờ mà anh vẫn còn xí gạt em, toàn nói xạo không à! Hãy cho em biết phải dùng cái gì mới trói được anh!” Ông nói với nàng: “Nếu em kết tóc trên đầu anh thành bảy bím, rồi cột vào dây thừng của khung dệt, đóng cọc siết cho chặt, thì anh sẽ mất sức và trở nên như bất cứ người nào khác.” (14) Vậy nàng làm cho ông ngủ, đoạn kết tóc trên đầu ông thành bảy bím rồi cột vào dây thừng của khung dệt và đóng cọc siết cho chặt. Nàng nói với ông: “Này anh Sam-sôn, quân Phi-li-tinh đấy!” Ông tỉnh giấc và bứng cả cọc, cả khung dệt, lẫn dây thừng của khung dệt.
(15) Nàng lại nói với ông: “Làm sao anh nói là anh yêu em, trong khi anh không thật lòng với em? Đây là lần thứ ba anh xí gạt em và không tỏ cho em biết: bởi đâu anh có sức mạnh như thế?” (16) Vì ngày nào nàng cũng dùng hết lời lẽ mà nài ép và làm khổ ông, khiến ông héo hắt đến chết được, (17) ông thổ lộ hết tâm can với nàng, và nói: “Dao cạo chưa hề đụng đến đầu anh, vì anh là một na-dia của Thiên Chúa từ lúc còn trong lòng mẹ. Nếu anh bị cạo đầu thì anh sẽ mất sức ngay, trở nên yếu nhược và như mọi người khác.” (18) Đa-li-la thấy rằng ông đã thổ lộ hết tâm can với nàng, liền sai người đi gọi các vương hầu Phi-li-tinh và nói: “Lần này các ông hãy lên, vì anh ấy đã thổ lộ hết tâm can với tôi.” Các vương hầu Phi-li-tinh liền lên gặp nàng, mang sẵn bạc trong tay. (19) Vậy nàng làm cho ông ngủ trên đầu gối mình, rồi kêu người cạo bảy bím tóc trên đầu ông; nàng bắt đầu khống chế ông, và ông đã mất sức. (20) Nàng nói: “Này anh Sam-sôn, quân Phi-li-tinh đấy!” Ông tỉnh giấc và nói: “Mình sẽ bung ra như mọi lần và lại thoát thôi.” Nhưng ông đâu có biết: ĐỨC CHÚA không còn ở với ông nữa. (21) Quân Phi-li-tinh bắt lấy ông, móc mắt và giải ông xuống Ga-da. Chúng chập xích đồng lại, cột ông và bắt ông kéo cối xay trong nhà tù.
[SECTION] Ông Sam-sôn trả thù rồi chết
(22) Nhưng rồi từ cái đầu bị cạo trọc, tóc ông lại mọc ra. (23) Các vương hầu Phi-li-tinh họp lại để long trọng tế thần Đa-gôn của chúng và ăn mừng. Chúng nói:
“Thần của ta đã trao vào tay ta tên Sam-sôn, kẻ thù của ta.”
(24) Khi nhìn thấy ông, dân chúng reo hò tung hô thần của chúng và nói:
“Thần của ta đã trao vào tay ta tên Sam-sôn, kẻ thù của ta,
kẻ tàn phá xứ sở ta, kẻ tăng thêm số tử vong của ta.”
(25) Trong khi lòng hả hê, chúng nói: “Hãy gọi Sam-sôn ra làm trò tiêu khiển cho chúng ta!” Vậy chúng kêu ông Sam-sôn từ nhà tù đến; và ông làm trò tiêu khiển trước mặt chúng. Rồi chúng đặt ông đứng giữa các cột. (26) Bấy giờ ông Sam-sôn nói với cậu thiếu niên đang dắt tay ông: “Cậu dẫn tôi đi và cho tôi sờ vào các cột cái chống đỡ tòa nhà, để tôi dựa lưng.” (27) Tòa nhà lúc đó đầy chật đàn ông đàn bà. Tất cả các vương hầu Phi-li-tinh đều ở đó, và trên sân thượng có khoảng ba ngàn đàn ông đàn bà đang coi ông Sam-sôn làm trò tiêu khiển. (28) Ông Sam-sôn kêu cầu ĐỨC CHÚA và thưa: “Lạy ĐỨC CHÚA là Chúa Thượng của con, xin nhớ đến con và ban sức cho con lần này nữa thôi, ôi lạy Thiên Chúa, để chỉ đánh một trận là con trả thù được quân Phi-li-tinh đã móc mắt con.” (29) Bấy giờ ông Sam-sôn rờ vào hai chiếc cột ở giữa, là những cột cái chống đỡ tòa nhà, và ông tì vào các cột ấy, tay mặt bên này, tay trái bên kia. (30) Rồi ông Sam-sôn nói: “Đành chết với bọn Phi-li-tinh vậy!” Đoạn ông dùng sức đẩy mạnh, và tòa nhà sụp đổ đè các vương hầu và tất cả dân chúng có mặt ở đó. Thành ra số người ông giết được khi ông chết lại đông hơn số người ông đã giết được khi còn sống. (31) Anh em ông và cả nhà cha ông xuống đưa ông về chôn cất giữa Xo-rơ-a và Ét-ta-ôn trong phần mộ ông Ma-nô-ác, cha ông. Ông làm thủ lãnh Ít-ra-en được hai mươi năm.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'tl', 17, '[PART] PHỤ LỤC
[PART] 1. NHÀ THỜ CỦA ÔNG MI-KHA VÀ NHÀ THỜ CỦA HỌ ĐAN
[SECTION] Nhà thờ tư của ông Mi-kha
(1) Xưa có một người thuộc vùng núi Ép-ra-im, tên là Mi-kha-giơ-hu. (2) Ông thưa với bà mẹ: “Số bạc một ngàn một trăm thỏi mà người ta đã lấy mất của mẹ, khiến mẹ chửi rủa và mẹ cũng đã nói cho con nghe, thì này số bạc đó, con đang giữ đây; chính con đã lấy đó.” Mẹ ông liền nói: “Xin ĐỨC CHÚA chúc lành cho con tôi!” (3) Ông trả lại mẹ ông số bạc một ngàn một trăm thỏi, nhưng mẹ ông nói: “Chính tay mẹ đã dâng hiến trọn số bạc này cho ĐỨC CHÚA, để con của mẹ dùng làm một tượng, một hình đúc bằng kim khí. Vậy bây giờ mẹ đưa lại cho con.”
(4) Nhưng ông trả số bạc lại cho mẹ. Mẹ ông giữ lấy hai trăm thỏi, rồi trao cho thợ đúc, người này làm một tượng, một hình đúc, đặt tại nhà ông Mi-kha-giơ-hu. (5) Ông Mi-kha này có một nhà thờ; ông đã làm một ê-phốt và các te-ra-phim, rồi phong cho một người trong các con làm tư tế cho ông. (6) Thời đó Ít-ra-en không có vua, ai muốn làm gì thì làm.
(7) Có một thanh niên, người Bê-lem Giu-đa, thuộc chi tộc Giu-đa. Anh là một thầy Lê-vi ở đó như khách trú. (8) Người ấy đi khỏi thành Bê-lem Giu-đa để tìm chỗ cư trú. Trên đường đi, anh vào vùng núi Ép-ra-im đến nhà ông Mi-kha. (9) Ông Mi-kha nói với anh: “Anh từ đâu tới?” Anh nói với ông: “Tôi là một người Lê-vi thuộc Bê-lem Giu-đa; tôi đi tìm chỗ cư trú.” (10) Ông Mi-kha nói với anh: “Xin ở lại đây với tôi, để làm sư phụ và tư tế cho tôi. Phần tôi, mỗi năm tôi sẽ cung cấp cho anh mười thỏi bạc, áo mặc và lương thực cần dùng.” (11) Thầy Lê-vi đồng ý ở lại với ông; người trẻ tuổi ấy được ông coi như một trong các con ông. (12) Ông Mi-kha phong cho thầy Lê-vi làm tư tế; người trẻ tuổi ấy trở thành tư tế của ông và ở trong nhà ông Mi-kha. (13) Ông Mi-kha nói: “Bây giờ tôi biết ĐỨC CHÚA sẽ phù hộ tôi vì tôi đã có một thầy Lê-vi làm tư tế.”') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'tl', 18, '[SECTION] Những người thuộc chi tộc Đan đi kiếm đất
(1) Thời ấy Ít-ra-en không có vua. Cũng thời ấy chi tộc Đan đang tìm đất làm gia nghiệp để định cư, vì cho tới ngày đó họ không được lãnh phần gia nghiệp riêng giữa các chi tộc Ít-ra-en. (2) Vậy con cái Đan sai năm người dũng cảm trong thị tộc của họ, ra khỏi ranh giới Xo-rơ-a và Ét-ta-ôn, rảo quanh khắp xứ để do thám. Họ nói với những người này: “Các anh hãy đi do thám đất đai.” Năm người đi vào vùng núi Ép-ra-im. Đến gần nhà ông Mi-kha và qua đêm tại đây. (3) Vì họ ở cạnh nhà ông Mi-kha, nên đã nhận ra tiếng của chàng thanh niên Lê-vi; họ đã rẽ qua đó và nói với anh: “Ai đã bảo anh tới đây? Anh làm gì ở đây? Chuyện gì đã xảy ra cho anh tại đây?” (4) Anh trả lời họ: “Ông Mi-kha đã làm cho tôi thế này thế này: ông đã thuê tôi và tôi đã trở thành tư tế của ông.” (5) Họ nói với anh: “Xin anh thỉnh vấn Thiên Chúa cho chúng tôi biết công cuộc chúng tôi đang theo đuổi có thành tựu hay không.” (6) Thầy tư tế bảo họ: “Các anh cứ đi bình an; ĐỨC CHÚA để mắt nhìn xem công cuộc các anh đang theo đuổi.”
(7) Năm người ấy ra đi. Họ vào La-gít và thấy dân chúng ở đây an cư lạc nghiệp theo kiểu người Xi-đôn, yên lành và an tâm, không thiếu hụt gì trong xứ. Dân chúng thừa hưởng của cải, lại ở xa người Xi-đôn, và không có chuyện gì với ai cả. (8) Năm người ấy trở về với anh em ở Xo-rơ-a và Ét-ta-ôn. Anh em họ hỏi: “Thế nào?” (9) Họ đáp: “Đứng lên! Chúng ta hãy lên đánh chúng! Vì chúng tôi đã thấy xứ đó: Thật là tuyệt vời! Thế mà các anh cứ điềm nhiên! Đừng chần chừ nữa: đi đi, vào chiếm lấy xứ ấy! (10) Tới nơi các anh sẽ gặp một dân yên lành, một xứ mênh mông bốn bề bát ngát. Chắc chắn là Thiên Chúa đã trao đất ấy vào tay các anh: Đó là một nơi không thiếu hụt gì trên mặt đất.”
[SECTION] Cuộc di dân của họ Đan
(11) Vậy một số người thuộc chi tộc Đan, là sáu trăm người được vũ trang để chiến đấu, đã rời khỏi nơi ấy, từ Xo-rơ-a và từ Ét-ta-ôn. (12) Họ tiến lên đóng trại tại Kia-giát Giơ-a-rim miền Giu-đa. Bởi thế người ta gọi nơi ấy là Trại Đan cho tới ngày nay. Nơi ấy ở phía tây Kia-giát Giơ-a-rim. (13) Từ đấy họ qua vùng núi Ép-ra-im và đến tận nhà ông Mi-kha.
(14) Năm người đã đi thăm dò đất La-gít lên tiếng nói với anh em họ: “Các anh biết không? Trong các ngôi nhà đó có một ê-phốt, mấy te-ra-phim, một tượng, một hình đúc bằng kim khí. Vậy bây giờ các anh nghĩ xem phải làm gì.” (15) Họ rẽ qua hướng đó, vào nhà thầy Lê-vi trẻ tuổi, trong nhà ông Mi-kha, và chào hỏi thầy, (16) đang khi sáu trăm người trong số con cái họ Đan, được vũ trang để chiến đấu, chực sẵn ở ngưỡng cửa. (17) Năm người đã đi thăm dò đất và đã vào đấy, liền lấy tượng, ê-phốt, te-ra-phim và hình đúc bằng kim khí đang khi thầy tư tế chực sẵn ở ngưỡng cửa cùng với sáu trăm người được vũ trang để chiến đấu. (18) Vậy những người ấy đã vào nhà ông Mi-kha lấy tượng, ê-phốt, te-ra-phim và hình đúc bằng kim khí. Nhưng thầy tư tế nói với họ: “Các anh làm gì thế?” (19) Họ bảo thầy: “Im! Lấy tay bịt miệng lại và đi theo chúng tôi, thầy sẽ là sư phụ và tư tế của chúng tôi. Thầy làm tư tế cho gia đình của một người hơn là cho cả một chi tộc và một thị tộc trong Ít-ra-en sao?” (20) Thầy tư tế, lòng đầy phấn khởi, liền cầm lấy ê-phốt, te-ra-phim và hình đúc bằng kim khí, rồi nhập đoàn với họ.
(21) Họ lui gót ra đi. Họ để đàn bà, con trẻ, súc vật và hành lý đi trước. (22) Khi những người ấy đã đi xa nhà ông Mi-kha, thì hàng xóm láng giềng của ông Mi-kha tri hô lên, và rượt theo con cái Đan. (23) Họ gọi theo con cái Đan; những người này quay lại, nói với ông Mi-kha: “Chuyện gì mà ông la ó thế?” (24) Ông trả lời: “Các ngươi đánh cắp tượng thần ta đã làm, lại còn rước cả tư tế đi, thì ta còn gì nữa? Vậy mà còn hỏi ‘Chuyện gì thế’, thế là thế nào?” (25) Con cái Đan đáp: “Đừng bắt chúng tôi phải nghe ông nói nữa, kẻo những kẻ bực bội sẽ tấn công các người, và ông cùng gia đình ông sẽ mất mạng.” (26) Rồi con cái Đan tiếp tục đi. Còn ông Mi-kha, thấy họ mạnh hơn mình, thì quay gót trở về nhà.
[SECTION] Chiếm La-gít. Thiết lập họ Đan và nhà thờ.
(27) Các người ấy lấy tượng ông Mi-kha đã làm, và đem theo thầy tư tế đã ở với ông; rồi họ đánh La-gít, chống một dân yên lành và an tâm. Họ dùng lưỡi kiếm chém giết dân ấy và nổi lửa đốt thành. (28) Không có ai tiếp cứu, vì thành ấy ở xa Xi-đôn và không có liên hệ gì với ai cả. Thành ấy nằm trong thung lũng gần Bết Rơ-khốp. Họ xây lại thành và định cư ở đấy. (29) Họ đặt tên thành là Đan, theo tên ông tổ của họ là Đan, con của ông Ít-ra-en. Thật ra trước kia tên thành là La-gít. (30) Con cái Đan dựng tượng ấy lên mà thờ. Ông Giơ-hô-na-than, con ông Ghéc-sôm, cháu ông Mơ-na-se, ông và con cái ông làm tư tế cho họ Đan mãi tới ngày dân trong nước bị lưu đày. (31) Vậy tượng ông Mi-kha đã làm, thì họ dựng lên mà thờ, trong suốt thời gian có nhà Thiên Chúa ở Si-lô.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'tl', 19, '[PART] 2. TỘI ÁC CỦA DÂN GHÍP-A. CHIẾN TRANH CHỐNG BEN-GIA-MIN.
[SECTION] Người Lê-vi vùng Ép-ra-im và cô tỳ thiếp
(1) Thời ấy –thời Ít-ra-en chưa có vua– có một người Lê-vi cư trú trong thung lũng vùng núi Ép-ra-im. Người ấy lấy một phụ nữ Bê-lem Giu-đa làm tỳ thiếp. (2) Người tỳ thiếp giận chồng, bỏ về nhà cha mình tại Bê-lem Giu-đa. Nàng lưu lại đây một thời gian là bốn tháng. (3) Chồng nàng lên đường đi tìm nàng để năn nỉ, mong đưa nàng về với mình. Cùng đi với chàng, có một người đầy tớ và hai con lừa. Nàng dẫn chàng vào nhà cha mình. Khi thấy chàng, người cha của thiếu phụ vui mừng ra đón chàng. (4) Ông bố vợ, cha của thiếu phụ, giữ chàng lại, nên chàng ở với ông ba ngày. Họ ăn uống và qua đêm tại đó. (5) Ngày thứ tư, chàng dậy sớm và chuẩn bị lên đường, thì cha của thiếu phụ nói với con rể: “Anh dùng chút bánh lót dạ đã, rồi hãy đi.” (6) Họ ngồi xuống và cả hai cùng ăn uống với nhau. Đoạn cha của thiếu phụ lại nói với anh ta: “Mời anh ở lại qua đêm cho thoải mái.” (7) Khi người ấy đứng lên đi, thì ông bố vợ nài ép, nên chàng ở lại qua đêm nữa. (8) Ngày thứ năm chàng dậy sớm để lên đường, nhưng cha của thiếu phụ nói: “Mời anh ăn lót dạ đã.” Thế là họ lại kéo dài tới xế chiều và cả hai cùng ăn với nhau. (9) Khi người ấy đứng lên đi cùng với người tỳ thiếp và tên đầy tớ, thì bố vợ, cha của thiếu phụ, nói với chàng: “Này trời đã về chiều, hãy qua đêm đã! Đây ngày sắp tàn, hãy qua đêm tại đây cho thoải mái. Ngày mai các người sẽ dậy sớm lên đường và anh sẽ về lều của anh.” (10) Nhưng người ấy không muốn ở lại qua đêm; chàng đứng lên và đi cho tới khi nhìn thấy Giơ-vút tức là Giê-ru-sa-lem. Cùng đi với chàng có hai con lừa đã thắng yên, người tỳ thiếp và tên đầy tớ của chàng.
[SECTION] Tội ác của dân Ghíp-a
(11) Khi họ đến gần Giơ-vút, thì lúc ấy, giờ đã quá muộn. Người đầy tớ nói với chủ: “Thưa ngài, chúng ta nên rẽ vào thành của người Giơ-vu-xi mà qua đêm tại đó.” (12) Người chủ trả lời: “Chúng ta sẽ không rẽ vào một thành nào của người xa lạ, vì những người đó không phải là con cái Ít-ra-en; chúng ta cứ đi cho tới Ghíp-a.” (13) Chàng còn nói với tên đầy tớ: “Đi! Chúng ta hãy tới một trong các nơi kia; chúng ta sẽ nghỉ đêm tại Ghíp-a hoặc Ra-ma.” (14) Vậy họ tiếp tục đi; khi họ tới sát Ghíp-a thuộc Ben-gia-min thì mặt trời lặn. (15) Họ liền ghé vào Ghíp-a để qua đêm. Chàng vào ngồi ở công trường thành phố, nhưng không ai mời họ về nhà nghỉ đêm.
(16) Chiều đến bỗng có một cụ già đi làm ruộng về. Cụ là người vùng núi Ép-ra-im, nhưng cư trú ở Ghíp-a; còn người địa phương thì là con cái Ben-gia-min. (17) Cụ già ngước mắt lên và thấy người lữ khách ở công trường thành phố, liền nói với người ấy: “Anh đi đâu, và từ đâu tới?” (18) Chàng trả lời: “Chúng tôi từ Bê-lem Giu-đa đi về thung lũng vùng núi Ép-ra-im, quê tôi ở đấy. Tôi đã đến Bê-lem Giu-đa và bây giờ đang trên đường trở về nhà. Thế nhưng chẳng người nào đón tiếp tôi cả. (19) Cỏ rơm cho lừa ăn, tôi có sẵn, cả bánh và rượu để tôi, nữ tỳ của ông và thằng bé đi theo tôi tớ của ông dùng, cũng đều có, không thiếu thứ gì.” (20) Cụ già nói: “Chúc anh bình an! Anh cần gì, cứ để tôi lo; chỉ xin anh đừng nghỉ đêm ở công trường.” (21) Vậy cụ đưa chàng vào nhà mình và vất rơm cho lừa ăn. Họ rửa chân rồi ăn uống.
(22) Đang lúc họ ăn uống vui vẻ như vậy, thì này có những người dân trong thành, những kẻ vô lại, bao vây nhà ấy, vừa đập cửa dồn dập, vừa nói với cụ già là gia chủ: “Hãy đưa người đàn ông đã vào nhà ông ra đây cho chúng tôi chơi!” (23) Cụ chủ nhà ra gặp chúng và nói: “Này anh em, tôi van anh em đừng làm chuyện ác đức! Một khi người đàn ông này đã vào nhà tôi rồi, thì xin các anh đừng làm điều bỉ ổi. (24) Này tôi có đứa con gái còn trinh, và người tỳ thiếp của anh ta nữa. Tôi đưa họ ra cho các anh cưỡng hiếp và xử với họ thế nào tùy ý. Còn đối với người này thì đừng làm điều bỉ ổi ấy.” (25) Nhưng đám người đó không thèm nghe. Bấy giờ người kia dẫn tỳ thiếp của mình ra ngoài cho chúng chơi. Chúng cưỡng hiếp nàng suốt đêm cho tới sáng, và lúc rạng đông mới buông tha.
(26) Gần sáng, khi người đàn bà trở về, thì nàng té xỉu ngay lối vào nhà cụ già, nơi chồng nàng đang trọ. Nàng nằm đấy cho tới sáng hẳn. (27) Sáng ngày ra chồng nàng dậy, mở cửa và chuẩn bị lên đường, thì này người đàn bà, tỳ thiếp của chàng nằm bên cửa nhà, hai tay vắt trên ngưỡng cửa. (28) Chàng gọi nàng: “Dậy đi! Chúng ta lên đường”, nhưng không một tiếng trả lời. Bấy giờ chàng xốc nàng lên lừa, rồi khởi hành về nhà. (29) Về tới nhà, chàng lấy dao đem chặt người tỳ thiếp ra từng mảnh, thành mười hai phần, rồi gửi đi khắp lãnh thổ Ít-ra-en. (30) Mọi người, ai thấy cũng đều nói: “Chưa xảy ra và chưa hề thấy như thế bao giờ, kể từ ngày con cái Ít-ra-en từ đất Ai-cập đi lên cho tới nay. Hãy suy nghĩ xem, hãy bàn luận và lên tiếng!”') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'tl', 20, '[SECTION] Người Ít-ra-en trả thù tội ác Ghíp-a
(1) Tất cả cộng đồng con cái Ít-ra-en, từ Đan tới Bơ-e Se-va và đất Ga-la-át, họp lại, muôn người như một, bên cạnh ĐỨC CHÚA ở Mít-pa. (2) Các người đứng đầu toàn dân và các chi tộc Ít-ra-en, đều tham dự công hội của Dân Thiên Chúa, tất cả là 400.000 bộ binh biết tuốt gươm. (3) Con cái Ben-gia-min nghe tin rằng con cái Ít-ra-en đã lên Mít-pa. Con cái Ít-ra-en nói: “Hãy kể đi! Tội ác đó đã xảy ra thế nào?” (4) Bấy giờ người Lê-vi, chồng của người đàn bà đã bị giết, lên tiếng nói: “Tôi cùng với người tỳ thiếp đến Ghíp-a thuộc Ben-gia-min để nghỉ đêm. (5) Các thân hào Ghíp-a đã xông đến phá tôi, và suốt đêm bao vây nhà tôi ở, để hại tôi, vì họ định giết tôi. Còn người tỳ thiếp của tôi thì họ cưỡng hiếp cho đến chết. (6) Vậy tôi đã đem chặt người tỳ thiếp của tôi ra từng phần, rồi gửi đi khắp lãnh thổ thuộc gia nghiệp Ít-ra-en, bởi vì những người ấy đã làm một điều sỉ nhục và bỉ ổi trong Ít-ra-en. (7) Này đây, tất cả quý vị là con cái Ít-ra-en, hãy trao đổi ý kiến và quyết định tại đây.” (8) Toàn dân, muôn người như một, đứng lên nói: “Không ai được về lều, không ai được trở lại nhà! (9) Bây giờ, chúng ta sẽ làm thế này đối với Ghíp-a, là rút thăm xem ai sẽ lên tấn công nó! (10) Trong tất cả các chi tộc Ít-ra-en, cứ 100 người thì lấy 10, 1.000 thì lấy 100, 10.000 thì lấy 1.000, để tải lương cho dân quân, là những người khi đến nơi sẽ xử với Ghíp-a thuộc Ben-gia-min, tương xứng với điều bỉ ổi nó đã làm tại Ít-ra-en.” (11) Như thế tất cả mọi người Ít-ra-en đã họp nhau muôn người như một, để chống lại thành ấy.
[SECTION] Người Ben-gia-min ngoan cố
(12) Các chi tộc Ít-ra-en sai người đi nói với toàn thể chi tộc Ben-gia-min: “Tội ác như vậy đã xảy ra nơi các người là thế nào? (13) Bây giờ hãy nộp những con người đó, những kẻ vô lại ở Ghíp-a, để chúng tôi xử tử chúng và khử trừ tội ác khỏi Ít-ra-en.” Nhưng con cái Ben-gia-min không muốn nghe lời con cái Ít-ra-en là anh em mình.
[SECTION] Giao tranh đầu tiên
(14) Bấy giờ con cái Ben-gia-min từ các thành tập họp lại ở Ghíp-a để đi giao chiến với con cái Ít-ra-en. (15) Ngày hôm ấy, con cái Ben-gia-min từ các thành được kiểm tra là 26.000 người biết tuốt gươm, không kể dân cư ở Ghíp-a. (16) Trong tất cả đám dân đó có 700 tinh binh thuận tay trái; những người này đều có thể dùng ná bắn một hòn đá trúng một sợi tóc mà không sai trệch. (17) Con cái Ít-ra-en cũng được kiểm tra, tổng số là 400.000 người biết tuốt gươm, không kể Ben-gia-min; tất cả đều là chiến binh. (18) Họ trỗi dậy tiến lên Bết Ên để thỉnh vấn Thiên Chúa. Con cái Ít-ra-en hỏi: “Ai trong chúng con sẽ lên trước để giao chiến với con cái Ben-gia-min?” ĐỨC CHÚA phán: “Giu-đa lên trước.” (19) Sáng sớm con cái Ít-ra-en tiến lên đóng trại tấn công Ghíp-a. (20) Người Ít-ra-en ra đi giao chiến với Ben-gia-min, và người Ít-ra-en dàn trận chống Ghíp-a. (21) Con cái Ben-gia-min từ Ghíp-a xông ra, và hôm ấy họ giết được 22.000 người Ít-ra-en nằm ngổn ngang trên mặt đất. (22) Nhưng đạo quân Ít-ra-en phục hồi được khí thế và lại dàn trận để chiến đấu tại chính nơi đã dàn trận hôm trước. (23) Sở dĩ như thế là vì con cái Ít-ra-en đã lên kêu khóc trước nhan ĐỨC CHÚA cho đến chiều và thỉnh vấn ĐỨC CHÚA rằng: “Con còn phải giao tranh chống con cái Ben-gia-min, anh em con nữa không?” ĐỨC CHÚA trả lời: “Tiến lên đánh nó đi!” (24) Ngày thứ hai con cái Ít-ra-en tới gần con cái Ben-gia-min. (25) Nhưng ngày thứ hai này Ben-gia-min từ Ghíp-a cũng xông ra ứng chiến, và trong số con cái Ít-ra-en họ còn giết được 18.000 người nằm ngổn ngang trên mặt đất, toàn là những người biết tuốt gươm. (26) Bấy giờ tất cả con cái Ít-ra-en và toàn dân đã lên Bết Ên; họ ngồi khóc tại đây trước nhan ĐỨC CHÚA. Hôm ấy họ ăn chay cho đến chiều. Rồi họ dâng lễ toàn thiêu và lễ kỳ an lên trước nhan ĐỨC CHÚA. (27) Con cái Ít-ra-en đã thỉnh vấn ĐỨC CHÚA –thời bấy giờ ở đấy có Hòm Bia Giao Ước của Thiên Chúa, (28) và có ông Pin-khát con ông E-la-da, cháu ông A-ha-ron, túc trực trước Hòm Bia – họ hỏi rằng: “Con còn phải lâm trận chống con cái Ben-gia-min, anh em con nữa hay là thôi?” ĐỨC CHÚA trả lời: “Các ngươi cứ lên, vì sáng mai Ta sẽ trao chúng vào tay (các) ngươi.”
[SECTION] Ben-gia-min bại trận
(29) Bấy giờ Ít-ra-en đặt quân phục kích bao vây Ghíp-a. (30) Ngày thứ ba, con cái Ít-ra-en tiến lên đánh con cái Ben-gia-min, và dàn trận tấn công Ghíp-a như những lần trước. (31) Con cái Ben-gia-min xông ra ứng chiến với đạo quân ấy và bị nhử ra xa thành. Như những lần trước, chúng bắt đầu giết một số người Ít-ra-en, chừng ba mươi mạng trong đám dân quân ấy, trên những con đường, ngả thì lên Bết Ên, ngả thì đi đến Ghíp-a, giữa đồng trống. (32) Con cái Ben-gia-min bảo nhau: “Bọn chúng lại bị ta đánh cho tháo chạy như lần trước”; nhưng con cái Ít-ra-en lại tự nhủ: “Trốn chạy đi! Ta sẽ nhử chúng ra xa thành, tới các con đường ấy.” (33) Mọi người Ít-ra-en từ vị trí của mình vùng lên và dàn trận tại Ba-an Ta-ma, đồng thời những người Ít-ra-en mai phục cũng từ vị trí của mình vùng lên ở phía tây Ghe-va. (34) Vậy 10.000 tinh binh được chọn từ khắp Ít-ra-en tiến đến ngay trước Ghíp-a. Giao tranh dữ dội xảy ra, mà người Ben-gia-min không hay biết tai họa đang ập xuống trên mình. (35) ĐỨC CHÚA đánh cho Ben-gia-min tháo chạy trước Ít-ra-en, và hôm đó con cái Ít-ra-en đã giết được 25.100 người Ben-gia-min, toàn là những người biết tuốt gươm.
(36) Con cái Ben-gia-min thấy mình bị đánh bại, nhưng người Ít-ra-en nhường đất lại cho người Ben-gia-min, vì họ tin tưởng ở quân mai phục họ đã đặt bao vây Ghíp-a. (37) Quân mai phục tấn công chớp nhoáng Ghíp-a; họ xông ra và dùng gươm tàn sát cả thành. (38) Giữa người Ít-ra-en và quân mai phục đã có lời hẹn rằng quân mai phục sẽ đốt lửa cho khói bốc lên khỏi thành làm hiệu. (39) Người Ít-ra-en sẽ rút khỏi trận địa, khi người Ben-gia-min bắt đầu giết một số chừng ba mươi người Ít-ra-en, vì chúng nói: “Chắc chắn là nó hoàn toàn bị ta đánh bại như lần trước.” (40) Rồi một cột khói làm hiệu bắt đầu bốc lên khỏi thành. Người Ben-gia-min liền quay trở lại, thì này toàn thành như lửa bốc cháy ngút trời. (41) Bấy giờ người Ít-ra-en quay lại phản công, khiến người Ben-gia-min khiếp vía, vì thấy tai họa đang ập xuống trên mình.
(42) Chúng quay đầu chạy về phía sa mạc để trốn người Ít-ra-en, nhưng trận chiến cũng lan tới chúng, và chúng bị những người từ các thành xông ra tiêu diệt giữa đường. (43) Họ vây chặt người Ben-gia-min, rượt bắt không ngừng và đè bẹp chúng cho đến khi trông thấy Ghíp-a, về hướng mặt trời mọc. (44) Phía Ben-gia-min có 18.000 người ngã gục, tất cả đều là dũng sĩ. (45) Còn những kẻ quay đầu chạy trốn vào sa mạc, về phía tảng đá Rim-môn, thì người ta giết tỉa được 5.000 trên các nẻo đường; họ bám sát chúng cho tới Ghít-ôm và giết thêm được 2.000 nữa. (46) Những người Ben-gia-min đã ngã gục hôm ấy tính tất cả là 25.000 biết tuốt gươm, toàn là dũng sĩ. (47) Những kẻ quay đầu chạy trốn vào sa mạc tới được tảng đá Rim-môn là 600 người; chúng ở tảng đá Rim-môn bốn tháng. (48) Người Ít-ra-en trở lại đánh con cái Ben-gia-min; họ dùng gươm tàn sát từ đàn ông trong thành cho đến súc vật và tất cả những gì họ gặp. Tới thành nào, họ cũng đều phóng hỏa.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'tl', 21, '[SECTION] Người Ít-ra-en hối hận
(1) Người Ít-ra-en đã thề tại Mít-pa rằng: “Không ai trong chúng ta sẽ gả con gái mình cho người Ben-gia-min.” (2) Dân chúng đến Bết Ên và ở lại đó trước nhan Thiên Chúa cho đến chiều; họ cất tiếng khóc nức nở. (3) Họ nói: “Lạy ĐỨC CHÚA, Thiên Chúa của Ít-ra-en, tại sao lại xảy ra chuyện này, là ngày nay Ít-ra-en mất đi một chi tộc?” (4) Sáng hôm sau, dân dậy sớm và lập bàn thờ ở đó, rồi dâng lễ toàn thiêu và lễ kỳ an. (5) Con cái Ít-ra-en nói: “Trong tất cả các chi tộc Ít-ra-en, ai là người đã không lên dự công hội chầu ĐỨC CHÚA?” vì ai đã không lên chầu ĐỨC CHÚA ở Mít-pa, thì đã có lời thề long trọng chống lại kẻ ấy rằng: “Chắc chắn nó phải chết.”
(6) Thấy tội nghiệp cho Ben-gia-min anh em mình, con cái Ít-ra-en nói: “Hôm nay một chi tộc đã bị cắt đứt khỏi Ít-ra-en. (7) Chúng ta sẽ làm gì để tìm vợ cho những kẻ còn sống sót, vì chúng ta đã thề nhân danh ĐỨC CHÚA là không gả con gái mình cho chúng?”
[SECTION] Các trinh nữ Gia-vết được trao cho người Ben-gia-min
(8) Họ lại hỏi: “Trong các chi tộc Ít-ra-en có ai đã không lên chầu ĐỨC CHÚA ở Mít-pa?” Thì ra chẳng có ai thuộc Gia-vết thuộc Ga-la-át đã lên trại, dự công hội. (9) Quả thật khi người ta kiểm tra dân chúng, thì ở đấy không có ai là người thuộc dân cư Gia-vết thuộc Ga-la-át cả. (10) Bấy giờ cộng đồng ở đó sai 12.000 người trong số các dũng sĩ và truyền cho họ rằng: “Các anh hãy dùng gươm đi giết dân cư Gia-vết thuộc Ga-la-át, kể cả đàn bà con nít. (11) Đây là điều các anh sẽ làm: tất cả đàn ông đàn bà đã biết chuyện vợ chồng, các anh sẽ tru hiến hết.” (12) Trong số dân cư Gia-vết thuộc Ga-la-át, họ tìm được bốn trăm thiếu nữ còn trinh, nghĩa là chưa ăn nằm với đàn ông, và đã đem các cô về trại Si-lô trong đất Ca-na-an. (13) Toàn thể cộng đồng sai người đi nói chuyện với con cái Ben-gia-min ở tảng đá Rim-môn và đề nghị hòa hoãn với họ. (14) Bấy giờ người Ben-gia-min trở về và người ta trao cho họ những phụ nữ còn sống sót trong số các phụ nữ Gia-vết thuộc Ga-la-át, nhưng không tìm được đủ số cho họ.
[SECTION] Bắt cóc các cô gái Si-lô
(15) Dân chúng thấy tội nghiệp cho Ben-gia-min, vì ĐỨC CHÚA đã làm cho các chi tộc Ít-ra-en bị một vết nứt rạn. (16) Bấy giờ các kỳ mục của cộng đồng nói: “Chúng ta sẽ làm gì để tìm vợ cho những kẻ còn sống sót, vì các phụ nữ Ben-gia-min đã bị tiêu diệt?” (17) Họ nói: “Ben-gia-min sẽ chiếm phần còn sót lại, để một chi tộc không bị xóa khỏi Ít-ra-en, (18) Thế mà chúng ta lại không thể gả con gái mình cho chúng được!” Sở dĩ như vậy vì con cái Ít-ra-en đã thề rằng: “Vô phúc cho ai gả con gái cho Ben-gia-min!”
(19) Nhưng họ lại nói: “Này hàng năm có lễ kính ĐỨC CHÚA tại Si-lô, mạn bắc Bết Ên, phía đông con đường từ Bết Ên lên Si-khem và phía nam Lơ-vô-na. (20) Vậy họ truyền cho con cái Ben-gia-min: ‘Các anh vào các vườn nho mà ẩn nấp. (21) Khi thấy các cô gái Si-lô đi ra múa hát với nhau, thì các anh cũng đi ra khỏi vườn nho, mỗi người bắt một cô trong đám con gái Si-lô ấy, đem về làm vợ, rồi đi về đất Ben-gia-min. (22) Nếu cha các cô hoặc anh các cô có tới kỳ kèo với chúng tôi, thì chúng tôi sẽ nói với họ: “Xin thông cảm với chúng tôi mà hiểu cho họ, vì mỗi người chúng tôi đã không bắt một cô đem về làm vợ trong lúc đánh nhau, mà các anh cũng chẳng gả các cô ấy cho họ; nếu gả, thì các anh đã mắc lỗi rồi.’”
(23) Con cái Ben-gia-min đã làm như thế. Họ đã lấy vợ trong đám các cô múa hát bị bắt cóc, tương đương với số người của họ, và trở về phần gia nghiệp của mình. Họ xây thành và cư ngụ ở đó.
(24) Còn con cái Ít-ra-en lúc bấy giờ cũng rời khỏi đó, ai nấy về chi tộc và thị tộc của mình: mỗi người rời khỏi đó mà về phần gia nghiệp của mình.
(25) Thời đó Ít-ra-en không có vua. Ai muốn làm gì thì làm.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;