INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'gdt', 1, '[PART] I. CUỘC VIỄN CHINH CỦA HÔ-LÔ-PHÉC-NÊ
[SECTION] Na-bu-cô-đô-nô-xo và Ắc-phắc-xát
(1) Năm thứ mười hai triều đại vua Na-bu-cô-đô-nô-xo cai trị người Át-sua ở Ni-ni-vê, một thành phố lớn, là lúc vua Ắc-phắc-xát cai trị người Mê-đi ở Éc-ba-tan. (2) Ông Ắc-phắc-xát dùng loại đá đẽo rộng một thước rưỡi, dài ba thước xây một thành lũy chung quanh Éc-ba-tan. Ông làm tường thành cao ba mươi lăm thước và dài hai mươi lăm thước. (3) Tại các cổng thành, ông cũng dựng các tháp cao năm mươi thước đặt trên nền móng rộng ba mươi thước. (4) Ông làm các cổng thành, mỗi cổng cao ba mươi lăm thước và rộng hai mươi thước để các đạo quân hùng mạnh xuất trận và bộ binh diễu hành.
(5) Trong những ngày ấy, vua Na-bu-cô-đô-nô-xo giao chiến với vua Ắc-phắc-xát tại đồng bằng rộng lớn, tức đồng bằng thuộc lãnh thổ Ra-gao. (6) Tất cả dân cư miền núi, tất cả dân cư ở Êu-phơ-rát, Tích-ra, Hy-đát-pê và đồng bằng thuộc quyền A-ri-ốc, vua người Ê-ly-mai đều về phe với ông. Cũng có rất nhiều sắc tộc kéo đến tham chiến với con cái Khe-le-út.
(7) Rồi Na-bu-cô-đô-nô-xo, vua nước Át-sua sai sứ giả đến với tất cả dân cư ở Ba-tư, tất cả dân cư ở Phương Tây, các dân cư ở Ki-li-ki-a, Đa-mát, Li-băng, An-ti-li-băng, tất cả dân cư ở dọc theo bờ biển, (8) đến một số sắc tộc ở Các-men, Ga-la-át, Ga-li-lê Thượng, đồng bằng rộng lớn Ét-rê-lon, (9) đến với tất cả dân cư ở Sa-ma-ri và các thành thị của Sa-ma-ri, bên kia sông Gio-đan cho tới Giê-ru-sa-lem, Ba-ta-nê, Khe-lút, Ca-đê, sông Ai-cập, Táp-nát, Ram-xết và tất cả lãnh thổ Gô-sen, (10) cho tới bên kia Ta-ni, Mem-phít, đến với tất cả dân cư Ai-cập cho tới biên giới Ê-thi-óp. (11) Nhưng tất cả dân cư trên toàn cõi đất đều coi nhẹ mệnh lệnh của Na-bu-cô-đô-nô-xo, vua nước Át-sua; họ không đến tham chiến với ông vì họ không sợ ông, lại coi ông chẳng ra gì. Họ đuổi các sứ giả của ông về tay không và còn sỉ nhục những người này nữa. (12) Na-bu-cô-đô-nô-xo nổi trận lôi đình với tất cả các nước này. Ông lấy ngai vàng và vương quốc của ông mà thề sẽ xử phạt tất cả miền Ki-li-ki-a, Đa-mát, Xy-ri, ông sẽ dùng gươm tàn sát tất cả dân cư trên đất Mô-áp, con cái Am-mon, tất cả xứ Giu-đê, tất cả mọi người ở Ai-cập, cho đến tận biên giới hai biển.
[SECTION] Chiến tranh chống Ắc-phắc-xát
(13) Năm thứ mười bảy, ông đem quân đi giao chiến với vua Ắc-phắc-xát. Ông chiến thắng trong trận này: đẩy lui tất cả đạo quân, tất cả kỵ binh và chiến xa của Ắc-phắc-xát. (14) Ông chiếm lĩnh các thành trì của vua này và đến tận Éc-ba-tan chiếm đoạt các tháp, cướp phá các đường phố và làm cho vẻ mỹ lệ của thành ấy trở nên nhơ nhuốc. (15) Ông bắt được Ắc-phắc-xát tại miền núi Ra-gao, dùng giáo đâm và làm cho tan xác.
(16) Rồi ông trở về với tất cả đám người ô hợp theo ông, một đoàn chiến binh nhiều vô kể. Ông ở lại đó nghỉ ngơi; ông và đạo quân mở tiệc ăn mừng suốt một trăm hai mươi ngày ròng rã.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'gdt', 2, '[SECTION] Chiến tranh ở Phương Tây
(1) Năm thứ mười tám, ngày hai mươi hai tháng thứ nhất, có tiếng đồn trong triều đình Na-bu-cô-đô-nô-xo, vua nước Át-sua, là ông sắp trừng phạt toàn cõi đất như lời ông nói. (2) Ông triệu tập tất cả triều thần, tất cả thân hào và tỏ cho họ biết quyết định bí mật của ông. Chính miệng ông công bố đại họa cho toàn cõi đất. (3) Họ quyết định tiêu diệt tất cả những ai không tuân hành lệnh vua ban truyền.
(4) Vậy sau khi nghị quyết, Na-bu-cô-đô-nô-xo, vua nước Át-sua cho vời Hô-lô-phéc-nê, đại tướng chỉ huy quân đội và cũng là nhân vật thứ hai sau vua. Vua nói với ông: (5) “Đại đế, chúa tể toàn cõi đất phán thế này: đây, ngươi hãy lui ra, đem theo binh sĩ tinh nhuệ, chừng một trăm hai mươi ngàn bộ binh, một số lớn chiến mã và mười hai ngàn kỵ binh. (6) Ngươi hãy đi chinh phạt tất cả các xứ ở Phương Tây, bởi vì chúng không chịu tuân theo mệnh lệnh của ta. (7) Hãy truyền cho chúng chuẩn bị đất và nước, vì ta đang phẫn nộ và sắp đi đánh chúng; ta sẽ cho đạo quân của ta phủ lấp khắp mặt đất và tha hồ cướp phá. (8) Người bị thương đầy trũng lấp khe; xác người chết tràn sông ngập suối. (9) Ta sẽ đưa tù binh của chúng đến tận cùng cõi đất. (10) Vậy ngươi hãy đi chinh phục cho ta mọi lãnh thổ của chúng. Chúng sẽ đầu hàng, và ngươi sẽ giam chúng lại cho ta chờ ngày ta trừng trị. (11) Còn những kẻ bất tuân, đừng nhìn chúng mà thương hại, nhưng hãy đẩy chúng vào cuộc thảm sát và cướp bóc trên toàn cõi đất ngươi chiếm được. (12) Vì ta lấy mạng sống và vương quốc hùng mạnh của ta mà thề: những gì ta đã nói, ta sẽ tự tay làm. (13) Phần ngươi, chớ vi phạm một điều nào trong các mệnh lệnh của chúa tể ngươi, trái lại, phải chu toàn cho thấu đáo như ta đã chỉ thị cho ngươi. Ngươi không được chậm trễ thi hành những điều ấy.”
(14) Hô-lô-phéc-nê từ biệt chúa tể của ông; ông cho vời tất cả quan chức, tướng lãnh, sĩ quan quân đội Át-sua. (15) Ông điểm danh số người được chọn để chiến đấu, như chúa tể của ông đã truyền: chừng một trăm hai mươi ngàn người và mười hai ngàn kỵ binh xạ thủ. (16) Ông sắp xếp họ thành đội ngũ tác chiến. (17) Sau đó, ông dùng rất nhiều lạc đà, lừa và la để tải quân nhu, và mang theo vô số chiên, bò, dê làm quân lương. (18) Người nào cũng được lãnh lương thực dồi dào với rất nhiều vàng bạc xuất từ đền vua. (19) Ông cùng với tất cả đạo quân xuất trận làm tiền phong cho Na-bu-cô-đô-nô-xo; ông cho chiến xa, kỵ binh và bộ binh tinh nhuệ phủ lấp khắp mặt đất phía tây. (20) Một đám quân ô hợp cùng đi với chúng, nhiều như châu chấu, như cát trên mặt đất, vì chúng quá đông, không sao đếm nổi.
[SECTION] Các trạm nghỉ của đạo quân Hô-lô-phéc-nê
(21) Chúng đi khỏi Ni-ni-vê ba ngày đường thì tới được phía trước đồng bằng Béc-ti-lét; từ Béc-ti-lét chúng tới đóng quân ở gần ngọn núi nằm về phía trái miền Ki-li-ki-a Thượng. (22) Rồi từ đó, ông đem tất cả đạo quân gồm bộ binh, kỵ binh và chiến xa, tiến lên miền núi. (23) Ông tàn phá Pút và Lút, cướp bóc tất cả con cái Rát-xít và con cái Ít-ma-ên đang sống ở ven sa mạc phía nam từ xứ người Khe-le-ôn. (24) Ông tiến dọc theo sông Êu-phơ-rát, băng qua miền Mê-xô-pô-ta-mi-a và phá bình địa tất cả các thành nằm ở trên cao, dọc bờ suối Áp-rô-na cho tới biển. (25) Ông chiếm các lãnh thổ thuộc xứ Ki-li-ki-a và đánh tan tất cả những ai kháng cự; ông đi đến biên giới Gia-phét, ở mạn nam, đối diện với xứ Ả-rập. (26) Ông bao vây toàn thể con cái Ma-đi-an, đốt lều trại và cướp phá chuồng súc vật của họ. (27) Rồi ông đi xuống phía đồng bằng Đa-mát vào mùa gặt lúa mì; ông đốt tất cả cánh đồng, tiêu diệt bò dê chiên cừu, cướp bóc các thành thị, tàn phá các đồng ruộng và dùng gươm tàn sát tất cả các thanh niên. (28) Sợ hãi và kinh hoàng ập xuống trên toàn thể dân cư miền bờ biển là các dân ở Xi-đôn, Tia, trên các dân cư ở Xua, ở Ô-ki-na và toàn thể dân cư ở Giam-ni-a. Các dân cư ở Át-đốt và ở Át-cơ-lôn đều rất sợ hãi ông.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'gdt', 3, '(1) Họ cử sứ giả đến gặp ông xin cầu hòa và nói: (2) “Này chúng tôi là tôi tớ của đại đế Na-bu-cô-đô-nô-xo. Chúng tôi xin phủ phục trước mặt ngài; xin ngài sử dụng chúng tôi như ý ngài muốn. (3) Kìa lều trại của chúng tôi, tất cả cánh đồng lúa mì, bò bê, chiên cừu, tất cả chuồng súc vật trong lều trại chúng tôi đều ở trước mặt ngài, xin ngài sử dụng như ý ngài muốn. (4) Này, các thành thị của chúng tôi và dân cư trong thành đều là tôi tớ của ngài. Xin ngài đến và đối xử với các thành ấy tùy theo tôn ý.” (5) Các người ấy đến gặp Hô-lô-phéc-nê và trình với ông những lời lẽ trên.
(6) Ông và đạo quân đi xuống phía bờ biển. Ông cho canh phòng các thành ở trên cao và tuyển mộ dân trong thành để trợ chiến. (7) Dân trong thành và tất cả các miền phụ cận đội vòng hoa ra múa nhảy và đánh trống để nghênh đón ông. (8) Ông phá tất cả các điện thờ của họ, chặt các cột thờ, và được quyền diệt tất cả các thần trên cõi đất, khiến mọi dân tộc chỉ thờ một mình Na-bu-cô-đô-nô-xo, và mọi ngôn ngữ, mọi chi tộc phải kêu cầu Na-bu-cô-đô-nô-xo như một vị thần.
(9) Ông Hô-lô-phéc-nê đến phía trước Ét-rê-lon, gần Đô-tai-a, trước mặt dãy núi lớn xứ Giu-đê. (10) Ông đóng quân ở giữa vùng Ghê-vai và thành Xi-ky-thô-pô-li, rồi lưu lại đó một tháng trời để tập trung toàn bộ quân nhu của đạo quân.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'gdt', 4, '[SECTION] Giu-đê náo động
(1) Con cái Ít-ra-en đang sống ở Giu-đê nghe biết tất cả những gì Hô-lô-phéc-nê, đại tướng chỉ huy của Na-bu-cô-đô-nô-xo, vua nước Át-sua, đã làm đối với các dân và cách ông đã cướp bóc tất cả đền thờ của họ, rồi cho tiêu hủy các đền thờ ấy như thế nào. (2) Vì thế, khi nghe tin ông đến, họ sợ hãi, sợ hãi vô cùng và lo lắng cho thành Giê-ru-sa-lem cũng như Đền Thờ của Đức Chúa là Thiên Chúa của họ; (3) vì họ cũng vừa thoát cảnh lưu đày trở về và toàn dân cũng mới được đoàn tụ ở Giu-đê; và các đồ thờ, bàn thờ và Đền Thờ đều được thánh hiến để tẩy sạch mọi ô uế.
(4) Vì vậy, họ sai sứ giả đến khắp lãnh thổ Sa-ma-ri, đến Cô-na, Bết Khô-rôn, Ben-ma-in, Giê-ri-khô, và đến Khô-ba, Ai-xô-ra và thung lũng Sa-lem. (5) Họ chiếm trước tất cả các đỉnh núi cao, xây tường đắp lũy chung quanh làng mạc ở các nơi ấy và chuẩn bị lương thực để đề phòng chiến tranh, vì đồng ruộng của họ vừa mới gặt hái xong. (6) Thượng tế Giô-gia-kim bấy giờ đang ở Giê-ru-sa-lem, viết cho các dân cư ở Bai-ty-lu-a và Bai-tô-mét-tha-im; thành này nằm trước mặt Ét-rê-lon, đối diện với đồng bằng gần Đô-tha-im. (7) Ông bảo họ trấn giữ các đường đèo lên núi, vì phải qua các ngả đó mới vào được xứ Giu-đê; đàng khác cũng dễ chặn những ai tiến lên, vì lối đi quá hẹp, chỉ đủ cho hai người thôi. (8) Con cái Ít-ra-en làm theo lệnh của thượng tế Giô-gia-kim và của hội đồng kỳ mục toàn dân Ít-ra-en đặt trụ sở tại Giê-ru-sa-lem.
[SECTION] Cầu khẩn
(9) Hết mọi người nam trong dân Ít-ra-en đều tha thiết kêu lên cùng Thiên Chúa và sốt sắng ăn chay. (10) Họ cùng với vợ con, súc vật, ngoại kiều, người làm công và cả nô lệ mua được, tất cả đều mặc áo vải thô. (11) Hết mọi người nam trong dân Ít-ra-en cùng với vợ con cư ngụ ở Giê-ru-sa-lem đều phủ phục trước Đền Thờ, rắc tro lên đầu, mặc áo vải thô ra trước nhan Đức Chúa. (12) Họ trải vải thô lên cả bàn thờ. Họ đồng tâm khẩn khoản kêu lên cùng Thiên Chúa Ít-ra-en, xin Người đừng để con họ bị cướp bóc, vợ họ bị bắt đi, các thành trong phần gia nghiệp của họ bị tiêu hủy, Đền Thờ ra ô uế, bị nguyền rủa và trở nên trò đùa cho dân ngoại. (13) Đức Chúa lắng nghe tiếng họ kêu cầu và đoái nhìn cơn khốn quẫn của họ.
Dân chúng ăn chay nhiều ngày trong toàn xứ Giu-đê và ở Giê-ru-sa-lem trước Đền Thờ của Đức Chúa toàn năng. (14) Thượng tế Giô-gia-kim và tất cả những người phục vụ trước nhan Đức Chúa, tức là các tư tế và các thừa tác viên của Đức Chúa, đều mặc áo vải thô, dâng lễ vật toàn thiêu thường tiến, lễ vật khấn hứa và lễ vật tự nguyện của dân. (15) Họ rắc tro lên mũ tế và hết sức kêu cầu cùng Đức Chúa, xin Người thương thăm viếng toàn thể nhà Ít-ra-en.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'gdt', 5, '[SECTION] Hô-lô-phéc-nê bàn kế hoạch giao chiến
(1) Người ta báo tin cho Hô-lô-phéc-nê, đại tướng chỉ huy quân đội Át-sua là con cái Ít-ra-en đang chuẩn bị chiến tranh: họ đóng các cửa ải miền núi, xây tường đắp lũy trên tất cả các đỉnh núi cao và đặt chướng ngại vật ở đồng bằng. (2) Hô-lô-phéc-nê đùng đùng nổi giận, ông triệu tập tất cả các vương hầu Mô-áp, các tướng lãnh Am-mon và tất cả các tổng đốc miền bờ biển. (3) Ông nói với họ: “Hỡi con cái Ca-na-an, giờ đây hãy nói cho ta hay: đám dân đang ở trên miền núi là dân nào? Tên những thành chúng đang ở là gì? Đạo quân chúng đông bao nhiêu? Chúng hùng mạnh ở chỗ nào? Ai đứng đầu làm vua, chỉ huy binh lực chúng? (4) Và tại sao chúng lại khinh thường không đến đón tiếp ta, như các dân cư ở phía tây?”
(5) A-khi-ô, viên chỉ huy toàn thể con cái Am-mon, nói với ông: “Xin chủ tướng nghe lời từ miệng tôi tớ ngài đây; tôi sẽ kể cho ngài sự thật về dân ấy, đám dân ở trên miền núi đó, ở sát bên ngài. Không có lời dối trá nào phát ra từ miệng tôi tớ ngài. (6) Dân này là dòng giống Can-đê. (7) Trước kia chúng đã trú ngụ ở Mê-xô-pô-ta-mi-a, vì chúng không muốn theo các thần của cha ông chúng ở đất Can-đê. (8) Chúng đã lìa bỏ đường lối của tổ tiên mà thờ lạy Thiên Chúa trên trời, Thiên Chúa chúng đã biết. Vì thế chúng bị đuổi cho khuất mắt các thần của chúng, phải chạy trốn sang Mê-xô-pô-ta-mi-a và trú ngụ ở đó một thời gian dài. (9) Rồi Thiên Chúa của chúng truyền cho chúng rời khỏi nơi trú ngụ mà đi tới đất Ca-na-an. Chúng định cư tại đây, được dư dật vàng bạc và rất nhiều súc vật. (10) Nhưng vì nạn đói lan tràn khắp đất Ca-na-an, nên chúng đi xuống Ai-cập và trú ngụ tại đó bao lâu còn kiếm được của ăn. Ở đó chúng nên đông đúc, giống nòi chúng nhiều không đếm nổi. (11) Nhưng vua Ai-cập đứng lên chống lại chúng, dùng biện pháp khôn khéo bắt phải lao động cực nhọc, phải đúc gạch; vua hạ nhục và bắt chúng làm nô lệ. (12) Chúng kêu lên cùng Thiên Chúa của chúng, nên Người đánh phạt khắp mặt đất Ai-cập, giáng xuống những tai ương hết đường cứu chữa, khiến người Ai-cập phải đuổi chúng đi cho khuất mắt. (13) Thiên Chúa làm cho Biển Đỏ cạn khô trước mắt chúng, (14) rồi dẫn đường cho chúng đến Xi-nai và Ca-đê Bác-nê-a. Chúng đánh đuổi tất cả dân cư ở sa mạc, (15) định cư trong đất của người E-mô-ri và dùng sức mạnh tiêu diệt tất cả người Khét-bôn. Vượt qua sông Gio-đan, chúng chiếm tất cả miền núi làm gia nghiệp. (16) Chúng đánh đuổi người Ca-na-an, người Pơ-rít-di, người Giơ-vút, người Si-khem, và tất cả những người Ghia-ga-si cho khuất mắt. Rồi chúng định cư ở đó một thời gian lâu dài. (17) Bao lâu chúng không phạm tội trước nhan Thiên Chúa của chúng, thì chúng được hạnh phúc, vì Thiên Chúa, Đấng ghét sự gian ác, luôn ở với chúng. (18) Còn khi chúng xa lìa đường lối Người chỉ định, thì chúng bị chiến tranh tiêu diệt, hết trận này đến trận khác, lại còn phải đày ải nơi đất khách quê người. Đền Thờ Thiên Chúa của chúng bị phá bình địa và thành thị của chúng bị đối phương chiếm giữ. (19) Nhưng nay khi trở về với Thiên Chúa của chúng, chúng đã thoát cảnh lưu lạc tha phương. Chúng chiếm lại Giê-ru-sa-lem, nơi có Thánh Điện và định cư ở miền núi, vì nơi này còn hoang vắng. (20) Vậy bây giờ, thưa tướng quân, thưa chủ tướng, giả như dân ấy có lầm lỗi và đắc tội với Thiên Chúa của chúng, thì ta cứ để ý xem chúng có thật sự làm gì nên cớ vấp ngã, lúc ấy ta hãy tiến lên và đánh chúng; (21) còn nếu dân ấy không làm gì nên tội, thì xin chủ tướng bỏ qua, kẻo Đức Chúa là Thiên Chúa của chúng sẽ bảo vệ chúng và chúng ta sẽ nên trò cười cho bàn dân thiên hạ.”
(22) A-khi-ô vừa dứt lời, toàn dân đứng chung quanh lều đều phản kháng; các thân hào của Hô-lô-phéc-nê, tất cả dân cư ở miền bờ biển và ở Mô-áp nói là phải đánh ông nhừ tử. (23) Họ bảo: “Chúng ta sợ gì con cái Ít-ra-en. Này quả thật đám dân ấy chẳng hùng chẳng mạnh để đối phó với một trận chiến cam go. (24) Vậy giờ đây, thưa chủ tướng Hô-lô-phéc-nê, chúng ta hãy tiến lên và chúng sẽ trở thành miếng mồi ngon cho toàn thể binh lực của ngài.”') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'gdt', 6, '[SECTION] Ông A-khi-ô bị nộp cho người Ít-ra-en
(1) Khi ngưng tiếng ồn ào của những người vây quanh hội nghị, Hô-lô-phéc-nê, đại tướng chỉ huy quân đội Át-sua, liền nói với A-khi-ô và toàn thể con cái Mô-áp trước mặt tất cả các dân ngoại bang: (2) “A-khi-ô, tên cầm đầu lính đánh thuê cho Ép-ra-im, ngươi là ai mà dám nói tiên tri giữa chúng ta hôm nay? Ngươi nói đừng giao chiến với nòi giống Ít-ra-en, vì Thiên Chúa của chúng sẽ bảo vệ chúng? Ai là Thiên Chúa nếu không phải là Na-bu-cô-đô-nô-xo? Chính người sẽ phái lực lượng của người tới tiêu diệt chúng khỏi mặt đất và Thiên Chúa của chúng sẽ chẳng cứu chúng đâu. (3) Nhưng chúng ta, bầy tôi của Na-bu-cô-đô-nô-xo, sẽ đánh chúng như đánh một người. Chúng sẽ không đương đầu nổi với chiến mã hùng mạnh của chúng ta đâu. (4) Quả thật, chúng ta sẽ thiêu hủy chúng; núi đồi của chúng sẽ ngập chìm trong máu, thây ma nằm la liệt khắp đồng bằng. Chân chúng không thể đứng vững trước mặt chúng ta, nhưng chúng sẽ hoàn toàn bị tiêu diệt. Đó là lời của vua Na-bu-cô-đô-nô-xo, chúa tể toàn cõi đất. Thật thế, một khi người đã phán thì không một lời nào của người lại vô hiệu. (5) Còn ngươi, A-khi-ô, tên lính đánh thuê gốc người Am-mon, ngươi đã thốt ra những lời ấy trong ngày tận số của ngươi; ngươi sẽ không nhìn thấy mặt ta nữa, kể từ hôm nay cho đến khi ta trừng trị cái nòi giống đã ra khỏi Ai-cập. (6) Gươm của binh sĩ ta, giáo của tôi tớ ta sẽ đâm thấu sườn ngươi và ngươi sẽ ngã gục giữa đám thương binh của chúng khi ta trở về. (7) Các tôi tớ ta sẽ áp giải ngươi lên miền núi và bỏ ngươi lại một trong những thành hẻo lánh. (8) Ngươi sẽ không chết trước khi cùng bị tiêu diệt với chúng. (9) Nếu lòng ngươi còn hy vọng chúng không bị bắt, thì ngươi đừng cúi gầm xuống như vậy! Ta đã nói thì không một lời nào của ta hóa ra vô hiệu.”
(10) Hô-lô-phéc-nê ra lệnh cho thuộc hạ đang đứng trực quanh lều của ông bắt giữ A-khi-ô, áp giải đến Bai-ty-lu-a và trao nộp vào tay con cái Ít-ra-en. (11) Vậy thuộc hạ của ông bắt giữ A-khi-ô, dẫn ông này ra khỏi trại đến cánh đồng; từ giữa cánh đồng chúng đi lên phía núi, rồi đến các con suối ở bên dưới Bai-ty-lu-a. (12) Nhìn thấy chúng, dân quân trong thành liền cầm khí giới, ùa ra khỏi thành –thành này nằm trên đỉnh núi–, còn tất cả binh lính bắn ná thì liệng đá xuống để chặn đường chúng tiến lên. (13) Chúng trườn xuống khỏi núi, trói A-khi-ô lại, quẳng xuống chân núi, rồi trở về với chủ mình.
(14) Con cái Ít-ra-en bỏ thành đi xuống, dừng lại bên A-khi-ô, cởi trói cho ông và đưa ông đến Bai-ty-lu-a, rồi đem ông trình diện với các thủ lãnh trong thành (15) lúc bấy giờ, là các ông Út-di-gia con ông Mi-kha, thuộc chi tộc Si-mê-ôn, Kháp-rít con ông Gô-thô-ni-ên và Khác-mít con ông Man-ki-ên. (16) Các ông triệu tập toàn thể kỳ mục trong thành. Tất cả thanh niên và phụ nữ cũng đều tới dự đại hội. Các ông để A-khi-ô đứng giữa toàn dân; rồi ông Út-di-gia hỏi ông về những việc đã xảy ra. (17) Ông trả lời cho họ biết những việc đã xảy ra trong hội nghị của Hô-lô-phéc-nê, cùng tất cả những điều ông đã nói giữa các thủ lãnh con cái Át-sua cũng như những lời Hô-lô-phéc-nê huênh hoang chống lại nhà Ít-ra-en. (18) Nghe vậy, dân phủ phục xuống thờ lạy Thiên Chúa và kêu cầu rằng: (19) “Lạy Đức Chúa là Thiên Chúa trên trời, xin Chúa thấy cho: chúng thật là kiêu ngạo; xin thương xót giống nòi chúng con đang phải nhục nhã, và hôm nay, xin đoái nhìn gương mặt những người đã được thánh hiến cho Chúa.” (20) Rồi họ an ủi ông A-khi-ô và hết lời khen ngợi ông. (21) Sau đại hội, ông Út-di-gia đưa ông về nhà và mở tiệc khoản đãi các kỳ mục. Suốt đêm ấy, họ kêu cầu xin Thiên Chúa Ít-ra-en cứu giúp.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'gdt', 7, '[PART] II. VÂY HÃM BAI-TY-LU-A
[SECTION] Chinh phạt Ít-ra-en
(1) Hôm sau, Hô-lô-phéc-nê ra lệnh cho tất cả binh lính và toàn thể dân đến trợ chiến với ông phải rời trại đến sát Bai-ty-lu-a, chiếm trước các đường đèo đi lên núi và giao chiến với con cái Ít-ra-en. (2) Hôm ấy, toàn thể đạo quân rời trại. Đạo quân chiến đấu gồm một trăm bảy mươi ngàn bộ binh, mười hai ngàn kỵ binh, không kể quân nhu và đám người cùng đi bộ với chúng. Một đoàn người đông vô kể. (3) Chúng đóng trại ở thung lũng gần Bai-ty-lu-a, phía có suối nước; chúng rải quân theo chiều rộng từ Đô-tha-im đến Ben-ba-im, theo chiều dài từ Bai-ty-lu-a đến Ky-a-môn đối diện với Ét-rê-lon. (4) Thấy chúng đông đảo như thế, con cái Ít-ra-en rất lo sợ. Họ bảo nhau: “Phen này chúng sẽ quét sạch mặt đất. Chẳng núi, chẳng khe, chẳng đồi nào có thể chịu nổi sức nặng của chúng.” (5) Mọi người đều cầm khí giới. Họ nổi lửa trên các tháp và ở lại canh phòng suốt đêm ấy.
(6) Sang ngày thứ hai, Hô-lô-phéc-nê dẫn tất cả kỵ binh của ông ra giáp mặt với con cái Ít-ra-en đang ở Bai-ty-lu-a. (7) Ông quan sát các đường tiến lên thành của họ, do thám các suối nước và chiếm lấy, rồi đặt trạm lính canh, sau đó trở về với dân của ông. (8) Tất cả các thủ lãnh con cái Ê-xau, các vị chỉ huy dân Mô-áp và các tướng lãnh miền bờ biển đều đến với ông và nói: (9) “Xin minh chủ nghe lời này để không một ai trong đạo quân của ngài bị thương vong. (10) Vì đám dân Ít-ra-en ấy chẳng tin vào giáo mác của chúng, nhưng lại cậy vào đỉnh núi cao nơi chúng đang ở. Quả thật, leo lên các đỉnh núi đó không dễ dàng gì.
(11) “Vậy, thưa minh chủ, xin đừng giao chiến với chúng theo đội ngũ, không một ai trong dân quân của ngài sẽ gục ngã đâu. (12) Xin ngài cứ ở lại trong trại với tất cả quân sĩ của ngài, án binh bất động; các tôi tớ ngài chỉ cần kiểm soát các nguồn nước xuất phát từ chân núi, (13) bởi vì tất cả dân cư ở Bai-ty-lu-a đều lấy nước từ đó. Chúng sẽ phải chết khát và sẽ trao nộp thành của chúng. Còn chúng ta và dân quân của chúng ta sẽ lên các đỉnh núi kế cận. Chúng ta sẽ lập tiền đồn trên các đỉnh núi ấy để không một ai thoát ra khỏi thành. (14) Chúng và vợ con chúng sẽ chết dần chết mòn vì đói; trước khi bị gươm đâm, chúng đã nằm phơi xác trên đường phố trước nhà chúng ở. (15) Như thế ngài sẽ bắt chúng phải đền tội ác chúng đã gây ra vì chúng đã nổi loạn và không ra nghênh đón ngài để cầu hòa.”
(16) Lời lẽ của họ làm vừa lòng Hô-lô-phéc-nê và các quan chức của ông. Ông ra lệnh thi hành như lời họ nói. (17) Con cái Am-mon rời trại đi; năm ngàn người trong số con cái Át-sua cùng đi với chúng. Chúng đóng quân ở dưới thung lũng, chiếm các nơi có nước và các nguồn nước của con cái Ít-ra-en. (18) Con cái Ê-xau và con cái Am-mon tiến lên và đóng quân ở trên núi đối diện với Đô-tha-im. Chúng cử một số người xuống phía nam và sang phía đông đối diện với Éc-re-bên, gần Khút, trên bờ suối Mốc-mua. Số binh sĩ Át-sua còn lại đóng quân ở đồng bằng và tràn ngập khắp mặt đất. Chúng dựng lều, đặt chỗ chứa quân nhu thành một doanh trại dày đặc, đông đảo.
(19) Con cái Ít-ra-en kêu cầu cùng Đức Chúa là Thiên Chúa của họ, vì tinh thần họ bạc nhược và mọi kẻ thù vây hãm họ tứ phía, khiến họ không thể nào thoát khỏi vòng vây. (20) Toàn thể đạo quân Át-sua gồm bộ binh, chiến xa và kỵ binh vây hãm họ suốt ba mươi bốn ngày. Tất cả các vò đựng nước của dân cư ở Bai-ty-lu-a vơi dần. (21) Các bể nước cạn sạch. Không có ngày nào họ đủ nước uống cho đã khát, vì họ được phát cho uống có hạn chế. (22) Trẻ con hao mòn, đàn bà và thanh niên kiệt sức vì khát; họ ngã gục ở ngoài đường phố trong thành, ở các ngả đường ra cổng thành, chẳng còn chút sức lực nào nữa.
(23) Toàn dân gồm thanh niên, đàn bà con trẻ kéo nhau đến phản đối ông Út-di-gia và các thủ lãnh trong thành. Họ lớn tiếng kêu la và nói trước mặt các kỳ mục: (24) “Xin Thiên Chúa phân xử cho chúng tôi và các ông, vì các ông đã gây ra tội ác tày trời cho chúng tôi là không cầu hòa với con cái Át-sua. (25) Vì thế, giờ đây chẳng có ai đến cứu giúp chúng tôi. Trái lại, Thiên Chúa đã bán đứng chúng tôi vào tay chúng, khiến chúng tôi phải phơi xác trước mặt chúng, phải chết khát và bị tận diệt. (26) Vậy các ông hãy gọi ngay chúng lại và trao nộp thành cho dân của Hô-lô-phéc-nê và cho toàn thể đạo quân của ông tha hồ cướp phá. (27) Quả thật, thà bị chúng cướp bóc, thà phải làm nô lệ mà bảo toàn được tính mạng và khỏi phải thấy tận mắt cảnh con lìa đời, vợ hấp hối. (28) Chúng tôi xin thề nhân danh trời đất và Thiên Chúa chúng ta là Đức Chúa của cha ông chúng ta, Đấng trừng phạt chúng ta tùy theo tội ác chúng ta và lầm lỗi của cha ông chúng ta: các ông cứ thực hiện các điều ấy ngay ngày hôm nay.” (29) Mọi người òa lên khóc giữa đại hội và lớn tiếng kêu cầu cùng Đức Chúa là Thiên Chúa.
(30) Rồi ông Út-di-gia nói với họ: “Này anh em, can đảm lên! Chúng ta hãy kiên nhẫn cầm cự năm ngày nữa; trong thời gian ấy, Đức Chúa, Thiên Chúa chúng ta sẽ ngoảnh mặt lại thương xót chúng ta, vì Người sẽ chẳng bỏ rơi chúng ta mãi mãi. (31) Nếu những ngày ấy trôi qua mà chẳng ai đến cứu giúp, tôi sẽ làm theo lời anh em.” (32) Ông giải tán dân; ai nấy về trạm gác của mình. Họ đi đến các tường thành và các tháp canh của thành; còn vợ con thì cho về nhà. Trong thành, chẳng ai còn nhuệ khí.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'gdt', 8, '[PART] III. BÀ GIU-ĐI-THA
[SECTION] Tiểu sử bà Giu-đi-tha
(1) Trong những ngày ấy, bà Giu-đi-tha nghe biết những chuyện đó. Bà là con gái ông Mơ-ra-ri; ông Mơ-ra-ri là con ông Ốc; ông Ốc là con ông Giô-xếp; ông Giô-xếp là con ông Út-di-ên; ông Út-di-ên là con ông Khen-ki-gia; ông Khen-ki-gia là con ông Kha-na-ni-a; ông Kha-na-ni-a là con ông Ghít-ôn; ông Ghít-ôn là con ông Ra-pha-in; ông Ra-pha-in là con ông A-khi-túp; ông A-khi-túp là con ông Ê-li-a; ông Ê-li-a là con ông Khen-ki-gia; ông Khen-ki-gia là con ông Ê-li-áp; ông Ê-li-áp là con ông Nơ-than-ên; ông Nơ-than-ên là con ông Sơ-lu-mi-ên; ông Sơ-lu-mi-ên là con ông Xa-ra-xa-đai; ông Xa-ra-xa-đai là con ông Ít-ra-en. (2) Chồng bà là ông Mơ-na-se, người cùng chi tộc và gia tộc của bà. Ông đã chết vào mùa gặt lúa mạch. (3) Quả thật, khi ông đang trông coi những người bó lúa ở ngoài đồng, thì bị trúng nắng và ngã bệnh liệt giường. Ông chết ở Bai-ty-lu-a là thành của ông. Người ta chôn cất ông bên cạnh tổ tiên tại cánh đồng nằm giữa Đô-tha-im và Ba-la-môn. (4) Bà Giu-đi-tha ở góa đã được ba năm bốn tháng. (5) Bà làm một căn phòng nhỏ trên sân thượng nhà bà; bà mặc áo vải thô và áo góa phụ. (6) Bà ăn chay suốt thời gian ở góa, trừ các ngày áp sa-bát và các ngày sa-bát, các ngày áp ngày mồng một và các ngày mồng một, cũng như các ngày lễ ngày hội của nhà Ít-ra-en. (7) Dung mạo bà xinh đẹp, dáng điệu thật duyên dáng. Hơn nữa, ông Mơ-na-se, chồng bà, còn để lại cho bà vàng bạc, tôi tớ trai gái, súc vật và ruộng nương. Bà thừa hưởng tất cả tài sản ấy. (8) Không một ai chê trách bà được điều gì, vì bà rất kính sợ Thiên Chúa.
[SECTION] Bà Giu-đi-tha và các kỳ mục
(9) Bà Giu-đi-tha nghe được những lời dân chúng ta thán chống lại vị thủ lãnh, vì tinh thần họ đã ra bạc nhược bởi thiếu nước. Bà cũng được nghe tất cả những lời ông Út-di-gia đã nói với họ và lời ông thề sẽ nộp thành cho quân Át-sua sau năm ngày cầm cự. (10) Bà sai người nữ tỳ cai quản tất cả tài sản của bà đi mời hai vị kỳ mục của thành là các ông Kháp-rít và Khác-mít. (11) Các ông đến nhà bà. Bà nói với các ông:
“Thưa các vị thủ lãnh của dân cư ở Bai-ty-lu-a, xin nghe tôi nói đây. Lời các vị nói trước mặt dân hôm nay, cũng như lời các vị đã thề giữa Thiên Chúa và các vị đều không phải. Các vị nói là sẽ trao nộp thành cho kẻ thù, nếu trong thời gian các vị ấn định, Đức Chúa không ngoảnh lại cứu giúp chúng ta. (12) Vậy các vị là ai mà hôm nay dám thử thách Thiên Chúa và chiếm chỗ Thiên Chúa ở giữa con cái loài người? (13) Và giờ đây, các vị thử thách Đức Chúa toàn năng, nhưng đến muôn đời các vị cũng chẳng hiểu được gì. (14) Quả thật, đối với các vị, tâm khảm con người đã khôn dò, suy tưởng con người đã khôn thấu, thì làm sao các vị có thể hiểu được Thiên Chúa, Đấng làm nên mọi sự, làm sao hiểu được tư tưởng và thấu suốt được dự tính của Người? Không, nhất định không, thưa anh em, đừng chọc giận Đức Chúa, Thiên Chúa chúng ta. (15) Giả như trong năm ngày ấy, Người không muốn cứu giúp chúng ta, thì vào những ngày Người muốn, Người vẫn thừa sức bảo vệ chúng ta hoặc tiêu diệt chúng ta trước mặt kẻ thù. (16) Còn các vị, đừng đòi hỏi Đức Chúa, Thiên Chúa chúng ta, đảm bảo những quyết định của Người, bởi vì Thiên Chúa đâu phải là phàm nhân mà có thể bị đe dọa, đâu phải là con người mà chịu khuất phục. (17) Vì thế, một khi chúng ta kiên nhẫn đợi chờ Người cứu độ và kêu cầu Người đến cứu giúp, Người sẽ đoái nghe lời chúng ta, nếu điều ấy đẹp lòng Người.
(18) “Thật ra, trong các thế hệ của chúng ta, hay trong ngày hôm nay, không chi tộc hay gia tộc nào, không thị trấn nào hay thành phố nào của chúng ta thấy xuất hiện những kẻ thờ lạy các thần do tay người phàm làm ra, như đã xảy ra trước kia, (19) khiến cha ông chúng ta đã bị gươm đâm và cướp phá, nhiều người đã ngã gục trước mặt quân thù. (20) Còn chúng ta, chúng ta không nhận biết một thần nào khác ngoài Thiên Chúa; vì thế chúng ta hy vọng Người sẽ chẳng khinh thường chúng ta hoặc bất cứ ai trong giống nòi chúng ta.
(21) “Bởi vậy, nếu chúng ta bị bắt thì toàn cõi Giu-đê cũng bị mất, Nơi Thánh sẽ bị cướp phá. Thiên Chúa sẽ đòi chúng ta phải lấy máu mà đền vì đã để cho Nơi Thánh bị xúc phạm. (22) Anh em chúng ta bị sát hại, xứ sở phải lưu đày, gia nghiệp trở nên hoang tàn, trách nhiệm ấy Người sẽ trút lên đầu chúng ta giữa các dân chúng ta phải làm nô lệ; chúng ta sẽ trở thành cớ vấp ngã và nên trò cười cho những kẻ chinh phục chúng ta; (23) bởi vì cảnh nô lệ sẽ chẳng đưa chúng ta tới chỗ vẻ vang, trái lại, Đức Chúa, Thiên Chúa chúng ta sẽ biến nó thành nỗi tủi nhục. (24) Vậy giờ đây, thưa anh em, chúng ta hãy nêu gương cho anh em chúng ta, vì sinh mạng của họ gắn liền với chúng ta; cả Nơi Thánh, Đền Thờ và bàn thờ cũng đều tùy thuộc vào chúng ta.
(25) “Vì những lý do đó, chúng ta hãy tạ ơn Đức Chúa, Thiên Chúa chúng ta, Người đã thử thách chúng ta cũng như đã thử thách cha ông chúng ta. (26) Các vị hãy nhớ lại những điều Người đã làm cho ông Áp-ra-ham, những gì Người đã thử thách ông I-xa-ác, những gì đã xảy ra cho ông Gia-cóp ở Mê-xô-pô-ta-mi-a thuộc xứ Xy-ri, lúc ông đang chăn chiên cho ông La-ban là cậu của ông. (27) Đức Chúa không bắt chúng ta đi qua lửa như đã bắt các ông để thử lòng các ông và Người cũng không trừng phạt chúng ta, nhưng đánh phạt những ai đến gần Người, để cảnh cáo.”
(28) Ông Út-di-gia nói với bà: “Tất cả những điều bà nói là do thiện tâm mà ra; không ai cưỡng được lời bà. (29) Vì không phải hôm nay bà mới tỏ rõ tài khôn ngoan, nhưng ngay từ thời bà còn niên thiếu, toàn dân đã biết đến trí thông minh của bà. Những điều bà nghĩ trong lòng là hay. (30) Thế nhưng dân đang cực khổ vì khát, buộc chúng tôi phải làm như chúng tôi đã nói với họ và phải thề điều chúng tôi không thể vi phạm. (31) Vậy giờ đây, xin bà cầu nguyện cho chúng tôi, vì bà là một phụ nữ đạo hạnh, và Đức Chúa sẽ cho mưa rào đổ xuống đầy bể nước chúng tôi và chúng tôi sẽ không còn kiệt sức nữa.”
(32) Đoạn bà Giu-đi-tha nói với họ: “Xin các vị nghe đây, tôi sẽ làm một việc, mà việc này sẽ được truyền tụng cho con cháu thuộc giống nòi chúng ta, từ thế hệ này đến thế hệ kia. (33) Đêm nay, các vị đứng ở cổng thành; còn tôi, tôi sẽ đi ra với người nữ tỳ. Và nội trong những ngày các vị đã nói là sẽ trao nộp thành cho kẻ thù, Đức Chúa sẽ dùng tôi mà viếng thăm Ít-ra-en. (34) Còn các vị, đừng tìm cách dò xét công việc của tôi vì tôi sẽ chẳng nói cho các vị biết, cho đến khi những việc tôi làm được hoàn tất.” (35) Ông Út-di-gia và các thủ lãnh liền nói với bà: “Chúc bà ra đi bình an và xin Đức Chúa là Thiên Chúa hằng đi trước bà để báo oán kẻ thù của chúng ta!” (36) Rồi họ ra khỏi lều và đến vị trí của mình.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'gdt', 9, '[SECTION] Lời cầu nguyện của bà Giu-đi-tha
(1) Bà Giu-đi-tha sấp mặt xuống đất, rắc tro lên đầu, cởi áo vải thô đang mặc. Tại Đền Thờ của Thiên Chúa ở Giê-ru-sa-lem, vào một buổi dâng hương ban chiều, bà Giu-đi-tha lớn tiếng kêu cầu cùng Đức Chúa. Bà nói:
(2) “Lạy Đức Chúa, Thiên Chúa của cha con là Si-mê-ôn,
Ngài đã trao gươm vào tay người để trừng trị lũ ngoại bang.
Chúng cởi dây lưng người thiếu nữ,
làm cho nàng nhơ nhuốc, lột trần ra cho nàng xấu hổ
và cưỡng hiếp để làm nhục nàng.
Quả thật, Ngài đã nói: “Không được phép làm điều ấy”,
thế mà chúng lại làm như vậy.
(3) Vì thế, Ngài đã để cho các thủ lãnh của chúng bị sát hại,
và giường của chúng vấy máu,
nơi đây chúng lừa người ta, nay chúng bị lừa lại;
Ngài đánh phạt tên nô lệ cũng như người quyền thế,
đánh phạt người quyền thế ngự trên ngai vàng.
(4) Ngài để cho vợ chúng bị bắt đi,
con gái chúng phải lưu đày;
còn tất cả chiến lợi phẩm, Ngài chia cho đoàn con yêu quý,
vì họ nhiệt tâm nhiệt tình với Ngài;
máu nhuốc nhơ của chúng làm họ kinh tởm,
nên họ đã kêu cầu Ngài cứu giúp.
Lạy Thiên Chúa, lạy Thiên Chúa của con,
thân con góa bụa, xin đoái thương nghe lời.
(5) Quả vậy, quá khứ, hiện tại và tương lai,
tất cả đều do Ngài thực hiện.
Điều xảy ra bây giờ cũng như sắp xảy ra,
Ngài đều suy tính cả.
Điều gì đã xảy ra, cũng do Ngài suy tính.
(6) Ngài muốn vật gì, vật ấy liền xuất hiện và thưa:
“Có chúng con hiện diện!”
Quả thật, mọi đường lối của Ngài đều có sẵn,
và phán quyết của Ngài được tiên liệu hết.
(7) Kìa quân Át-sua, chúng đông vô kể,
chúng kiêu ngạo vì có nhiều chiến mã, kỵ binh.
Chúng vênh vang vì bộ binh hùng mạnh,
cậy vào giáo, vào khiên, vào cung tên cũng như nỏ bắn đá.
Chúng đâu nhận biết rằng
Ngài là Đức Chúa, Đấng tiêu diệt mọi thứ chiến tranh.
(8) Danh Ngài là Đức Chúa,
Ngài sẽ dùng quyền năng đập tan sức mạnh của chúng,
sẽ nổi trận lôi đình bẻ gãy dũng lực của chúng.
Quả thật, chúng lăm le xâm phạm đến nơi thánh của Ngài,
làm ô uế nơi Ngài ngự trị,
chốn tôn vinh danh thánh của Ngài.
Chúng dùng gươm chặt gãy góc cong của bàn thờ.
(9) Xin Ngài nhìn xem chúng ngạo mạn
mà trút cơn thịnh nộ lên đầu chúng.
Xin cho tay góa bụa này thêm mạnh mẽ
để hoàn thành điều con suy tính.
(10) Xin cho môi miệng con biết dùng xảo ngôn hoa ngữ,
để Ngài đánh đứa nô lệ cùng với tên thủ lãnh,
và đánh tên thủ lãnh cùng với đứa tôi đòi.
Xin Ngài dùng bàn tay nhi nữ
mà bẻ gãy thói kiêu căng của chúng.
(11) Vì sức mạnh của Ngài không dựa vào số đông,
quyền lực của Ngài chẳng ở nơi người mạnh thế.
Nhưng Ngài là Thiên Chúa của kẻ khiêm nhu,
là Đấng cứu giúp người hèn mọn,
Đấng đỡ nâng kẻ cô thế, Đấng bảo vệ người bị bỏ rơi,
Đấng Cứu Tinh của những ai thất vọng.
(12) Vâng, vâng, lạy Thiên Chúa của cha con,
Thiên Chúa của dân Ít-ra-en, Chúa Tể trời đất,
Đấng sáng tạo sông ngòi biển khơi, Vua muôn loài thụ tạo,
xin lắng nghe lời con khẩn cầu.
(13) Xin làm cho lời con nói và mưu chước của con
gây thương tích và sát hại những kẻ mưu toan làm tội ác
chống lại giao ước của Ngài, chống lại Nhà được thánh hiến
và đỉnh núi Xi-on, cũng như Nhà của con cái Ngài.
(14) Xin làm cho mọi dân nước và chi tộc nhận biết rằng:
Ngài là Thiên Chúa,
vị Thiên Chúa nắm giữ mọi quyền năng và sức mạnh;
và chẳng một ai khác, ngoại trừ Ngài,
có thể phù hộ dòng giống Ít-ra-en.”') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'gdt', 10, '[PART] IV. BÀ GIU-ĐI-THA VÀ TƯỚNG HÔ-LÔ-PHÉC-NÊ
[SECTION] Bà Giu-đi-tha đến trại tướng Hô-lô-phéc-nê
(1) Vậy sau khi dứt lời kêu cầu cùng Thiên Chúa Ít-ra-en và nói xong tất cả những lời ấy, (2) bà Giu-đi-tha không phủ phục nữa; bà trỗi dậy, gọi người nữ tỳ và đi xuống nhà, nơi bà thường ở trong các ngày sa-bát và ngày lễ. (3) Bà cởi tấm áo vải thô đang mặc, trút bỏ áo bà góa, lấy nước tắm rửa, xức dầu thơm hảo hạng, bới tóc chải đầu, trùm khăn lên, mặc áo sang trọng trước kia bà vẫn mặc khi ông Mơ-na-se, chồng bà, còn sống. (4) Bà đi dép, mang kiềng, đeo xuyến, nhẫn, bông tai và tất cả các đồ trang sức. Bà trang điểm rất lộng lẫy đến nỗi bất cứ người đàn ông nào cũng phải đưa mắt nhìn bà. (5) Rồi bà trao cho người nữ tỳ một bầu da đầy rượu, một vò dầu; bà chất đầy túi da: nào là bột lúa mạch, nào là bánh vả khô, nào là bánh làm bằng bột nguyên chất. Bà bọc tất cả các bình lại, rồi đặt lên vai người nữ tỳ.
(6) Cả hai đi ra phía cổng thành Bai-ty-lu-a. Họ thấy ông Út-di-gia và hai vị kỳ mục của thành là Kháp-rít và Khác-mít đang đứng đó. (7) Khi thấy diện mạo bà biến đổi và y phục ra khác, họ rất sửng sốt vì sắc đẹp của bà nên nói với bà: (8) “Xin Thiên Chúa của cha ông chúng ta ban ơn giúp sức cho bà, xin Người hoàn thành công việc bà sắp thực hiện cho con cái Ít-ra-en được hiển vinh và cho Giê-ru-sa-lem được ca tụng.”
(9) Bà Giu-đi-tha phục lạy Thiên Chúa, và nói với họ: “Xin các ông ra lệnh mở cổng thành cho tôi. Và tôi sẽ đi ra để hoàn tất những điều các ông vừa nói với tôi.” Thế rồi họ truyền cho các thanh niên mở cổng cho bà như bà yêu cầu. (10) Các thanh niên đã làm y như thế. Bà Giu-đi-tha và người nữ tỳ cùng đi ra. Dân quân trong thành cứ nhìn theo đang lúc bà từ núi đi xuống, mãi cho đến khi bà băng qua thung lũng; và họ chẳng còn thấy bà nữa.
(11) Bà Giu-đi-tha và người nữ tỳ đi thẳng vào thung lũng. Lính gác tiền đồn của quân Át-sua bắt gặp bà. (12) Chúng giữ bà lại và hỏi: “Bà thuộc dân nào? Từ đâu đến? Đi đâu?” Bà trả lời: “Tôi là một người phụ nữ Híp-ri; tôi bỏ họ mà trốn, vì họ sắp bị trao nộp làm miếng mồi ngon cho các ông. (13) Còn tôi, tôi đến gặp tướng Hô-lô-phéc-nê, vị chỉ huy quân đội các ông, để đưa những tin chính xác. Tôi sẽ chỉ cho tướng quân phải tiến theo con đường nào để bá chủ toàn miền núi mà không một người lính nào bị thiệt mạng!” (14) Bọn lính nghe bà nói, cứ nhìn chằm chằm vào mặt bà, vì trước mặt chúng, bà thực là một trang tuyệt thế giai nhân. Chúng nói với bà: (15) “Bà đã cứu được mạng mình rồi đấy, vì đã vội vàng xuống gặp chủ tướng chúng tôi. Vậy giờ đây, bà hãy đến lều của ông; một số người trong bọn chúng tôi sẽ hộ tống bà, cho tới khi giao bà trực tiếp cho ông. (16) Khi đứng trước mặt ông, bà đừng hồi hộp sợ hãi, nhưng hãy báo cho ông những điều bà vừa nói. Và ông sẽ đối xử tử tế với bà.” (17) Vậy chúng tuyển một trăm quân đi hộ vệ bà và người nữ tỳ; chúng dẫn hai người tới lều của tướng Hô-lô-phéc-nê.
(18) Từ khắp nơi trong doanh trại, người ta ùn ùn kéo nhau đến, vì tin bà Giu-đi-tha xuất hiện đã lan ra tới tận các lều; người ta đến vây quanh lấy bà, đang lúc bà đứng bên ngoài lều của tướng Hô-lô-phéc-nê, chờ người ta báo tin cho ông biết là bà đã đến. (19) Chúng sửng sốt vì sắc đẹp của bà; và cũng vì bà, chúng thán phục luôn con cái Ít-ra-en. Chúng bảo nhau: “Ai dám khinh thường dân ấy, một dân có những phụ nữ xinh đẹp như thế? Nếu còn để một tên đàn ông nào của chúng sống sót thì chẳng hay gì, vì những tên ấy có thể đánh lừa cả thiên hạ.”
(20) Các cận vệ của tướng Hô-lô-phéc-nê cũng như tất cả các võ quan của ông ra dẫn bà vào trong lều. (21) Tướng Hô-lô-phéc-nê đang nằm nghỉ trên giường có giăng màn may bằng vải điều dát vàng, bích ngọc và đá quý. (22) Người ta báo tin cho ông biết là bà Giu-đi-tha đã đến; ông ra tận cửa lều, có những người cầm đèn bằng bạc đi trước. (23) Khi bà Giu-đi-tha đến trước mặt ông và các võ quan của ông, thì tất cả mọi người đều sửng sốt vì nhan sắc của bà. Bà sấp mình xuống đất phủ phục trước mặt ông, nhưng thuộc hạ của ông nâng bà dậy.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'gdt', 11, '[SECTION] Hội ngộ lần đầu giữa bà Giu-đi-tha và tướng Hô-lô-phéc-nê
(1) Tướng Hô-lô-phéc-nê nói với bà Giu-đi-tha: “Này bà, cứ yên tâm, đừng hồi hộp sợ hãi, vì chưa bao giờ ta làm hại ai đã ưng phục vụ vua Na-bu-cô-đô-nô-xo, vua toàn cõi đất. (2) Ngay cả bây giờ, giả như dân tộc của bà đang ở trên núi kia đừng có khinh thường ta, thì ta cũng chẳng cầm giáo đánh chúng, chính chúng đã muốn rước họa vào thân. (3) Và giờ đây bà hãy nói cho ta biết tại sao bà đã lén bỏ chúng trốn đi mà đến với ta. Quả thật bà đến đây là thoát nạn rồi! Cứ yên tâm! Bà sẽ sống đêm nay và nhiều đêm khác nữa. (4) Thật thế, sẽ chẳng ai làm hại bà, mà ngược lại người ta sẽ đối xử tử tế với bà, như vẫn thường đối xử với các tôi tớ của vua Na-bu-cô-đô-nô-xo, chúa tể của ta.”
(5) Bà Giu-đi-tha nói với ông: “Xin ngài nghe nữ tỳ ngài nói; xin cho phép tôi tớ đây được hầu chuyện ngài. Đêm nay nữ tỳ ngài sẽ không dám nói lời thất thiệt với chủ tướng. (6) Và nếu ngài làm điều nữ tỳ ngài nói, thì Thiên Chúa sẽ đưa các hành động của ngài đến chỗ thành công, và chúa tể tôi sẽ không phải luống công về các điều người toan tính. (7) Quả thật, nhân danh mạng sống của vua Na-bu-cô-đô-nô-xo, vua toàn cõi đất, và nhân danh vương quốc hùng mạnh của vua, chính vua đã sai ngài đi sửa dạy trăm họ, nữ tỳ xin thề rằng: nhờ ngài, không những thiên hạ được làm tôi vua, mà cả dã thú, súc vật, chim trời cũng đều nhờ sức mạnh của ngài mà được sống dưới quyền vua Na-bu-cô-đô-nô-xo và tất cả triều đình của vua.
(8) “Thật thế, chúng tôi đã nghe biết ngài là người tài trí mưu lược: khắp cõi đất người ta loan truyền rằng trong toàn vương quốc, ngài là người hoàn hảo độc nhất vô nhị, kiến thức uyên bác, tài thao lược tuyệt vời. (9) Hơn nữa, những gì A-khi-ô đã nói trong hội nghị của ngài, chúng tôi đều nghe biết cả, bởi vì dân quân thành Bai-ty-lu-a đã cứu sống ông ta và ông ta đã tường thuật cho họ tất cả những điều ông ta đã nói lúc còn ở với ngài. (10) Vì thế, thưa tướng quân, thưa chủ tướng, xin ngài đừng bỏ qua lời ông ta nói, mà trái lại xin hãy lưu tâm, bởi vì đó là sự thật! Quả vậy, nòi giống chúng tôi sẽ không bị trừng phạt, không bị gươm đao khuất phục, nếu họ không đắc tội với Thiên Chúa của họ. (11) Vậy giờ đây tôi xin nói để chủ tướng khỏi mất công vô ích là cái chết sẽ giáng xuống trên họ nhãn tiền, vì tội lỗi đang vây hãm họ, bởi họ chọc giận Thiên Chúa của họ, mỗi khi vi phạm điều không được phép. (12) Quả thật, một khi thiếu thực phẩm, khan hiếm nước, thì họ muốn giết súc vật của họ và tất cả những gì Thiên Chúa đã ra lệnh cho họ không được ăn, như đã ghi trong Lề Luật. (13) Cả những lúa mì dâng làm của lễ đầu mùa, cả rượu và dầu nộp thuế thập phân –những thứ này được thánh hiến và dành riêng cho các tư tế là những người phục vụ trước nhan Thiên Chúa của chúng tôi ở Giê-ru-sa-lem–, họ đã quyết định dùng hết những thứ mà không một thường dân nào được phép đụng tay tới. (14) Họ cử người lên Giê-ru-sa-lem –vì thật ra dân cư ở đó cũng phải làm như vậy– để xin hội đồng kỳ mục cho phép dùng và mang về cho dân. (15) Vậy ngày nào phép đó được công bố và thi hành, thì chính ngày ấy họ sẽ bị nộp cho ngài tiêu diệt.
(16) “Vì thế, chính nữ tỳ của ngài đây, khi biết rõ sự thể, đã lén bỏ họ mà trốn thoát. Thiên Chúa sai tôi đến để cùng với ngài thực hiện những việc mà trên toàn cõi đất, bất cứ ai nghe nói cũng phải rụng rời tay chân. (17) Nữ tỳ của ngài đây là người sùng đạo, sớm hôm thờ phượng Thiên Chúa trên trời. Và giờ đây, thưa chủ tướng, tôi xin ở lại bên ngài; và đêm đêm, xin cho phép nữ tỳ ngài được ra bờ khe để cầu nguyện cùng Thiên Chúa. Người sẽ cho tôi biết khi nào họ phạm tội. (18) Bấy giờ tôi sẽ trở lại báo cho ngài; ngài sẽ xuất trận cùng với toàn thể đạo quân và không một người nào trong họ có thể chống nổi ngài. (19) Tôi sẽ hướng dẫn ngài đi khắp xứ Giu-đê cho tới khi đến thành Giê-ru-sa-lem. Tôi sẽ đưa chiến xa của ngài vào giữa thành. Họ như đàn chiên không người chăn dắt, nhưng chính ngài sẽ chăn dắt họ. Sẽ không có một con chó nào dám sủa trước mặt ngài. Vì tất cả những điều ấy, tôi đã được linh tính báo cho biết và tôi được sai đến thuật lại cho ngài.”
(20) Lời lẽ của bà Giu-đi-tha làm vừa lòng tướng Hô-lô-phéc-nê và các võ quan của ông. Chúng thán phục trí khôn ngoan của bà và nói: (21) “Từ chân trời này đến chân trời kia trên khắp cùng cõi đất, chưa hề thấy một phụ nữ nào dung nhan kiều diễm, ngôn từ sắc sảo như thế!” (22) Bấy giờ tướng Hô-lô-phéc-nê nói với bà: “Thiên Chúa hành động thật chí lý khi sai bà đi trước dân bà, để chúng ta nắm được thế mạnh, còn những kẻ khinh miệt chúa tể của tôi phải diệt vong. (23) Phần bà, trông bà duyên dáng quá, lời bà nói dịu dàng biết bao. Quả thật, nếu bà làm được như bà nói, thì Thiên Chúa của bà sẽ là Thiên Chúa của tôi. Bà sẽ ở trong cung điện vua Na-bu-cô-đô-nô-xo, bà sẽ lừng danh trên toàn cõi đất.”') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'gdt', 12, '(1) Ông ra lệnh đưa bà vào gian phòng trưng bày các đồ bằng bạc của ông, và truyền thết bà món ăn riêng của ông, lại mời bà uống thứ rượu dành riêng cho ông. (2) Nhưng bà Giu-đi-tha nói: “Tôi sẽ không dùng những thức ăn ấy để khỏi lỗi luật; những thứ tôi mang theo đây cũng đủ rồi.” (3) Tướng Hô-lô-phéc-nê nói với bà: “Nhỡ hết lương thực bà mang theo, thì chúng tôi kiếm đâu ra những thứ như thế để cung cấp cho bà? Vì chẳng có ai thuộc nòi giống bà đang ở với chúng tôi.” (4) Bà Giu-đi-tha nói với ông: “Thưa chủ tướng, tôi xin lấy mạng sống ngài mà thề: nô tỳ ngài đây chưa dùng hết lương thực mang theo, thì Đức Chúa đã dùng bàn tay này mà thực hiện điều Người đã định!” (5) Sau đó, các thuộc hạ của tướng Hô-lô-phéc-nê đưa bà vào lều. Bà ngủ cho tới nửa đêm và đến gần sáng thì thức dậy. (6) Bà sai người đến thưa với tướng Hô-lô-phéc-nê rằng: “Xin chủ tướng ra lệnh để cho nô tỳ ngài được đi cầu nguyện.” (7) Tướng Hô-lô-phéc-nê ra lệnh cho các cận vệ không được ngăn trở bà. Bà ở trong doanh trại đã được ba ngày. Ban đêm bà ra bờ khe Bai-ty-lu-a, trầm mình trong suối nước thuộc doanh trại. (8) Khi lên bờ, bà cầu nguyện cùng Đức Chúa, Thiên Chúa Ít-ra-en, xin Người hướng dẫn bà đi đúng đường lối để con cái dân Người được hồi phục. (9) Thanh sạch rồi, bà trở về và ở lại trong lều cho tới khi người ta mang bữa ăn chiều đến.
[SECTION] Bà Giu-đi-tha dự tiệc với tướng Hô-lô-phéc-nê
(10) Đến ngày thứ tư, tướng Hô-lô-phéc-nê mở tiệc khoản đãi riêng các thân hữu, nhưng không mời một ai trong số các võ quan. (11) Ông nói với hoạn quan Ba-gô-át, người trông coi tất cả tài sản của ông: “Ngươi hãy đi thuyết phục cô gái Híp-ri đang ở lều ngươi, đến đây ăn uống với chúng ta. (12) Này, thật là bẽ mặt, nếu chúng ta để người đàn bà xinh đẹp như thế ra đi mà chẳng ân ái với nàng; nếu ta không dụ dỗ được nàng, nàng sẽ chê cười chúng ta.” (13) Ông Ba-gô-át ra khỏi lều tướng Hô-lô-phéc-nê, đến gặp bà Giu-đi-tha và nói: “Nữ tỳ xinh đẹp kia ơi, đừng ngại đến gặp chủ tướng của tôi để được ông trọng đãi, để được cùng chúng tôi hân hoan uống rượu, và để ngày hôm nay cô nương trở thành một trong số phụ nữ Át-sua được vào ở trong cung điện vua Na-bu-cô-đô-nô-xo.” (14) Bà Giu-đi-tha trả lời: “Tôi là ai mà dám cưỡng lại chủ tướng? Bất cứ điều gì người lấy làm ưa thích, tôi xin mau mắn thi hành; đó cũng là niềm vui của tôi cho đến ngày tôi nhắm mắt.”
(15) Bà trỗi dậy, trang điểm, sửa soạn xiêm y, đeo tất cả đồ trang sức. Người nữ tỳ đi trước, trải xuống đất, trước mặt tướng Hô-lô-phéc-nê, những tấm thảm lông chiên ông Ba-gô-át đã trao cho bà; hằng ngày bà vẫn trải những tấm thảm ấy ra khi dùng bữa. (16) Bà Giu-đi-tha đi vào và sấp mình phục lạy. Trái tim tướng Hô-lô-phéc-nê rung động vì bà; tâm hồn ngất ngây, ông thèm khát được chung chăn gối với bà; từ ngày trông thấy bà, ông những tìm dịp quyến rũ bà. (17) Tướng Hô-lô-phéc-nê nói với bà: “Uống đi em! Ta cùng vui đi nào!” (18) Bà Giu-đi-tha liền nói: “Thiếp xin uống hầu chủ tướng. Quả thật đối với thiếp, từ lúc chào đời cho đến hôm nay, chưa bao giờ thiếp được vẻ vang như thế này.” (19) Rồi bà cầm lấy những của ăn thức uống người nữ tỳ đã dọn sẵn mà ăn uống trước mặt tướng Hô-lô-phéc-nê. (20) Ông đắm đuối vì bà nên uống rất nhiều rượu; có lẽ suốt cả đời, chưa ngày nào ông uống nhiều như vậy.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'gdt', 13, '(1) Trời đã về khuya, các thuộc hạ của tướng Hô-lô-phéc-nê vội vàng lui gót. Từ bên ngoài, ông Ba-gô-át đóng cửa lều lại, và đuổi khéo những người còn túc trực bên chủ tướng. Chúng đi ngủ. Tất cả đều mệt lả vì quá chén. (2) Chỉ còn một mình bà Giu-đi-tha ở lại trong lều, và tướng Hô-lô-phéc-nê nằm sóng sượt trên giường vì say khướt. (3) Bà Giu-đi-tha đã dặn người nữ tỳ đứng ngoài phòng ngủ của bà phải canh chừng cẩn thận lúc bà đi ra ngoài như mọi khi, vì bà nói là sẽ đi ra ngoài cầu nguyện. Bà cũng nói với ông Ba-gô-át như thế.
(4) Sau khi mọi người từ lớn chí bé đã rời khỏi lều của tướng Hô-lô-phéc-nê, không còn ai ở lại trong phòng ngủ nữa, thì bà Giu-đi-tha đứng bên cạnh giường của ông, thầm nghĩ trong lòng rằng:
“Lạy Đức Chúa là Thiên Chúa các đạo binh.
Giờ đây xin nhìn xem các việc tay con sắp làm
để Giê-ru-sa-lem được tán dương ca tụng.
(5) Vì chính bây giờ là lúc
Ngài củng cố phần gia nghiệp của Ngài,
và thực hiện điều con đang dự tính,
để đập tan quân thù nổi dậy chống chúng con.”
(6) Đoạn bà tiến đến phía đầu giường của tướng Hô-lô-phéc-nê, gỡ lấy thanh đại đao của ông, (7) rồi lại gần giường, nắm lấy tóc ông. Bà nói: “Lạy Đức Chúa, Thiên Chúa Ít-ra-en, giờ đây xin ban sức mạnh cho con!” (8) Bà lấy hết sức bình sinh chém vào cổ ông hai nhát cho đầu lìa khỏi thân. (9) Rồi bà lăn xác ông xuống đất, tháo mùng ra khỏi cọc. Một lát sau, bà đi ra và trao thủ cấp tướng Hô-lô-phéc-nê cho người nữ tỳ. (10) Cô bỏ thủ cấp vào cái túi da đựng thức ăn; rồi cả hai cùng đi ra như thói quen vẫn làm khi đi cầu nguyện. Họ băng qua doanh trại, đi dọc theo khe, tiến lên núi Bai-ty-lu-a và đến cổng thành.
[SECTION] Bà Giu-đi-tha đem thủ cấp tướng Hô-lô-phéc-nê về Bai-ty-lu-a
(11) Từ đằng xa, bà Giu-đi-tha lên tiếng gọi những người canh cổng: “Mở cổng, mở cổng mau! Thiên Chúa, Thiên Chúa chúng ta ở cùng chúng ta; Người vẫn còn biểu dương sức mạnh của Người trong Ít-ra-en và thi thố quyền năng của Người chống lại kẻ thù, như Người đã làm hôm nay!” (12) Vừa nghe tiếng bà, dân quân trong thành vội vã chạy xuống cổng và đi mời các kỳ mục. (13) Tất cả mọi người từ lớn chí bé ùn ùn kéo nhau đến, vì không ai ngờ rằng bà có thể trở về, họ mở cổng, nghênh đón hai người: nhóm lửa cho sáng rồi đứng vây quanh. (14) Bà Giu-đi-tha nói với họ thật to: “Hãy ca ngợi Thiên Chúa! Hãy ca ngợi Người, hãy ca ngợi Thiên Chúa! Người đã không rút lại lòng thương xót của Người đối với nhà Ít-ra-en, nhưng đêm nay đã dùng tay tôi mà nghiền nát kẻ thù của chúng ta.” (15) Rồi bà lôi cái thủ cấp ra khỏi túi da cho họ thấy và nói: “Đây là thủ cấp Hô-lô-phéc-nê, đại tướng chỉ huy quân đội Át-sua, và đây là cái mùng ông ta đã nằm trong lúc say túy lúy. Đức Chúa đã dùng bàn tay nhi nữ mà hạ ông ta. (16) Thật vậy, có Đức Chúa hằng sống, Đấng đã giữ gìn tôi trên đường tôi đi, tôi xin thề: “Nhan sắc tôi đã quyến rũ ông ta, khiến ông ta phải mất mạng, mà chưa kịp phạm tội với tôi cho tôi phải nhuốc nhơ và xấu hổ.”
(17) Toàn dân hết sức kinh ngạc. Họ sấp mình thờ lạy Thiên Chúa và đồng thanh nói: “Lạy Thiên Chúa chúng con, xin chúc tụng Ngài. Hôm nay Ngài hủy diệt kẻ thù của dân Ngài!” (18) Ông Út-di-gia nói với bà:
“Này trang nữ kiệt, bà được Thiên Chúa Tối Cao ban phúc
hơn tất cả các phụ nữ trên cõi đất này.
Chúc tụng Đức Chúa là Thiên Chúa,
Đấng dựng nên trời đất;
Người đã hướng dẫn bà chặt đầu tướng giặc!
(19) Vì cho đến muôn đời muôn thuở,
những ai hằng nhớ đến sức mạnh của Thiên Chúa
sẽ không lãng quên lòng trông cậy bà đặt nơi Người.
(20) Nguyện xin Thiên Chúa thực hiện cho bà những điều ấy
để muôn đời bà được tán dương.
Xin Người viếng thăm và ban cho bà muôn phúc lộc,
vì bà đã không tiếc mạng sống mình
khi nòi giống chúng ta lâm cảnh nhục nhã;
bà đã cứu chúng ta thoát họa diệt vong
vì bà đã sống ngay thẳng trước nhan Thiên Chúa.”
Toàn dân đáp lại: “A-men! A-men!”') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'gdt', 14, '[PART] V. CHIẾN THẮNG
[SECTION] Người Do-thái vây hãm doanh trại quân Át-sua
(1) Bà Giu-đi-tha nói với dân thành Bai-ty-lu-a: “Thưa anh em, xin nghe tôi nói đây. Anh em hãy đem thủ cấp này bêu lên lỗ châu mai trên tường thành của anh em. (2) Rồi khi bình minh vừa ló rạng và mặt trời xuất hiện trên mặt đất, mỗi người trong anh em hãy cầm lấy vũ khí, tất cả các người cường tráng hãy ra khỏi thành. Anh em hãy đặt một vị chỉ huy cai quản những người này và làm như đi xuống cánh đồng tấn công tiền đồn con cái Át-sua; nhưng đừng có xuống! (3) Quân Át-sua cũng sẽ lấy toàn bộ binh giáp vũ khí, đi ra trạm gác, đánh thức các tướng lãnh của mình, rồi ồ ạt tuốn đến lều Hô-lô-phéc-nê, nhưng không tìm thấy ông ta. Nỗi kinh hoàng sẽ ập xuống trên chúng, nên chúng sẽ bỏ chạy, trốn thoát anh em. (4) Bấy giờ anh em và toàn thể dân cư trên khắp lãnh thổ Ít-ra-en sẽ đuổi theo và hạ sát chúng trên đường chúng tháo chạy.
(5) “Nhưng trước khi làm những việc ấy, anh em hãy gọi ông A-khi-ô người Am-mon đến đây cho tôi, để ông thấy và nhận ra kẻ đã dám miệt thị nhà Ít-ra-en và sai ông đến với chúng ta như đi vào chỗ chết.” (6) Vậy người ta gọi ông A-khi-ô đang ở nhà ông Út-di-gia đến. Khi vừa tới nơi, ông thấy một người trong hội nghị toàn dân đang cầm thủ cấp tướng Hô-lô-phéc-nê, ông liền sấp mặt xuống đất, khiếp vía kinh hồn. (7) Nhưng người ta vực ông dậy, ông lại nằm vật dưới chân bà Giu-đi-tha, phủ phục trước mặt bà và nói:
“Bà đáng được chúc tụng trong mọi lều trại ở Giu-đa
và trong tất cả các dân nước,
khi nghe đến danh bà, ai cũng đều kinh hãi!
(8) “Giờ đây, xin bà thuật lại cho tôi những việc bà đã làm trong mấy ngày qua!” Bà Giu-đi-tha đứng giữa dân chúng, kể lại cho ông tất cả những việc bà đã làm từ ngày bà ra đi cho đến lúc bà đang nói với họ. (9) Bà vừa dứt lời, toàn dân lớn tiếng hoan hô và reo mừng vang dậy khắp thành. (10) Khi thấy tất cả những việc Thiên Chúa của Ít-ra-en đã làm, ông A-khi-ô vững tin vào Thiên Chúa. Ông chịu phép cắt bì và được nhận vào nhà Ít-ra-en kể từ ngày ấy.
(11) Bình minh vừa ló rạng, người ta bêu đầu Hô-lô-phéc-nê ở tường thành; đàn ông Ít-ra-en người nào cũng cầm khí giới, đi ra theo từng toán đến các đường đèo lên núi. (12) Vừa thấy họ, con cái Át-sua liền phái người đến với các vị chỉ huy. Những người này đến gặp các tướng, các người chỉ huy một ngàn quân và tất cả các thủ lãnh của chúng. (13) Rồi chúng đến lều của tướng Hô-lô-phéc-nê và nói với Ba-gô-át, người trông coi tất cả các tài sản của ông ta: “Xin ông đánh thức chủ tướng, vì lũ nô lệ cả gan xuống phía chúng ta gây chiến với chúng ta để chuốc lấy họa diệt vong.” (14) Ba-gô-át đi vào, lay động bức rèm cửa lều, vì tưởng là tướng Hô-lô-phéc-nê đang ngủ với bà Giu-đi-tha. (15) Nhưng không thấy động tĩnh gì, Ba-gô-át liền vén rèm đi vào phòng ngủ và thấy ông ta đã chết, xác bị quăng ở cửa lều mà không có đầu. (16) Hắn kêu thất thanh, khóc lóc, rên la, tru tréo, xé áo mình ra. (17) Hắn bước vào lều bà Giu-đi-tha, nhưng chẳng thấy bà đâu. Hắn lao mình về phía quân lính, kêu la ầm ĩ: (18) “Quân nô lệ xảo quyệt! Chỉ một con mụ Híp-ri thôi đã mang ô nhục đến cho nhà vua Na-bu-cô-đô-nô-xo! Vì này tướng Hô-lô-phéc-nê đang nằm dưới đất không còn đầu nữa.” (19) Vừa nghe những lời ấy, các người đứng đầu quân đội Át-sua xé nhung phục ra, kinh hồn bạt vía, kêu la, tru tréo ở giữa doanh trại.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'gdt', 15, '(1) Khi vừa nghe biết chuyện mới xảy ra, những người còn ở trong lều trại đều thất kinh. (2) Sợ hãi và kinh hoàng ập xuống trên đầu chúng; không còn người nào bên cạnh người nào, nhưng chúng nhất loạt chạy tứ tán, theo mọi ngả đường ở đồng bằng cũng như trên miền núi. (3) Cả những quân đóng trên núi chung quanh Bai-ty-lu-a cũng quay lưng chạy trốn. Bấy giờ con cái Ít-ra-en –những người có khả năng chiến đấu– đều đổ xô đuổi theo chúng. (4) Ông Út-di-gia phái người đến Bai-tô-mét-tha-im, Be-bai, Khô-bai, Cô-la và khắp lãnh thổ Ít-ra-en báo tin về những sự việc đã xảy ra, để mọi người đổ xô đuổi theo quân giặc mà tiêu diệt chúng. (5) Vừa nghe tin ấy, con cái Ít-ra-en, mọi người đều nhất loạt xông ra đánh và tàn sát chúng, cho đến tận Khô-ba. Cả những người từ Giê-ru-sa-lem và từ khắp miền núi cũng đến hỗ trợ, vì họ đã được báo tin về những việc xảy ra trong doanh trại quân thù. Các người ở Ga-la-át và Ga-li-lê giáng một đòn chí tử vào sườn quân địch, đuổi theo chúng cho tới Đa-mát và đến tận lãnh thổ của chúng. (6) Còn những người khác ở Bai-ty-lu-a thì tràn vào doanh trại quân Át-sua mà cướp phá; vì vậy họ trở nên rất giàu. (7) Chém giết xong, con cái Ít-ra-en trở về, chiếm hữu tất cả những gì còn lại. Dân ở các làng mạc, các lều trại miền núi hay đồng bằng cũng chiếm được nhiều chiến lợi phẩm. Số chiến lợi phẩm chiếm được nhiều vô kể.
[SECTION] Tạ ơn
(8) Thượng tế Giô-gia-kim và hội đồng kỳ mục con cái Ít-ra-en ở Giê-ru-sa-lem đến mục kích những sự tốt lành Đức Chúa đã làm cho dân Ít-ra-en, và diện kiến bà Giu-đi-tha để chúc mừng. (9) Khi vào nhà bà, mọi người đồng thanh chúc tụng và nói với bà:
“ Bà làm cho Giê-ru-sa-lem hãnh diện,
cho Ít-ra-en vinh hiển,
cho giống nòi chúng ta được vinh dự lớn lao.
(10) Chính tay bà làm nên những việc ấy
và thực hiện những điều tốt lành cho nhà Ít-ra-en.
Thiên Chúa hài lòng về những việc của bà.
Xin Thiên Chúa toàn năng ban cho bà nhiều ơn phúc,
đến muôn thuở muôn đời.”
Mọi người đáp: “A-men.”
(11) Toàn dân cướp đoạt doanh trại suốt ba mươi ngày. Người ta tặng bà Giu-đi-tha cái lều của tướng Hô-lô-phéc-nê, tất cả vật dụng bằng bạc, cùng với giường, chậu và mọi thứ đồ đạc khác của ông ta. Bà nhận và chất tất cả lên lưng lừa. Bà cho thắng các cỗ xe và chất hết lên đó. (12) Hết thảy phụ nữ Ít-ra-en đều chạy ùa ra để nhìn xem bà; họ ca tụng bà, một số phụ nữ tổ chức múa nhảy để chúc mừng. Bà Giu-đi-tha tay cầm chùm hoa sim, phân phát lá hoa cho các phụ nữ tháp tùng bà. (13) Bà và các phụ nữ tháp tùng đội vòng hoa kết bằng cành ô-liu; bà đi trước toàn dân, dẫn đầu đoàn phụ nữ múa nhảy. Tất cả đàn ông Ít-ra-en mang vũ khí và đội vòng hoa đi sau, miệng hát thánh thi. (14) Bà Giu-đi-tha đứng giữa con cái Ít-ra-en xướng lên bài ca tạ ơn và toàn dân họa theo.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'gdt', 16, '(1) Bà Giu-đi-tha cất tiếng nói:
“ Hãy ca ngợi Thiên Chúa của tôi, theo nhịp trống,
hát lên mừng Người, rập tiếng chiêng,
trầm bổng hòa vang thánh ca cùng thánh vịnh,
hãy suy tôn và cầu khẩn danh Người.
(2) Vì Đức Chúa là vị thần tiêu diệt chiến tranh,
Người đặt doanh trại ngay giữa lòng dân thánh,
để giải thoát tôi khỏi tay phường bách hại.
(3) Quân Át-sua đến từ núi rừng Phương Bắc,
kéo nhau đến hàng vạn quân binh,
chúng đông đảo làm tắt nghẽn khe suối,
chiến mã chúng che lấp cả núi đồi.
(4) Chúng dự định đốt cháy quê hương tôi,
tuốt lưỡi gươm hạ sát đoàn trai trẻ,
lũ bé thơ, quẳng bừa dưới đất,
bọn thiếu nhi, đem giết tha hồ,
còn trinh nữ, bắt đem đi hết.
(5) Nhưng Đức Chúa toàn năng đã dùng tay nhi nữ
khiến chúng phải tháo lui.
(6) Quả thật người hùng của chúng,
thanh niên không thắng nổi,
con cái Ti-tan chẳng hạ được y,
người khổng lồ cũng vô phương áp đảo.
Thế mà Giu-đi-tha, con gái Mơ-ra-ri,
đã dùng nhan sắc khiến y phải tê liệt.
(7) Để vực dậy nhà Ít-ra-en đang điêu đứng,
áo góa phụ, bà trút bỏ đi,
dầu ngát thơm điểm tô gương mặt,
(8) dải khăn xinh buộc gọn tóc trên đầu,
áo lụa mịn làm y mê mẩn.
(9) Dép bà đi khiến y hoa mắt, nhan sắc bà giam hãm hồn y,
cổ họng y, thanh đại đao xuyên thủng.
(10) Quân Ba-tư run rẩy khi thấy bà táo bạo,
dân Mê-đi khiếp đảm vì bà quá can trường.
(11) Bấy giờ dân tôi đang khốn khổ
cất tiếng hò la làm chúng phải thất kinh,
người yếu nhược hô lên, khiến chúng hoảng hồn;
họ cất tiếng, chúng quay lưng tháo chạy.
(12) Lũ trẻ thơ đã đâm giết chúng,
đả thương chúng như những kẻ đào binh.
Chúng phải tiêu vong vì Đức Chúa của tôi đánh phạt.
(13) Mừng Chúa Tể tôi thờ, tôi hát bài ca mới:
Lạy Chúa, Ngài vĩ đại vinh quang,
mạnh mẽ lạ lùng, không ai thắng được.
(14) Muôn loài Ngài dựng lên phải phụng thờ Ngài,
vì Ngài đã phán, chúng liền xuất hiện,
Ngài gửi sinh khí tới, chúng được tác thành.
Tiếng Ngài phán ra, nào ai chống nổi!
(15) Núi với biển có ầm ầm chuyển động,
đá có chảy tan như sáp trước mặt Ngài,
thì đối với những ai hằng kính sợ,
Ngài vẫn tỏ lòng nhân hậu từ bi.
(16) Quả thật, hiến tế dâng lên Ngài,
hương thơm có ngào ngạt,
cũng chẳng đáng kể chi;
lễ toàn thiêu với nhiều mỡ béo
càng không đáng kể gì.
Còn những ai kính sợ Đức Chúa muôn đời vẫn lớn lao.
(17) Khốn thay dân tộc nào dám đứng lên chống lại giống nòi tôi!
Đức Chúa toàn năng sẽ trừng phạt chúng
trong ngày Người xét xử.
Người sẽ khiến lửa thiêu, khiến giòi bọ rúc rỉa thân xác chúng.
Chúng sẽ phải than khóc và đau khổ muôn đời!”
(18) Vừa đến Giê-ru-sa-lem, cả đoàn người thờ lạy Thiên Chúa. Sau khi đã thanh tẩy, toàn dân thượng tiến lễ toàn thiêu, lễ vật khấn hứa và tự nguyện. (19) Bà Giu-đi-tha cũng tiến dâng mọi đồ đạc của tướng Hô-lô-phéc-nê mà dân đã tặng bà; cả cái mùng đã lấy ở phòng ngủ của ông ta, bà cũng dâng làm lễ vật tru hiến kính Thiên Chúa. (20) Dân chúng hân hoan mừng lễ ở Giê-ru-sa-lem trước Nơi Thánh ròng rã ba tháng trời; bà Giu-đi-tha cũng ở lại với họ.
[SECTION] Tuổi già và cái chết của bà Giu-đi-tha
(21) Sau những ngày đó, ai nấy trở về phần đất gia nghiệp của mình. Bà Giu-đi-tha trở lại Bai-ty-lu-a và cư ngụ trong phần đất bà vẫn có. Ngay trong buổi sinh thời, tiếng tăm bà đã lừng lẫy khắp nơi. (22) Nhiều người muốn kết duyên với bà, nhưng chẳng một ai được bà ưng thuận, trong suốt đời bà, kể từ khi chồng bà là ông Mơ-na-se khuất núi và về sum họp với tổ tiên. (23) Danh tiếng bà mỗi ngày một thêm lừng lẫy. Bà sống tại nhà chồng bà, tuổi đời rất cao, thọ được một trăm lẻ năm tuổi. Bà trả tự do cho người nữ tỳ. Cuối cùng bà qua đời ở Bai-ty-lu-a và được chôn cất trong hang mộ bên cạnh ông Mơ-na-se, chồng bà. (24) Nhà Ít-ra-en khóc thương bà suốt bảy ngày. Trước khi nhắm mắt, bà Giu-đi-tha đã phân phát của cải cho tất cả bà con bên chồng cũng như cho thân quyến của bà.
(25) Không còn một ai làm cho con cái Ít-ra-en phải sợ nữa, trong suốt thời bà Giu-đi-tha còn sống cũng như mãi về sau, khi bà đã qua đời.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;