INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'plm', 1, '[SECTION] Lời chào thăm
(1) Phao-lô, kẻ bị tù vì Đức Ki-tô Giê-su, cùng với người anh em là Ti-mô-thê, gửi anh Phi-lê-môn, cộng sự viên thân mến của chúng tôi, (2) cùng chị Áp-phi-a và anh Ác-khíp-pô, chiến hữu của chúng tôi, đồng thời kính gửi Hội Thánh họp tại nhà anh. (3) Chúc anh chị em được đầy tràn ân sủng và bình an của Thiên Chúa, Cha chúng ta, và của Chúa Giê-su Ki-tô.
[SECTION] Tạ ơn và cầu nguyện
(4) Tôi luôn luôn tạ ơn Thiên Chúa, khi nhớ đến anh trong lời cầu nguyện, (5) bởi được nghe nói về lòng mến và lòng tin của anh đối với Chúa Giê-su: lòng mến và lòng tin ấy có ích cho mọi người trong dân thánh. (6) Chớ gì lòng tin mà anh chia sẻ với chúng tôi trở nên hữu hiệu, giúp anh hiểu biết tất cả những gì tốt chúng ta có thể làm để phục vụ Đức Ki-tô. (7) Thật thế, tôi rất vui mừng và lấy làm an ủi, khi thấy đức bác ái của anh, bởi vì, thưa anh, anh đã làm cho lòng trí các người trong dân thánh được phấn khởi.
[SECTION] Can thiệp cho Ô-nê-xi-mô
(8) Vì thế, mặc dầu nhờ kết hợp với Đức Ki-tô, tôi có đủ mạnh dạn để truyền cho anh làm điều anh phải làm. (9) Nhưng tôi thích kêu gọi lòng bác ái của anh hơn, để xin anh làm điều đó. Tôi, Phao-lô, một người đã già và hơn nữa, một người đang bị tù vì Đức Ki-tô Giê-su, (10) tôi van xin anh cho đứa con của tôi, đứa con tôi đã sinh ra trong cảnh xiềng xích, đó là Ô-nê-xi-mô, (11) kẻ xưa kia đối với anh là vô dụng, thì nay đã thành người hữu dụng cho cả anh lẫn tôi, (12) tôi xin gửi nó về cho anh; xin anh hãy đón nhận nó như người ruột thịt của tôi. (13) Phần tôi, tôi cũng muốn giữ nó ở lại với tôi, để nó thay anh mà phục vụ tôi trong khi tôi bị xiềng xích vì Tin Mừng. (14) Nhưng tôi chẳng muốn làm gì mà không có sự chấp thuận của anh, kẻo việc nghĩa anh làm có vẻ miễn cưỡng, chứ không phải tự nguyện. (15) Nó đã xa anh một thời gian, có lẽ chính là để anh được lại nó vĩnh viễn, (16) không phải được lại một người nô lệ, nhưng thay vì một người nô lệ, thì được một người anh em rất thân mến; đối với tôi đã vậy, phương chi đối với anh lại càng thân mến hơn biết mấy, cả về tình người cũng như về tình anh em trong Chúa. (17) Vậy, nếu anh coi tôi là bạn đồng đạo, thì xin anh hãy đón nhận nó như đón nhận chính tôi. (18) Nếu nó đã làm thiệt hại anh hoặc mắc nợ anh điều gì, thì xin để tôi nhận cả... (19) Chính tôi, Phao-lô, tự tay viết điều này: tôi sẽ hoàn trả lại. Tôi khỏi cần nói với anh là anh còn mắc nợ tôi: món nợ đó là chính anh. (20) Phải, thưa anh, xin anh cho tôi được hưởng niềm vui đó trong Chúa. Anh hãy làm cho lòng trí tôi được phấn khởi trong Đức Ki-tô. (21) Tôi viết thư này cho anh với niềm tin tưởng là anh sẽ nghe theo. Tôi biết rằng anh sẽ còn làm hơn những gì tôi xin nữa.
[SECTION] Những lời dặn dò, thăm hỏi
(22) Đồng thời, xin anh dọn cho tôi một chỗ ở, bởi vì tôi hy vọng là nhờ lời anh em cầu nguyện, tôi sẽ được trở về với anh em.
(23) Anh Ê-páp-ra, người bạn tù với tôi trong Đức Ki-tô Giê-su, gửi lời chào anh, (24) cùng với các cộng sự viên của tôi là Mác-cô, A-rít-ta-khô, Đê-ma và Lu-ca.
(25) Cầu chúc anh em được đầy tràn ân sủng của Chúa Giê-su Ki-tô. A-men.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;