INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'r', 1, '[SECTION] Rút và bà Na-o-mi
(1) Vào thời các thủ lãnh cai trị, một nạn đói xảy ra trong xứ. Có một người cùng với vợ và hai con trai bỏ Bê-lem miền Giu-đa mà đến ở trong cánh đồng Mô-áp. (2) Tên người đàn ông là Ê-li-me-léc, tên người vợ ấy là Na-o-mi và tên của hai con trai là Mác-lôn và Kin-giôn. Họ là người Ép-ra-tha thuộc xứ Bê-lem miền Giu-đa. Họ đến cánh đồng Mô-áp và ở lại đó. (3) Rồi ông Ê-li-me-léc, chồng bà Na-o-mi, chết đi, còn lại bà Na-o-mi và hai đứa con. (4) Hai người này lấy vợ Mô-áp, một người tên là Oóc-pa, người kia tên là Rút. Họ ở lại đó chừng mười năm. (5) Rồi Mác-lôn và Kin-giôn cả hai đều chết, còn lại bà Na-o-mi mất chồng, mất con. (6) Bà lên đường cùng với hai người con dâu, bỏ cánh đồng Mô-áp mà trở về quê hương, vì tại cánh đồng Mô-áp, bà nghe nói là ĐỨC CHÚA đã viếng thăm dân Người và cho họ có bánh ăn. (7) Vậy bà cùng với hai con dâu ra khỏi nơi họ đã ở mà lên đường trở về xứ Giu-đa.
(8) Bà Na-o-mi nói với hai con dâu: “Thôi, mỗi người chúng con hãy trở về nhà mẹ mình. Xin ĐỨC CHÚA tỏ lòng thương chúng con, như chúng con đã tỏ lòng thương những người quá cố và mẹ! (9) Xin ĐỨC CHÚA cho mỗi người chúng con tìm được cuộc sống an nhàn dưới mái nhà một người chồng!” Rồi bà ôm hôn hai con dâu. Họ òa lên khóc. (10) Họ thưa: “Chúng con muốn cùng mẹ trở về với dân của mẹ.” (11) Bà Na-o-mi nói: “Các con ơi, về đi, theo mẹ làm gì? Trong lòng mẹ còn con trai nào nữa đâu mà gả chồng cho các con. (12) Về đi, các con ơi! Đi đi! Mẹ quá già rồi, không còn tái giá được nữa. Cho dù mẹ có nói được: mẹ còn hy vọng, ngay đêm nay sẽ lấy chồng và sinh được con trai, (13) thì chẳng lẽ chúng con cứ đợi mãi cho đến khi chúng lớn lên? Chẳng lẽ chúng con cứ ở vậy, không chịu lấy chồng? Không, các con ơi! Tình cảnh chúng con làm mẹ cay đắng lắm, vì tay ĐỨC CHÚA giáng phạt mẹ.” (14) Hai người con dâu lại òa lên khóc. Oóc-pa ôm hôn từ giã mẹ chồng, còn Rút thì cứ khắng khít theo bà.
(15) Bà Na-o-mi nói: “Kìa chị dâu con trở về với dân tộc của nó và các thần của nó. Con cũng vậy, hãy theo chị dâu con mà về đi!” (16) Rút đáp: “Xin mẹ đừng ép con bỏ mẹ mà trở về, không theo mẹ nữa, vì
mẹ đi đâu, con đi đó,
mẹ ở đâu, con ở đó,
dân của mẹ là dân của con,
Thiên Chúa của mẹ là Thiên Chúa của con.
(17) Mẹ chết ở đâu, con chết ở đó,
và nơi đó con sẽ được chôn cất.
Xin ĐỨC CHÚA phạt con thế này
và thêm thế kia nữa,
nếu con lìa xa mẹ
mà không phải vì cái chết!”
(18) Thấy Rút cứ một mực đi với mình, bà Na-o-mi không còn nói gì về chuyện đó nữa. (19) Hai mẹ con cùng đi cho đến khi tới Bê-lem. Họ tới Bê-lem, làm cả thành xôn xao. Các người phụ nữ hỏi: “Có phải bà Na-o-mi đấy không?” (20) Bà nói: “Đừng gọi tôi là Na-o-mi nữa, hãy gọi tôi là Ma-ra, vì Đấng Toàn Năng đã bắt tôi phải chịu quá nhiều cay đắng. (21) Tôi ra đi, của cải dư đầy, ĐỨC CHÚA đem tôi về hai bàn tay trắng! Gọi tôi là Na-o-mi làm gì, trong khi ĐỨC CHÚA đã làm cho tôi tủi nhục, Đấng Toàn Năng đã để tôi đau khổ?”
(22) Thế là từ cánh đồng Mô-áp, bà Na-o-mi trở về cùng với con dâu người Mô-áp là Rút. Họ đã đến Bê-lem vào đầu mùa gặt lúa mạch.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'r', 2, '[SECTION] Cô Rút trong đồng ruộng của ông Bô-át
(1) Bà Na-o-mi có một thân nhân bên họ nhà chồng, một người khá giàu, thuộc thị tộc Ê-li-me-léc. Người ấy tên là Bô-át. (2) Rút, người Mô-áp, nói với bà Na-o-mi: “Xin mẹ để con đi ra ruộng mót lúa đằng sau người nào có lòng nhân từ đoái nhìn con.” Bà trả lời: “Con cứ đi đi.” (3) Nàng đi và đến ruộng mót lúa đằng sau thợ gặt. Nàng may mắn gặp được một thửa ruộng của ông Bô-át, người trong thị tộc Ê-li-me-léc. (4) Và kìa ông Bô-át từ Bê-lem đến, nói với thợ gặt: “Xin ĐỨC CHÚA ở cùng các anh!” Họ nói: “Xin ĐỨC CHÚA giáng phúc cho ông!” (5) Ông Bô-át nói với người tôi tớ trông coi thợ gặt: “Cô kia là người của ai thế?” (6) Người tôi tớ trông coi thợ gặt trả lời: “Đó là một thiếu phụ Mô-áp, người đã cùng với bà Na-o-mi từ cánh đồng Mô-áp trở về. (7) Cô đã nói: ‘Cho phép tôi mót và nhặt những bông lúa đằng sau thợ gặt.’ Cô ấy đã đến và ở lại từ sáng tới giờ: Cô ấy chẳng chịu nghỉ ngơi chút nào.”
(8) Ông Bô-át nói với Rút: “Này con, con có nghe không? Đừng đi mót ở ruộng nào khác, cũng đừng rời khỏi đây, nhưng cứ theo sát các tớ gái của ta. (9) Con nhìn thửa ruộng chúng gặt và cứ đi theo chúng. Nào ta đã chẳng ra lệnh cho các tôi tớ không được đụng tới con sao? Nếu khát, con cứ đến chỗ để bình mà uống nước các tôi tớ đã múc.” (10) Rút liền cúi rạp xuống đất mà lạy ông, rồi nói: “Sao con lại được ông lấy lòng nhân từ đoái nhìn và quan tâm đến, dù con là một người ngoại quốc?” (11) Ông Bô-át đáp: “Người ta đã kể lại cho ta nghe tất cả những gì con đã làm cho mẹ chồng sau khi chồng con mất, cũng như chuyện con đã bỏ cả cha mẹ và quê hương, mà đến với một dân trước kia con không hề biết tới. (12) Xin ĐỨC CHÚA trả công cho con vì những gì con đã làm! Chớ gì ĐỨC CHÚA, Thiên Chúa của Ít-ra-en, thưởng công bội hậu cho con, Người là Đấng cho con ẩn náu dưới cánh Người!” (13) Nàng nói: “Thưa ông, ước gì con được ông lấy lòng nhân từ đoái nhìn, vì ông đã an ủi con và nói những lời thân ái với nữ tỳ của ông, mặc dù con không đáng làm một nữ tỳ của ông.”
(14) Đến bữa ăn, ông Bô-át nói với nàng: “Con lại gần đây, lấy bánh chấm vào nước dấm mà ăn.” Nàng ngồi bên cạnh thợ gặt. Ông Bô-át đưa cho nàng một mớ lúa rang. Nàng ăn no và còn để dành nữa. (15) Rồi nàng trỗi dậy mót lúa. Ông Bô-át ra lệnh này cho các tôi tớ của ông: “Cho dù cô ấy có mót ngay giữa những bó lúa đi nữa, các anh cũng đừng nhục mạ cô ấy. (16) Hơn nữa, các anh hãy để ý rút vài bông lúa ra khỏi đống lúa đã gặt và để lại cho cô ấy mót. Đừng trách móc cô ấy làm gì.” (17) Nàng mót trong ruộng cho đến chiều, rồi đập lúa đã mót. Tất cả được gần hai thùng lúa mạch.
(18) Nàng đem lúa trở về thành và mẹ chồng thấy những gì nàng đã mót được. Rồi nàng lấy ra, đưa cho bà những gì nàng để dành sau khi ăn no. (19) Mẹ chồng nói với nàng: “Hôm nay con đã mót ở đâu? Con đã làm ở đâu? Xin Thiên Chúa giáng phúc cho người đã quan tâm đến con!” Nàng cho mẹ chồng biết mình đã làm ở ruộng người nào. Nàng nói: “Người đã cho con làm ở ruộng mình hôm nay tên là Bô-át.” (20) Bà Na-o-mi nói với con dâu: “Xin ĐỨC CHÚA giáng phúc cho ông ấy, Người là Đấng đã không từ chối tỏ lòng nhân nghĩa đối với kẻ sống và kẻ chết!” Bà lại nói: “Ông ấy là bà con gần của chúng ta, ông ấy là một trong những người bảo tồn dòng dõi của chúng ta.” (21) Rút người Mô-áp thưa: “Ông ấy còn nói với con: ‘Con cứ theo sát các tôi tớ của ta cho đến khi chúng gặt hái xong tất cả.’” (22) Bà Na-o-mi bảo con dâu là Rút: “Con ơi, tốt hơn là con cứ đi ra với các tớ gái của ông ấy, để khỏi bị người ta ngược đãi trong ruộng khác.” (23) Vậy nàng theo sát các tớ gái của ông Bô-át để mót, cho đến hết mùa gặt lúa mạch và lúa mì. Và nàng vẫn ở với mẹ chồng.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'r', 3, '[SECTION] Ông Bô-át nằm ngủ
(1) Bà mẹ chồng Na-o-mi nói với Rút: “Con ơi, mẹ chẳng có bổn phận tìm cho con một chốn an nhàn để con được hạnh phúc sao? (2) Mà ông Bô-át không phải là chỗ bà con gần của chúng ta đó ư? Con lại đã chẳng ở với các tớ gái của ông ấy sao? Này, đêm nay ông phải rê lúa mạch dưới sân lúa. (3) Vậy con tắm rửa đi, xức dầu thơm, khoác áo choàng vào, rồi xuống sân lúa. Con đừng cho ông nhận ra con trước khi ông ăn uống xong. (4) Khi ông đi ngủ, con hãy để ý xem ông nằm chỗ nào, rồi đến lật góc chăn phủ chân ông mà nằm xuống. Ông sẽ cho con biết con phải làm gì.” (5) Rút thưa với bà: “Mẹ dạy gì, con sẽ làm tất cả.”
(6) Nàng xuống sân lúa và làm đúng như mẹ chồng đã dạy. (7) Ông Bô-át ăn uống xong, lòng vui tươi hớn hở. Ông đi ngủ ở đầu đống lúa. Rút nhẹ nhàng đi tới đó, lật góc chăn phủ chân ông và nằm xuống. (8) Vào giữa đêm, ông Bô-át rùng mình; ông trở mình thì thấy một phụ nữ nằm dưới chân. (9) Ông hỏi: “Chị là ai?” Nàng đáp: “Con là Rút, tớ gái của ông. Xin ông giăng vạt áo choàng ra mà phủ lấy tớ gái của ông, vì ông là người bảo tồn dòng dõi.” (10) Ông nói: “Này con, xin ĐỨC CHÚA ban phúc lành cho con! Việc hiếu nghĩa thứ hai con đã làm còn có giá hơn việc trước: con đã không chạy theo các người trai trẻ, dù họ nghèo hay giàu. (11) Giờ đây, hỡi con, con đừng sợ. Tất cả những điều con sẽ nói, ta sẽ làm cho con. Vì mọi người hội họp ở cửa thành này đều biết con là một phụ nữ đức hạnh. (12) Quả thật, hiện nay ta là người bảo tồn dòng dõi, nhưng còn có người bảo tồn dòng dõi họ hàng với con gần hơn ta. (13) Con cứ qua đêm ở đây. Sáng mai, nếu người ấy muốn dùng quyền bảo tồn dòng dõi đối với con thì tốt, người ấy cứ việc; nếu người ấy không muốn thì, có ĐỨC CHÚA hằng sống, ta thề sẽ dùng quyền đó! Hãy ngủ đi cho đến sáng.” (14) Nàng đã ngủ dưới chân ông cho đến sáng. Tờ mờ sáng, lúc chưa ai nhận ra ai, nàng đã trỗi dậy. Ông tự nhủ: “Không được để cho người ta biết là người phụ nữ này đã đến sân lúa.” (15) Ông nói: “Hãy đưa vạt áo choàng của con ra, và cầm chắc lấy.” Nàng cầm chắc rồi, thì ông đong cho nàng sáu đấu lúa mạch, rồi đặt lên vai nàng. Sau đó, nàng đi vào thành.
(16) Nàng về đến nhà mẹ chồng, mẹ chồng hỏi: “Thế nào, con?” Nàng thuật lại cho mẹ chồng nghe tất cả những gì người đó đã làm cho nàng. (17) Nàng nói: “Ông ấy đã cho con sáu đấu lúa mạch này, vì ông nói: ‘Con không được trở về nhà mẹ chồng tay không.’” (18) Bà nói: “Này con, con cứ ở nhà cho đến khi biết việc này ngã ngũ ra sao, vì ông ấy sẽ không chịu ở yên đâu, cho đến khi lo xong việc đó nội ngày hôm nay.”') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, 'r', 4, '[SECTION] Ông Bô-át cưới cô Rút
(1) Ông Bô-át lên cửa thành và ngồi ở đó. Và này, người bảo tồn dòng dõi mà ông Bô-át đã nói tới, đi ngang qua. Ông Bô-át nói: “Này ông ơi, mời ông đến và ngồi xuống đây.” Người ấy đến và ngồi xuống. (2) Ông Bô-át chọn lấy mười người trong số các kỳ mục của thành và nói: “Mời các ông ngồi lại đây.” Họ ngồi xuống. (3) Ông nói với người bảo tồn dòng dõi: “Bà Na-o-mi từ cánh đồng Mô-áp mới về, định bán thửa ruộng của người anh em chúng ta là Ê-li-me-léc. (4) Phần tôi, tôi nghĩ là cần phải báo cho ông biết rằng: trước mặt quý vị hiện diện ở đây và các kỳ mục trong dân, ông hãy tậu thửa ruộng ấy! Nếu ông muốn dùng quyền bảo tồn dòng dõi của ông, thì xin hãy dùng; bằng không thì xin tuyên bố cho tôi biết, vì ngoài ông ra, không ai có quyền bảo tồn dòng dõi; còn tôi thì chỉ đứng sau ông.” Người ấy nói: “Vâng, tôi sẽ dùng quyền bảo tồn đó.” (5) Ông Bô-át nói: “Ngày nào ông tậu ruộng chính tay bà Na-o-mi bán, thì lúc đó ông cũng phải lấy cả cô Rút người Mô-áp, vợ của người quá cố, để gia nghiệp người đó mãi mãi mang tên người đó.” (6) Người bảo tồn dòng dõi nói: “Thế thì tôi không thể dùng quyền bảo tồn đó được, để khỏi làm hại gia nghiệp của tôi. Xin ông thay tôi mà dùng quyền đó, vì tôi không thể dùng được.”
(7) Theo phong tục thời xưa tại Ít-ra-en, khi có chuyện liên quan đến quyền bảo tồn hay việc đổi chác, để xác nhận việc đó, thì người này cởi dép trao cho người kia. Đó là cách chứng nhận tại Ít-ra-en. (8) Người bảo tồn dòng dõi nói với ông Bô-át: “Ông hãy tậu cho ông đi”, rồi người ấy cởi dép ra.
(9) Ông Bô-át nói với các kỳ mục và toàn dân: “Hôm nay, xin quý vị làm chứng cho là tôi tậu từ tay bà Na-o-mi tất cả những gì thuộc về ông Ê-li-me-léc, tất cả những gì thuộc về Kin-giôn và Mác-lôn. (10) Và cả Rút người Mô-áp, vợ của Mác-lôn nữa, tôi cũng lấy làm vợ, để gia nghiệp người quá cố mãi mãi mang tên người đó, và để người đó khỏi bị xóa tên trong đám bà con họ hàng, cũng như trong số dân cư tụ họp tại cửa thành. Hôm nay, quý vị làm chứng cho điều đó.” (11) Toàn dân ở cửa thành và các kỳ mục đáp: “Chúng tôi xin làm chứng! Xin ĐỨC CHÚA cho người phụ nữ sắp vào nhà ông được nên giống như bà Ra-khen và bà Lê-a, cả hai bà này đã xây dựng nhà Ít-ra-en!
Chúc ông được giàu có ở Ép-ra-tha!
Chúc ông được nổi tiếng ở Bê-lem!
(12) Chớ gì dòng dõi mà ĐỨC CHÚA sẽ ban cho ông, nhờ người thiếu phụ này, làm cho nhà của ông được nên giống như nhà của ông Pe-rét, là người con mà bà Ta-ma đã sinh cho ông Giu-đa!”
(13) Vậy ông Bô-át lấy cô Rút, và nàng trở thành vợ ông. Ông đến với nàng. Nhờ ơn ĐỨC CHÚA, nàng đã thụ thai và sinh một con trai. (14) Các phụ nữ nói với bà Na-o-mi: “Chúc tụng ĐỨC CHÚA, Đấng hôm nay đã không để cho bà phải thiếu người bảo tồn dòng dõi: tên tuổi con trẻ sẽ được tung hô tại Ít-ra-en! (15) Nó sẽ giúp bà lấy lại sức sống, và sẽ là người nâng đỡ bà trong tuổi già, vì người con dâu biết yêu quý bà đã sinh ra nó, nàng quý giá hơn bảy đứa con trai.” (16) Bà Na-o-mi bế đứa trẻ lên và ôm vào lòng. Chính bà nuôi nấng đứa trẻ đó.
(17) Các bà hàng xóm láng giềng đặt tên cho đứa trẻ và nói: “Bà Na-o-mi đã sinh được một cháu trai.” Họ đặt tên cho nó là Ô-vết. Đó là cha của ông Gie-sê, là ông nội vua Đa-vít.
[SECTION] Gia phả vua Đa-vít
(18) Đây là dòng dõi của ông Pe-rét:
Pe-rét sinh Khét-rôn. (19) Khét-rôn sinh Ram; Ram sinh Am-mi-na-đáp. (20) Am-mi-na-đáp sinh Nác-sôn; Nác-sôn sinh Xan-môn. (21) Xan-môn sinh Bô-át; Bô-át sinh Ô-vết; (22) Ô-vết sinh Gie-sê; Gie-sê sinh Đa-vít.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;