INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, '2tm', 1, '[SECTION] Lời mở đầu và tạ ơn
(1) Tôi là Phao-lô, Tông Đồ của Đức Ki-tô Giê-su, do ý muốn của Thiên Chúa, chiếu theo lời Thiên Chúa hứa ban sự sống vốn có trong Đức Ki-tô Giê-su, (2) gửi anh Ti-mô-thê, người con yêu dấu. Xin Thiên Chúa là Cha và xin Đức Giê-su Ki-tô, Chúa chúng ta, ban cho anh được ân sủng, lòng thương xót và sự bình an.
(3) Tôi tạ ơn Thiên Chúa, Đấng tôi phụng thờ với lương tâm trong sạch, theo gót tổ tiên; tôi tạ ơn Người khi tôi không ngừng nhắc nhớ đến anh, trong các lời cầu nguyện của tôi, đêm cũng như ngày. (4) Nhớ đến những giọt nước mắt của anh, tôi ước ao gặp lại anh để được chan chứa niềm vui. (5) Tôi hồi tưởng lại lòng tin không giả hình của anh, lòng tin đã có nơi cụ Lô-ít, bà ngoại anh, nơi bà Êu-ni-kê, mẹ anh, cũng như chính nơi anh, tôi xác tín như vậy.
[SECTION] Những ơn ông Ti-mô-thê đã nhận được
(6) Vì lý do đó, tôi nhắc anh phải khơi dậy đặc sủng của Thiên Chúa, đặc sủng anh đã nhận được khi tôi đặt tay trên anh. (7) Vì Thiên Chúa đã chẳng ban cho chúng ta một thần khí làm cho chúng ta trở nên nhút nhát, nhưng là một Thần Khí khiến chúng ta được đầy sức mạnh, tình thương, và biết tự chủ. (8) Vậy anh đừng hổ thẹn vì phải làm chứng cho Chúa chúng ta, cũng đừng hổ thẹn vì tôi, người tù của Chúa; nhưng dựa vào sức mạnh của Thiên Chúa, anh hãy đồng lao cộng khổ với tôi để loan báo Tin Mừng. (9) Người đã cứu độ và kêu gọi chúng ta vào dân thánh của Người, không phải vì công kia việc nọ chúng ta đã làm, nhưng là do kế hoạch và ân sủng của Người. Ân sủng đó, Người đã ban cho chúng ta từ muôn thuở trong Đức Ki-tô Giê-su, (10) nhưng giờ đây mới được biểu lộ, vì Đấng cứu độ chúng ta là Đức Ki-tô Giê-su đã xuất hiện. Chính Đức Ki-tô đã tiêu diệt thần chết, và đã dùng Tin Mừng mà làm sáng tỏ phúc trường sinh bất tử. (11) Thiên Chúa đã đặt tôi làm người rao giảng Tin Mừng đó, làm tông đồ và thầy dạy.
(12) Chính vì lý do ấy mà tôi phải chịu những đau khổ này; nhưng tôi không hổ thẹn, vì tôi biết tôi tin vào ai, và xác tín rằng: Người có đủ quyền năng bảo toàn giáo lý đã được giao phó cho tôi, mãi cho tới Ngày đó.
(13) Với đức tin và đức mến của một người được kết hợp với Đức Ki-tô Giê-su, anh hãy lấy làm mẫu mực những lời lành mạnh anh đã nghe tôi dạy. (14) Giáo lý tốt đẹp đã giao phó cho anh, anh hãy bảo toàn, nhờ có Thánh Thần ngự trong chúng ta.
(15) Anh biết rằng mọi người ở A-xi-a đã bỏ tôi; Phy-ghê-lô và Héc-mô-ghê-nê cũng ở trong số ấy. (16) Xin Chúa tỏ lòng thương xót gia đình anh Ô-nê-xi-phô-rô, vì đã nhiều lần anh làm cho tôi lên tinh thần, và đã không hổ thẹn vì tôi phải mang xiềng xích; (17) trái lại, vừa đến Rô-ma, anh vội vã đi tìm và đã thấy tôi. (18) Xin Chúa ban cho anh tìm thấy nơi Chúa lòng thương xót, trong Ngày đó. Về công việc phục vụ của anh ấy ở Ê-phê-xô, thì anh đã quá rõ.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, '2tm', 2, '[SECTION] Ý nghĩa các đau khổ của người tông đồ
(1) Vậy hỡi anh, người con của tôi, anh hãy nên mạnh mẽ trong ân sủng của Đức Ki-tô Giê-su. (2) Những gì anh đã nghe tôi nói trước mặt nhiều nhân chứng, thì hãy trao lại cho những người tin cẩn, những người sẽ có khả năng dạy cho người khác.
(3) Anh hãy đồng lao cộng khổ như một người lính giỏi của Đức Ki-tô Giê-su. (4) Trong nghề binh, không ai vướng mắc vào những việc thuộc đời sống dân sự; có thế mới đẹp lòng người đã tuyển mộ. (5) Người tham dự điền kinh cũng vậy, không đoạt giải nếu không thi đấu theo luật lệ. (6) Còn người nông dân làm việc vất vả, thì phải là người đầu tiên được hưởng phần hoa lợi. (7) Anh hãy hiểu điều tôi nói, vì Chúa sẽ ban cho anh ơn thông hiểu mọi sự.
(8) Anh hãy nhớ đến Đức Giê-su Ki-tô,
Đấng đã sống lại từ cõi chết,
Đấng xuất thân từ dòng dõi Đa-vít,
như tôi vẫn nói trong Tin Mừng tôi loan báo. (9) Vì Tin Mừng ấy, tôi chịu khổ, tôi còn phải mang cả xiềng xích như một tên gian phi. Nhưng lời Thiên Chúa đâu bị xiềng xích! (10) Bởi vậy, tôi cam chịu mọi sự, để mưu ích cho những người Thiên Chúa đã chọn, để họ cũng đạt tới ơn cứu độ trong Đức Ki-tô Giê-su, và được hưởng vinh quang muôn đời.
(11) Đây là lời đáng tin cậy:
Nếu ta cùng chết với Người,
ta sẽ cùng sống với Người.
(12) Nếu ta kiên tâm chịu đựng,
ta sẽ cùng hiển trị với Người.
Nếu ta chối bỏ Người,
Người cũng sẽ chối bỏ ta.
(13) Nếu ta không trung tín,
Người vẫn một lòng trung tín,
vì Người không thể nào
chối bỏ chính mình.
[SECTION] Chống lại những người dạy giáo lý sai lạc
(14) Anh hãy nhắc nhở lại những điều đó, trước mặt Thiên Chúa, hãy tha thiết khuyên người ta đừng cãi chữ: chuyện không có ích lợi gì, chỉ làm cho người nghe phải diệt vong. (15) Hãy cố gắng ra trước mặt Thiên Chúa như một người đã được thử luyện, một người thợ không có gì phải xấu hổ, một người thẳng thắn dạy lời chân lý. (16) Còn những chuyện nhảm nhí, trống rỗng, anh hãy tránh xa, vì những kẻ nói những chuyện ấy sẽ tiến sâu vào con đường vô luân. (17) Lời họ như một thứ ung nhọt cứ loét thêm ra. Trong số những người đó có Hy-mê-nê và Phi-lê-tô. (18) Hai người này đã đi trệch đường chân lý, khi nói rằng sự phục sinh đã xảy ra rồi và như vậy họ phá đổ đức tin của một số người. (19) Tuy nhiên, nền móng vững chắc Thiên Chúa đã đặt thì tồn tại; trên đó có ghi tạc lời này: Chúa biết những kẻ thuộc về Người, và Phàm ai kêu cầu danh Chúa phải tránh xa điều bất chính.
(20) Trong một ngôi nhà lớn, không phải chỉ có những đồ vật bằng vàng bằng bạc, nhưng cũng có những đồ vật bằng gỗ bằng sành; thứ thì dùng vào việc cao quý, thứ thì dùng vào việc thấp hèn. (21) Vậy ai thanh tẩy mình cho sạch những điều xấu nói trên, người đó sẽ là một đồ vật dùng vào việc cao quý, một đồ vật được thánh hiến, có ích cho chủ, sẵn sàng làm mọi việc lành.
(22) Anh hãy tránh xa các đam mê của tuổi trẻ, cố gắng trở nên người công chính, giàu lòng tin và lòng mến, ăn ở thuận hòa cùng những ai kêu cầu Chúa với tấm lòng trong sạch. (23) Còn những tranh luận điên rồ và ngu xuẩn, anh hãy gạt ra một bên, vì biết rằng những thứ ấy sinh ra cãi cọ. (24) Thế mà người tôi tớ Chúa thì không được cãi cọ, nhưng phải dịu dàng với mọi người, có khả năng giảng dạy, biết chịu đựng gian khổ. (25) Người ấy phải lấy lòng hiền hòa mà giáo dục những kẻ chống đối: biết đâu Thiên Chúa lại chẳng ban cho họ ơn sám hối để nhận biết chân lý, (26) và họ sẽ tỉnh ngộ, thoát khỏi cạm bẫy ma quỷ đã dùng để bắt giữ họ và khiến họ làm theo ý nó?') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, '2tm', 3, '[SECTION] Đề phòng các nguy hiểm của những thời cuối cùng
(1) Anh hãy biết điều này: Vào những ngày sau hết sẽ có những lúc gay go. (2) Quả thế, người ta sẽ ra ích kỷ, ham tiền bạc, khoác lác, kiêu ngạo, nói lộng ngôn, không vâng lời cha mẹ, vô ân bạc nghĩa, phạm thượng, (3) vô tâm vô tình, tàn nhẫn, nói xấu, thiếu tiết độ, hung dữ, ghét điều thiện, (4) phản trắc, nông nổi, lên mặt kiêu căng, yêu khoái lạc hơn yêu Thiên Chúa; (5) hình thức của đạo thánh thì họ còn giữ, nhưng cái chính yếu thì đã chối bỏ. Anh hãy xa lánh cả những người ấy.
(6) Thuộc bọn đó là những kẻ lẻn vào nhà người ta chinh phục thứ đàn bà nhẹ dạ, đầy những tội lỗi và bị đủ thứ đam mê lôi cuốn, (7) học mãi mà chẳng bao giờ nhận biết được chân lý. (8) Cũng như Gian-nê và Giam-rê xưa chống lại ông Mô-sê, thì nay họ cũng chống lại chân lý; họ là hạng người đầu óc lệch lạc, lòng tin không có gì vững chắc. (9) Nhưng họ sẽ không đi xa hơn được, vì như trường hợp hai tên kia, mọi người sẽ thấy rõ là họ điên khùng.
(10) Phần anh, anh đã theo sát đạo lý, cách sống, dự định của tôi; anh đã thấy lòng tin, sự nhẫn nại, lòng yêu mến, sự kiên trì của tôi; (11) anh đã biết những cơn bắt bớ, những sự đau khổ tôi đã gặp ở An-ti-ô-khi-a, I-cô-ni-ô, Lýt-ra, đã biết tôi chịu bắt bớ như thế nào. Nhưng Chúa đã giải thoát tôi khỏi tất cả. (12) Vả lại, những ai muốn sống đạo đức trong Đức Ki-tô Giê-su, đều sẽ bị bắt bớ. (13) Còn hạng người xấu xa và bịp bợm sẽ ngày càng xấu hơn, họ vừa lừa dối, vừa bị lừa dối.
(14) Phần anh, hãy giữ vững những gì anh đã học được và đã tin chắc. Anh biết anh đã học với những ai. (15) Và từ thời thơ ấu, anh đã biết Sách Thánh, sách có thể dạy anh nên người khôn ngoan để được ơn cứu độ, nhờ lòng tin vào Đức Ki-tô Giê-su. (16) Tất cả những gì viết trong Sách Thánh đều do Thiên Chúa linh hứng, và có ích cho việc giảng dạy, biện bác, sửa dạy, giáo dục để trở nên công chính. (17) Nhờ vậy, người của Thiên Chúa nên thập toàn, và được trang bị đầy đủ để làm mọi việc lành.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;

INSERT INTO chapters (translation_id, book_id, chapter, content) VALUES (1, '2tm', 4, '[SECTION] Lời khuyên nhủ thiết tha
(1) Trước mặt Thiên Chúa và Đức Ki-tô Giê-su, Đấng sẽ phán xét kẻ sống và kẻ chết, Đấng sẽ xuất hiện và nắm vương quyền, tôi tha thiết khuyên anh: (2) hãy rao giảng Lời Chúa, hãy lên tiếng, lúc thuận tiện cũng như lúc không thuận tiện; hãy biện bác, ngăm đe, khuyên nhủ, với tất cả lòng nhẫn nại và chủ tâm dạy dỗ. (3) Thật vậy, sẽ đến thời người ta không còn chịu nghe giáo lý lành mạnh, nhưng theo những dục vọng của mình mà kiếm hết thầy này đến thầy nọ, bởi ngứa tai muốn nghe. (4) Họ sẽ ngoảnh tai đi không nghe chân lý, nhưng hướng về những chuyện hoang đường. (5) Phần anh, hãy thận trọng trong mọi sự, hãy chịu đựng đau khổ, làm công việc của người loan báo Tin Mừng và chu toàn chức vụ của anh.
[SECTION] Ông Phao-lô vào cuối đời
(6) Còn tôi, tôi sắp phải đổ máu ra làm lễ tế, đã đến giờ tôi phải ra đi. (7) Tôi đã đấu trong cuộc thi đấu cao đẹp, đã chạy hết chặng đường, đã giữ vững niềm tin. (8) Giờ đây tôi chỉ còn đợi vòng hoa dành cho người công chính; Chúa là vị Thẩm Phán chí công sẽ trao phần thưởng đó cho tôi trong Ngày ấy, và không phải chỉ cho tôi, nhưng còn cho tất cả những ai hết tình mong đợi Người xuất hiện. (9) Anh hãy mau mau đến với tôi, (10) vì anh Đê-ma đã bỏ tôi, bởi yêu mến thế gian này; anh ta đã đi Thê-xa-lô-ni-ca. Anh Cơ-rét-xen đã đi sang miền Ga-lát, anh Ti-tô đi sang miền Đan-ma-ti-a. (11) Chỉ còn một mình anh Lu-ca ở với tôi. Anh hãy đem anh Mác-cô đi với anh, vì anh ấy rất hữu ích cho công việc phục vụ của tôi. (12) Anh Ty-khi-cô thì tôi đã sai đi Ê-phê-xô. (13) Cái áo choàng tôi đã để lại nhà anh Các-pô ở Trô-a, thì khi đến, xin anh đem theo, cũng như các sách vở, nhất là những cuộn giấy da. (14) A-lê-xan-đê, người thợ rèn, đã gây cho tôi nhiều khốn khổ; Chúa sẽ cứ việc anh ta làm mà trả báo. (15) Cả anh nữa, cũng hãy đề phòng anh ta, vì anh ta mạnh mẽ chống lại lời chúng ta rao giảng.
(16) Khi tôi đứng ra tự biện hộ lần thứ nhất, thì chẳng có ai bênh vực tôi. Mọi người đã bỏ mặc tôi. Xin Chúa đừng chấp họ. (17) Nhưng có Chúa đứng bên cạnh, Người đã ban sức mạnh cho tôi, để nhờ tôi mà việc rao giảng được hoàn thành, và tất cả các dân ngoại được nghe biết Tin Mừng. (18) Và tôi đã thoát khỏi nanh vuốt sư tử. Chúa sẽ còn cho tôi thoát khỏi mọi hành vi hiểm độc, sẽ cứu và đưa tôi vào vương quốc của Người ở trên trời. Chúc tụng Người vinh hiển đến muôn thuở muôn đời. A-men.
[SECTION] Lời chào và lời chúc cuối thư
(19) Xin gửi lời thăm chị Pơ-rít-ca và anh A-qui-la, và gia đình anh Ô-nê-xi-phô-rô. (20) Anh Ê-rát-tô đã ở lại Cô-rin-tô. Còn anh Trô-phi-mô đang đau, tôi đã để anh ấy ở lại Mi-lê-tô. (21) Anh hãy mau đến trước mùa đông.
Các anh Êu-bu-lô, Pu-đê, Li-nô, chị Cơ-lau-đi-a và toàn thể anh em gửi lời thăm anh.
(22) Chúa ở cùng thần trí anh. Chúc anh em được ân sủng.') ON CONFLICT (translation_id, book_id, chapter) DO UPDATE SET content = EXCLUDED.content;